Softwareupdate
withfig/autocomplete pull request #1002
Opened 2022-03-06 08:00 UTC by harimm

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature: New completion spec

**What is the current behavior? (You can also link to an open issue here)**
CLI request: https://github.com/withfig/autocomplete/issues/942
Spec does not exist for `softwareupdate` command 

**What is the new behavior (if this is a feature change)?**
Adds completion spec for `softwareupdate` command

**Additional info:**

2022-03-06 10:31 UTC, fedeci requested changes
I left some comments to improve the spec, but thanks for writing this down!
p.s. when you link an issue you can use a closing keyword to make the issue close automatically when this PR gets merged

2022-03-06 10:31 UTC, fedeci commented on src/softwareupdate.ts
> +  subcommands: [
```suggestion
  options: [
```

2022-03-06 10:31 UTC, fedeci commented on src/softwareupdate.ts
> +      args: {
Can we add a generator for this arg? It should be fairly simple using the `softwareupdate --list` results

2022-03-06 10:31 UTC, fedeci commented on src/softwareupdate.ts
> +      ],
Since we cannot have options of options, we need to `dependsOn: ["--install"]` to these.

2022-03-06 10:31 UTC, fedeci commented on src/softwareupdate.ts
> +      ],
Same here

2022-03-06 10:31 UTC, fedeci commented on src/softwareupdate.ts
> +  ],
`isPersistent` really doesn't make sense if there is no subcommand, so we can remove it safely!

2022-03-06 14:59 UTC, harimm commented on src/softwareupdate.ts
> +  subcommands: [
I initally wrote these stuff as options but the man page mentions several of these as `commands` and not `options`. Also when this is what `softwareupdate -h` gives you

```
softwareupdate -h
usage: softwareupdate <cmd> [<args> ...]

** Manage Updates:
	-l | --list		List all appropriate update labels (options:  --no-scan, --product-types)
	-d | --download		Download Only
	-i | --install		Install
		<label> ...	specific updates
		-a | --all		All appropriate updates
		-R | --restart		Automatically restart (or shut down) if required to complete installation.
		-r | --recommended	Only recommended updates
	--list-full-installers		List the available macOS Installers
	--fetch-full-installer		Install the latest recommended macOS Installer
		--full-installer-version	The version of macOS to install. Ex: --full-installer-version 10.15
	--install-rosetta	Install Rosetta 2
	--background		Trigger a background scan and update operation

** Other Tools:
	--dump-state		Log the internal state of the SU daemon to /var/log/install.log
	--evaluate-products	Evaluate a list of product keys specified by the --products option
	--history		Show the install history.  By default, only displays updates installed by softwareupdate.
	--all 			Include all processes in history (including App installs)

** Options:
	--no-scan		Do not scan when listing or installing updates (use available updates previously scanned)
	--product-types <type>		Limit a scan to a particular product type only - ignoring all others
		Ex:  --product-types macOS  || --product-types macOS,Safari
	--products		A comma-separated (no spaces) list of product keys to operate on.
	--force			Force an operation to complete.  Use with --background to trigger a background scan regardless of "Automatically check" pref
	--agree-to-license		Agree to the software license agreement without user interaction.

	--verbose		Enable verbose output
	--help			Print this help
```
Only the ones mentioned under `** Options I have added as option

2022-03-06 22:00 UTC, fedeci commented on src/softwareupdate.ts
> +  subcommands: [
Let's keep it as is then!

2022-03-06 22:00 UTC, fedeci approved these changes
Thanks!

2022-03-06 22:00 UTC, merged

2022-03-06 22:00 UTC, fedeci commented
I forgot about this [comment](https://github.com/withfig/autocomplete/pull/1002#discussion_r820212761), @harimm would you mind opening a new PR adding that generator?

2022-03-07 03:54 UTC, harimm commented
@fedeci Created draft PR https://github.com/withfig/autocomplete/pull/1008/

Keeping it as draft as I haven't been able to test it out yet