feat(npm): improvements
withfig/autocomplete pull request #1019
Opened 2022-03-10 13:07 UTC by harimm

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Improve completion spec of `npm`

**What is the current behavior? (You can also link to an open issue here)**
Several commands are incorrectly grouped. Several options are missing
Partially fixes issue: https://github.com/withfig/autocomplete/issues/983

**What is the new behavior (if this is a feature change)?**
Improves multiple subcommands

**Additional info:**
NOTE: Though this improves the whole npm spec by adding options to certain subcommands and by grouping aliased subcommands together, this is in no way exhaustive and further improvements would be needed
Follow up of: https://github.com/withfig/autocomplete/pull/1001

2022-03-10 13:56 UTC, fedeci requested changes

2022-03-10 13:56 UTC, fedeci commented on src/npm.ts
> +          "A url or file path to a gzipped tar archive containing a single folder with a package.json file inside | A folder containing a package.json file",
```suggestion
        name: "tarball|folder",
        isOptional: true,
        description:
          "A url or file path to a gzipped tar archive containing a single folder with a package.json file inside | A folder containing a package.json file",
        template: ["folders"],
```

2022-03-12 13:09 UTC, harimm reviewed
Changes made as per review comments. Thanks @fedeci

2022-03-12 13:14 UTC, fedeci approved these changes
Thanks!

2022-03-12 13:14 UTC, merged