feat: add `go-task` spec
withfig/autocomplete pull request #1036
Opened 2022-03-19 17:24 UTC by yoavbls

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature, add spec for [go-task](taskfile.dev)

**What is the current behavior? (You can also link to an open issue here)**
Currently, fig shows autocompletion only for `taskwarrior` binary when writing `task ...`

**What is the new behavior (if this is a feature change)?**
fig will show autocompletion for `go-task` if it is the binary that runs on `task`, or `taskwarrior` if it isn't

<img width="633" alt="CleanShot 2022-03-19 at 19 18 36@2x" src="https://user-images.githubusercontent.com/5693018/159131467-304efac3-cd85-4fa6-9d83-4294bc4301fe.png">

**Additional info:**
Unfortunately, autocompletion appears also when writing `go-task ...` or `taskwarrior ...`
I would like to know about a way to disable it

2022-03-19 18:37 UTC, fedeci commented
> **Additional info:** Unfortunately, autocompletion appears also when writing `go-task ...` or `taskwarrior ...` I would like to know about a way to disable it

I still have to review this PR but you can nest `taskwarrior.ts` and `go-task.ts` under a directory e.g. `task/taskwarrior.ts`, `task/go-task.ts`

2023-02-13 00:41 UTC, davidalpert commented
@fedeci or @mschrage could we please review and merge this PR?

I have run into this exact issue recently and popped over to investigate/fix it only to find that @yoavbls has already fixed it! 😍 

I just checked out this branch locally, ran the autocomplete specs in dev mode, and verified that this PR does in fact replace the taskwarrior autocompletions with the tasks from my taskfile. 🎉

2023-02-13 18:33 UTC, fedeci commented
I am giving a look!

2023-02-13 18:34 UTC, fedeci commented
recheck

2023-02-13 18:44 UTC, yoavbls commented
@fedeci where do I accept it?
Do you want me to resolve the conflicts? Is someone going to review it?

2023-02-13 18:55 UTC, fedeci commented
@yoavbls I am reviewing right now, don't worry about conflicts, I am fixing those!
Sorry for late response!

2023-02-13 18:58 UTC, yoavbls commented
I have read the CLA Document and I hereby sign the CLA

2023-02-13 19:10 UTC, fedeci requested changes
Thanks, I left a couple perf improvements but it looks great!

2023-02-13 19:10 UTC, fedeci commented on src/task/go-task.ts
> +      .filter((_, i) => i > 0) // The first line is not a task
```suggestion
      .slice(1) // The first line is not a task
```

2023-02-13 19:10 UTC, fedeci commented on src/task/go-task.ts
> +const DIRECTORY_FLAGS = ["-d", "--dir"];
```suggestion
const DIRECTORY_FLAGS = ["-d", "--dir"];
const taskDirectoryFlags = new Set([...TASKFILE_FLAGS, ...DIRECTORY_FLAGS]);
```

2023-02-13 19:10 UTC, fedeci commented on src/task/go-task.ts
> +          [...TASKFILE_FLAGS, ...DIRECTORY_FLAGS].includes(token)
```suggestion
          taskDirectoryFlags.has(token)
```

2023-02-13 19:15 UTC, fedeci requested changes

2023-02-13 20:03 UTC, fedeci approved these changes

2023-02-13 20:03 UTC, merged