feat: add `shopify- cli` specs
withfig/autocomplete pull request #1037
Opened 2022-03-19 18:10 UTC by beynar

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
**Feature** : this PR introduces autocompletion for the [shopify-cli](https://shopify.dev/apps/tools/cli/core-commands).

<img width="906" alt="CleanShot 2022-03-19 at 19 07 35@2x" src="https://user-images.githubusercontent.com/21969002/159133224-e79f38e2-d864-45e5-ad1a-14d2e2f3ee68.png">

2022-03-20 22:00 UTC, fedeci requested changes
Thank you for this contribution! There are some things to fix but it looks really nice!

2022-03-21 07:19 UTC, beynar commented on src/shopify.ts
> +};
nice !

2022-03-22 15:23 UTC, fedeci commented on src/shopify.ts
> +  },
Can you also add a small description to these?

2022-03-22 15:23 UTC, fedeci commented on src/shopify.ts
> +                isOptional: false,
And here :)

2022-03-22 15:23 UTC, fedeci commented on src/shopify.ts
> +    isRequired: true,
Friendly ping here😄

2022-03-22 15:24 UTC, fedeci commented on src/shopify.ts
> +                isOptional: false,
And here :)

2022-03-28 18:56 UTC, mschrage commented on src/shopify.ts
> +  },
If this is the only thing we are waiting on, then I think it's okay to merge this in cc @fedeci @beynar

2022-03-29 11:16 UTC, fedeci approved these changes

2022-03-29 11:17 UTC, fedeci commented
Thanks!

2022-03-29 11:17 UTC, merged