feat: add zellij completion spec
withfig/autocomplete pull request #1055
Opened 2022-03-24 14:47 UTC by anthonycicc

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
`zellij` commands are not currently supported

**What is the new behavior (if this is a feature change)?**
Autocompletion support for `zellij`

**Additional info:**
[x] Basic generator-based completion for interacting with live sessions as possible

2022-03-24 16:17 UTC, fedeci requested changes

2022-03-24 16:17 UTC, fedeci commented on src/zellij.ts
> +  description: "Print help information",
You can use `isPersistent` to add the help option to all subcommands

2022-03-24 16:17 UTC, fedeci commented on src/zellij.ts
> +        isOptional: false,
This is implicit
```suggestion
```

2022-03-24 16:17 UTC, fedeci commented on src/zellij.ts
> +        isOptional: false,
```suggestion
```

2022-03-24 16:17 UTC, fedeci commented on src/zellij.ts
> +        ],
```suggestion
        template: "help",
```

2022-03-24 16:17 UTC, fedeci commented on src/zellij.ts
> +      args: {},
This apparently accepts a folders template, right?

2022-03-24 16:18 UTC, fedeci commented
Thanks for this first contibution! There are a couple thing to fix but overall it looks good! It would be nice if you could also add some names and descriptions to the args😄

2022-03-24 17:10 UTC, mschrage commented on src/zellij.ts
> +        isOptional: false,
Can we add a linter for this?

2022-03-24 17:49 UTC, fedeci commented on src/zellij.ts
> +        isOptional: false,
👍

2022-03-31 20:37 UTC, cstrnt requested changes
Some small bits. Like @fedeci said, having names / descriptions for args would be awesome 🔥

2022-03-31 20:37 UTC, cstrnt commented on src/zellij.ts
> +          description: "Automation yes to prompts",
I think having this would make sense here
```suggestion
          description: "Automation yes to prompts",
          isDangerous: true
```

2022-03-31 20:37 UTC, cstrnt commented on src/zellij.ts
> +          args: {},
see above

2022-03-31 20:37 UTC, cstrnt commented on src/zellij.ts
> +          description: "Set the default theme",
I think this takes an argument (theme name)

2022-03-31 20:37 UTC, cstrnt commented on src/zellij.ts
> +          args: {},
The layout is a file, right? Then it would be cool to have `template: files`here

2022-03-31 20:37 UTC, cstrnt commented on src/zellij.ts
> +      args: {},
Here it would be cool to have `template: "folders"` again

2022-03-31 20:37 UTC, cstrnt commented on src/zellij.ts
> +      args: {},
see above; file template

2022-03-31 20:37 UTC, cstrnt commented on src/zellij.ts
> +      args: {},
see above

2022-07-28 04:28 UTC, SeparateRecords commented
Hey there! Didn't realize there was already an open PR for this - I just opened #1369, should we close this one?

2022-07-28 07:18 UTC, fedeci commented
Yes if this one isn't adding nothing more.

2022-07-28 08:12 UTC, closed without merging