feat: add oh-my-posh
withfig/autocomplete pull request #1064
Opened 2022-03-26 17:36 UTC by JanDeDobbeleer

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

feature: a new autocompletion

2022-03-28 18:53 UTC, mschrage commented on src/oh-my-posh.ts
> +        },
Looks like this option takes an filepath argument!


```suggestion
        {
          name: ["--config", "-c"],
          description:
            "The config file to use, example usage: 'oh-my-posh debug --config ~/.config.omp.json'",
           args: {
              name: "config file",
              template: "filepath"
           },
        },
```

2022-03-28 18:54 UTC, JanDeDobbeleer commented on src/oh-my-posh.ts
> +        },
@mschrage not necessarily. It can, but a URL is also valid.

2022-03-28 19:43 UTC, JanDeDobbeleer commented on src/oh-my-posh.ts
> +        },
only `--shell` actually, everything else is free form (apart from the type obviously).

2022-03-28 20:04 UTC, mschrage commented on src/oh-my-posh.ts
> +        },
It seems like in a lot of the example usage the options take another argument:
oh-my-posh print primary --terminal-width 200
`oh-my-posh print tooltip --command az'`
`oh-my-posh print primary --error 127`

2022-03-28 20:04 UTC, mschrage commented on src/oh-my-posh.ts
> +        },
What do you mean by free form?

2022-03-28 20:24 UTC, JanDeDobbeleer commented on src/oh-my-posh.ts
> +        },
@mschrage aaaah. Ok, got it. As in, they're not boolean switches. Got it. Will add.

2022-03-29 02:54 UTC, mschrage commented on src/oh-my-posh.ts
> +        },
Thanks <3

2022-03-29 06:46 UTC, JanDeDobbeleer commented on src/oh-my-posh.ts
> +        },
Added

2022-03-29 06:47 UTC, JanDeDobbeleer commented on src/oh-my-posh.ts
> +        },
Done and tested, I moved the subcommands as args, because that makes the model clean and works as expected with autocomplete. If there's a way to inherit options from one subcommand to another I could make it even better without repeating myself.

2022-03-29 06:58 UTC, cstrnt requested changes

2022-03-29 06:58 UTC, cstrnt commented on src/oh-my-posh.ts
> +        },
I would say that this is rather an argument and not an option. Options start with `-` (or `--`). Having an argument with suggestions here is the proper way

2022-03-29 06:58 UTC, cstrnt commented on src/oh-my-posh.ts
> +        },
I think that those are arguments as well!

2022-03-29 06:58 UTC, cstrnt commented on src/oh-my-posh.ts
> +        },
Those should be arguments

2022-03-29 06:58 UTC, cstrnt commented on src/oh-my-posh.ts
> +          ],
see above

2022-03-29 06:59 UTC, JanDeDobbeleer commented on src/oh-my-posh.ts
> +        },
@cstrnt that's what I was looking for, thx!

2022-03-29 07:30 UTC, JanDeDobbeleer commented
@cstrnt @mschrage question as it's not clear to me how to achieve the following. Looking at `oh-my-posh init`, it actually has subcommands and not arguments as I do not want `--config` to show up when you haven't specified a required argument or subcommand. Right now the following command definition will still display the `--config` option, same as when defining it as a required argument (it needs to be added before the options, implying it's a subcommand in this case I presume:

```typescript
   {
      name: "init",
      description: "Initialize oh-my-posh for your shell",
      subcommands: [
        {
          name: "bash",
          description: "Initialize oh-my-posh for bash",
        },
        {
          name: "fish",
          description: "Initialize oh-my-posh for fish",
        },
        {
          name: "pwsh",
          description: "Initialize oh-my-posh for pwsh",
        },
        {
          name: "powershell",
          description: "Initialize oh-my-posh for PowerShell 5",
        },
        {
          name: "cmd",
          description: "Initialize oh-my-posh for cmd",
        },
        {
          name: "zsh",
          description: "Initialize oh-my-posh for zsh",
        },
      ],
      options: [
        {
          name: ["--config", "-c"],
          description:
            "The config file to use, example usage: 'oh-my-posh init --config ~/.config.omp.json'",
          isPersistent: true,
          args: {
            name: "CONFIG",
            description: "The configuration to use",
            template: ["filepaths", "history"],
          },
        },
        {
          name: ["--print", "-p"],
          description: "Print the init script",
        },
      ],
    },
```

To get what I want, I would need to do this:

```typescript
    {
      name: "init",
      description: "Initialize oh-my-posh for your shell",
      subcommands: [
        {
          name: "bash",
          description: "Initialize oh-my-posh for bash",
          options: [
            {
              name: ["--config", "-c"],
              description:
                "The config file to use, example usage: 'oh-my-posh init --config ~/.config.omp.json'",
              isPersistent: true,
              args: {
                name: "CONFIG",
                description: "The configuration to use",
                template: ["filepaths", "history"],
              },
            },
            {
              name: ["--print", "-p"],
              description: "Print the init script",
            },
          ],
        },
        {
          name: "fish",
          description: "Initialize oh-my-posh for fish",
          options: [
            {
              name: ["--config", "-c"],
              description:
                "The config file to use, example usage: 'oh-my-posh init --config ~/.config.omp.json'",
              isPersistent: true,
              args: {
                name: "CONFIG",
                description: "The configuration to use",
                template: ["filepaths", "history"],
              },
            },
            {
              name: ["--print", "-p"],
              description: "Print the init script",
            },
          ],
        },
        {
          name: "pwsh",
          description: "Initialize oh-my-posh for pwsh",
          options: [
            {
              name: ["--config", "-c"],
              description:
                "The config file to use, example usage: 'oh-my-posh init --config ~/.config.omp.json'",
              isPersistent: true,
              args: {
                name: "CONFIG",
                description: "The configuration to use",
                template: ["filepaths", "history"],
              },
            },
            {
              name: ["--print", "-p"],
              description: "Print the init script",
            },
          ],
        },
        {
          name: "powershell",
          description: "Initialize oh-my-posh for PowerShell 5",
          options: [
            {
              name: ["--config", "-c"],
              description:
                "The config file to use, example usage: 'oh-my-posh init --config ~/.config.omp.json'",
              isPersistent: true,
              args: {
                name: "CONFIG",
                description: "The configuration to use",
                template: ["filepaths", "history"],
              },
            },
            {
              name: ["--print", "-p"],
              description: "Print the init script",
            },
          ],
        },
        {
          name: "cmd",
          description: "Initialize oh-my-posh for cmd",
          options: [
            {
              name: ["--config", "-c"],
              description:
                "The config file to use, example usage: 'oh-my-posh init --config ~/.config.omp.json'",
              isPersistent: true,
              args: {
                name: "CONFIG",
                description: "The configuration to use",
                template: ["filepaths", "history"],
              },
            },
            {
              name: ["--print", "-p"],
              description: "Print the init script",
            },
          ],
        },
        {
          name: "zsh",
          description: "Initialize oh-my-posh for zsh",
          options: [
            {
              name: ["--config", "-c"],
              description:
                "The config file to use, example usage: 'oh-my-posh init --config ~/.config.omp.json'",
              isPersistent: true,
              args: {
                name: "CONFIG",
                description: "The configuration to use",
                template: ["filepaths", "history"],
              },
            },
            {
              name: ["--print", "-p"],
              description: "Print the init script",
            },
          ],
        },
      ],
    },
```

But surely there has to be a better way so I can reuse the options?

2022-03-29 08:58 UTC, cstrnt commented
> @cstrnt @mschrage question as it's not clear to me how to achieve the following. Looking at `oh-my-posh init`, it actually has subcommands and not arguments as I do not want `--config` to show up when you haven't specified a required argument or subcommand. Right now the following command definition will still display the `--config` option when typing `oh-my-posh init`, same as when defining it as a required argument (it needs to be added before the options, implying it's a subcommand in this case I presume:
> 
> ```ts
>    {
>       name: "init",
>       description: "Initialize oh-my-posh for your shell",
>       subcommands: [
>         {
>           name: "bash",
>           description: "Initialize oh-my-posh for bash",
>         },
>         {
>           name: "fish",
>           description: "Initialize oh-my-posh for fish",
>         },
>         {
>           name: "pwsh",
>           description: "Initialize oh-my-posh for pwsh",
>         },
>         {
>           name: "powershell",
>           description: "Initialize oh-my-posh for PowerShell 5",
>         },
>         {
>           name: "cmd",
>           description: "Initialize oh-my-posh for cmd",
>         },
>         {
>           name: "zsh",
>           description: "Initialize oh-my-posh for zsh",
>         },
>       ],
>       options: [
>         {
>           name: ["--config", "-c"],
>           description:
>             "The config file to use, example usage: 'oh-my-posh init --config ~/.config.omp.json'",
>           isPersistent: true,
>           args: {
>             name: "CONFIG",
>             description: "The configuration to use",
>             template: ["filepaths", "history"],
>           },
>         },
>         {
>           name: ["--print", "-p"],
>           description: "Print the init script",
>         },
>       ],
>     },
> ```
> 
> To get what I want, I would need to do this:
> 
> ```ts
>     {
>       name: "init",
>       description: "Initialize oh-my-posh for your shell",
>       subcommands: [
>         {
>           name: "bash",
>           description: "Initialize oh-my-posh for bash",
>           options: [
>             {
>               name: ["--config", "-c"],
>               description:
>                 "The config file to use, example usage: 'oh-my-posh init --config ~/.config.omp.json'",
>               isPersistent: true,
>               args: {
>                 name: "CONFIG",
>                 description: "The configuration to use",
>                 template: ["filepaths", "history"],
>               },
>             },
>             {
>               name: ["--print", "-p"],
>               description: "Print the init script",
>             },
>           ],
>         },
>         {
>           name: "fish",
>           description: "Initialize oh-my-posh for fish",
>           options: [
>             {
>               name: ["--config", "-c"],
>               description:
>                 "The config file to use, example usage: 'oh-my-posh init --config ~/.config.omp.json'",
>               isPersistent: true,
>               args: {
>                 name: "CONFIG",
>                 description: "The configuration to use",
>                 template: ["filepaths", "history"],
>               },
>             },
>             {
>               name: ["--print", "-p"],
>               description: "Print the init script",
>             },
>           ],
>         },
>         {
>           name: "pwsh",
>           description: "Initialize oh-my-posh for pwsh",
>           options: [
>             {
>               name: ["--config", "-c"],
>               description:
>                 "The config file to use, example usage: 'oh-my-posh init --config ~/.config.omp.json'",
>               isPersistent: true,
>               args: {
>                 name: "CONFIG",
>                 description: "The configuration to use",
>                 template: ["filepaths", "history"],
>               },
>             },
>             {
>               name: ["--print", "-p"],
>               description: "Print the init script",
>             },
>           ],
>         },
>         {
>           name: "powershell",
>           description: "Initialize oh-my-posh for PowerShell 5",
>           options: [
>             {
>               name: ["--config", "-c"],
>               description:
>                 "The config file to use, example usage: 'oh-my-posh init --config ~/.config.omp.json'",
>               isPersistent: true,
>               args: {
>                 name: "CONFIG",
>                 description: "The configuration to use",
>                 template: ["filepaths", "history"],
>               },
>             },
>             {
>               name: ["--print", "-p"],
>               description: "Print the init script",
>             },
>           ],
>         },
>         {
>           name: "cmd",
>           description: "Initialize oh-my-posh for cmd",
>           options: [
>             {
>               name: ["--config", "-c"],
>               description:
>                 "The config file to use, example usage: 'oh-my-posh init --config ~/.config.omp.json'",
>               isPersistent: true,
>               args: {
>                 name: "CONFIG",
>                 description: "The configuration to use",
>                 template: ["filepaths", "history"],
>               },
>             },
>             {
>               name: ["--print", "-p"],
>               description: "Print the init script",
>             },
>           ],
>         },
>         {
>           name: "zsh",
>           description: "Initialize oh-my-posh for zsh",
>           options: [
>             {
>               name: ["--config", "-c"],
>               description:
>                 "The config file to use, example usage: 'oh-my-posh init --config ~/.config.omp.json'",
>               isPersistent: true,
>               args: {
>                 name: "CONFIG",
>                 description: "The configuration to use",
>                 template: ["filepaths", "history"],
>               },
>             },
>             {
>               name: ["--print", "-p"],
>               description: "Print the init script",
>             },
>           ],
>         },
>       ],
>     },
> ```
> 
> But surely there has to be a better way so I can reuse the options?



So two things here:

- I'm pretty sure that this should be an argument to the init subcommand
- You can just create a variable at the top of the file that has the shared options and then use the variable down where you need it

2022-03-29 10:31 UTC, JanDeDobbeleer commented
> I'm pretty sure that this should be an argument to the init subcommand

@cstrnt but then I can still type `oh-my-posh init --config xxx` by following the suggestions which isn't allowed. You're right, as they are arguments, but how do I avoid fig from displaying options before the argument is added (given that it's required).

2022-03-29 11:43 UTC, JanDeDobbeleer commented
I think I finally nailed it, thanks all for your patience. This is an amazing tool, I just needed to get my head around how to model this correctly.

2022-03-30 18:36 UTC, mschrage approved these changes
Thanks for making all of these revisions! Congrats on your first contribution 🥳

2022-03-30 18:36 UTC, merged