feat: add args for mix run
withfig/autocomplete pull request #1078
Opened 2022-03-29 08:41 UTC by Darth-Knoppix

**What kind of change does this PR introduce?**
Improve argument suggestions for the `mix run` command based off [Mix run documentation](https://hexdocs.pm/mix/1.12/Mix.Tasks.Run.html#module-command-line-options).

**What is the current behavior?**

Fig does not suggest any args for the `mix run` command.

**What is the new behavior?**

Fig will suggest options like:
- `mix run --no-halt`
- `mix run --no-deps-check` 

**Additional info:**
- [Documentation with the options the run subcommand can take](https://hexdocs.pm/mix/1.12/Mix.Tasks.Run.html#module-command-line-options).

2022-03-29 11:14 UTC, fedeci requested changes

2022-03-29 11:14 UTC, fedeci commented on src/mix.ts
> +            description: "The file|pattern to execute",
```suggestion
            description: "The file|pattern to execute",
            template: "filepaths",
```

2022-03-29 11:14 UTC, fedeci commented on src/mix.ts
> +            name: "file",
```suggestion
            name: "file",
            template: "filepaths",
```

2022-03-29 11:14 UTC, fedeci commented on src/mix.ts
> +          description: "Does not check the Elixir version from mix.exs",
Are you sure these accept an argument?

2022-03-29 11:14 UTC, fedeci commented on src/mix.ts
> +            description: "String contianing code to execute",
```suggestion
            description: "String containing code to execute",
            isScript: true,
```

2022-03-29 11:14 UTC, fedeci commented on src/mix.ts
> +          },
```suggestion
          description: "Makes all requires parallel",
```

2022-03-29 12:49 UTC, Darth-Knoppix commented on src/mix.ts
> +            description: "The file|pattern to execute",
Thanks, I missed this in the docs 👌

2022-03-29 12:52 UTC, Darth-Knoppix commented on src/mix.ts
> +          description: "Does not check the Elixir version from mix.exs",
Ah, this was a misunderstanding. Fixing now 👍

2022-03-29 13:32 UTC, Darth-Knoppix commented
Thanks for the tips and great feedback @fedeci!

I used the `filepaths` template but added a custom `filterTemplateSuggestions` to bump up the priority for script files (.exs) as they are the most likely to be run too.

2022-03-29 19:03 UTC, mschrage commented on src/mix.ts
> +
This doesn't need to be a function - it can just be a constant.
```suggestion
const preferredFilepaths: Fig.Generator = {
    template: "filepaths",
    filterTemplateSuggestions: (paths) =>
      paths.map((path) =>
        path.name.endsWith(".exs") ? { ...path, priority: 75 } : path
      ),
}

```

2022-03-29 19:51 UTC, fedeci commented on src/mix.ts
> +
It can be also simplified with the `@fig/autocomplete-generators` package!

2022-03-30 14:00 UTC, Darth-Knoppix commented on src/mix.ts
> +
Thanks, I didn't see this either 🤦. I've simplified it based on what's in the elixir autocomplete using `@fig/autocomplete-generators` as suggested 🙏

2022-03-30 16:09 UTC, fedeci approved these changes
Thanks!

2022-03-30 16:10 UTC, merged