Add `src` by Sourcegraph
withfig/autocomplete pull request #1081
Opened 2022-03-30 15:00 UTC by jdorfman

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Feature

**What is the new behavior (if this is a feature change)?**

This adds autocomplete for users of `src` a command line interface to Sourcegraph that allows you to [search code](https://docs.sourcegraph.com/code_search) from your terminal, [create and apply batch changes](https://docs.sourcegraph.com/batch_changes), and [manage and administrate repositories, users, and more](https://docs.sourcegraph.com/admin).

**Additional info:**

I look forward to your feedback and consideration. =)

2022-03-30 18:08 UTC, fedeci requested changes
Thanks for this spec! Could you provide some descriptions to subcommands that are missing one? Also some options and subcommands accept an argument and it would be great if you could add those too!
I've seen you are using the flag go package for the cli, would you be interested in an integration that automatically generates a spec from that source code and pushes it directly to this repo?

2022-03-30 18:08 UTC, fedeci commented on src/sourcegraph-src.ts
> +      args: [
```suggestion
      subcommands: [
```

2022-03-30 18:08 UTC, fedeci commented on src/sourcegraph-src.ts
> +      args: [
```suggestion
      subcommands: [
```

2022-03-30 18:08 UTC, fedeci commented on src/sourcegraph-src.ts
> +      args: [
```suggestion
      subcommands: [
```

2022-03-30 18:08 UTC, fedeci commented on src/sourcegraph-src.ts
> +      args: {
```suggestion
      subcommands: {
```

2022-03-30 18:08 UTC, fedeci commented on src/sourcegraph-src.ts
> +            "Limit the number of results that are displayed. Only supported together with stream flag. Statistics continue to report all results",
```suggestion
            "Limit the number of results that are displayed. Only supported together with stream flag. Statistics continue to report all results",
          dependsOn: ["-stream"],
```

2022-03-30 18:55 UTC, jdorfman commented
> Thanks for this spec! Could you provide some descriptions to subcommands that are missing one? Also some options and subcommands accept an argument and it would be great if you could add those too!

Sure thing!

> I've seen you are using the flag go package for the cli, would you be interested in an integration that automatically generates a spec from that source code and pushes it directly to this repo?

Yeah that would be amazing! How can we do that?

2022-03-30 23:09 UTC, jdorfman commented on src/sourcegraph-src.ts
> +const completionSpec: Fig.Spec = {
yeah I didn't want to confuse anyone since the folder is named `src`. I can remove `sourcegraph-`, just LMK I don't want to screw anything up.

2022-03-30 23:31 UTC, jdorfman commented on src/sourcegraph-src.ts
> +        "'src login' helps you authenticate 'src' to access a Sourcegraph instance with your user credentials",
Great catch! I updated to to `"'Batch gives you a declarative structure for finding and modifying code across all of your repositories",` but now I'm getting eslint errors:

```
 ~/github/sg/autocomplete  ± (master → origin S:1 ✗)
> git commit -am "Update 'batch' description"
✔ Preparing...
⚠ Running tasks...
  ❯ Running tasks for *.ts
    ✖ eslint --fix [FAILED]
    ◼ pretty-quick --staged
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up...

✖ eslint --fix:

Oops! Something went wrong! :(

ESLint: 7.32.0

ESLint couldn't find the config "@fig/autocomplete" to extend from. Please check that the name of the config is correct.

The config "@fig/autocomplete" was referenced from the config file in "/Users/jdorfman/github/sg/autocomplete/.eslintrc.cjs".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

husky - pre-commit hook exited with code 1 (error)
```

2022-03-31 12:45 UTC, fedeci commented
> > I've seen you are using the flag go package for the cli, would you be interested in an integration that automatically generates a spec from that source code and pushes it directly to this repo?
> 
> Yeah that would be amazing! How can we do that?

First of all we have to create some kind of tool for the flag go package so that we can generate a spec in a similar way to how we do for [cobra](https://fig.io/docs/guides/autocomplete-for-teams/cobra). Then we just need to integrate it in the `src-cli` repo along with [this](https://github.com/withfig/push-to-fig-autocomplete-action) GH action I am finishing to build.

2022-03-31 12:46 UTC, fedeci commented on src/sourcegraph-src.ts
> +        "'src login' helps you authenticate 'src' to access a Sourcegraph instance with your user credentials",
Have you tried to reinstall the node_modules of the repo? using eslint configs is a pretty recent change.

2022-03-31 15:04 UTC, jdorfman commented on src/sourcegraph-src.ts
> +        "'src login' helps you authenticate 'src' to access a Sourcegraph instance with your user credentials",
That fixed it!

2022-03-31 15:11 UTC, jdorfman commented on src/sourcegraph-src.ts
> +const completionSpec: Fig.Spec = {
Fixed (I hope)

2022-04-01 09:37 UTC, fedeci approved these changes
Thanks!

2022-04-01 09:37 UTC, merged

2022-04-01 17:48 UTC, jdorfman commented
Thanks @fedeci!