feat: Add tfsec Spec
withfig/autocomplete pull request #1099
Opened 2022-04-02 19:56 UTC by dirien

Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
This PR adds the spec for tfsec and fixex #1098 
**What is the current behavior? (You can also link to an open issue here)**
-
**What is the new behavior (if this is a feature change)?**
-
**Additional info:**

2022-04-02 20:15 UTC, mschrage requested changes
Just a few tweaks to add generators for arguments. Otherwise this looks great!

2022-04-02 20:15 UTC, mschrage commented on src/tfsec.ts
> +        name: "config-file",
You could add `template: "filepaths"` here in order to provide filepath suggestions.

2022-04-02 20:15 UTC, mschrage commented on src/tfsec.ts
> +    },
This option should take an argument. (You could add `default, json, csv, checkstyle, junit, sarif` as `suggestions`)

2022-04-02 20:15 UTC, mschrage commented on src/tfsec.ts
> +      },
You could add `suggestions: [ "CRITICAL", "HIGH", "MEDIUM", "LOW"]`

2022-04-02 20:15 UTC, mschrage commented on src/tfsec.ts
> +      },
```suggestion
      args: {
        name: "outputFile",
        template: "filepaths",
        suggestCurrentToken: true,
      },
```

2022-04-02 20:15 UTC, mschrage commented on src/tfsec.ts
> +      },
```suggestion
      args: {
        name: "tfvarsFilePath",
        template: "filepaths"
      },
```

2022-04-02 20:15 UTC, mschrage commented on src/tfsec.ts
> +  },
```suggestion
  args: {
    name: "directory",
    template: "folders",
  },
```

2022-04-02 20:15 UTC, mschrage commented on src/tfsec.ts
> +      },
Is there any way to list the possible workspaces by running a script?

2022-04-02 20:15 UTC, mschrage commented on src/tfsec.ts
> +      },
```suggestion
      args: {
        name: "excludePath",
        template: "filepaths",
      },
```

2022-04-02 21:57 UTC, dirien commented on src/tfsec.ts
> +        name: "config-file",
Cool, thanks! thats great feedback! Done!

2022-04-02 21:59 UTC, dirien commented on src/tfsec.ts
> +    },
nice! done added suggestions

2022-04-02 21:59 UTC, dirien commented on src/tfsec.ts
> +      },
added suggestions! Thx

2022-04-02 22:01 UTC, dirien commented on src/tfsec.ts
> +      },
Cool, added suggestion! thx!

2022-04-02 22:02 UTC, dirien commented on src/tfsec.ts
> +      },
added suggestion!

2022-04-02 22:02 UTC, dirien commented on src/tfsec.ts
> +  },
Done!

2022-04-02 22:03 UTC, dirien commented on src/tfsec.ts
> +      },
Thanks for this! done!

2022-04-02 22:07 UTC, dirien commented on src/tfsec.ts
> +      },
I am not sure, if by workspace they mean the TF workspace. 

Let us ask @liamg or @owenrumney if could call `terraform workspace list`.

@mschrage, this would mean the spec relies on the installation of another cli to work?

2022-04-02 22:25 UTC, mschrage commented on src/tfsec.ts
> +      },
In general, we try to keep specs self-contained (eg. don't use `jq` to parse anything).  But is it fair to assume that if someone has `tfsec` downloaded, they would probably also have `terraform`?

Also worse case, if the user doesn't have `terraform` installed, the generator just errors out and doesn't show suggestions. So I think there is no downside to adding in this case.

2022-04-02 22:43 UTC, dirien commented on src/tfsec.ts
> +      },
Do you have a link to a spec, where I can lookup this kind of behaviour?

2022-04-02 22:48 UTC, mschrage commented on src/tfsec.ts
> +      },
What kind of behavior? 

Check out this link for an example generator: https://github.com/withfig/autocomplete/blob/5283ac798555ce965287ddc36425b91e181e41c8/src/brew.ts#L15

2022-04-02 22:58 UTC, dirien commented on src/tfsec.ts
> +      },
Ok perfect, @mschrage!

2022-04-03 10:17 UTC, dirien commented on src/tfsec.ts
> +      },
Hi @mschrage, worked like a charm! Thanks for the hint!

2022-04-03 10:18 UTC, dirien commented
FYI @liamg and @owenrumney

2022-04-03 10:39 UTC, fedeci approved these changes
Thanks!

2022-04-03 10:44 UTC, merged