feat: add Docker sbom spec
withfig/autocomplete pull request #1118
Opened 2022-04-07 21:07 UTC by dirien

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Fixes #1117 

**What is the current behavior? (You can also link to an open issue here)**
No sbom spec
**What is the new behavior (if this is a feature change)?**
`docker sbom` support
**Additional info:**

2022-04-07 21:21 UTC, mschrage approved these changes

2022-04-09 12:50 UTC, fedeci commented on src/docker.ts
> +          "An optional platform specifier for container image sources (e.g. 'linux/arm64', 'linux/arm64/v8', 'arm64', 'linux')",
Can you add a suggestions object to this arg containing the currently available platforms?
```ts
args: {
	name: "platform",
	suggestions: [
		"linux/arm64",
		"linux/arm64/v8",
		"arm64",
		// ...other targets
	]
}
```

2022-04-09 12:53 UTC, fedeci requested changes
Thanks @dirien, I left some comments.

2022-04-09 12:53 UTC, fedeci commented on src/docker.ts
> +          'Report output format, options=[syft-json cyclonedx-xml cyclonedx-json github-0-json spdx-tag-value spdx-json table text] (default "table")',
```suggestion
          'Report output format',
```

2022-04-09 12:53 UTC, fedeci commented on src/docker.ts
> +          '[experimental] selection of layers to catalog, options=[squashed all] (default "squashed")',
```suggestion
          '[experimental] selection of layers to catalog',
```

2022-04-09 12:53 UTC, fedeci commented on src/docker.ts
> +          name: `${i.Repository}`,
nit:
```suggestion
          name: i.Repository,
```

2022-04-09 12:53 UTC, fedeci commented on src/docker.ts
> +          name: "file",
```suggestion
          name: "file",
          template: ["filepaths"],
          suggestCurrentToken: true,
```

2022-04-10 20:10 UTC, dirien commented on src/docker.ts
> +          name: "file",
thx for the feedback -> done :)

2022-04-10 20:10 UTC, dirien commented on src/docker.ts
> +          name: `${i.Repository}`,
thx for the feedback -> done :)

2022-04-10 20:11 UTC, dirien commented on src/docker.ts
> +          '[experimental] selection of layers to catalog, options=[squashed all] (default "squashed")',
thx for the feedback -> done :)

2022-04-10 20:11 UTC, dirien commented on src/docker.ts
> +          'Report output format, options=[syft-json cyclonedx-xml cyclonedx-json github-0-json spdx-tag-value spdx-json table text] (default "table")',
thx for the feedback -> done :)

2022-04-10 20:12 UTC, dirien commented
hi @fedeci, thanks for reviewing the PR. Did you suggested changes. :)

2022-04-10 21:49 UTC, merged