feat: Add cloudflared spec (withfig#1091)
withfig/autocomplete pull request #1137
Opened 2022-04-09 19:44 UTC by diogofalken

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature.

**What is the current behavior? (You can also link to an open issue here)**
Closes #1091, missing spec of cloudflared.

**What is the new behavior (if this is a feature change)?**
Support for cloudflared CLI

2022-04-09 20:31 UTC, fedeci commented
Was this generated through some tool or was it done manually?

2022-04-09 20:55 UTC, diogofalken commented
> Was this generated through some tool or was it done manually?

@fedeci it was done manually.

2022-04-10 09:42 UTC, fedeci commented
Thanks for all this work! It will be huge to review 😄

2022-04-10 09:45 UTC, diogofalken commented
I am sorry, it was really a painful work 😅
Everything you see that I can improve just @ me, it's my first contribution 😁

2022-04-10 10:03 UTC, fedeci requested changes
Thanks it looks really good! I left a few comments about thing to change. Great first contribution man🎉

2022-04-10 10:03 UTC, fedeci commented on src/cloudflared.ts
> +          { name: ">3", description: "High" },
If we insert >3 the CLI will probably reject that value.
```suggestion
          { name: "3", description: "High" },
```

2022-04-10 20:14 UTC, diogofalken commented on src/cloudflared.ts
> +        },
That's true, do you think it's better to get it out and add a `dependsOn` on all of this?

2022-04-10 20:46 UTC, diogofalken commented on src/cloudflared.ts
> +            "Name of trace output file, generated when cloudflared stops. [$TUNNEL_TRACE_OUTPUT]",
I didn't know, just tried it out and it doesn't 🥲

2022-04-11 17:35 UTC, diogofalken commented on src/cloudflared.ts
> +    },
Fixed in 27b7ed14ee2f094b815dd6b26406c16ef9ebca26.

2022-04-11 17:35 UTC, diogofalken commented on src/cloudflared.ts
> +          name: ["--allow-request", "-ar"],
It was a typo, thanks! Fixed in 27b7ed14ee2f094b815dd6b26406c16ef9ebca26

2022-04-11 17:35 UTC, diogofalken commented on src/cloudflared.ts
> +            description: "Config file",
Added it on 27b7ed14ee2f094b815dd6b26406c16ef9ebca26

2022-04-11 17:35 UTC, diogofalken commented on src/cloudflared.ts
> +        },
Added `dependsOn` on all occurrences of this issue in 27b7ed14ee2f094b815dd6b26406c16ef9ebca26

2022-04-14 15:39 UTC, diogofalken commented
@fedeci if you think something else needs to be changed @ me. Thank you :)

2022-04-19 12:59 UTC, fedeci approved these changes
Great! Thanks for this spec and I'm sorry for being late on merging this one!

2022-04-19 12:59 UTC, merged