feat(dtm): add `dtm` spec
withfig/autocomplete pull request #1140
Opened 2022-04-11 01:54 UTC by imxw

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
`dtm` command are not currently supported

**What is the new behavior (if this is a feature change)?**
Autocompletion support for `dtm`

**Additional info:**
`dtm` project found [here](https://github.com/devstream-io/devstream)

2022-04-11 20:44 UTC, fedeci requested changes
Thanks, there are a couple nits but overall it looks good!

2022-04-11 20:44 UTC, fedeci commented on src/dtm.ts
> +        generators: cmds,
```suggestion
        templates: "help",
```

2022-04-11 20:44 UTC, fedeci commented on src/dtm.ts
> +          },
Suggestion: if this `--config` only accepts certain file extensions you can use the `@fig/autocomplete-generators` package.

2022-04-12 02:04 UTC, imxw commented on src/dtm.ts
> +        generators: cmds,
Thanks for your help

2022-04-12 02:05 UTC, mschrage approved these changes
This looks great. Thanks so much for contributing @imxw!

2022-04-12 02:05 UTC, imxw commented on src/dtm.ts
> +          },
Thanks for your help!

2022-04-12 05:06 UTC, imxw commented
> Looks like these flags are global:
> 
> ```
>   -f, --config-file string   config file (default "config.yaml")
>   -d, --debug                debug level log
>   -p, --plugin-dir string    plugins directory (default ".devstream")
>   -y, --yes                  apply/delete directly without confirmation
> ```
> 
> Could you add these to the top-level `options` array, and give them all `isPersistent: true`?
> 
> I think this would be the last change! Looks good 🙂

Thanks for your rigor!  With more subcommands, these flags can no longer be used globally. We will move them to the appropriate subcommands in the next version.

2022-04-12 08:09 UTC, merged

2022-04-12 08:39 UTC, imxw commented
> @imxw would you be interested in having automatic updates and versioning for this completion spec? I've seen you are using cobra in your CLI and we provide a cobra integration for autogenerating specs. I can open a PR in the next days, WDYT? I am merging this one in the meanwhile, thanks again!

Yes, I've noticed the cobra integration. Once I remove some unnecessary global flags from `dtm`, I'll use it.