Add support for workspaces.packages
withfig/autocomplete pull request #1141
Opened 2022-04-11 01:55 UTC by elevatebart

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Bug fix

**What is the current behavior? (You can also link to an open issue here)**

#880

**What is the new behavior (if this is a feature change)?**

`yarn workspace` now works with the full specification
A good testing repo to test this is [cypress](https://github.com/cypress-io/cypress)

2022-04-11 02:51 UTC, elevatebart commented
Follow-up to @bolshoytoster PR 

- #887

2022-04-11 20:21 UTC, fedeci requested changes
This doesn't work for yarn@2 or yarn@3 ([reference](https://github.com/withfig/autocomplete/pull/887#pullrequestreview-866993143))

2022-04-11 20:31 UTC, fedeci requested changes
Thanks for this PR @elevatebart!

2022-04-11 20:31 UTC, fedeci commented on src/yarn.ts
> +                  name: `${name} - scripts`,
This `generateSpec` is not required and the `postProcess` can be added directly to the outer `generateSpec` args.

2022-04-11 20:31 UTC, fedeci commented on src/yarn.ts
> +                        strategy: "stale-while-revalidate" as const,
Why is `as const` required here?

2022-04-11 21:01 UTC, elevatebart commented on src/yarn.ts
> +                        strategy: "stale-while-revalidate" as const,
TypeScript refuses to consider `"stale-while-revalidate"` as a constant unless you tell it. 
By default, it considers it a modifiable string.

2022-04-11 21:05 UTC, elevatebart commented on src/yarn.ts
> +                  name: `${name} - scripts`,
Fixed it ;)

2022-04-11 21:34 UTC, fedeci commented on src/yarn.ts
> +                        strategy: "stale-while-revalidate" as const,
That's super strange. It is statically typed and ts should recognize it correctly as an accepted string.

2022-04-11 21:39 UTC, elevatebart commented on src/yarn.ts
> +                        strategy: "stale-while-revalidate" as const,
It started mattering in typescript 4 for enum literal types.
I could also type the whole created object if you prefer.

2022-04-11 21:42 UTC, elevatebart commented on src/yarn.ts
> +                        strategy: "stale-while-revalidate" as const,
I did this in 6da6b53

2022-04-12 08:19 UTC, fedeci commented
Still not working for v2 and v3, see the examples below:
- For yarn@1 this is the output of `yarn workspaces info --silent`
```json
{
  "@fig/autocomplete-generators": {
    "location": "packages/autocomplete-generators",
    "workspaceDependencies": [
      "@withfig/autocomplete-types"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@fig/autocomplete-helpers": {
    "location": "packages/autocomplete-helpers",
    "workspaceDependencies": [
      "@withfig/autocomplete-types"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@fig/autocomplete-merge": {
    "location": "packages/autocomplete-merge",
    "workspaceDependencies": [],
    "mismatchedWorkspaceDependencies": []
  },
  "@withfig/autocomplete-tools": {
    "location": "packages/autocomplete-tools",
    "workspaceDependencies": [
      "@withfig/autocomplete-types"
    ],
    "mismatchedWorkspaceDependencies": [
      "@withfig/commander",
      "@fig/autocomplete-helpers",
      "@fig/autocomplete-merge"
    ]
  },
  "@withfig/autocomplete-types": {
    "location": "packages/autocomplete-types",
    "workspaceDependencies": [],
    "mismatchedWorkspaceDependencies": []
  },
  "@fig/eslint-config-autocomplete": {
    "location": "packages/eslint-config-autocomplete",
    "workspaceDependencies": [
      "@withfig/eslint-plugin-fig-linter"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@withfig/eslint-plugin-fig-linter": {
    "location": "packages/eslint-plugin-fig-linter",
    "workspaceDependencies": [],
    "mismatchedWorkspaceDependencies": []
  },
  "@withfig/oclif": {
    "location": "packages/oclif",
    "workspaceDependencies": [
      "@withfig/autocomplete-types"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@withfig/commander": {
    "location": "packages/commander",
    "workspaceDependencies": [
      "@withfig/autocomplete-types"
    ],
    "mismatchedWorkspaceDependencies": []
  }
}
```

- For yarn@2 and yarn@3 this is the output of `yarn workspaces list --json`
```sh
{"location":".","name":"babel"}
{"location":"benchmark","name":"@babel/benchmark"}
{"location":"codemods/babel-plugin-codemod-object-assign-to-object-spread","name":"@babel/plugin-codemod-object-assign-to-object-spread"}
{"location":"codemods/babel-plugin-codemod-optional-catch-binding","name":"@babel/plugin-codemod-optional-catch-binding"}
{"location":"eslint/babel-eslint-config-internal","name":"@babel/eslint-config-internal"}
{"location":"eslint/babel-eslint-parser","name":"@babel/eslint-parser"}
{"location":"eslint/babel-eslint-plugin","name":"@babel/eslint-plugin"}
{"location":"eslint/babel-eslint-plugin-development","name":"@babel/eslint-plugin-development"}
{"location":"eslint/babel-eslint-plugin-development-internal","name":"@babel/eslint-plugin-development-internal"}
{"location":"eslint/babel-eslint-shared-fixtures","name":"@babel/eslint-shared-fixtures"}
{"location":"eslint/babel-eslint-tests","name":"@babel/eslint-tests"}
{"location":"packages/babel-cli","name":"@babel/cli"}
{"location":"packages/babel-code-frame","name":"@babel/code-frame"}
{"location":"packages/babel-compat-data","name":"@babel/compat-data"}
{"location":"packages/babel-core","name":"@babel/core"}
{"location":"packages/babel-generator","name":"@babel/generator"}
{"location":"packages/babel-helper-annotate-as-pure","name":"@babel/helper-annotate-as-pure"}
```

As you can see they changed both the format, the command and the flags, I would get the correct output relative to the used version, convert it to a common format like `type Workspace = { name: string, path: string }` and then generate subcommands and args relative to that.

2022-04-13 14:39 UTC, fedeci requested changes
Here are some other suggested changes. We definitely need to implement cache for `generateSpec` too, for the moment this is great!

2022-04-13 14:39 UTC, fedeci commented on src/yarn.ts
> +        const isYarnV1 = /^1\.\d+\.\d+/.test(version);
nit: this is more performant
```suggestion
        const isYarnV1 = version.startsWith('1');
```

2022-04-13 14:39 UTC, fedeci commented on src/yarn.ts
> +                JSON.parse(out) as Record<string, { location: string }>
```suggestion
                JSON.parse(out.slice(out.indexOf("\n") + 1, out.lastIndexOf('\n'))) as Record<string, { location: string }>
```

2022-04-13 14:39 UTC, fedeci commented on src/yarn.ts
> +                    strategy: "stale-while-revalidate",
```suggestion
                    strategy: "stale-while-revalidate",
                    ttl: 60_000, // 60s
```

2022-04-13 15:22 UTC, elevatebart commented on src/yarn.ts
> +                JSON.parse(out) as Record<string, { location: string }>
What would be a good test for this change?

2022-04-13 15:26 UTC, elevatebart commented
@fedeci one last question I think we are ready to go.

2022-04-13 15:28 UTC, fedeci commented on src/yarn.ts
> +                JSON.parse(out) as Record<string, { location: string }>
Any yarn@1 workspace. There are some header and footer information printed along with the json.

2022-04-13 15:29 UTC, fedeci approved these changes
Thanks! Great work @elevatebart!

2022-04-13 15:31 UTC, elevatebart commented on src/yarn.ts
> +                JSON.parse(out) as Record<string, { location: string }>
not with the `--silent` option (at least from what I saw)

2022-04-13 15:33 UTC, elevatebart commented on src/yarn.ts
> +                JSON.parse(out) as Record<string, { location: string }>
OK it does...

2022-04-13 15:51 UTC, fedeci commented on src/yarn.ts
> +                JSON.parse(out) as Record<string, { location: string }>
😅yeah

2022-04-13 15:52 UTC, merged