feat: add `hexo` completion spec
withfig/autocomplete pull request #1143
Opened 2022-04-12 14:20 UTC by patrick330602

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

feature: autocomplete for `hexo-cli` for [Hexo](https://hexo.io)

**What is the current behavior? (You can also link to an open issue here)**

does not provide autocomplete for hexo-cli

**What is the new behavior (if this is a feature change)?**

provides autocomplete for hexo-cli commands

2022-04-13 05:49 UTC, SeparateRecords requested changes
Amazing!! Just one quick change and then I think it's ready to merge!

2022-04-13 05:49 UTC, SeparateRecords commented on src/hexo.ts
> +        description: "draft for " + title,
Just a quick case change 🙂 (we try to keep to "conventional descriptions", eg. upper case first letters, no periods at the end)
```suggestion
        description: "Draft for " + title,
```

2022-04-13 06:49 UTC, patrick330602 commented on src/hexo.ts
> +        description: "draft for " + title,
Gotcha, and updated the description

2022-04-13 07:10 UTC, SeparateRecords commented on src/hexo.ts
> +  ],
One more thing, these look like they're global options - could you add `isPersistent` to them? Sorry for that 😅

2022-04-13 13:15 UTC, patrick330602 commented on src/hexo.ts
> +  ],
Gotcha and added

2022-04-14 00:06 UTC, SeparateRecords approved these changes

2022-04-14 00:08 UTC, SeparateRecords commented
Thanks so much for adding this! Looks good 👍

2022-04-14 00:08 UTC, merged