docs: update README
withfig/autocomplete pull request #1173
Opened 2022-04-22 08:14 UTC by SeparateRecords

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2022-04-22 17:44 UTC, fedeci requested changes

2022-04-22 17:44 UTC, fedeci commented on README.md
> +[![Badge: Sign up (public beta)](https://img.shields.io/badge/signup-public%20beta-blueviolet)](https://fig.io?ref=github_autocomplete)
Are we still in beta?

2022-04-22 17:44 UTC, fedeci commented on README.md
> +npm run dev
We use `npm run dev` only in development, I think this is more appropriate for the scope of the guide
```suggestion
npm run build
```

2022-04-22 17:44 UTC, fedeci commented on README.md
> +[Join the Discord server](https://fig.io/community) and we'll debug it. Fixing Fig in your setup will also fix it for other people too! 🙂
```suggestion
[Join the Discord server](https://fig.io/community) and we'll debug it. Fixing Fig in your setup will fix it for other people too! 🙂
```

2022-04-22 17:44 UTC, fedeci commented on README.md
> +Not yet, Fig is only available on MacOS for now. [Windows](https://github.com/withfig/fig/issues/35) and [Linux](https://github.com/withfig/fig/issues/34) is in progress!
```suggestion
Not yet, Fig is only available on MacOS for now. [Windows](https://github.com/withfig/fig/issues/35) and [Linux](https://github.com/withfig/fig/issues/34) support is in progress!
```

2022-04-22 17:44 UTC, fedeci commented on README.md
> +[Nova]: https://nova.app/
Are all this square brackets required?

2022-04-22 19:42 UTC, mschrage approved these changes
Lgtm!

2022-04-22 19:43 UTC, mschrage commented on README.md
> +[![Badge: Sign up (public beta)](https://img.shields.io/badge/signup-public%20beta-blueviolet)](https://fig.io?ref=github_autocomplete)
Yup - still lots to improve :-)

2022-04-25 01:41 UTC, SeparateRecords commented on README.md
> +[Nova]: https://nova.app/
The links could be inline, but I think it's a lot easier to read when moved out. Not entirely sure the links are necessary in the first place, but I kept them since that's what was there before. Maybe it'll help people find a cool terminal they didn't know about before 😄

2022-04-25 10:54 UTC, fedeci commented on README.md
> +[Nova]: https://nova.app/
Oh cool that's a markdown feature, I hadn't thought you could separate urls from the text.

2022-04-25 10:56 UTC, fedeci approved these changes
Great!

2022-04-25 10:57 UTC, merged