feat(steadybit): add spec
withfig/autocomplete pull request #1174
Opened 2022-04-22 14:27 UTC by bripkens

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

New autocompletion spec for the [steadybit CLI](https://github.com/steadybit/cli)

**What is the current behavior? (You can also link to an open issue here)**

No autocompletion :trollface: 

**What is the new behavior (if this is a feature change)?**

Auto completion! ❤️ 

**Additional info:**

2022-04-22 18:06 UTC, fedeci requested changes
Thanks! There is just a small typo to fix.

2022-04-22 18:06 UTC, fedeci commented on src/steadybit.ts
> +      description: "Set the versions in policu and task references",
```suggestion
      description: "Set the versions in policies and task references",
```

2022-04-22 18:57 UTC, bripkens commented on src/steadybit.ts
> +      description: "Set the versions in policu and task references",
whoops, good catch. Thank you @fedeci!

2022-04-22 19:24 UTC, mschrage commented
Also @bripkens it looks like `steadybit` uses commander.js to build the CLI. You might be able to generate this spec automatically using our [integration with commander.js](https://fig.io/docs/guides/autocomplete-for-teams/commander).

2022-04-23 09:11 UTC, fedeci approved these changes

2022-04-23 09:11 UTC, merged