feat: add qodana spec
withfig/autocomplete pull request #1189
Opened 2022-04-25 16:07 UTC by bxb100

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

feature

**What is the current behavior? (You can also link to an open issue here)**

add spec

**What is the new behavior (if this is a feature change)?**

add spec

**Additional info:**

qodana cli: https://github.com/JetBrains/qodana-cli

2022-04-25 16:51 UTC, fedeci requested changes
I left a few comments, thanks for opening this PR!

2022-04-25 16:51 UTC, fedeci commented on src/qodana.ts
> +      exclusiveOn: exclusives,
This exclusive won't have any effect because none of the options listed are options of the `quodana` command itself but are options of its subcommands.
```suggestion
```

2022-04-25 16:51 UTC, fedeci commented on src/qodana.ts
> +            "Send the inspection report to Qodana Cloud, requires the '--token' option to be specified",
```suggestion
            "Send the inspection report to Qodana Cloud, requires the '--token' option to be specified",
          dependsOn: ["--token"],
```

2022-04-25 16:51 UTC, fedeci commented on src/qodana.ts
> +          description:
```suggestion
          isRepeatable: true,
          description:
```

2022-04-25 16:51 UTC, fedeci commented on src/qodana.ts
> +          name: ["-e", "--env"],
```suggestion
          name: ["-e", "--env"],
          isRepeatable: true,
```

2022-04-25 16:51 UTC, fedeci commented on src/qodana.ts
> +  "--sarif-file",
nit:
`exclusiveOn` does not require both the long and short options to be mentioned, I would remove "duplicates" because of maintainability.
e.g. `--help` is enough and `-h` can be omitted

2022-04-25 17:52 UTC, bxb100 commented on src/qodana.ts
> +      exclusiveOn: exclusives,
Thank review, is it any way to avoid type `option + space` not showing other subcommands or options behind?

2022-04-25 18:42 UTC, fedeci commented on src/qodana.ts
> +  "--sarif-file",
Likely `isPersistent` does not work correctly with `exclusiveOn`, I'll fix it!

2022-04-26 14:45 UTC, fedeci commented on src/qodana.ts
> +      exclusiveOn: exclusives,
I don't think anyone will ever add commands or other flags after `--version`, but is seems like a good addition for the future!

2022-04-26 14:47 UTC, fedeci approved these changes
Thanks!

2022-04-26 14:47 UTC, merged