feat: add mosh completion spec
withfig/autocomplete pull request #1208
Opened 2022-05-05 18:46 UTC by brandonleon

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature, new completion spec for mosh.

**What is the current behavior? (You can also link to an open issue here)**
missing completion for mosh, mobile shell

**What is the new behavior (if this is a feature change)?**
new completion spec

**Additional info:**

2022-05-05 19:38 UTC, mschrage commented on src/mosh.ts
> +    },
Do these options take an argument?

2022-05-06 17:25 UTC, fedeci requested changes
Thanks for this spec 🚀! I left a couple comments. Can you also run `npm run lint:fix` before pushing so that we can get the CI not to fail?

2022-05-06 17:25 UTC, fedeci commented on src/mosh.ts
> +    },
```suggestion
      name: "--experimental-remote-ip",
      description: "Select the method for discovering the remote IP address to use for mosh",
      requiresSeparator: true,
      args: {
        name: "method",
        suggestions: ["local", "remote", "proxy"],
        default: "proxy",
      },
    },
```

2022-05-06 17:25 UTC, fedeci commented on src/mosh.ts
> +      name: ["--ssh="],
```suggestion
      name: "--ssh",
      requiresSeparator: true,
      args: {
        name: "command",
        isCommand: true,
      },
```

2022-05-06 17:25 UTC, fedeci commented on src/mosh.ts
> +    },
I wonder if it's better to keep these options separate or to merge them and then duplicate `-4` and `-6`.
/cc @SeparateRecords @mschrage WDYT?

2022-05-06 17:25 UTC, fedeci commented on src/mosh.ts
> +};
You can avoid to duplicate these generators and import them from the ssh spec:
```suggestion
import { knownHosts, configHosts } from "./ssh"
```

2022-05-06 20:59 UTC, brandonleon commented on src/mosh.ts
> +    },
Agreed

2022-05-06 21:01 UTC, brandonleon commented on src/mosh.ts
> +};
I missed this feature. I like this method much better.

2022-05-06 21:04 UTC, brandonleon commented on src/mosh.ts
> +    },
I considered that as well. I decided to stick to how the --help had it laid out, but that's not to say collapsing it all into -4 and -6 isn't a better option. 

I'm actually leaning toward your suggestion of making it simpler.

2022-05-06 21:57 UTC, mschrage commented on src/mosh.ts
> +    },
I think these options should be split out. Any option that has a `=` character in the name is really is the combination of _an option_ and _an argument_.

2022-05-07 15:49 UTC, fedeci commented on src/mosh.ts
> +    },
Let's merge them in a single option + argument then!

2022-05-07 19:20 UTC, brandonleon commented on src/mosh.ts
> +    },
I'll get that done this evening.

2022-05-08 10:42 UTC, fedeci requested changes
Great, a couple more changes and we are done!

2022-05-08 10:42 UTC, fedeci commented on src/mosh.ts
> +      description: "Aggressively echo even when incorrect",
Could you apply the same changes of `--family` to `--predict` too?

2022-05-08 10:42 UTC, fedeci commented on src/mosh.ts
> +      description: "Network Type",
If an equals is required between the option and the argument you should add this option:
```suggestion
      description: "Network Type",
      requiresSeparator: true,
```

2022-05-08 10:42 UTC, fedeci commented on src/mosh.ts
> +        description: "Autodetect network type for single-family hosts only",
```suggestion
        name: "type",
```

2022-05-09 06:17 UTC, brandonleon commented
Will fix the last few errors tomorrow.

2022-05-09 23:04 UTC, fedeci approved these changes
Thanks!

2022-05-09 23:07 UTC, merged