feat: update mob completion spec
withfig/autocomplete pull request #1209
Opened 2022-05-07 11:50 UTC by thmuch

Updates the "mob" completion spec with frequently used, but undocumented abbreviations of some subcommands.

2022-05-07 15:51 UTC, fedeci requested changes
Thanks! I left a comment to resolve before merging this.

2022-05-07 15:51 UTC, fedeci commented on src/mob.ts
>        description: "Show help",
This needs to be separated to an option and a subcommand.

2022-05-07 16:36 UTC, thmuch commented on src/mob.ts
>        description: "Show help",
@fedeci Thanks for your review!

Actually, these "options" aren't really options, but just aliases for the subcommands. I had a look at the [source code](https://github.com/remotemobprogramming/mob/blob/cf479c3018dcabb3c05f09f1a3f727c314113484/mob.go#L775) of the "mob" tool: `--version`, `-v`, `--help`and `-h` cannot be used as options, they're just there for convenience.

Should I better remove them from the completion spec (if this is a problem for Fig in any way)?

2022-05-07 18:38 UTC, fedeci commented on src/mob.ts
>        description: "Show help",
It makes sense they cannot be used as options as it makes no sense to combine them with anything else and I don't think anyone will ever try to use them along with other options. We may leave them as subcommands if they are correctly suggested right now, but I am concerned for future changes to the engine that may lead to errors with them, so that's why I prefer to have them under options.
Probably a more appropriate solution would be to create a property that only suggest `--help` and `--version` when nothing else has been inserted, I'll work on that in the future.

2022-05-07 20:32 UTC, thmuch commented on src/mob.ts
>        description: "Show help",
Thinking about it... These pseudo options are there just for convenience if someone tries the usual help and version options.

Since we have Fig suggest the `version` and `help`subcommands, I think I can safely remove these pseudo options (which aren't documented anyway). I'll do that tomorrow.

Later on (in a separate PR) I'll add them as options, once the new property is available.

For this PR, having the one-letter abbreviations of the other subcommands in far more important.

2022-05-08 10:36 UTC, fedeci commented on src/mob.ts
>        description: "Show help",
👍

2022-05-08 10:36 UTC, fedeci approved these changes
Thanks!

2022-05-08 10:36 UTC, merged