Create nylas.ts (Nylas CLI)
withfig/autocomplete pull request #1218
Opened 2022-05-09 17:29 UTC by atejada

Nylas CLI Autocomplete

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2022-05-09 23:08 UTC, fedeci reviewed
Has the spec been generated through some tool? It will be easier to review that instead of the spec itself

2022-05-09 23:08 UTC, fedeci commented on package.json
> +    "pretty-quick": "pretty-quick"
This can be either removed as can be run through `yarn pretty-quick` and `npx pretty-quick` or can be documented under the "fig" property in the package.json.

2022-05-10 09:35 UTC, atejada commented on package.json
> +    "pretty-quick": "pretty-quick"
@fedeci I generated the spec manually. I went through every Nylas CLI command and generated the subcommands and options. Should I delete the "pretty-quick" line? I wasn't sure so I added it according to Pretty-quick instructions...

2022-05-10 14:04 UTC, fedeci commented on package.json
> +    "pretty-quick": "pretty-quick"
I would honestly remove it.

2022-05-10 16:10 UTC, fedeci commented on src/nylas.ts
> +                      name: "--display_columns",
This accepts an optional argument

2022-05-10 16:24 UTC, fedeci requested changes
Thanks for the PR! I left a few comments of things to adjust throughout the spec.

2022-05-10 16:24 UTC, fedeci commented on src/nylas.ts
> +                    {
If all the subcommands allow the `--help` property you can just add it once in the root command along with [`isPersistent: true`](https://fig.io/docs/reference/option#ispersistent)

2022-05-10 16:24 UTC, fedeci commented on src/nylas.ts
> +                  options: [
Some of the options hereby seem to accept some kind of argument.
e.g. --display_columns, --started_after, etc...

2022-05-10 16:24 UTC, fedeci commented on src/nylas.ts
> +                    "Request body (or use < to redirect a JSON file)",
This accepts an optional argument.

2022-05-10 16:24 UTC, fedeci commented on src/nylas.ts
> +                  name: "--display_columns",
`--display_columns` appears to be persistent like `--help`, right?

2022-05-10 16:24 UTC, fedeci commented on src/nylas.ts
> +                  name: "id",
`id` is likely an argument of `delete` instead of a subcommand, right?
I think it will be used like this: `nylas api drafts delete <id> [options]`.
In this case the structure should be 
```js
subcommands: [
            {
              name: "delete",
              description: "Delete a Draft",
              args: { name: "id" },
              options: [
                  // delete options
              ]
```

2022-05-10 19:34 UTC, mschrage commented
@atejada btw how is the `nylas` CLI implemented? Do you use any CLI framework, like `commander.js` or `oclif`, to handle parsing?

2022-05-12 14:47 UTC, atejada commented on src/nylas.ts
> +                      name: "--display_columns",
Fixed

2022-05-12 14:48 UTC, atejada commented on src/nylas.ts
> +                  options: [
I went through everything and added what was missing

2022-05-12 14:48 UTC, atejada commented on src/nylas.ts
> +                    "Request body (or use < to redirect a JSON file)",
Fixed

2022-05-12 14:49 UTC, atejada commented on src/nylas.ts
> +                  name: "--display_columns",
I would say on 90% of the cases...so I just make it persistent...

2022-05-12 14:49 UTC, atejada commented on src/nylas.ts
> +                  name: "id",
Thanks! Fix that across all the spec

2022-05-12 14:50 UTC, atejada commented
@mschrage I asked the product owner and he told me they use https://github.com/spf13/cobra

2022-05-12 15:24 UTC, atejada commented
I'm planning to build a tool to automate the spec generation...don't want to build by hand every time there's additions to the CLI 😅

2022-05-12 22:46 UTC, fedeci commented
We already provide a cobra integration. Just wait a couple of days that we update our docs, then I'll ping you!

2022-05-13 02:26 UTC, atejada commented
Awesome! Can't wait 😎

2022-05-24 16:18 UTC, fedeci commented
Yeah, sorry about the delay! https://fig.io/docs/guides/integrating/integrations/cobra

2022-05-25 20:30 UTC, fedeci commented
Great @atejada, can I ask you what difficulties have you encountered? I am not a Go developer either and would love to hear more about how we can improve DX!

2022-05-25 20:39 UTC, fedeci requested changes
Some other stuff to fix before merging, sorry for the delay and thanks again for the spec!

2022-05-25 20:39 UTC, fedeci commented on src/nylas.ts
> +      name: ["--display_columns", ""],
```suggestion
      name: "--display_columns",
```

2022-05-25 20:39 UTC, fedeci commented on src/nylas.ts
> +        "(optional) A comma separated list of column headers to display for the table output",
```suggestion
        "(optional) A comma separated list of column headers to display for the table output",
      args: {
        name: "headers",
        isOptional: true
      },
```

2022-05-25 20:39 UTC, fedeci commented on src/nylas.ts
> +                },
These options cannot have the `?...` metadata there but it should be added to the description or removed

2022-05-26 00:15 UTC, atejada reviewed
Changes accepted

2022-05-26 00:17 UTC, atejada commented on src/nylas.ts
> +                },
That should be fixed. I can see it's on the description.

2022-05-26 00:19 UTC, atejada commented on src/nylas.ts
> +      name: ["--display_columns", ""],
This should be fixed already

2022-05-26 00:27 UTC, atejada commented on src/nylas.ts
> +        "(optional) A comma separated list of column headers to display for the table output",
Done

2022-05-26 00:29 UTC, atejada commented
@fedeci Well...mostly with Cobra installation...needed Cobra-Cli, then with compiling the Nylas CLI... "generate-fig-spec" worked like a charm 🥳

2022-05-26 01:33 UTC, atejada commented on src/nylas.ts
> +        "(optional) A comma separated list of column headers to display for the table output",
I submitted the changes

2022-05-26 09:29 UTC, fedeci commented
> @fedeci Well...mostly with Cobra installation...needed Cobra-Cli, then with compiling the Nylas CLI... "generate-fig-spec" worked like a charm 🥳

Not our business I suppose😁

2022-05-26 11:01 UTC, atejada commented
@fedeci Yup 😉 You're making a fantastic job with @fig-io 😁

2022-05-26 14:47 UTC, fedeci commented on src/nylas.ts
> +                },
Yeah sorry I reviewed a single commit instead of the whole PR 🤦‍♂️

2022-05-26 17:20 UTC, atejada commented on src/nylas.ts
> +                },
No worries 😂 Happens to me too 😁

2022-05-26 17:25 UTC, atejada commented on src/nylas.ts
> +        "(optional) A comma separated list of column headers to display for the table output",
No worries...although I prefer just to fix things and submit a new commit...so...should it be like this?

                    {
                      name: "--display_columns",
                      description:
                        "(optional) A comma separated list of column headers to display for the table output",
                      args: {
                        name: "headers",
                      },
                      isOptional: true,
                    },

2022-05-26 19:12 UTC, fedeci commented on src/nylas.ts
> +        "(optional) A comma separated list of column headers to display for the table output",
Options are already optional so isOptional there is not needed:
```
                {
                  name: "--display_columns",
                  description:
                    "A comma separated list of column headers to display for the table output",
                  args: {
                    name: "headers",
                  },
                },

```

2022-05-27 03:10 UTC, atejada commented on src/nylas.ts
> +        "(optional) A comma separated list of column headers to display for the table output",
Gotcha 😄 Removed all instances of isOption from "--display_colums" 😉

2022-05-27 03:12 UTC, atejada commented
@fedeci New commit submitted with **isOptional** removed for all instances of  **--display_colums**

2022-05-27 05:42 UTC, SeparateRecords submitted a review, later dismissed
Looks good! Couple places where we can add some polish but aside from that it looks ready to merge

2022-05-27 05:42 UTC, SeparateRecords commented on src/nylas.ts
> +            },
Looks like there's a set of known valid strings for this argument - would you be able to add them all as a `suggestions` list? No worries if that's an unreasonable amount though 😅

2022-05-27 05:42 UTC, SeparateRecords commented on src/nylas.ts
> +    },
Same with this arg, looks like there are some known values for it, could you make a `suggestions` array with them?

2022-05-27 05:42 UTC, SeparateRecords commented on src/nylas.ts
> +      },
```suggestion
      args: {
        name: "output",
        default: "json",
        suggestions: ["json", "table"],
      },
```

2022-05-27 05:42 UTC, SeparateRecords commented on src/nylas.ts
> +      },
```suggestion
      args: {
        name: "config_file",
        template: "filepaths",
      },
```

2022-05-27 05:42 UTC, SeparateRecords commented on src/nylas.ts
> +      },
```suggestion
      args: {
        name: "config_dir",
        default: "/Users/blag/.nylas",
        template: "folders",
      },
```

2022-05-27 19:06 UTC, atejada commented on src/nylas.ts
> +            },
Ain't no list long enough 😂 Added them as suggestions 😉

2022-05-27 19:06 UTC, atejada commented on src/nylas.ts
> +    },
Added 😀

2022-05-27 19:06 UTC, atejada commented on src/nylas.ts
> +      },
Added 😀

2022-05-27 19:06 UTC, atejada commented on src/nylas.ts
> +      },
Added 😀

2022-05-27 19:06 UTC, atejada commented on src/nylas.ts
> +      },
Added 😀

2022-05-27 19:07 UTC, atejada commented
@SeparateRecords All suggestions done 🥳

2022-05-28 18:54 UTC, fedeci commented on src/nylas.ts
> +      },
That default value is wrong cause it depends on user's account name:
```js
args: {
        name: "config_dir",
        default: "~/.nylas",
        template: "folders",
      },
```

2022-05-28 20:19 UTC, atejada commented on src/nylas.ts
> +      },
You're right 🤦‍♂️ Will fix it 😅

2022-05-29 09:43 UTC, atejada commented on src/nylas.ts
> +      },
All done @fedeci 😉

2022-05-29 09:44 UTC, atejada commented
@fedeci @SeparateRecords I hope everything is looking good now 😁

2022-05-29 11:22 UTC, fedeci approved these changes
Nice, thanks! 🚀

2022-05-29 11:24 UTC, merged

2022-06-03 18:31 UTC, ashryanbeats commented
Hi @fedeci! Thanks for working with @atejada on this. 

Can you let us know when the autocompletes will be publicly available in Fig? We’d like to share this out publicly when it’s available. ☺️

2022-06-04 19:54 UTC, fedeci commented
Hey @ashryanbeats this is already available in Fig! Actually once a PR gets merged all users gets almost instantly those updates. Out of curiosity, do you use autocomplete for internal CLIs?