Brandonleon/feat/corc
withfig/autocomplete pull request #1224
Opened 2022-05-11 07:12 UTC by brandonleon

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature, adding spec for croc, the command line tool for sending files and folders.

**What is the current behavior? (You can also link to an open issue here)**
No current spec for croc.

**What is the new behavior (if this is a feature change)?**
Adding spec for the croc command.

**Additional info:**

2022-05-11 07:20 UTC, SeparateRecords requested changes
Thanks for the PR! Left some notes - not much left to add 🙂

2022-05-11 07:20 UTC, SeparateRecords commented on src/croc.ts
> +    },
`send` and `relay` both have options but it looks like they're missing here

2022-05-11 07:20 UTC, SeparateRecords commented on src/croc.ts
> +  // args: {}
It should take an argument which is the secret code

2022-05-11 14:24 UTC, brandonleon commented on src/croc.ts
> +  // args: {}
Added receive code argument.

2022-05-12 05:52 UTC, SeparateRecords requested changes
Done a final pass on it, checking for missing args. I've marked the options that should take an arg, once that's done it's ready to merge!

2022-05-12 05:52 UTC, SeparateRecords commented on src/croc.ts
> +      description: "Show help for croc",
```suggestion
      description: "Show help for croc",
      isPersistent: true,
```

2022-05-12 05:52 UTC, SeparateRecords commented on src/croc.ts
> +    },
These should all take an argument, `args: { name: "value" }` on each of them would be good enough!

2022-05-12 05:52 UTC, SeparateRecords commented on src/croc.ts
> +        },
These both take a value, can just do `args: { name: "value" }`

2022-05-12 06:46 UTC, brandonleon commented on src/croc.ts
> +    },
Got a little more detailed on a few of them.

2022-05-12 06:56 UTC, SeparateRecords approved these changes
LGTM! Thanks for adding all of that 😄

Note that you probably won't instantly get this spec since the package size is now over 100MB, which causes issues for the CDN we use (jsdelivr).

I have an issue open to increase the size limit for us and have a workaround PR up internally, so hopefully it'll be usable soon!

2022-05-12 06:58 UTC, merged