feat: add kubevela cli spec
withfig/autocomplete pull request #1226
Opened 2022-05-12 12:55 UTC by basuotian

Signed-off-by: tianshuai 

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
kubevela is A Highly Extensible Platform Engine based on Kubernetes and Open Application Model.
Feature to support vela cli

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**
support vela (cli for kubevela) autocomplete

**Additional info:**
vela cli info: https://kubevela.net/docs/cli/vela

2022-05-14 13:36 UTC, fedeci requested changes
Hey @basuotian, thanks for this spec! I am seeing a lot of args missing throughout the file, can you add those, please? I have not marked all the missing ones but only gave you a few examples. For the rest the spec looks great!

2022-05-14 13:36 UTC, fedeci commented on src/vela.ts
> +          description: "Specify environment name for application",
This accepts an argument

2022-05-14 13:36 UTC, fedeci commented on src/vela.ts
> +            "The revision to use for deploying the application, if empty, the current application configuration will be used",
All these accept an argument

2022-05-14 13:36 UTC, fedeci commented on src/vela.ts
> +          ],
An arg is missing here too

2022-05-16 02:36 UTC, basuotian commented
sorry for missing the args, the latest commit has resolved, PTAL, thx

2022-05-16 06:37 UTC, fedeci approved these changes
Thanks a lot for the changes!

2022-05-16 06:43 UTC, SeparateRecords commented
Thanks for the contribution @basuotian! Looks like a lot of work to have written this by hand. Awesome work.

2022-05-16 06:44 UTC, merged