feat(who): add completion
withfig/autocomplete pull request #1236
Opened 2022-05-22 00:13 UTC by mamercad

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

New completion

**What is the current behavior? (You can also link to an open issue here)**

There is no completion for `who` currently

**What is the new behavior (if this is a feature change)?**

There will be completion for `who`

**Additional info:**

`man who`

2022-05-23 02:40 UTC, SeparateRecords requested changes
Looks good - same suggestion as the other review, plus a few more notes 🙂

2022-05-23 02:40 UTC, SeparateRecords commented on src/who.ts
> +      insertValue: "-bdlprTtu",
I think inserting the options explicitly isn't necessary since `-a` is an option itself, although if you prefer this UX then I'm happy to go with your judgement on it

2022-05-23 02:40 UTC, SeparateRecords commented on src/who.ts
> +      },
As far as I know the options shouldn't take any args, these can be safely deleted from the options

2022-05-23 02:40 UTC, SeparateRecords commented on src/who.ts
> +const completionSpec: Fig.Spec = {
This is a bit of a weird suggestion but since it also supports `who am I` as an invocation, you can add this:
```typescript
subcommands: [
  {
    name: "am",
    insertValue: "am I",
    displayName: "am I",  // You can change this to make it look better if `am I` looks strange
    subcommands: [{ name: "I" }],
  },
],
```
Of course with appropriate descriptions, I omitted them for brevity 😄

Modelling the `who am I` invocation as an `am` subcommand with an `I` subcommand, and selecting the suggestion for `am` inserts that too. This also gives some other behavior for free (eg. it's optional and can't be used with options)

And if it looks weird, you can set `priority: 40` (or any number below 50) to put it at the bottom of the list

2022-05-23 02:40 UTC, SeparateRecords commented on src/who.ts
> +  },
Can use `template: "filepaths"` here

2022-05-23 23:44 UTC, mamercad commented on src/who.ts
> +      insertValue: "-bdlprTtu",
Hehe, yeah, reading `Same as -bdlprTtu` is a bit ridiculous; I'll leave it in the description (since it's straight from the man page), but, I'll drop the `insertValue`.

2022-05-23 23:45 UTC, mamercad commented on src/who.ts
> +const completionSpec: Fig.Spec = {
Yeah, not going to lie, I was wondering how to do this -- thanks for the help!

2022-05-24 15:38 UTC, mamercad commented
@SeparateRecords I think this is ready for another look when you have time please!

2022-05-25 01:41 UTC, SeparateRecords approved these changes
Two very small tweaks to the `am I` subcommand. Everything else looks great!

(I'd recommend making the changes yourself instead of accepting them on GH to keep the sole credit for the PR - just a vanity thing 😄)

2022-05-25 01:41 UTC, SeparateRecords commented on src/who.ts
> +      insertValue: "am I",
```suggestion
      insertValue: "am I{cursor}",
```
Small change, but it puts the cursor directly after `I`, eg, `who am I|` instead of `who am I |`

2022-05-25 01:41 UTC, SeparateRecords commented on src/who.ts
> +      priority: 40,
Just adds descriptions
```suggestion
      description: "Returns the invoker's real user name",
      subcommands: [{
      	name: "I",
        description: "Returns the invoker's real user name",
      }],
      priority: 40,
```

2022-05-25 11:26 UTC, mamercad commented on src/who.ts
> +      priority: 40,
Thanks for the help through this @SeparateRecords !

2022-05-25 19:23 UTC, fedeci commented on src/who.ts
> +const completionSpec: Fig.Spec = {
I wonder if it would work with `additionalSuggestions`, instead. Let me check!

2022-05-25 19:47 UTC, fedeci commented on src/who.ts
> +const completionSpec: Fig.Spec = {
@mamercad this works fine and you can remove the insertValue and displayValue from the `am` subcommand. 
```js
additionalSuggestions: [
    {
      name: "am I",
      insertValue: "am I{cursor}",
      icon: "fig://icon?type=command"
    }
  ],
```

2022-05-25 23:12 UTC, mamercad commented on src/who.ts
> +const completionSpec: Fig.Spec = {
I think I had to drop the `am ` from `insertValue` though (I was getting `who am am I` (it's pushed).

2022-05-26 13:56 UTC, fedeci commented on src/who.ts
> +const completionSpec: Fig.Spec = {
👍

2022-05-26 13:56 UTC, fedeci approved these changes
Thanks!

2022-05-26 13:57 UTC, merged