feat(ansible-doc): add completion
withfig/autocomplete pull request #1237
Opened 2022-05-22 14:24 UTC by mamercad

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

New completion

**What is the current behavior? (You can also link to an open issue here)**

There is no completion for `ansible-doc` currently

**What is the new behavior (if this is a feature change)?**

There will be completion for `ansible-doc`

**Additional info:**

`man ansible-doc`

2022-05-25 20:05 UTC, fedeci requested changes

2022-05-25 23:15 UTC, mamercad commented on src/ansible-doc.ts
> +): Fig.Generator => ({
It enumerates the installed plugins like this:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/6192266/170384421-52ba687d-7872-4267-8b53-fe076a96b8ae.png">

2022-05-25 23:16 UTC, mamercad commented on src/ansible-doc.ts
> +        isDangerous: false,
Cool; I'll push without them shortly.

2022-05-26 14:28 UTC, fedeci commented on src/ansible-doc.ts
> +});
I mean, can we just refactor to this?
```suggestion
const allPluginsGenerator: Fig.Generator = {
  script: "ansible-doc --list --json 2>/dev/null",
  postProcess: function (output) {
    const plugins = JSON.parse(output);
    return Object.keys(plugins).map((key) => ({
      name: key,
      description: plugins[key],
    }));
  },
};
```

2022-05-26 19:41 UTC, mamercad commented on src/ansible-doc.ts
> +});
I've committed this, but, it's failing `typecheck`. I don't know enough TypeScript to know what to do, can you help?

2022-05-29 11:37 UTC, fedeci commented on src/ansible-doc.ts
> +    generators: allPluginsGenerator(),
This was the cause of the typecheck failing @mamercad 
```suggestion
    generators: allPluginsGenerator,
```

2022-05-29 16:56 UTC, mamercad commented on src/ansible-doc.ts
> +    generators: allPluginsGenerator(),
Ah; thanks, will push.

2022-05-29 17:03 UTC, mamercad commented
Hrm; I rebased and the linter is exploding on all sorts of things that aren't mind 😄

2022-05-31 08:55 UTC, fedeci approved these changes
Thanks!

2022-05-31 09:21 UTC, merged