feat(ansible-config): add completion
withfig/autocomplete pull request #1238
Opened 2022-05-22 14:33 UTC by mamercad

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

New completion

**What is the current behavior? (You can also link to an open issue here)**

There is no completion for `ansible-config` currently

**What is the new behavior (if this is a feature change)?**

There will be completion for `ansible-config`

**Additional info:**

`man ansible-config`

2022-05-23 03:12 UTC, SeparateRecords requested changes
Same thing as the others 🙂 `args` in some extra places, `isDangerous: false` too, but aside from that it looks great!

2022-05-23 03:12 UTC, SeparateRecords commented on src/ansible-config.ts
> +      },
Does this need to be here? I think --verbose/-v don't take args (could be wrong!)

2022-05-23 03:12 UTC, SeparateRecords commented on src/ansible-config.ts
> +      },
Same thing, does --help take an arg? If it does, what value is it expecting? (Eg subcommand name?)

2022-05-23 03:12 UTC, SeparateRecords commented on src/ansible-config.ts
> +      },
Should this be here?

2022-05-23 16:54 UTC, mamercad commented on src/ansible-config.ts
> +      },
Right; they don't ... I've been unclear about the need for this (if the option doesn't take any arguments):

```
      args: {
        isOptional: true,
      },
```

Is it best to omit this if that's the case, or, include it to be explicit?

2022-05-23 16:55 UTC, mamercad commented on src/ansible-config.ts
> +      },
(I'll push without it.)

2022-05-23 23:37 UTC, mamercad commented on src/ansible-config.ts
> +      },
I *think* this is fixed now.

2022-05-23 23:38 UTC, mamercad commented on src/ansible-config.ts
> +      },
I *think* this is fixed now.

2022-05-24 01:56 UTC, SeparateRecords commented on src/ansible-config.ts
> +      },
> Right; they don't ... I've been unclear about the need for this (if the option doesn't take any arguments):

If the option doesn't take any arguments then you can omit `args` entirely since the parser will then that the token following `--verbose` is the argument _for_ `--verbose`. Meaning if the next token is another option, you won't get suggestions for it since you're in an argument

2022-05-24 01:57 UTC, SeparateRecords commented on src/ansible-config.ts
> +      },
> Is it best to omit this if that's the case, or, include it to be explicit?

You're correct! If no args, you can omit args entirely. Would you be able to update the other options that don't take args too?

2022-05-24 11:54 UTC, mamercad commented
@SeparateRecords I think this is ready for another look when you have time please!

2022-05-25 01:23 UTC, SeparateRecords approved these changes
Looks great! Thanks for making all those changes. This can definitely be merged as-is. Left one question then we're good to go 🚀

2022-05-25 01:23 UTC, SeparateRecords commented on src/ansible-config.ts
> +        },
Are the long/short forms of this option treated differently? (eg. `-v` can be repeated but `--verbose` can't be)

Not a merge blocker but I'd like to know :)

2022-05-25 20:09 UTC, fedeci commented on src/ansible-config.ts
> +        },
Friendly ping @mamercad. I'm merging this one in the meanwhile, thank you for the contribution!

2022-05-25 20:09 UTC, merged

2022-05-25 23:25 UTC, mamercad commented on src/ansible-config.ts
> +        },
> Are the long/short forms of this option treated differently? (eg. `-v` can be repeated but `--verbose` can't be)
> 
> Not a merge blocker but I'd like to know :)

Yep, I think that's how it works. I think `ansible-config --verbose` is the same as `ansible-config -v` is the same as `ansible-config --verbose -v` (sigh).

But, I think we do have a problem (that doesn't break anything) with this -- it looks like `ansible-config` doesn't actually support stacking the `-v`s. I probably copy/pasta'd too much, i.e., `ansible-playbook` supports stacking the `-v's to get more and more verbosity.

Looking more closely, it looks like only `-v` and `--verbose` (which are the same) are supported to `ansible-config`.

I'll PR a fix to this shortly.

2022-05-25 23:36 UTC, mamercad commented on src/ansible-config.ts
> +        },
Err, I stand corrected:

```
❯ ansible-config -h 2>&1 | grep verbose
  -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
```

```
❯ ansible-config list -h 2>&1 | grep verbose
  -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
```

```
❯ ansible-config dump -h 2>&1 | grep verbose
  -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
```

```
❯ ansible-config view -h 2>&1 | grep verbose
  -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
```

```
❯ ansible-config init -h 2>&1 | grep verbose
  -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
```

2022-05-25 23:49 UTC, mamercad commented on src/ansible-config.ts
> +        },
```bash
❯ cat v.sh
#!/usr/bin/env bash

ansible-config list       >/tmp/0 2>&1
ansible-config list -v    >/tmp/1 2>&1
ansible-config list -vv   >/tmp/2 2>&1
ansible-config list -vvv  >/tmp/3 2>&1
ansible-config list -vvvv >/tmp/4 2>&1

echo "=== no v versus -v ==="
diff -q /tmp/0 /tmp/1 >/dev/null && echo same || echo diff
echo

echo "=== -v versus -vv ==="
diff -q /tmp/1 /tmp/2 >/dev/null && echo same || echo diff
echo

echo "=== -vv versus -vvv ==="
diff -q /tmp/2 /tmp/3 >/dev/null && echo same || echo diff
echo

echo "=== -vvv versus -vvvv ==="
diff -q /tmp/3 /tmp/4 >/dev/null && echo same || echo diff
echo
```

```
❯ ./v.sh

=== no v versus -v ===
diff

=== -v versus -vv ===
diff

=== -vv versus -vvv ===
same

=== -vvv versus -vvvv ===
same
```