remotion sites + remotion functions
withfig/autocomplete pull request #1243
Opened 2022-05-24 17:20 UTC by JonnyBurger

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Update Remotion completions with new commands, flags and Remotion Lambda feature

**What is the current behavior? (You can also link to an open issue here)**

Represents the capability of Remotion 2.0 while 3.0 is out now

**What is the new behavior (if this is a feature change)?**

Represents 3.0 functionality

**Additional info:**

2022-05-25 02:11 UTC, SeparateRecords requested changes
Looking really good! Not much to change, awesome job on this update to the CLI. Looks like it was all hand written 😮

2022-05-25 02:11 UTC, SeparateRecords commented on src/remotion.ts
> +];
Do these options require an `=` separator? Federico fixed the implementation in the autocomplete engine (and we renamed a property) so now you can omit the `insertValue` and set `requiresSeparator: true`, you'll get this behavior for free.

(same goes for the other options further down in this file)

2022-05-25 02:11 UTC, SeparateRecords commented on src/remotion.ts
>          },
Can use `insertValue` to automatically put the cursor between two quotes, which is likely what you want if you're writing JSON in a shell
```suggestion
        {
          type: "arg",
          displayName: "[json string]",
          insertValue: "'{cursor}'",
        },
```

2022-05-25 02:11 UTC, SeparateRecords commented on src/remotion.ts
> +      })),
Clever! 😄

2022-05-25 02:11 UTC, SeparateRecords commented on src/remotion.ts
> +                    suggestions: [{ name: "x86_64" }, { name: "arm64" }],
This isn't documented anywhere but there's actually an icon for CPU architecture! `fig://icon?type=cpu`

2022-05-26 09:13 UTC, JonnyBurger commented on src/remotion.ts
> +];
This is nice to hear! I must have been on the old version, yes, I wanted that when you autocomplete this, the options pop up right away.

2022-05-26 09:30 UTC, JonnyBurger commented on src/remotion.ts
> +      })),
Thanks! 😄 Credits to @MatteoGauthier!

2022-05-26 09:31 UTC, JonnyBurger commented on src/remotion.ts
> +                    suggestions: [{ name: "x86_64" }, { name: "arm64" }],
Nice, we'll take that!

2022-05-26 09:35 UTC, JonnyBurger commented
Thanks a lot for these great improvement suggestions! 🙌 
All fixed up!

2022-05-26 09:45 UTC, SeparateRecords approved these changes

2022-05-26 09:46 UTC, SeparateRecords commented
Perfect - awesome job on this (and on 3.0!) 🎉🚀

2022-05-26 09:47 UTC, merged

2022-05-26 11:49 UTC, MatteoGauthier commented
Extending fig is so easy, thanks for that