feat(screen): add completion
withfig/autocomplete pull request #1247
Opened 2022-05-27 13:50 UTC by mamercad

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

New completion

**What is the current behavior? (You can also link to an open issue here)**

There is no completion for `screen`

**What is the new behavior (if this is a feature change)?**

There will be completion for `screen`

**Additional info:**

`man screen`

2022-05-29 11:47 UTC, fedeci requested changes

2022-05-29 11:47 UTC, fedeci commented on src/screen.ts
> +    },
Does this have double dash? If it doesn't you should add the `flagsArePosixNoncompliant` parserOption: https://fig.io/docs/reference/subcommand#parserdirectives

2022-05-29 11:47 UTC, fedeci commented on src/screen.ts
> +    },
I've just seen that many options are not simple flags (e.g. `-RR` or `-fn`) so that `parserOption` is required for correct parsing.

2022-05-29 11:47 UTC, fedeci commented on src/screen.ts
> +  ],
Why these are considered as subcommands?

2022-05-29 17:07 UTC, mamercad commented on src/screen.ts
> +  ],
What's the mechanism for "chaining arguments"?

2022-05-31 09:06 UTC, fedeci commented on src/screen.ts
> +  ],
Do you mean that `-d` is exclusive on `-D` and they both allow some kind of subcommand (`-r`, `R`, `-RR`) after them?

2022-05-31 13:27 UTC, fedeci commented
It would be great if you could rebase and lint:fix everything after reinstalling npm deps.

2022-06-04 20:05 UTC, fedeci approved these changes
Thanks!

2022-06-04 20:05 UTC, merged