feat: (npm) npm install autosuggests from npm search
withfig/autocomplete pull request #126
Opened 2021-04-14 20:51 UTC by DannyAziz

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature
**What is the current behavior? (You can also link to an open issue here)**
Npm install returns packages that are already in the package.json
**What is the new behavior (if this is a feature change)?**
Uses`npm search` to search as you are typing
**Additional info:**
![Screen Recording 2021-04-14 at 21 48 38](https://user-images.githubusercontent.com/3679064/114777363-86967180-9d6b-11eb-9953-6385f38202a8.gif)

2021-04-15 07:10 UTC, QuiiBz commented
Really cool idea! I don't know why but it's a lot slower for me, the `npm search` command takes ages. Any idea why?

2021-04-15 07:17 UTC, QuiiBz commented on dev/npm.ts
> +
We should add the `Fig.Generator` type to prevent mistakes, so we will need to cast the return of the `postProcess` function to `Fig.Suggestion[]`:
```suggestion
const searchGenerator: Fig.Generator = {
  script: function (context) {
    if (context[context.length - 1] === "") return "";
    const searchTerm = context[context.length - 1];
    return `npm search ${searchTerm}`;
  },
  postProcess: function (out) {
    return out
      .split("\n")
      .filter(
        (line) =>
          !line.includes(
            '"NAME | DESCRIPTION | AUTHOR | DATE | VERSION | KEYWORDS '
          )
      )
      .map((item) => item.split("|")[0].trim()) as Fig.Suggestion[];
    return allLines;
  },
  trigger: function () {
    return true;
  },
};
```

2021-04-15 08:43 UTC, cstrnt commented
Hey @DannyAziz you can use `npm search --json` which makes the string splitting stuff much easier, because you can just parse the json and look for the`name` prop :)

2021-04-15 10:16 UTC, DannyAziz commented
Hey @cstrnt `--json` seems to fail for me every time I use it with an error:

```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/danny/.npm/_logs/2021-04-15T10_15_41_562Z-debug.log
```

2021-04-15 11:25 UTC, cstrnt commented
@DannyAziz what npm version do you use? (`npm -v`) ?

2021-04-15 12:12 UTC, QuiiBz commented
Having the same error with Node v15.9.0 and NPM v7.5.3

2021-04-15 12:15 UTC, cstrnt commented
https://github.com/npm/cli/pull/2845
It got fixed in version 7.6.2 and works with npm ~6.x

2021-04-15 18:53 UTC, falky97 commented
Hey guys - so this generator is good, however, it would be best to switch over to running a `curl` request in our script hitting this API: https://api-docs.npms.io/. 

Why?
We want generators that are 1. fast and 2. work on everyone's device. We can't assume that an end user has a specific version of a CLI installed (at least not until we version specs). Therefore, we always need a solution that works for everyone.

In general, I'd agree with Tim that using `--json` is nicer for parsing, however as it's not supported everywhere, we shouldn't do it. 

https://api-docs.npms.io/ is fast and works for everyone and so we should switch to it. Not gonna merge this PR until that's done

2021-04-15 20:56 UTC, DannyAziz commented
@falky97 Bump

2021-04-15 21:10 UTC, falky97 commented
Code looks good, either @mattschrage or I will test later today / tomorrow
Two concerns:
1. npm install should ideally rank commands in the local package.json higher up should it not? I guess this is annoying to mix in a slow generator with a fast local json parse of the package.json... But we should think a little more about how to do this
2. Why is the check PR / danger test not working? (haven't had a chance to look into it)

2021-04-15 21:39 UTC, mattschrage commented
1. Does anyone really install local packages individually? Seems like the usual workflow is running `npm install` in this case. Totally could be wrong.

2. The `danger.js` workflow failing is not an issue with this PR.  We just need to add a Github token for danger to use.

2021-04-15 22:48 UTC, falky97 commented
Yeah @matt probably fair re npm local installs. The only times I have done it for local files was when I was updating the version number. Main workflow is installing foreign packages

2021-04-16 06:10 UTC, cstrnt commented
# Overview
<!-- id: review-bot --> 
## dev/npm.ts:
### Info:
**Script:**
`cat package.json`
**postProcess(function):**
```typescript
 function (out) {
              if (out.trim() === "") {
                return [];
              }
              try {
                const packageConten = JSON.parse(out);
                const dependencies = packageConten["dependencies"];
                if (dependencies) {
                  const dps = Object.keys(dependencies);
                  return dps.map((pkg) => {
                    const scope = pkg.indexOf("/") + 1;
                    if (scope !== -1) {
                      pkg = pkg.substring(scope);
                    }
                    const version = pkg.indexOf("@");
                    if (version !== -1) {
                      pkg = pkg.substring(version);
                    }
                    return {
                      name: pkg,
                      icon: `fig://icon?type=file`,
                      description: "dependency file",
                    };
                  });
                }
              } catch (e) {}
              return [];
            }
```

**Script:**
`until [[ -f package.json ]] || [[ $PWD = '/' ]]; do cd ..; done; cat package.json`
**postProcess(function):**
```typescript
 function (out) {
              if (out.trim() == "") {
                return [];
              }

              try {
                const packageContent = JSON.parse(out);
                const scripts = packageContent["scripts"];
                const figCompletions = packageContent["fig"];

                if (scripts) {
                  const keys = Object.keys(scripts).map((key) => {
                    return Object.assign(
                      {},
                      { icon: "fig://icon?type=npm" },
                      figCompletions[key],
                      { name: key, insertValue: key }
                    ); // ensure that name and insertValue are defined by "scripts" dict
                  });
                  return keys;
                }
              } catch (e) {}

              return [];
            }
```

**Script:**
`cat package.json`
**postProcess(function):**
```typescript
 function (out) {
              if (out.trim() === "") {
                return [];
              }
              try {
                const packageContent = JSON.parse(out);
                const dependencies = packageContent["dependencies"];
                if (dependencies) {
                  const dps = Object.keys(dependencies);
                  return dps.map((pkg) => {
                    const scope = pkg.indexOf("/") + 1;
                    if (scope !== -1) {
                      pkg = pkg.substring(scope);
                    }
                    const version = pkg.indexOf("@");
                    if (version !== -1) {
                      pkg = pkg.substring(version);
                    }
                    return {
                      name: pkg,
                      icon: `fig://icon?type=file`,
                      description: "dependency file",
                    };
                  });
                }
              } catch (e) {}
              return [];
            }
```

**Script:**
`cat package.json`
**postProcess(function):**
```typescript
 function (out) {
              if (out.trim() === "") {
                return [];
              }
              try {
                const packageContent = JSON.parse(out);
                const dependencies = packageContent["dependencies"];
                if (dependencies) {
                  const dps = Object.keys(dependencies);
                  return dps.map((pkg) => {
                    const scope = pkg.indexOf("/") + 1;
                    if (scope !== -1) {
                      pkg = pkg.substring(scope);
                    }
                    const version = pkg.indexOf("@");
                    if (version !== -1) {
                      pkg = pkg.substring(version);
                    }
                    return {
                      name: pkg,
                      icon: `fig://icon?type=file`,
                      description: "dependency file",
                    };
                  });
                }
              } catch (e) {}
              return [];
            }
```

2021-04-20 08:49 UTC, cstrnt requested changes

2021-04-20 08:49 UTC, cstrnt commented on dev/npm.ts
> +    ) as Fig.Suggestion[];
The json also includes the description. I think this would be extremely nice if we could also include it

```suggestion
    return JSON.parse(out).results.map(
      (item) =>
        ({
          name: item.package.name,
          description: item.package.description,
        } as Fig.Suggestion)
    ) as Fig.Suggestion[];
```

2021-04-20 08:49 UTC, cstrnt commented on dev/npm.ts
> +    },
Why is this a separate command? Shouldn't it be the same as install? The name prop can take an array as well!

2021-04-20 12:42 UTC, QuiiBz commented on dev/npm.ts
> +    ) as Fig.Suggestion[];
The `Fig.Suggestion[]` should be inferred by typescript since we cast above in the map to a `Fig.Suggestion`, isn't it?

2021-04-20 15:46 UTC, cstrnt commented on dev/npm.ts
> +    ) as Fig.Suggestion[];
Unfortunately it isn't. Atleast I didn't get autocompletion in vscode

2021-04-22 01:16 UTC, falky97 commented on dev/npm.ts
> +    },
Nope this is correct. Name prop of a subcommand cannot currently take an array. However, it could be interesting to add this as a feature.

2021-04-22 01:23 UTC, falky97 approved these changes

2021-04-22 01:23 UTC, merged