feat: create `trunk` completion spec
withfig/autocomplete pull request #1279
Opened 2022-06-10 14:59 UTC by t-bre

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
No completion spec for `trunk`

**What is the new behavior (if this is a feature change)?**
Creates completion spec for `trunk`

**Additional info:**
[trunk website](https://trunk.io/products/check)

2022-06-12 19:18 UTC, fedeci requested changes
Thanks for this spec, I left two comments to be solved before merging but overall it looks good!

2022-06-12 19:18 UTC, fedeci commented on src/trunk.ts
> +    },
Are these mutually [exclusiveOn](https://fig.io/docs/reference/option#exclusiveon)

2022-06-12 19:18 UTC, fedeci commented on src/trunk.ts
> +        },
These too are likely `exclusiveOn`

2022-06-13 18:52 UTC, t-bre commented on src/trunk.ts
> +    },
Yes you're right, fixed

2022-06-13 18:52 UTC, t-bre commented on src/trunk.ts
> +        },
Same here, also fixed

2022-06-14 00:46 UTC, SeparateRecords requested changes
Looks good! Couple of quetions in reviews, but aside from that this spec is in a really good place :)

2022-06-14 00:46 UTC, SeparateRecords commented on src/trunk.ts
> +  description: "",
Would you be able to add a description here?

2022-06-14 00:46 UTC, SeparateRecords commented on src/trunk.ts
> +        suggestions: ["0", "1"],
Should this be `true`/`false` instead of `0`/`1`?

2022-06-14 00:46 UTC, SeparateRecords commented on src/trunk.ts
> +      name: "--action_timeout",
All the other options use dashes, should this be a dash instead of underscore?

2022-06-14 00:46 UTC, SeparateRecords commented on src/trunk.ts
> +      isPersistent: true,
Is this persistent on each subcommand? Usually `--version` is only on the root (I don't have trunk installed to check)

2022-06-14 14:41 UTC, t-bre commented on src/trunk.ts
> +        suggestions: ["0", "1"],
Good point, just checked and both ways work. I think `true`/`false` is more intuitive, so I've changed it to that.

2022-06-14 14:41 UTC, t-bre commented on src/trunk.ts
> +  description: "",
Yes sorry I missed that, done now.

2022-06-14 14:48 UTC, t-bre commented on src/trunk.ts
> +      name: "--action_timeout",
Yeah I thought that as well, but no for some reason this one has an underscore. Tried it with a dash and it throws an error. According to the help text `--action_timeout` is correct:

```
usage
  trunk [flags] [subcommand]

flags
  -h, --help                  usage information
      --version               the version
  -m, --monitor               enable the trunk daemon to monitor file changes in your repo
      --ci                    run in continuous integration mode
  -o, --output                output format {text | json}
      --no-progress           don't show progress updates
      --ci-progress           show updates every 30 seconds without clearing terminal screen (implicit with --ci
      --action_timeout        how long actions (downloads, lint runs, etc.) have to time out
  -v, --verbose               output details about what's happening under the hood
```

2022-06-14 14:49 UTC, SeparateRecords commented on src/trunk.ts
> +      name: "--action_timeout",
That's super weird! Thanks for double checking 😄

2022-06-14 14:56 UTC, SeparateRecords commented on src/trunk.ts
> +      isPersistent: true,
Neat! Unusual behavior but good to have it modeled perfectly.

2022-06-14 14:57 UTC, SeparateRecords reviewed
LGTM! Thanks so much for contributing this 😄

2022-06-14 14:57 UTC, SeparateRecords approved these changes

2022-06-14 14:58 UTC, merged