feat: add docksal/fin completion spec
withfig/autocomplete pull request #1304
Opened 2022-06-21 09:28 UTC by XxHalbfettxX

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adding completion spec for Docksal/fin

**What is the current behavior? (You can also link to an open issue here)**
#101

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2022-06-22 07:41 UTC, SeparateRecords requested changes
Wow, big spec!! Thank you for the contribution. Looks like a lot of work to make this.

Most of it looks great. Only some (hopefully) easy additions :)

The biggest thing to change is moving the spec itself out of `generateSpec`, because generateSpec merges the output and spec.

2022-06-22 07:41 UTC, SeparateRecords commented on src/fin.ts
> +              name: "",
Looks like this is missing a name?

2022-06-22 07:41 UTC, SeparateRecords commented on src/fin.ts
> +                description: "",
Name/description can be omitted if you want them to be blank, adding a name is good though because it shows up on https://fig.io/manual :)

2022-06-22 07:41 UTC, SeparateRecords commented on src/fin.ts
> +                name: "name",
Might be able to use `fin db list` for a generator 🙂

2022-06-22 07:41 UTC, SeparateRecords commented on src/fin.ts
> +          // TODO: ???????
Got a good chuckle from this line 😄

Does this subcommand still need its options? Is that what the todo is for?

2022-06-28 07:33 UTC, SeparateRecords commented
@XxHalbfettxX quick ping! Would love to get this merged, shouldn't take much time to get the spec ready :) happy to help out / provide more info if you want!

2022-06-29 10:26 UTC, XxHalbfettxX commented
I'm on holiday this week and would get on it next week :)

2022-07-06 08:23 UTC, XxHalbfettxX commented on src/fin.ts
> +          // TODO: ???????
Oh, I forgot to do this ToDo. 😅
This subcommand was mentioned in the man page, but was removed in the current version of. Therefore, I will remove this subcommand.

2022-07-06 08:50 UTC, XxHalbfettxX commented on src/fin.ts
> +  generateSpec: async (tokens, executeShellCommand) => {
Thanks for the Tip :)

2022-07-06 09:25 UTC, XxHalbfettxX commented on src/fin.ts
> +                description: "",
I forgot to remove this section :D

2022-07-14 11:56 UTC, XxHalbfettxX commented
Are the desired changes fulfilled by my adaptations?

2022-07-15 01:16 UTC, SeparateRecords commented
Hey hey! Sorry for the wait, thanks for the ping 🙂 Will review now.

2022-07-15 02:18 UTC, SeparateRecords requested changes
Awesome job on this. Really killing it. It's a big spec so there's lots of places to add generators - most of the review comments I've left are things that can be worked on in a follow up. All the generator suggestions are just nice-to-haves.

There's a couple of easy improvements like adding `template: '...'` to some args which I think is important for good UX. So let's get that done for this PR at least, and if you want to do the generators then go for it! 🙂

2022-07-15 02:18 UTC, SeparateRecords commented on src/fin.ts
> +        },
Is there a way to list the valid services? We can add in a follow up pr if you'd like

2022-07-15 02:18 UTC, SeparateRecords commented on src/fin.ts
> +            },
Could you add a description to this one?

2022-07-15 02:18 UTC, SeparateRecords commented on src/fin.ts
> +            "Add a private SSH key from $HOME/.ssh by file name. mAdds all default keys (id_rsa/id_dsa/id_ecdsa/id_ed25519) if no file name is given",
Extra `m` in the text 🙂
```suggestion
            "Add a private SSH key from $HOME/.ssh by file name. Adds all default keys (id_rsa/id_dsa/id_ecdsa/id_ed25519) if no file name is given",
```

2022-07-15 02:18 UTC, SeparateRecords commented on src/fin.ts
> +          },
If this uses keys in ~/.ssh we can use a generator like this:
```js
generators: {
  script: "\\command ls .ssh | grep --color=never -E '^id_'",
  splitOn: "\n",
}
```

2022-07-15 02:18 UTC, SeparateRecords commented on src/fin.ts
> +          description: "Remove all keys from the docksal-ssh-agent",
Can reuse the output from `fin ssh-key ls` in a generator?

2022-07-15 02:18 UTC, SeparateRecords commented on src/fin.ts
> +          description: "List all docker machines",
You could probably use this command for a generator for the other `fin vm` commands :D

2022-07-15 02:18 UTC, SeparateRecords commented on src/fin.ts
> +              },
```suggestion
              args: {
                name: "name",
                template: "filepaths",
              },
```

2022-07-15 02:18 UTC, SeparateRecords commented on src/fin.ts
> +              },
```suggestion
              args: {
                name: "name",
                template: "filepaths",
              },
```

2022-07-15 02:18 UTC, SeparateRecords commented on src/fin.ts
> +      },
```suggestion
      args: {
        name: "command|file",
        isCommand: true,
      },
```
Will give correct suggestions if you provide a command name there!

2022-07-16 10:39 UTC, XxHalbfettxX commented on src/fin.ts
> +          description: "Remove all keys from the docksal-ssh-agent",
I can write a generator for this, but there is no command into which the generated completions can be inserted. The rm command does not take an argument. It deletes all the keys at once.

2022-07-16 10:45 UTC, XxHalbfettxX commented on src/fin.ts
> +          description: "List all docker machines",
The same as with the ssh-key ls command. I have not found a place where I can insert the vm as a completion. 

But it could also be that I lack experience with docksal

2022-07-16 11:07 UTC, XxHalbfettxX commented on src/fin.ts
> +        },
I have added a generator for the services.

2022-07-17 17:01 UTC, fedeci commented on src/fin.ts
> +                "\\command ls .ssh | \\command grep --color=never -E '^id_'",
I think \\command is wrong here, isn't it?

2022-07-18 11:14 UTC, fedeci commented on src/fin.ts
> +                "\\command ls .ssh | \\command grep --color=never -E '^id_'",
Yeah, I meant which it should be used in a different way: `\\ls .ssh ...` is the correct one. It takes the original `ls` command and not eventual aliases the user may have create around it e.g. `alias ls="ls -ls"`

2022-07-19 07:51 UTC, XxHalbfettxX commented on src/fin.ts
> +                "\\command ls .ssh | \\command grep --color=never -E '^id_'",
Hups :D I guess I didn't read that carefully enough :D

2022-07-19 23:30 UTC, SeparateRecords commented on src/fin.ts
> +                "\\command ls .ssh | \\command grep --color=never -E '^id_'",
@fedeci actually `command` is correct - Bash has an `ls` builtin with different behavior, so using `command` means it will skip using the builtin and search the path! The reason `command` is "quoted" with `\\` is because users can also alias it, so we skip the alias lookup

2022-07-20 11:49 UTC, fedeci commented on src/fin.ts
> +                "\\command ls .ssh | \\command grep --color=never -E '^id_'",
That's crazy😕

2022-07-28 00:58 UTC, SeparateRecords approved these changes
This is really fantastic. Sorry it's taken so long to merge this, been swamped with a million things to do. You've really nailed this spec @XxHalbfettxX :D

2022-07-28 00:58 UTC, merged