feat: add `create-t3-app` spec
withfig/autocomplete pull request #1339
Opened 2022-07-08 17:51 UTC by fernandoxu

Feature add [create-t3-app](https://create.t3.gg/)

2022-07-08 18:46 UTC, fedeci requested changes
Thanks! Great first spec!

2022-07-08 18:46 UTC, fedeci commented on src/create-t3-app@latest.ts
> +  name: "create-t3-app@latest",
Can you remove @latest please (from the filename also)? Eventually if you are used to run this CLI with the trailing @latest you can create another file named `src/create-t3-app@latest.ts` that contains the following:
```ts
import create_t3_app from "./create_t3_app";

const completionSpec: Fig.Spec = {
  ...create_t3_app,
  name: "create_t3_app@latest",
};

export default completionSpec;
```

2022-07-08 18:46 UTC, fedeci commented on src/create-t3-app@latest.ts
> +  template: "folders",
Do folders need to exist or they may not exist?

2022-07-08 18:46 UTC, fedeci commented on src/npx.ts
> +  },
Here you should duplicate the suggestion adding "create-t3-app" also.

2022-07-09 02:14 UTC, fernandoxu commented on src/create-t3-app@latest.ts
> +  name: "create-t3-app@latest",
OK! thanks a lot for your check!

2022-07-09 02:24 UTC, SeparateRecords commented on src/create-t3-app@latest.ts
> +  template: "folders",
IIRC you're correct, folder doesn't need to exist

You can add `suggestCurrentToken: true` to make the behavior correct! (I think that's the name of the prop...)

2022-07-09 11:25 UTC, fedeci requested changes

2022-07-09 11:25 UTC, fedeci commented on src/create-t3-app.ts
> +};
This wasn't to remove, we have options for everything! `suggestCurrentToken` was what this argument needed.
```suggestion
const dirArgument: Fig.Arg = {
  name: "dir",
  description:
    "The name of the application, as well as the name of the directory to create",
  template: "folders",
  isOptional: true,
  suggestCurrentToken: true,
};

const completionSpec: Fig.Spec = {
  name: "create-t3-app",
  description: "A CLI for creating web applications with the t3 stack",
  icon: "https://create.t3.gg/favicon.svg",
  options: [
    {
      name: "--noGit",
      description:
        "Explicitly tell the CLI to not initialize a new git repo in the project (default: false)",
    },
    {
      name: ["-y", "--default"],
      description:
        "Bypass the CLI and use all default options to bootstrap a new t3-app (default: false)",
    },
    {
      name: ["--help", "-h"],
      description: "Display help for command",
    },
  ],
  args: dirArgument,
};
```

2022-07-09 15:57 UTC, fedeci approved these changes
Thanks again!

2022-07-09 15:57 UTC, merged