feat(gh): add browse core command
withfig/autocomplete pull request #1349
Opened 2022-07-16 03:16 UTC by johnmerrill

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature

**What is the current behavior? (You can also link to an open issue here)**
`gh` command `browse` is not supported with autocomplete

**What is the new behavior (if this is a feature change)?**
`gh` command `browse` will be an option

**Additional info:**
`gh browse` documentation https://cli.github.com/manual/gh_browse

2022-07-17 16:13 UTC, fedeci requested changes
Thanks for the PR 🎉, can you solve the comments please?

2022-07-17 16:13 UTC, fedeci commented on src/gh.ts
> +          description: "Select another branch by passing in the branch name",
```suggestion
          description: "Open the last commit",
```

2022-07-17 16:13 UTC, fedeci commented on src/gh.ts
> +      subcommands: [
All these are options and should be moved to the `options` property array

2022-07-17 16:13 UTC, fedeci commented on src/gh.ts
> +      description: "Open the repository in the browser",
The browse command also accepts arguments, we may provide generators for this but I think we can tackle that in another PR
```suggestion
      description: "Open the repository in the browser",
      args: {
        name: "pr | issue | path[:line]"
      },
```

2022-07-19 17:55 UTC, johnmerrill commented on src/gh.ts
> +      description: "Open the repository in the browser",
I added the existing generator `ghGenerators.listPR` to this argument. Not sure how you feel about using a generator that only satisfies part of the argument.

2022-07-19 18:15 UTC, fedeci commented on src/gh.ts
> +        generators: ghGenerators.listPR,
I'm fine with this as long as this also gets added:
```suggestion
        generators: ghGenerators.listPR,
        suggestCurrentToken: true,
```

2022-07-19 19:35 UTC, fedeci approved these changes
Thanks!

2022-07-19 19:37 UTC, merged