feat add Hop
withfig/autocomplete pull request #1350
Opened 2022-07-16 14:21 UTC by Looskie

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adding completion spec for Hop's CLI  - Interact with Hop in your terminal

**Additional info:**

2022-07-16 14:24 UTC, Looskie commented
👍

2022-07-17 16:56 UTC, fedeci requested changes
Thanks for this first spec 🎉! I left a couple comments to solve before merging.

2022-07-17 16:56 UTC, fedeci commented on src/hop.ts
> +          description: "Type of the container, defaults to `ephemeral`",
```suggestion
          description: "Type of the container, defaults to `ephemeral`",
          args: {
            name: "container type",
          },
```

2022-07-17 16:56 UTC, fedeci commented on src/hop.ts
> +      ],
All of these need an argument, see a simple example above, I would suggest you to give a look to this property too that may be useful [`suggestions`](https://fig.io/docs/reference/arg#suggestions), let me know if you need help!

2022-07-17 16:56 UTC, fedeci commented on src/hop.ts
> +      ],
We have some nice sugar to avoid having to maintain this list, the `help` template which creates some argument suggestions in a smart way!
```suggestion
      args: {
        name: "command",
        template: "help,"
      },
```

2022-07-17 18:07 UTC, Looskie commented on src/hop.ts
> +      ],
oh this is so beautiful

2022-07-17 18:09 UTC, Looskie commented on src/hop.ts
> +      ],
added! thank you for the `suggestions` tip, thats going to be REALLY handy :).

2022-07-17 18:10 UTC, Looskie commented
Thanks for the speedy review! Let me know if theres anything else with these changes :)

2022-07-18 11:24 UTC, fedeci approved these changes
Love it! This really improves the spec a lot! Thanks you so much @Looskie

2022-07-18 11:24 UTC, fedeci commented on src/hop.ts
> +          },
@SeparateRecords has key value generators been merged?

2022-07-24 17:55 UTC, Looskie commented
Hi @fedeci ! I've added a small command to the spec, hopefully this isn't a burden!

2022-07-26 05:37 UTC, SeparateRecords commented on src/hop.ts
> +          },
keyValue works fine but there's no generator for this so no point to adding it :)

2022-07-26 05:38 UTC, SeparateRecords commented
lgtm!

2022-07-26 05:39 UTC, merged