add: java spec.
withfig/autocomplete pull request #1354
Opened 2022-07-20 03:43 UTC by Koooooo-7

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature about `Java` basic cmd.
**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2022-07-20 12:00 UTC, fedeci requested changes
Thanks for this PR, I left two comments to solve before merge.

2022-07-21 03:44 UTC, Koooooo-7 commented on src/java.ts
> +    template: "filepaths",
I see,  yes, it should keep `cp` as a single command.

2022-07-21 03:44 UTC, Koooooo-7 commented on src/java.ts
> +      name: ["--classpath", "-cp"],
I see, yes, it should keep cp as a single command.

2022-07-21 06:35 UTC, fedeci commented on src/java.ts
> +        name: "seach files",
```suggestion
        name: "search files",
```

2022-07-21 06:35 UTC, fedeci commented on src/java.ts
> +        template: "filepaths",
```suggestion
        generators: filepaths({ extensions: ["jar"] }),
```

2022-07-21 08:09 UTC, fedeci approved these changes
Thanks!

2022-07-22 06:57 UTC, merged