feat: add `ykman` spec
withfig/autocomplete pull request #1363
Opened 2022-07-24 22:31 UTC by vaaleyard

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature, new spec for `ykman`
**What is the current behavior? (You can also link to an open issue here)**
Done

**Additional info:**
This is the yubikey-manager CLI: https://github.com/Yubico/yubikey-manager

2022-07-27 06:15 UTC, SeparateRecords requested changes
Hey @vaaleyard, looks good! There's a few superficial / polish improvements to make but I'd even be happy to merge this and add those in the future if you like. Shouldn't be too hard to add them, so it's up to you!

2022-07-27 06:15 UTC, SeparateRecords commented on src/ykman.ts
> +          },
Would love to add suggestions to this. Because it takes predefined values but they're separated by `+` we need to use a generator:
```suggestion
          args: {
            name: "MODE",
            description:
              "MODE can be a string, such as 'OTP+FIDO+CCID', or a shortened form: 'o+f+c'. It can also be a mode number",
            generators: {
              getQueryTerm: "+",
              custom: () => Promise.resolve(["OTP", "FIDO", "CCID"]),
            }
          },
```

2022-07-27 06:15 UTC, SeparateRecords commented on src/ykman.ts
> +              },
```suggestion
              args: {
                name: "application",
                suggestions: ["OTP", "U2F", "FIDO2", "OATH", "PIV", "OPENPGP", "HSMAUTH"],
              },
```

2022-07-27 06:15 UTC, SeparateRecords commented on src/ykman.ts
> +              },
```suggestion
              args: {
                name: "application",
                suggestions: ["OTP", "U2F", "FIDO2", "OATH", "PIV", "OPENPGP", "HSMAUTH"],
              },
```

2022-07-27 06:15 UTC, SeparateRecords commented on src/ykman.ts
> +              },
Suspecting there might be a couple more of these - could you replace all of them with the suggestions?

2022-07-27 06:15 UTC, SeparateRecords commented on src/ykman.ts
> +                  },
Same thing, probably easiest to just search for all instances of `|` and add the different items as `suggestions`

2022-07-27 06:15 UTC, SeparateRecords commented on src/ykman.ts
> +                    "Generate a random management key. Implied by --protect unless --new-management-key is also given. Conflicts with --new-management-key",
Can you add an `exclusiveOn` property for this option?
Eg. `exclusiveOn: ["--new-management-key"]`

2022-07-27 06:15 UTC, SeparateRecords commented on src/ykman.ts
> +                },
Same thing for the arg below this one, can have a template and suggestions.
```suggestion
                {
                  name: "PUBLIC-KEY",
                  description:
                    "File containing a public key. Use '-' to use stdin",
                  template: "filepaths",
                  suggestions: [{ name: "-", hidden: true }],
                },
```

2022-07-27 06:15 UTC, SeparateRecords commented on src/ykman.ts
> +                },
Same as above! And for any of the other args -- you can probably search for "stdout"

2022-07-27 06:15 UTC, SeparateRecords commented on src/ykman.ts
> +      },
```suggestion
      args: {
        name: "FILE",
        template: "filepaths",
      },
```

2022-07-27 06:15 UTC, SeparateRecords commented on src/ykman.ts
> +      },
Can we know the available readers at runtime? Is there a command you can use to list them all out?

2022-07-29 20:19 UTC, vaaleyard commented on src/ykman.ts
> +          },
I get this error message when copying this code:
``` 
Type 'Promise<string[]>' is not assignable to type 'Promise<Suggestion[]>'.  Type 'string[]' is not assignable to type 'Suggestion[]'.    Type 'string' has no properties in common with type 'Suggestion'. typescript (2322) [55, 29]
```
No idea why, could you help me?

2022-07-29 20:20 UTC, vaaleyard commented on src/ykman.ts
> +              },
Resolved in 9498b07611edacca15c095724da90551af8799e4

2022-07-29 20:21 UTC, vaaleyard commented on src/ykman.ts
> +              },
Fixed in 9498b07611edacca15c095724da90551af8799e4

2022-07-29 20:21 UTC, vaaleyard commented on src/ykman.ts
> +              },
Fixed in 9498b07611edacca15c095724da90551af8799e4

2022-07-29 20:21 UTC, vaaleyard commented on src/ykman.ts
> +                  },
Fixed in 9498b07611edacca15c095724da90551af8799e4

2022-07-29 20:22 UTC, vaaleyard commented on src/ykman.ts
> +                    "Generate a random management key. Implied by --protect unless --new-management-key is also given. Conflicts with --new-management-key",
Fixxed in c4e66847af0377a0f9a6a91105ce8a464c263274

2022-07-29 20:24 UTC, vaaleyard commented on src/ykman.ts
> +                },
Fixed in ce1664646dac9df1dd1d72f8c0130935bfe66b38

2022-07-29 20:24 UTC, vaaleyard commented on src/ykman.ts
> +      },
Fixed in ce1664646dac9df1dd1d72f8c0130935bfe66b38

2022-07-29 20:24 UTC, vaaleyard commented on src/ykman.ts
> +                },
Fixed in ce1664646dac9df1dd1d72f8c0130935bfe66b38

2022-07-29 20:24 UTC, vaaleyard commented on src/ykman.ts
> +      },
Fixed in ce1664646dac9df1dd1d72f8c0130935bfe66b38

2022-07-29 20:26 UTC, vaaleyard commented on src/ykman.ts
> +      },
Actually, there is, I've made some regex to get it and made another generator in the above option.
Here: 8b98bc8513b3798489767be723f5b53ae8bf6900.

It's suggesting the right stuff.

2022-08-02 04:24 UTC, SeparateRecords commented on src/ykman.ts
> +          },
Ah, sorry - totally forgot that in a generator it has to be a `Suggestion` object. You can make it `{ name: "OTP" }`, etc.

2022-08-02 04:25 UTC, SeparateRecords commented
Fantastic, will be ready to merge once that simple change is made - I get a lot of notifications on github so please do bump this if I miss it :)

2022-08-02 04:40 UTC, vaaleyard commented on src/ykman.ts
> +          },
I'm sorry, but I didn't understand at all. What has to be a `Suggestion` object? I'm trying to find another spec that use some generator to see if I can get it.

2022-08-03 09:47 UTC, SeparateRecords commented on src/ykman.ts
> +          },
Ah, my bad, should've been clearer.

The `Suggestion` type is what everything inherits from. It has all the `name`, `description`, `displayName`, etc... properties. So instead of returning strings, you can return Suggestions.

I don't think there's a particular reason that suggestions _couldn't_ return strings, will add this to my to-dos for the month :)

2022-08-04 23:13 UTC, vaaleyard commented on src/ykman.ts
> +          },
I've commited some code, could you see if it's right? My mind is telling that is definitely wrong...

Do I have to create a generator like [this](https://github.com/withfig/autocomplete/blob/master/src/gpg.ts#L1), for example?

2022-08-06 19:16 UTC, fedeci commented on src/ykman.ts
> +          },
@vaaleyard here we want a generator that triggers on each + but also that removes previously inserted tokens each time the suggestions are shown. Currently we do not provide any sugar to do this so the generator has to be written manually.

```
const generator: {
  trigger: "+",
  custom: async (tokens, executeShellCommand) => {
    const previouslyAdded = tokens[tokens.length - 1].split("+")
    // this has to be an alias map of the possible suggestions
    const possibleSuggestionsMap = new Map([
      ["OTP", ["o"]],
      ["o", ["OTP"]],
      // ...all other values
    ])
    const suggestions = new Set(possibleSuggestionsMap.values())
    
    for (const token of previouslyAdded) {
      suggestions.delete(token)
      const aliases = possibleSuggestionsMap.get(token)
      if (aliases) {
        aliases.forEach(v => { suggestions.delete(v) })
      }
    }
    return [...suggestions].map(v => ({ name: v }))
  },
}
```

Also consider this: ![image](https://user-images.githubusercontent.com/38510000/183262244-799c279b-762f-4529-b33a-978801a05f69.jpeg)

I will add a new property as a sugar for this problem this week!

2022-08-13 03:58 UTC, vaaleyard commented on src/ykman.ts
> +          },
I guess instead of
```js
      if (aliases) {
        aliases.forEach(v => { suggestions.delete(v) })
      }
```

should be
```js
      if (aliases) {
        suggestions.delete(aliases)
      }
```
?

because it only works with []string.

2022-08-17 12:10 UTC, fedeci commented on src/ykman.ts
> +          },
That's correct @vaaleyard

2022-08-17 12:11 UTC, fedeci commented on src/ykman.ts
> +          },
`Set.prototype.delete` accepts a single primitive as argument, not an array🤔

2022-09-19 13:12 UTC, vaaleyard commented on src/ykman.ts
> +          },
@fedeci there's no more errors now 😅. Could you check if it's all ok? thanks

2022-09-21 08:59 UTC, fedeci requested changes

2022-09-21 08:59 UTC, fedeci commented on src/ykman.ts
> +          suggestions.delete([v]);
```suggestion
          suggestions.delete(v);
```

2022-09-21 08:59 UTC, fedeci commented on src/ykman.ts
> +    const suggestions = new Set(possibleSuggestionsMap.values());
```suggestion
  const suggestions = new Set([...possibleSuggestionsMap.values()].flat());
```

2022-09-21 13:21 UTC, vaaleyard commented on src/ykman.ts
> +          suggestions.delete([v]);
committed

2022-09-21 13:21 UTC, vaaleyard commented on src/ykman.ts
> +    const suggestions = new Set(possibleSuggestionsMap.values());
Committed

2022-09-22 20:36 UTC, vaaleyard commented
I guess it's all okay now?

2022-09-24 06:19 UTC, fedeci approved these changes
Thanks for the big spec @vaaleyard!

2022-09-24 06:21 UTC, merged