feat: add `mamba` spec
withfig/autocomplete pull request #1373
Opened 2022-07-29 12:13 UTC by Lunchb0ne

[Mamba](https://github.com/mamba-org/mamba) is a faster alternative for conda written in C++.

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
New Spec for `mamba` 

Most of it is taken from the spec for `conda`

**Additional info:**

2022-07-31 14:36 UTC, fedeci submitted a review, later dismissed
Great one, thanks! I left two small comments to solve and we are ready to merge this.

2022-07-31 14:36 UTC, fedeci commented on src/mamba.ts
> +    }
Is the trycatch really required?

2022-07-31 14:36 UTC, fedeci commented on src/mamba.ts
> +    const parsed: Array<Package> = JSON.parse(out);
This should be trycatched

2022-07-31 14:36 UTC, fedeci commented on src/mamba.ts
> +        },
These are mutually `exclusiveOn` (see https://fig.io/docs/reference/option#exclusiveon)

2022-07-31 16:44 UTC, Lunchb0ne commented on src/mamba.ts
> +    }
Ah, it's not necessary now. Updated!

2022-07-31 16:44 UTC, Lunchb0ne commented on src/mamba.ts
> +    const parsed: Array<Package> = JSON.parse(out);
Done!

2022-07-31 16:45 UTC, Lunchb0ne commented on src/mamba.ts
> +        },
I updated some options with `exclusiveOn` and `dependsOn`.

2022-07-31 18:10 UTC, fedeci commented on src/mamba.ts
> +        },
Great, thanks!

2022-08-01 00:36 UTC, SeparateRecords requested changes
Spec is looking really good! One request - can you add a `name` prop everywhere you see `args: {}`? I know this is just inherited from conda but don't worry about fixing it there

Looks better in https://fig.io/manual because it describes what the argument is for :) no need to add a description to them

2022-08-01 07:46 UTC, SeparateRecords approved these changes
lgtm! Thank you so much for the contribution, nice job on it!

2022-08-01 07:49 UTC, merged