feat: add pipx
withfig/autocomplete pull request #1380
Opened 2022-08-03 05:37 UTC by meowmeowmeowcat

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Add spec for [pipx](https://github.com/pypa/pipx)

2022-08-22 04:37 UTC, SeparateRecords requested changes
Looking good! Not much to change here. Sorry for the delay too 😅

2022-08-22 04:37 UTC, SeparateRecords commented on src/pipx.ts
> +      },
You can import the suggestions from `./pip` and add them to this arg!

2022-08-22 04:37 UTC, SeparateRecords commented on src/pipx.ts
> +        },
Same thing as above 🙂

2022-08-22 04:37 UTC, SeparateRecords commented on src/pipx.ts
> +      },
For this and other args where you're specifying a package already installed, you can use a `generator` (https://fig.io/docs/reference/generator) and `pipx list` I think

2022-08-22 12:38 UTC, meowmeowmeowcat commented on src/pipx.ts
> +      },
pipx is used to install Python console applications, so not all Python packages can be installed by pipx.

2022-08-23 01:51 UTC, SeparateRecords commented on src/pipx.ts
> +      },
That's fair. Will leave this up to your judgement in that case!

2022-08-25 07:01 UTC, merged