feat: add gibo completion spec
withfig/autocomplete pull request #1385
Opened 2022-08-08 06:06 UTC by simonwhitaker

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Adds completions for [gibo](https://github.com/simonwhitaker/gibo)

**What is the current behavior? (You can also link to an open issue here)**

n/a

**What is the new behavior (if this is a feature change)?**

fig supports gibo

**Additional info:**

2022-08-08 06:13 UTC, fedeci requested changes
I didn't know about this tool but I am installing it immediately! Can you just address the comments I left please?

2022-08-08 06:13 UTC, fedeci commented on src/gibo.ts
> +      });
nitpick:
```suggestion
      .sort();
```

2022-08-08 06:13 UTC, fedeci commented on src/gibo.ts
> +      .split("\n")
```suggestion
      .trim()
      .split("\n")
```

2022-08-08 06:30 UTC, SeparateRecords commented on src/gibo.ts
> +      });
@fedeci why sort the objects themselves? the name property is the only thing we care about sorting by

There's also [`String.prototype.localCompare`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#sort_an_array) which is what I'd have used in this case

2022-08-08 06:34 UTC, SeparateRecords commented on src/gibo.ts
> +  script: 'find "$HOME/.gitignore-boilerplates" -name "*.gitignore"',
Is there a reason you're using this instead of `gibo list`? The output is piped into `cat` automatically so it'll be newline-separated, seems like less work to process.

```ts
script: "gibo list",
splitOn: "\n",
```

2022-08-08 17:29 UTC, fedeci commented on src/gibo.ts
> +      });
Oops I fucked up thinking those were strings.

2022-08-08 19:43 UTC, simonwhitaker commented on src/gibo.ts
> +      .split("\n")
Done!

2022-08-08 19:43 UTC, simonwhitaker commented on src/gibo.ts
> +      });
Ah, I forgot `localCompare` -- haven't written JS in a while. Thank you!

2022-08-08 19:44 UTC, simonwhitaker commented on src/gibo.ts
> +  script: 'find "$HOME/.gitignore-boilerplates" -name "*.gitignore"',
Oooh, nice! Let me try that.

2022-08-09 00:16 UTC, SeparateRecords commented on src/gibo.ts
> +      });
@simonwhitaker If it weren't for helping maintain this repo I don't think I'd be sorting strings in JS very often either 😄

2022-08-09 00:18 UTC, SeparateRecords commented
Looks great! @simonwhitaker thank you so much for contributing this, and also for bringing attention to gibo because that looks _so nice_ for setting up projects 🤩

2022-08-09 00:19 UTC, SeparateRecords approved these changes

2022-08-09 00:19 UTC, merged