feat: add cf
withfig/autocomplete pull request #1386
Opened 2022-08-08 15:49 UTC by howardwicks1

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adding spec for `cf` cloudfoundry-cli

**Additional info:**

2022-08-08 17:27 UTC, fedeci commented
Hi @howardwicks1, thanks for the PR! Was this created manually or generated via some integration?

2022-08-08 17:55 UTC, fedeci requested changes
`npm run lint:fix` should fix all the linting issues automatically, then we can either merge the PR or add a ton of generators here and there :)

2022-08-08 17:55 UTC, fedeci commented on src/cf.ts
> +      },
These appear to be mutually `exclusiveOn`

2022-08-08 17:55 UTC, fedeci commented on src/cf.ts
> +      },
These too

2022-08-08 17:55 UTC, fedeci commented on src/cf.ts
> +      name: "org",
It would be cool to have a generator for orgs, I can point you in the right direction if needed!

2022-08-09 08:02 UTC, howardwicks1 commented on src/cf.ts
> +      },
Good spot will sort that out

2022-08-09 08:02 UTC, howardwicks1 commented on src/cf.ts
> +      },
Yep will sort 👍

2022-08-09 08:05 UTC, howardwicks1 commented on src/cf.ts
> +      name: "org",
I experimented with a generator for `app name` but ripped it out in this [commit](https://github.com/withfig/autocomplete/pull/1386/commits/1b714997cad5f4d837d61af5755c7a4f08d45801) as it wasnt working as intended. Happy to have another look at creating some generators though 😄

2022-08-09 08:05 UTC, howardwicks1 commented
Hello @fedeci thank you for the comments. This completion spec was created manually.

2022-08-09 13:00 UTC, fedeci approved these changes
Thanks for the changes! We can merge it as is for the moment since it is already a big PR, if you want you can open an issue to discuss about generators. Can you just add a description to the root command?

2022-08-09 13:00 UTC, fedeci commented on src/cf.ts
> +  description: "",
The description can be important for manual pages https://fig.io/manual

2022-08-10 08:27 UTC, howardwicks1 commented on src/cf.ts
> +  description: "",
Updated description

2022-08-10 08:46 UTC, SeparateRecords requested changes
This spec is great! Really nice job on it, that's absolutely huge. Lot of work to do.

Left some comments for additional generators. Wasn't exhaustive, there are more places you could add them - adding them will make this spec absolutely 🔥 🤩

2022-08-10 08:46 UTC, SeparateRecords commented on src/cf.ts
> +          },
Beautiful! You can pull out this generator and assign it to a variable, then you can use it anywhere there's an app name arg.

2022-08-10 08:46 UTC, SeparateRecords commented on src/cf.ts
> +        },
Is there a way to list the tasks / commands that are valid? Can add another generator for this!

2022-08-10 08:46 UTC, SeparateRecords commented on src/cf.ts
> +      },
Same thing with services! Can build a generator to suggest them here + every other place that takes a service

2022-08-10 08:46 UTC, SeparateRecords commented on src/cf.ts
> +      },
Same with orgs :)

2022-08-10 09:46 UTC, howardwicks1 commented
Have added a basic generator for APP_NAME + description

2022-08-10 09:47 UTC, howardwicks1 commented on src/cf.ts
> +          },
Ooh sounds good, will have a look at expanding the generator to work like that. 😄

2022-08-10 12:56 UTC, howardwicks1 commented on src/cf.ts
> +        },
Not too sure about this one, afaik the command could be anything depending on what app a user has deployed via cloudfoundry 😄 ie a user could be passing a regular bash command, reference to a script or entrypoint.

2022-08-10 12:57 UTC, howardwicks1 commented on src/cf.ts
> +      },
Will look at this one 👍

2022-08-10 12:57 UTC, howardwicks1 commented
Added generators for orgs and spaces, going to look at one for services next 😄

2022-08-11 01:40 UTC, SeparateRecords commented on src/cf.ts
> +};
Looks like the output for all of these is fairly consistent since it's basically the same generator - here's a quick simplification!

```suggestion
const postProcessCfList =
  (description: string, leadingLines: number) => (out: string) =>
    out
      .trim() // output can have a trailing newline, prevents empty suggestion
      .split("\n")
      .slice(leadingLines)
      .map((name) => ({ name, description }));

const generateAppNames: Fig.Generator = {
  script: `cf apps | cut -d " " -f1`,
  postProcess: postProcessCfList("App name", 4),
};

const generateOrgs: Fig.Generator = {
  script: `cf orgs`,
  postProcess: postProcessCfList("Org", 3),
};

const generateSpaces: Fig.Generator = {
  script: `cf spaces`,
  postProcess: postProcessCfList("Space", 3),
};
```

2022-08-11 01:45 UTC, SeparateRecords commented
So pumped for the spec to land. If you want we can merge now, then do the remaining generators later - what you've got already is _absolutely fantastic_.

2022-08-11 18:34 UTC, howardwicks1 commented on src/cf.ts
> +};
Ah this is really nice! Will give this a go 👍

2022-08-11 18:37 UTC, howardwicks1 commented
> So pumped for the spec to land. If you want we can merge now, then do the remaining generators later - what you've got already is _absolutely fantastic_.

I will address the last couple comments first 😄 but then yes I would be happy for the merge to go ahead

2022-08-12 15:11 UTC, howardwicks1 commented
Generator for services is now included, I have not attached the services generator to some of the `user-provided` service commands as I dont think they would work with the generator (as thats only able to poll the proper list of services present on the platform

2022-08-15 01:10 UTC, SeparateRecords approved these changes
LGTM! Thank you so much for working on this! 🚀

After merge it may take a bit for it to show up for you because of caching, but it's deployed automatically and _will_ work after a couple of days at most (depending on how recently Fig cached its specs)

2022-08-17 10:16 UTC, merged