feat: Add nextflow
withfig/autocomplete pull request #1391
Opened 2022-08-12 01:39 UTC by mribeirodantas

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
It adds autocomplete specs for nextflow

2022-08-19 14:26 UTC, mribeirodantas commented
One question. When this is merged, the autocomplete for nextflow will be automatic when someone installs Fig, right?

2022-08-19 16:22 UTC, fedeci commented
Correct!

2022-08-22 02:52 UTC, SeparateRecords requested changes
Looking great! Added some easy suggestions, honestly there's not much to change here. You've done a great job on this pretty big spec!!

2022-08-22 02:52 UTC, SeparateRecords commented on src/nextflow.ts
> +  description: "",
Quick fix, can you add a description here?

2022-08-22 02:52 UTC, SeparateRecords commented on src/nextflow.ts
> +  },
Bit of a weird suggestion but I see there are some options eg. `-e.key=value` - we can pretend that `.` is the "option arg separator" which means arg suggestions _should_ work correctly.

```suggestion
  parserDirectives: {
    flagsArePosixNoncompliant: true,
    optionArgSeparators: ["=", "."],
  },
```

2022-08-22 02:52 UTC, SeparateRecords commented on src/nextflow.ts
> +        },
After adding `requiresSeparator` you _should_ be able to remove `insertValue`, but double check this because I could be wrong.
```suggestion
        {
          name: "-e.",
          description:
            "Add the specified variable to execution environment. Syntax: -e.key=value (Default: {})",
          requiresSeparator: ".",
          insertValue: "-e.{cursor}",
          args: {
            name: "key=value",
          },
        },
```

2022-08-22 02:52 UTC, SeparateRecords commented on src/nextflow.ts
> +          },
```suggestion
          args: {
            name: "JSON/YAML file",
            template: "filepaths",
          },
```

2022-08-22 02:52 UTC, SeparateRecords commented on src/nextflow.ts
> +          },
Same thing here, can add `requiresSeparator: "."`

2022-08-22 21:45 UTC, mribeirodantas commented on src/nextflow.ts
> +  description: "",
Sure!

2022-08-22 21:53 UTC, mribeirodantas commented on src/nextflow.ts
> +          },
Done!

2022-08-22 21:53 UTC, mribeirodantas commented on src/nextflow.ts
> +          },
This is not working as expected 😞

2022-08-27 04:39 UTC, mribeirodantas commented
Hello, @SeparateRecords and others 😄 

It's ready to merge from my side 🥳 . There's probably something here and there that we can improve with time, but I think this is a good first version. What do you think?

2022-08-27 16:15 UTC, fedeci requested changes
Thanks for the big spec! I am only asking for one last change before we merge this one!

2022-08-27 16:15 UTC, fedeci commented on src/nextflow.ts
> +            name: "key=value",
This can use the [kv](https://fig.io/docs/reference/generator/prebuilt-generators#keyvalueoptions) generator.
(Same for all the other key=value args)

2022-08-28 05:06 UTC, mribeirodantas commented on src/nextflow.ts
> +            name: "key=value",
I had seen this, but then I would have to look up these pairs and I'm not sure how extensive of a list this can be. It would require discussions with Nextflow engineering team and I thought for now we could go without it and then in the near future submit a PR for an improvement to this version of the spec. What do you think?

2022-08-28 11:29 UTC, fedeci commented on src/nextflow.ts
> +            name: "key=value",
Sounds good

2022-08-28 11:30 UTC, fedeci approved these changes

2022-08-28 11:37 UTC, fedeci reviewed
I was dismissing @SeparateRecords review and while checking his comments I found this mistake.

2022-08-28 11:37 UTC, fedeci commented on src/nextflow.ts
> +          name: "-e.",
```suggestion
          name: "-e",
```

2022-08-28 11:37 UTC, fedeci commented on src/nextflow.ts
> +          name: "-process.",
```suggestion
          name: "-process",
```

2022-08-28 11:41 UTC, fedeci commented
Thanks!

2022-08-28 11:41 UTC, merged