feat: add `neofetch` spec
withfig/autocomplete pull request #1416
Opened 2022-08-17 02:38 UTC by grant0417

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2022-08-17 02:39 UTC, grant0417 commented
Thanks to @Alonely0 for the spec!

2022-08-17 05:54 UTC, SeparateRecords requested changes

2022-08-17 13:22 UTC, Alonely0 commented on src/neofetch.ts
> +    description: "That hAcKeR black window you type on",
I was on a cafe with my tablet doing the spec (my laptop's screen broke, and that's the only place with decent WiFi around) and I had like 5 7-8 year olds around me calling me hacker because I was writing a JSON. They gave me the idea.

2022-08-17 13:28 UTC, Alonely0 commented
> Thanks to @Alonely0 for the spec!

Thanks to you for fixing all the typos I made on the tablet & debugging it!

2022-08-17 16:07 UTC, Alonely0 commented
@grant0417 can you give me write access so I can fix my mess?
![image](https://user-images.githubusercontent.com/59423215/185188915-71aa3376-5c96-4b2e-bf91-ba7a3b92db9d.png)

2022-08-17 18:13 UTC, grant0417 commented
Not sure i can give you perms

2022-08-17 20:06 UTC, Alonely0 commented
> Not sure i can give you perms

Then test the gist on my other comment and if it works well commit it.

2022-08-17 20:19 UTC, grant0417 commented
Okay, put your gist in

2022-08-17 20:49 UTC, Alonely0 commented
That's on me, I'm too used to rust.
![Screenshot_2022-08-17-22-47-43-028_org bromite bromite](https://user-images.githubusercontent.com/59423215/185240251-64df2da6-71ee-4a38-b4dd-e7980d69a5e6.jpg)

2022-08-17 20:51 UTC, Alonely0 commented
This is because somewhere I wrote
```ts
{ suggestions: "string" }
```
Instead of
```ts
{ suggestions: [string] }
```
![Screenshot_2022-08-17-22-50-01-490_org bromite bromite](https://user-images.githubusercontent.com/59423215/185240649-3245ea4d-a674-46bf-91fc-58a176f243c1.jpg)

2022-08-17 20:59 UTC, Alonely0 commented
Everything's green, @SeparateRecords if the spec works approve the PR

2022-08-17 21:06 UTC, Alonely0 approved these changes
Seems to be ok, but I can't test the spec because as I said earlier my laptop's screen is broken and I'm doing everything on my tablet. Shouldn't be merged until someone tests it.

2022-08-18 08:52 UTC, fedeci approved these changes
It looks good to me! Thanks @Alonely0!

2022-08-18 20:04 UTC, merged