feat: add `apt`
withfig/autocomplete pull request #1429
Opened 2022-08-19 16:07 UTC by mrhappyma

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2022-08-20 15:36 UTC, SeparateRecords reviewed
I know it's still in progress but this is looking really great! I don't have a VM set up to test this so will leave that to @grant0417 :)

2022-08-20 17:11 UTC, mrhappyma commented on src/apt.ts
> +      priority: 50,
Without it the folders from the `filepaths` template seemed to have higher priority than the generator and hide it's suggestions entirely. Would there be better way of fixing this?

2022-08-21 00:09 UTC, SeparateRecords commented on src/apt.ts
> +      priority: 50,
Ohhh that makes sense. Honestly the whole priority algorithm is still a black box to sometimes it does some weird stuff like that. 

I'd say keep the line, but document why it's there in a comment above it

2022-08-22 14:17 UTC, fedeci requested changes
Thanks, I cannot test generators but the spec looks good overall!

2022-08-22 14:17 UTC, fedeci commented on src/apt.ts
> +const instillationOptions: Fig.Option[] = [
typo:
```suggestion
const installationOptions: Fig.Option[] = [
```

2022-08-22 15:04 UTC, SeparateRecords requested changes
Apparently forgot to submit the review. Should be easy changes

2022-08-22 15:11 UTC, mrhappyma commented on src/apt.ts
> +          // no idea how this works
phew, when I saw that there I was worried you were going to ask for a description

2022-08-22 15:13 UTC, mrhappyma commented on src/apt.ts
> +    },
I was debating about this, while it does technically work with all subcommands, the help message doesn't change. Should this still appear?

2022-08-22 15:19 UTC, mrhappyma commented on src/apt.ts
> +const instillationOptions: Fig.Option[] = [
:+1: fixed this locally and just waiting for the linter to do its thing

2022-08-22 15:22 UTC, SeparateRecords commented on src/apt.ts
> +];
to clarify, should have `exclusiveOn: ["--assume-no"]` on `-y` and `exclusiveOn: ["-y"]` on `--assume-no`

2022-08-22 15:23 UTC, SeparateRecords commented on src/apt.ts
> +    },
I'd say so! If it's valid then may as well, can de-prioritize it (`priority: 40`)

2022-08-22 16:11 UTC, mrhappyma commented on src/apt.ts
> +    },
Done!
I've done that to the version option too, as it works similarly.

2022-08-22 16:15 UTC, mrhappyma commented
I give up, re-requesting review isn't working.

2022-08-23 01:48 UTC, SeparateRecords approved these changes
LGTM! Thank you @mrhappyma! 😊

apt is particular thorny because of the lack of docs, really appreciate the effort you went to to make sure things are as correct as they can realistically be.

2022-08-23 01:49 UTC, merged