feat: update helm spec with autocomplete-tools for cobra
withfig/autocomplete pull request #1433
Opened 2022-08-20 09:53 UTC by dirien

Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Update of the helm cli using the autocomplete-tools for cobra

**What is the current behavior? (You can also link to an open issue here)**
-

**What is the new behavior (if this is a feature change)?**
Update of the helm cli using the autocomplete-tools for cobra
**Additional info:**

2022-08-20 19:20 UTC, mschrage requested changes
This looks awesome! Thank you for updating the spec.

Can you make make sure that the arguments which take a filepath, eg. for `--keyring`, include `template: "filepaths"` ?

2022-08-20 19:33 UTC, dirien commented
Hi @mschrage, thanks for the feedback! 

I use the the autocomplete tool for cobra and want to use the autopush action in the future! 

Is this a manual rework I have to do every time?

2022-08-21 20:53 UTC, fedeci commented
Hi @dirien, you won't need to do this manual stuff every time because the autocomplete action is using a merge tool retaining manually set options.

2022-08-22 04:32 UTC, SeparateRecords requested changes
Looking good! Just one extra change on top of the `template: "filepaths"` stuff.

If you want I'm happy to do it for you 🙂

2022-08-22 04:32 UTC, SeparateRecords commented on src/helm.ts
> +        default: "/Users/dirien/Library/Preferences/helm/registry/config.json",
Can you replace all occurrences of `/Users/dirien` with `~`?

2022-08-23 09:17 UTC, dirien commented
Ok did my best to find all `template: "filepaths"` arguments. Feel free to add, if you found one. This is a huge spec! 😅

2022-08-24 04:48 UTC, SeparateRecords commented
LGTM! Thank you @dirien 😊

2022-08-24 04:49 UTC, merged