feat: add minectl cli spec
withfig/autocomplete pull request #1435
Opened 2022-08-20 11:50 UTC by dirien

Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Adds support for `minectl`, closes #1434

2022-08-21 20:35 UTC, fedeci requested changes
Thanks a lot for this specs @dirien! I left some comments to solve before merging this. Likely prettier will have to complain if you commit from github, you can fix those problems running `npm run lint:fix` and committing the changes

2022-08-21 20:35 UTC, fedeci commented on src/minectl.ts
> +        "Enable verbose logging: debug|info|warn|error|dpanic|panic|fatal",
This can be listed using the `suggestions` prop under the child argument of this option.

2022-08-21 20:35 UTC, fedeci commented on src/minectl.ts
> +      args: { name: "log-encoding", default: "console" },
This too can use the `suggestions` prop

2022-08-21 20:35 UTC, fedeci commented on src/minectl.ts
> +      ],
This template is a nice sugar that does the same thing requiring not maintenance
```suggestion
      args: {
        template: "help",
      },
```

2022-08-21 20:35 UTC, fedeci commented on src/minectl.ts
> +          args: { name: "filename" },
```suggestion
          args: { name: "filename", template: "filepaths" },
```

2022-08-21 20:35 UTC, fedeci commented on src/minectl.ts
> +          args: { name: "output" },
```suggestion
          args: { name: "output", template: "folders", suggestCurrentToken: true },
```

2022-08-21 20:35 UTC, fedeci commented on src/minectl.ts
> +          args: { name: "filename" },
```suggestion
          args: { name: "filename", template: "filepaths" },
```

2022-08-21 20:35 UTC, fedeci commented on src/minectl.ts
> +          args: { name: "plugin" },
```suggestion
          args: { name: "plugin", template: "filepaths" },
```

2022-08-21 20:35 UTC, fedeci commented on src/minectl.ts
> +          args: { name: "filename" },
```suggestion
          args: { name: "filename", template: "filepaths" },
```

2022-08-21 20:35 UTC, fedeci commented on src/minectl.ts
> +          args: { name: "destination" },
```suggestion
          args: { name: "destination", template: "folders" },
```

2022-08-21 20:35 UTC, fedeci commented on src/minectl.ts
> +          args: { name: "provider" },
This can be improved using a `suggestion` property too

2022-08-21 20:35 UTC, fedeci commented on src/minectl.ts
> +          args: { name: "filename" },
```suggestion
          args: { name: "filename", template: "filepaths" },
```

2022-08-21 20:35 UTC, fedeci commented on src/minectl.ts
> +          args: { name: "filename" },
```suggestion
          args: { name: "filename", template: "filepaths" },
```

2022-08-23 08:39 UTC, dirien commented on src/minectl.ts
> +        "Enable verbose logging: debug|info|warn|error|dpanic|panic|fatal",
done

2022-08-23 08:39 UTC, dirien commented on src/minectl.ts
> +      args: { name: "log-encoding", default: "console" },
done

2022-08-23 08:58 UTC, dirien commented
Hi @fedeci,

thanks for the feedback! I changed all parts you highlighted!

2022-08-23 09:14 UTC, fedeci approved these changes
Thanks!

2022-08-23 09:14 UTC, merged