feat: add `coda` spec
withfig/autocomplete pull request #1436
Opened 2022-08-20 12:51 UTC by arsm100

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature: Add [Coda SDK](https://coda.io/packs/build/latest/guides/development/cli/#create-pack-definition) autocomplete spec.

**What is the current behavior? (You can also link to an open issue here)**
No Coda SDK spec

**What is the new behavior (if this is a feature change)?**
New Coda SDK spec added

**Additional info:**
[Coda](https://coda.io/about) is a new kind of doc that brings words, data, and teams together. It comes with a set of building blocks that anyone can combine to create a doc as powerful as an app.
With a growing dev community, Coda SDK is becoming more popular than ever. This new spec will make Fig an easy choice for Coda Pack developers!

2022-08-21 20:47 UTC, fedeci requested changes
Thanks for this first spec! This spec looks great, there are just a couple nitpicks to solve before landing it!

2022-08-21 20:47 UTC, fedeci commented on src/coda.ts
> +};
This can use the `filepaths` function from the `@fig/autocomplete-generators` package to filter over .ts file extensions

2022-08-21 20:47 UTC, fedeci commented on src/coda.ts
> +    description: "Show version number",
This allow the option to be in all the subcommands too without having to add it multiple times
```suggestion
    description: "Show version number",
    isPersistent: true,
```

2022-08-21 20:47 UTC, fedeci commented on src/coda.ts
> +    description: "Show version number",
In this way you can avoid having `commonOptions` and we can just add it once to the root command.

2022-08-22 01:56 UTC, arsm100 commented on src/coda.ts
> +};
Addressed.

2022-08-22 01:57 UTC, arsm100 commented on src/coda.ts
> +    description: "Show version number",
Thanks for the suggestion. The file is much shorter and cleaner this way! Addressed.

2022-08-22 07:40 UTC, fedeci approved these changes
Thanks!

2022-08-22 07:43 UTC, merged