feat: add lsblk spec
withfig/autocomplete pull request #1440
Opened 2022-08-21 18:10 UTC by SebDanielsson

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
Autocompletion for lsblk is currently not available. Closes https://github.com/withfig/autocomplete/issues/1405 

**What is the new behavior (if this is a feature change)?**
Adds autocompletion for lsblk

**Additional info:**
This is my first contribution so feel free to point out any errors☺️

2022-08-21 20:21 UTC, fedeci requested changes
Thanks @SebDanielsson, this spec looks great! I just left two comments to be solved before landing this!

2022-08-21 20:21 UTC, fedeci commented on src/lsblk.ts
> +        name: "list",
```suggestion
        name: "list",
        isVariadic: true,
```

2022-08-21 20:21 UTC, fedeci commented on src/lsblk.ts
> +      description: "Force tree-like output format",
Apparently this requires an argument
```suggestion
      description: "Force tree-like output format",
      args: {
        name: "column",
      },
```

2022-08-21 20:54 UTC, SebDanielsson commented on src/lsblk.ts
> +      description: "Force tree-like output format",
Yeah I wasn't sure about that one because there's no space between the option and the argument.

2022-08-22 03:09 UTC, SeparateRecords approved these changes
LGTM! Thank you @SebDanielsson 😊

2022-08-22 03:11 UTC, merged