feat: add fdisk spec
withfig/autocomplete pull request #1442
Opened 2022-08-22 20:00 UTC by SebDanielsson

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
Autocompletion for fdisk is currently not available. Closes https://github.com/withfig/autocomplete/issues/1407

**What is the new behavior (if this is a feature change)?**
Adds autocompletion for fdisk

**Additional info:**

2022-08-22 20:25 UTC, SebDanielsson commented
> * [ ]  Are all options modular? E.g. `-a` `-u` `-x` instead of `-aux`

Hi! I'm pretty now to this. Is there an easy way to tell if an option is modular or not?☺️

2022-08-23 01:45 UTC, SeparateRecords requested changes
Thanks for the spec!! Lot of comments but it's actually not that much, mostly just adding templates and suggestions to the options. Should be quick to change 🙂

2022-08-23 01:45 UTC, SeparateRecords commented on src/fdisk.ts
> +      },
Are there predefined values for this? Eg. always, never, auto

```suggestion
      args: {
        name: "when",
        isOptional: true,
        suggestions: ["always", "never", "auto"],
      },
```

2022-08-23 01:45 UTC, SeparateRecords commented on src/fdisk.ts
> +      },
Can have suggestions! I like to add the more verbose ones if equivalent because it's easier to read at a glance.
```suggestion
      args: {
        name: "mode",
        description:
          "Optional argument mode can be yes, no (or 1 and 0) or nonblock",
        isOptional: true,
        suggestions: ["yes", "no", "nonblock"],
      },
```

2022-08-23 01:45 UTC, SeparateRecords commented on src/fdisk.ts
> +    },
I think there's a `deprecated` or `isDeprecated` property, can you add that?

2022-08-23 01:45 UTC, SeparateRecords commented on src/fdisk.ts
> +    },
Do we know the types ahead of time, or is there a way to list them dynamically?

2022-08-23 01:45 UTC, SeparateRecords commented on src/fdisk.ts
> +      },
```suggestion
      args: {
        name: "unit",
        isOptional: true,
        suggestions: ["sectors", "cylinders"],
      },
```

2022-08-23 01:45 UTC, SeparateRecords commented on src/fdisk.ts
> +      },
```suggestion
      args: {
        name: "when",
        description: "The argument when can be auto, never or always",
      },
      suggestions: ["auto", "never", "always"],
```

2022-08-23 01:45 UTC, SeparateRecords commented on src/fdisk.ts
> +  },
```suggestion
  args: {
    name: "device",
    description: "Device to list",
    isOptional: true,
    template: "filepaths",
  },
```

2022-08-23 01:45 UTC, SeparateRecords commented on src/fdisk.ts
> +      },
Can't help but read `nondos` as a typo of Nando's 🫠
```suggestion
      args: {
        name: "mode",
        isOptional: true,
        suggestions: ["dos", "nondos"],
      },
```

2022-08-23 01:45 UTC, SeparateRecords commented on src/fdisk.ts
> +      },
```suggestion
      args: {
        name: "mode",
        description: "Valid values are 512, 1024, 2048, and 4096",
        suggestions: ["512", "1024", "2048", "4096"],
      },
```

2022-08-24 04:36 UTC, mschrage approved these changes
Looks good to me! Thank you so much for contributing @SebDanielsson :)

2022-08-24 04:46 UTC, merged

2022-08-24 07:13 UTC, SebDanielsson commented
Thank you for accepting this PR!☺️ Do you still want me to send in a PR for the last unresolved comment above?