feat: add mkinitcpio spec
withfig/autocomplete pull request #1443
Opened 2022-08-22 21:43 UTC by SebDanielsson

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
Autocompletion for mkinitcpio is currently not available. Closes https://github.com/withfig/autocomplete/issues/1409

**What is the new behavior (if this is a feature change)?**
Adds autocompletion for mkinitcpio

**Additional info:**

2022-08-23 01:37 UTC, SeparateRecords requested changes
Looks good! One quick change then it's ready to merge 🙂

2022-08-23 01:37 UTC, SeparateRecords commented on src/mkinitcpio.ts
> +  description: "",
Can you add a description here?

2022-08-23 17:22 UTC, grant0417 commented
Here is a generator for `-p` 

```ts
        generators: {
          script: "ls /etc/mkinitcpio.d",
          postProcess: (out) =>
            out
              .trim()
              .split("\n")
              .map((line) => ({
                name: line.replace(/\.preset$/, ""),
              })),
        },
```

2022-08-24 04:47 UTC, SeparateRecords commented
Ah, good - let's add this generator first _then_ we'll merge 😄

2022-08-24 15:24 UTC, SeparateRecords approved these changes
LGTM! Thank you @SebDanielsson !

2022-08-24 15:25 UTC, merged