feat: add `yalc` spec
withfig/autocomplete pull request #1446
Opened 2022-08-23 03:30 UTC by jakeols

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature

**What is the current behavior? (You can also link to an open issue here)**
n/a

**What is the new behavior (if this is a feature change)?**
Adds a new spec for [yalc](https://github.com/wclr/yalc). 

**Additional info:**
Been using (and loving) fig for a long time now -- figured I'd add a spec for a cli I've been using frequently.

2022-08-23 05:14 UTC, clo4 submitted a review, later dismissed
Looking good! Not much to change here, thanks so much for contributing 😊

2022-08-23 05:14 UTC, SeparateRecords commented on src/yalc.ts
> +  description: "",
Can you add a description here? Useful for https://fig.io/manual

2022-08-23 05:14 UTC, SeparateRecords commented on src/yalc.ts
> +          name: "-no-workspace-resolve",
Should this have two dashes, eg. `--no-workspace-resolve`?

2022-08-23 05:14 UTC, SeparateRecords commented on src/yalc.ts
> +      },
Is there a command we can use to generate the names of the packages dynamically?

Args have a `generators` prop that allows you to write code that generates suggestions dynamically 🙂

2022-08-23 05:14 UTC, SeparateRecords commented on src/yalc.ts
> +      },
Same thing here, could we generate the suggestions for this?

2022-08-23 05:14 UTC, SeparateRecords commented on src/yalc.ts
> +          ],
Should these `options` be `args`?

2022-08-24 03:54 UTC, jakeols commented on src/yalc.ts
> +  description: "",
Yep, [d28b340](https://github.com/withfig/autocomplete/pull/1446/commits/d28b340f7a725d514f067d5cc888da3c04403c11)

2022-08-24 03:54 UTC, jakeols commented on src/yalc.ts
> +          name: "-no-workspace-resolve",
Good catch, [d28b340](https://github.com/withfig/autocomplete/pull/1446/commits/d28b340f7a725d514f067d5cc888da3c04403c11)

2022-08-24 03:55 UTC, jakeols commented on src/yalc.ts
> +          ],
Updated, [d28b340](https://github.com/withfig/autocomplete/pull/1446/commits/d28b340f7a725d514f067d5cc888da3c04403c11)

2022-08-24 04:00 UTC, jakeols commented on src/yalc.ts
> +      },
Let me dig into this a little bit -- the list of published packages are available within `~/.yalc/packages` but want to confirm the behavior is similar across different OS regardless of the linking method.

2022-08-24 04:31 UTC, SeparateRecords commented on src/yalc.ts
> +      },
Awesome. [The installed deno scripts generator](https://github.com/withfig/autocomplete/blob/f72c03bc76bf14a571e92b68d5e82b56b944bd80/src/deno/generators.ts#L353-L364) might be similar to what you want then, so take a look at that for a reference. Some other files with generators you might want to look at are `brew.ts` and `kill.ts`.

2022-09-08 22:58 UTC, jakeols commented on src/yalc.ts
> +      },
Got a bit busy recently but added the generators in [a2e91dd](https://github.com/withfig/autocomplete/pull/1446/commits/a2e91dd36f85b842416f2946325b51fa87bc440a). The generators for listing available packages defaults to appending a version (eg. `mypackage@1.0.0`) while removing does not as the `yalc.lock` only supports a single version, so version should be irrelevant.

2023-02-10 09:21 UTC, fedeci requested changes
Thanks for your work @judofyr! Can you please sign the CLA, commit the changes suggested and we are ready to land this! Sorry for late response :(

2023-02-10 09:21 UTC, fedeci commented on src/yalc.ts
> +  script: "ls .yalc",
```suggestion
  script: "command ls .yalc",
```

2023-02-10 09:21 UTC, fedeci commented on src/yalc.ts
> +  script: "\\find ~/.yalc/packages -maxdepth 4 -iname 'package.json'",
```suggestion
	// TODO: use the same as for npm and yarn package.json reverse lookup
  script: "command find ~/.yalc/packages -maxdepth 4 -iname 'package.json'",
```

2023-02-10 09:21 UTC, fedeci commented
@recheck

2023-02-10 09:23 UTC, fedeci commented
recheck

2023-02-11 02:31 UTC, jakeols commented
I have read the CLA Document and I hereby sign the CLA

2023-02-11 02:32 UTC, jakeols commented on src/yalc.ts
> +  script: "ls .yalc",
[cf6b8da](https://github.com/withfig/autocomplete/pull/1446/commits/cf6b8da6ee4d06a442dafa8dfc1ab18c77bdf25c)

2023-02-11 02:32 UTC, jakeols commented on src/yalc.ts
> +  script: "\\find ~/.yalc/packages -maxdepth 4 -iname 'package.json'",
[cf6b8da](https://github.com/withfig/autocomplete/pull/1446/commits/cf6b8da6ee4d06a442dafa8dfc1ab18c77bdf25c)

2023-02-11 09:50 UTC, fedeci approved these changes
Thanks!

2023-02-11 09:57 UTC, merged