feat: add tuist spec
withfig/autocomplete pull request #1447
Opened 2022-08-23 07:31 UTC by eventomer

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
N/A

**What is the new behavior (if this is a feature change)?**
Add autocomplete support for [tuist](https://docs.tuist.io/)

**Additional info:**
Tuist is a command line tool (CLI) that aims to facilitate the generation, maintenance, and interaction with Xcode projects.

2022-08-23 08:03 UTC, danyf90 commented on src/tuist.ts
> +      name: "generate",
Aren't we missing the argument, that is the list of targets to focus on?

2022-08-23 08:04 UTC, danyf90 commented on src/tuist.ts
> +const completionSpec: Fig.Spec = {
Aren't we missing the `cache` command?

2022-08-23 08:06 UTC, eventomer commented on src/tuist.ts
> +      ],
I was struggling with this too. it seems like options can't have sub-options so i figure i will just use `--update` as a subcommand

2022-08-23 08:08 UTC, fedeci commented on src/tuist.ts
> +      ],
@eventomer that's the correct way to do it!

2022-08-23 08:10 UTC, danyf90 commented on src/tuist.ts
> +      ],
not sure I got it? why is this a sub-option?

2022-08-23 08:10 UTC, fedeci reviewed
Is tuist using `swift-argument-parser`?

2022-08-23 08:12 UTC, danyf90 commented
> Is tuist using `swift-argument-parser`?

Yes!

2022-08-23 08:14 UTC, fedeci commented on src/tuist.ts
> +      ],
I guess it can only be used when `--update` is specified. Actually the better way to do this is to add both as options to the upper command and add [`dependsOn: "--path"`](https://fig.io/docs/reference/option#dependson) to the `--update` option.

2022-08-23 08:26 UTC, eventomer commented on src/tuist.ts
> +      ],
it doesn't allow for multiple options with the same name even that their description is different.

so this is not valid:
```
{
      name: "fetch",
      description:
        "Dependencies can be fetched by running the following command. They are stored in your project's `Tuist/Dependencies` directory. For more info see https://docs.tuist.io/commands/dependencies",
      options: [
        {
          name: ["--path", "-p"],
          description:
            "The path to the directory that contains the workspace or project whose dependencies will be fetched. The default is the current directory",
        },
        {
          name: ["--path", "-p"],
          dependsOn: ["--update"],
          description:
            "The path to the directory that contains the workspace or project whose dependencies will be updated. The default is the current directory",
        },
        {
          name: "--update",
          description:
            "Clean only the builds artifacts cache generated by Tuist, example usage: 'tuist fetch --update':"
        }
      ]
    }
```

I guess it doesn't really matter so ican just update the description to be:
```
"The path to the directory that contains the workspace or project whose dependencies will be fetched/updated. The default is the current directory"
```

2022-08-23 08:40 UTC, fedeci requested changes
I left a few comments, it should be all fast to solve, please let me know if you need any help!

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +            "The path to the directory that contains the definition of the project. Default is current directory",
```suggestion
            "The path to the directory that contains the definition of the project. Default is current directory",
          args: {
            name: "project dir",
            template: "folders",
          },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +            "The path to where the image will be exported. When not specified, it exports the image in the current directory",
```suggestion
            "The path to where the image will be exported. When not specified, it exports the image in the current directory",
          args: {
            name: "output path",
            template: "folders",
            suggestCurrentToken: true,
          },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +            "If you prefer to have the dot or json representations of the graph and render it separately. Available formats: dot, png, json (default: png)",
```suggestion
            "If you prefer to have the dot or json representations of the graph and render it separately. Available formats: dot, png, json (default: png)",
          args: {
            name: "format",
            suggestions: ["dot", "png", "json"],
            default: "png",
          },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +            "Available formats: dot, neato, twopi, circo, fdp, sfddp, patchwork (default: dot)",
```suggestion
            "Available formats: dot, neato, twopi, circo, fdp, sfddp, patchwork (default: dot)",
          args: {
            name: "format",
            suggestions: ["dot", "neato", "twopi", "circo", "fdp", "sfddp", "patchwork"],
            default: "dot",
          },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +            "If set, show only the targets for the given platform. Default is all platforms. Available platforms: ios, macos, tvos, watchos",
```suggestion
            "If set, show only the targets for the given platform. Default is all platforms. Available platforms: ios, macos, tvos, watchos", 
          args: {
            name: "platform",
            suggestions: ["ios", "macos", "tvos", "watchos"],
          },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +            "Tests will retry <number> of times until success. Example: if 1 is specified, the test will be retried at most once, hence it will run up to 2 times. (default: 0)",
```suggestion
            "Tests will retry <number> of times until success. Example: if 1 is specified, the test will be retried at most once, hence it will run up to 2 times. (default: 0)",
            args: {
              name: "times",
              default: "0",
            },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +          description: "Test with a specific version of the OS",
It would be cool to have a [generator](https://fig.io/docs/reference/generator#generators)
```suggestion
          description: "Test with a specific version of the OS",
          args: {
            name: "os",
          },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +          description: "Test on a specific device",
A generator would be even nicer here too
```suggestion
          description: "Test on a specific device",
          args: {
            name: "device",
          },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +            "The path to the directory that contains the projectto be tested",
```suggestion
            "The path to the directory that contains the project to be tested",
          args: {
            name: "path",
            template: "folders",
          },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +          description: "The name of the generate project",
```suggestion
          description: "The name of the generate project",
          args: {
            name: "name",
          },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +          description: "The platform used by the project",
```suggestion
          description: "The platform used by the project",
          args: {
            name: "platform",
          },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +            "The path to the folder where the template will be generated (Default: Current directory)",
```suggestion
            "The path to the folder where the template will be generated (Default: Current directory)",
          args: {
            name: "path",
          },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +              name: ["--xcodeproj-path", "-p"],
```suggestion
              name: ["--xcodeproj-path", "-p"],
              isRequired: true,
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +                "Required. Path to the Xcode project whose build settings will be extracted",
```suggestion
                "Required. Path to the Xcode project whose build settings will be extracted",
              isRequired: true,
              args: {
                name: "path",
                template: "folders",
              },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +                "Required. Path to the Xcode project whose build settings will be extracted",
```suggestion
                "Required. Path to the Xcode project whose build settings will be extracted",
              isRequired: true,
              args: {
                name: "path",
                template: "folders",
              },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +                "Optional. The name of the target whose build settings will be extracted. When not passed, it extracts the build settings of the project",
```suggestion
                "Optional. The name of the target whose build settings will be extracted. When not passed, it extracts the build settings of the project",
              args: {
                name: "target",
              },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +            "The path to the directory that contains the definition of the project. Default is current directory",
```suggestion
            "The path to the directory that contains the definition of the project. Default is current directory",
          args: {
            name: "path",
            template: "folders",
          },
```

2022-08-23 08:40 UTC, fedeci commented on src/tuist.ts
> +          description: "The name of the cache profile",
```suggestion
          description: "The name of the cache profile",
          args: {
            name: "cache profile",
          },
```

2022-08-23 08:40 UTC, eventomer commented
> swift-argument-parser

https://github.com/withfig/fig-swift-argument-parser

I wish I was aware of this tool before I wrote it manually :)

2022-08-23 08:42 UTC, fedeci commented
Yeah, that's what I was referring too😄, if you want we can integrate directly with the tuist project and have the spec automatically updated each time tuist is bumped. (eventually with versioning too!)

2022-08-23 09:14 UTC, danyf90 commented
There was already a PR for that, but I don't think having Tuist depending on fig is the right approach.
Still @eventomer you can do what was done in the PR to generate the completion and then copy it here without having to merge it in the codebase

2022-08-23 09:31 UTC, fedeci commented
Is there any way to only specify dev deps for swift packages?

2022-08-23 09:32 UTC, fedeci commented
@eventomer linter failing, I likely exceeded the limit of 100 chars/line or I missed some comma here and there, could you run `npm run lint:fix`

2022-08-23 09:59 UTC, fedeci approved these changes
Looks good to me, we can add generators in a follow up PR!

2022-08-23 09:59 UTC, fedeci commented
Thanks!

2022-08-23 10:08 UTC, merged

2022-08-30 20:23 UTC, fortmarek commented
>  Is there any way to only specify dev deps for swift packages?

Unfortunately, this is not supported out of the box 😞  I don't see many projects implementing this approach if they need to add a dependency just to automatically update the fig config, although I'd love to have that.