New Feature: Suggest hosts from ssh config included files
withfig/autocomplete pull request #1448
Opened 2022-08-23 12:14 UTC by yaronuliel

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Spec update for `ssh`

**What is the current behavior? (You can also link to an open issue here)**
If `~/.ssh/config` file includes `Include` statement - fig doesn't provide suggestion from the included file [Bug: #1187]

**What is the new behavior (if this is a feature change)?**
The `ssh` spec now suggests hosts that are defined in config file included from the `~/.ssh/config` file

**Additional info:**
Solves this case (`customer-main-site` will be suggested as host for `ssh ` command

`~/.ssh/config`:
```
Host my-personal-site
     HostName 172.0.0.1
     User siteuser

Include config.d/*
```

`~/.ssh/config.d/customer`:

```
Host customer-main-site
   HostName ...
   User blabla
```

2022-08-23 16:45 UTC, yaronuliel reviewed
Resolves #1450

2022-08-24 04:54 UTC, SeparateRecords approved these changes
Looks really good, thank you so much @yaronuliel!

@fedeci could you have a look as well? If you don't see anything to change either it's an easy merge 🙂

2022-08-24 16:26 UTC, fedeci requested changes
Also, this does not handle * imports, right?

2022-08-24 16:26 UTC, fedeci commented on src/ssh.ts
> +    includes.map((file) => getConfigLines(file, executeShellCommand, basePath))
When you recurse just one directory deep it is ok to keep the original basePath, but what if another include is added and it is way more nested?
e.g.
```
# ~/.ssh/config
include foo/config-2
```

```
# ~/.ssh/foo/config-2
include bar/config-3
```

```
# ~/.ssh/foo/bar/config-3
...
```
 
While recursing, basePath will always be `~/.ssh` while file will be "foo/config-2" and "bar/config-3". In the first case the file gets correctly loaded since we resolve it to `~/.ssh/foo/config-2` but the second one is not since it is `~/.ssh/bar/config-3`.

2022-08-24 16:26 UTC, fedeci commented on src/ssh.ts
> +  return basePath.replace(/\/$/, "") + "/" + path;
Is this replacing the last slash and then adding it again?

2022-08-25 09:39 UTC, yaronuliel commented on src/ssh.ts
> +    includes.map((file) => getConfigLines(file, executeShellCommand, basePath))
@fedeci You are correct, this is the way openssh works, ALL includes are relative to the `~/.ssh` (this was counterintuitive to me as well)
See https://man.openbsd.org/ssh_config#Include

> Files without absolute paths are assumed to be in ~/.ssh if included in a user configuration file or /etc/ssh if included from the system configuration file

2022-08-25 09:45 UTC, yaronuliel commented on src/ssh.ts
> +  executeShellCommand: ExecuteShellCommandFunction,
Thanks! I didn't realized it's available on the `Fig` namespace.. my bad

Fixed

2022-08-25 09:46 UTC, yaronuliel commented on src/ssh.ts
> +) => Promise<string>;
Fixed

2022-08-25 09:47 UTC, yaronuliel commented on src/ssh.ts
> +  return basePath.replace(/\/$/, "") + "/" + path;
@fedeci Yes, I do this to support both `dir/` and `dir` as parameters for the function

2022-08-25 18:19 UTC, fedeci commented on src/ssh.ts
> +    includes.map((file) => getConfigLines(file, executeShellCommand, basePath))
Oops sorry!

2022-08-26 08:48 UTC, fedeci commented on src/ssh.ts
> +  return basePath.replace(/\/$/, "") + "/" + path;
nitpicky but I prefer this syntax for future maintainers
```suggestion
  return basePath + (basePath.endsWith("/") ? "" : "/") + path;
```

2022-08-27 16:01 UTC, fedeci approved these changes
Thanks!

2022-08-27 16:05 UTC, merged