feat: add specs for c++ compilers
withfig/autocomplete pull request #1460
Opened 2022-08-25 11:59 UTC by gavrilikhin-d

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the new behavior (if this is a feature change)?**
Completion for `clang++`, `c++` (same as `clang`) and `g++` (same as `gcc`) 

**Additional info:**

2022-08-25 12:02 UTC, gavrilikhin-d commented
Is it possible to override some options with `loadSpec`? I'd like to override `-std` to add suggestions for C++ standards (`c++11`, `gnu++11`, etc)

2022-08-26 08:42 UTC, fedeci requested changes
For specs that only change name and description I would encourage to use imports since those are resolved at build time and not at runtime

2022-08-26 08:42 UTC, fedeci commented on src/g++.ts
> +export default completionSpec;
```suggestion
import gcc from "./gcc"
const completionSpec: Fig.Spec = {
  ...gcc,
  name: "g++",
  description: "The default C++ compiler for most linux distributions",
};
export default completionSpec;
```

2022-08-27 01:11 UTC, mschrage commented
> Is it possible to override some options with `loadSpec`? I'd like to override `-std` to add suggestions for C++ standards (`c++11`, `gnu++11`, etc)

Now that you are importing the other completion spec at build time, you should be able to overwrite suggestions.

2022-08-27 01:15 UTC, gavrilikhin-d commented
> > Is it possible to override some options with `loadSpec`? I'd like to override `-std` to add suggestions for C++ standards (`c++11`, `gnu++11`, etc)
> 
> Now that you are importing the other completion spec at build time, you should be able to overwrite suggestions.

Yes, i added these. However, for some reason g++ suggestions don't show up :(

2022-08-27 01:20 UTC, gavrilikhin-d commented
And, maybe, it's better to generate suggestions from clang's [LangStandards.def](https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/LangStandards.def)?

2022-08-29 01:54 UTC, gavrilikhin-d commented on src/clang++.ts
> +    },
Done! However, i still see no suggestions for gcc and g++. May it be because they are aliases to clang?

2022-08-31 08:16 UTC, fedeci approved these changes
Thanks!

2022-08-31 08:16 UTC, merged