feat: add capacitor completion spec
withfig/autocomplete pull request #1463
Opened 2022-08-26 13:44 UTC by tmwrnr

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature

**What is the current behavior? (You can also link to an open issue here)**
n/a

**What is the new behavior (if this is a feature change)?**
Adds a new spec for [capacitor](https://capacitorjs.com/docs/cli)

**Additional info:**
I also added a `cap.ts` spec file because the capacitor CLI can be used either with `capacitor` or `cap` ([Reference](https://github.com/ionic-team/capacitor/blob/22c2fb505ee80dfce335c05f841ffafd21b7842c/cli/package.json#L34)). I was not sure if this is ok or if there is a better way of doing this. If you prefer not to have the second spec I can remove it again.

2022-08-26 16:14 UTC, fedeci requested changes
Thanks! It seems capacitor can run through yarn and npx, could you add it to those specs too?

2022-08-26 16:14 UTC, fedeci commented on src/capacitor.ts
> +};
If you add this property the option become available globally to all subcommands so it no longer needs to be repeated and can be moved directly in the completion object
```suggestion
  name: ["--help", "-h"],
  description:
    "Output usage information. Can be used with individual commands too",
  isPersistent: true,
};
```

2022-08-26 16:14 UTC, fedeci commented on src/capacitor.ts
> +            name: "target",
Can you add a [generator](https://fig.io/docs/reference/generator) here? Ping me if you need help!

2022-08-27 06:13 UTC, tmwrnr commented on src/capacitor.ts
> +};
Thanks that is way better 👍

2022-08-27 16:03 UTC, fedeci approved these changes
Thanks!

2022-08-27 16:03 UTC, fedeci commented on src/capacitor.ts
> +  },
Love it!

2022-08-27 16:04 UTC, merged