feat: add mgnl completion spec
withfig/autocomplete pull request #1468
Opened 2022-08-30 12:20 UTC by tmwrnr

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature

**What is the current behavior? (You can also link to an open issue here)**
n/a

**What is the new behavior (if this is a feature change)?**
Adds a new spec for [mgnl](https://docs.magnolia-cms.com/magnolia-cli/4.x/magnolia-cli.html)

**Additional info:**
n/a

2022-08-31 08:38 UTC, fedeci requested changes

2022-08-31 08:38 UTC, fedeci commented on src/mgnl.ts
> +};
This breaks when we query versions. The solution may be to refactor the npm generator logic to a function that accepts both the context and the eventual optional keywords.

2022-08-31 08:38 UTC, fedeci commented on src/mgnl.ts
> +        name: "query",
```suggestion
        name: "query",
        generators: lightModuleGenerator,
```

2022-08-31 08:38 UTC, fedeci commented on src/mgnl.ts
> +  description: "",
Can you add a description here? It is useful for https://fig.io/manual

2022-08-31 08:38 UTC, fedeci commented
Hey @tmwrnr, thanks for this completion! I left a couple comments, let me know what do you think.

2022-08-31 10:54 UTC, tmwrnr commented on src/mgnl.ts
> +};
Good catch, I did not think about versions. Are the changes as you imagined?

2022-08-31 11:11 UTC, tmwrnr commented
> Hey @tmwrnr, thanks for this completion! I left a couple comments, let me know what do you think.

Thank you for the review! I hope the changes look good to you. I also added support for running the cli with `npx`.

2022-09-05 10:06 UTC, fedeci requested changes

2022-09-05 10:06 UTC, fedeci commented on src/npm.ts
> +  ): Promise<Fig.Suggestion[]> => {
We cannot change the signature of a function we call internally in the engine because it may change in the future. By refactoring I meant something like this: 
```ts
export const createNpmSearchHandler = (keywords?: string[]) => 
  async (
    context: string[],
    executeShellCommand: Fig.ExecuteShellCommandFunction,
    shellContext: Fig.ShellContext
  ) => {
    // the logic you wrote for the the generator goes here
  }
```
Then in the `npm` spec you can use it so:
```ts
export const npmSearchGenerator: Fig.Generator = {
  trigger: ...,
  getQueryTerm: ...,
  cache: ...,
  custom: createNpmSearchHandler(),
}
```
And in `@magnolia/cli`:
```ts
const magnoliaPackageGenerator: Fig.Generator = {
  ...npmSearchGenerator,
  custom: createNpmSearchHandler([/* keywords here */])
}
```

2022-09-05 11:11 UTC, fedeci approved these changes
Thanks!

2022-09-05 11:11 UTC, merged