feat: add k9s completion spec
withfig/autocomplete pull request #1477
Opened 2022-09-04 13:10 UTC by AlanSyue

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature

**What is the current behavior? (You can also link to an open issue here)**
N/A

**What is the new behavior (if this is a feature change)?**
Add `k9s` completion spec ([issue](https://github.com/withfig/autocomplete/issues/1454))

**Additional info:**
N/A

2022-09-05 03:06 UTC, SeparateRecords commented on src/k9s.ts
> +    },
```suggestion
    {
      name: "help",
      description: "Help about any command",
      args: { name: "command", isOptional: true, template: "help" },
    },
```

2022-09-05 03:07 UTC, SeparateRecords commented on src/k9s.ts
> +      },
```suggestion
      args: {
        name: "string",
        description: "The log level",
        default: "info",
        suggestions: ["info", "warn", "debug", "trace", "error"],
      },
```

2022-09-05 03:07 UTC, SeparateRecords submitted a review, later dismissed
Looking good!! Not much to change here, thanks so much for contributing this 🙂

2022-09-05 18:11 UTC, fedeci requested changes
Thanks for this contribution @AlanSyue! Let me know if you need any help!

2022-09-05 18:11 UTC, fedeci commented on src/k9s.ts
> +        description: "The path to a client key file",
```suggestion
        description: "The path to a client key file",
        template: "filepaths",
```

2022-09-05 18:11 UTC, fedeci commented on src/k9s.ts
> +        description: "The path to a cert file",
```suggestion
        description: "The path to a cert file",
        template: "filepaths",
```

2022-09-05 18:11 UTC, fedeci commented on src/k9s.ts
> +        description: "The path to the kubeconfig file",
```suggestion
        description: "The path to the kubeconfig file",
        template: "filepaths",
```

2022-09-05 18:11 UTC, fedeci commented on src/k9s.ts
> +        description: "The path of the log file",
```suggestion
        description: "The path of the log file",
        template: "filepaths",
        suggestCurrentToken: true,
```

2022-09-06 13:44 UTC, AlanSyue commented
> Thanks for this contribution @AlanSyue! Let me know if you need any help!

Thanks for your suggestion!

2022-09-07 14:53 UTC, fedeci approved these changes
Thanks!

2022-09-07 14:53 UTC, merged