Added additional formatOptions to `trivy fs` command
withfig/autocomplete pull request #1480
Opened 2022-09-05 13:39 UTC by nevotheless

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
The spec for trivy seems a bit broken in regards of `sbom` scans. Since i'm not too familiar with the trivy cli i only added the additional `--format`'s for the `trivy fs` command.

**What is the current behavior? (You can also link to an open issue here)**
`trivy fs --format` is missing some formats.

**What is the new behavior (if this is a feature change)?**
`trivy fs --format` now includes additional formats.

**Additional info:**
The spec for `trivy sbom` seems to need changes as well.

2022-09-05 18:07 UTC, fedeci requested changes
Thanks for this PR!

2022-09-05 18:07 UTC, fedeci commented on src/trivy.ts
> +        fsFormatOptions,
`--format` is not a subcommand but it is an option instead. All the others too, can you change those? It should be as simple as changing `subcommands: [` to `options: [`
Also can you please check the others subcommands too? Apparently they have the same problem (e.g. the image subcommand)

2022-09-05 18:37 UTC, nevotheless commented on src/trivy.ts
> +        fsFormatOptions,
Thanks for the feedback. Much appreciated :) I'll do that tomorrow and also take a look at the other subcommands as well.

2022-09-05 18:48 UTC, fedeci commented on src/trivy.ts
> +        fsFormatOptions,
Thanks!

2022-09-13 18:43 UTC, nevotheless commented on src/trivy.ts
> +        fsFormatOptions,
Sorry, i haven't forgotten. I have little time right now but i'll try to finish this PR as soon as i can.

2023-10-12 19:33 UTC, closed without merging