Update `ffmpeg` spec
withfig/autocomplete pull request #1485
Opened 2022-09-08 14:14 UTC by ryanccn

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

regular update for `ffmpeg`

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2022-09-09 00:42 UTC, SeparateRecords requested changes
Looking good! One small comment to resolve then it's an easy merge

2022-09-09 00:42 UTC, SeparateRecords commented on src/ffmpeg.ts
> +
This PR introduces a lot of blank lines, can you remove these?
If you're a Vim user: `:%s/,\n\n/,\r/g`

2022-09-09 00:48 UTC, mschrage commented on src/ffmpeg.ts
> +
Or perhaps just update the function that generates this spec?
https://github.com/ryanccn/ffmpeg-fig

2022-09-09 03:53 UTC, ryanccn commented on src/ffmpeg.ts
> +
Well fair, probably some new line issues in the template. I'll fix it this weekend hopefully!

2022-10-11 12:51 UTC, ryanccn commented on src/ffmpeg.ts
> +
Quit a bit late but it's fixed :D

2022-10-12 03:32 UTC, SeparateRecords requested changes
LGTM! Only one change, I think the linter is failing specifically because of this one line

2022-10-12 03:32 UTC, SeparateRecords commented on src/ffmpeg.ts
> + const completionSpec: Fig.Spec = {
```suggestion
const completionSpec: Fig.Spec = {
```

2022-10-12 03:32 UTC, SeparateRecords commented
(Quick fix: `npx prettier -w src/ffmpeg.ts`)

2022-10-12 03:33 UTC, SeparateRecords commented
Also, if you want to close and reopen the PR for the hacktoberfest credit, I wouldn't blame you!! You're welcome to 🙂

2022-10-15 00:48 UTC, SeparateRecords approved these changes
Awesome, thanks so much @ryanccn!!

2022-10-15 00:48 UTC, merged