added Specs for m-cli
withfig/autocomplete pull request #1508
Opened 2022-09-16 23:47 UTC by BalliAsghar

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adding completion spec for [m-cli](https://github.com/rgcr/m-cli) -  Swiss Army Knife for macOS

2022-09-19 02:27 UTC, SeparateRecords approved these changes
WOW!! That's a huge spec. Thank you _so much_ for contributing this!

Lots of feedback but it's mostly ways to generate dynamic suggestions for each subcommand 😄

The only two pieces of feedback that apply broadly:
1. The commands have `help` subcommands, which should be added manually instead of with an option named `help`
2. The `list` commands have two names, `ls` and `list`, so that should be fixed on all of them. You can use an array for the name 🙂

(sorry for the delay btw, I've been slowly chipping away at writing the review since you opened the PR)

2022-09-19 02:27 UTC, SeparateRecords commented on src/m.ts
> +              },
Can make a generator:
```ts
const generateNetworkLocations: Fig.Generator = {
  script: "m network list | grep -e 'Device: ' | cut -d' ' -f2-",
  splitOn: "\n",
};
```

```suggestion
              args: {
                name: "name",
                description: "Name of the location",
                generators: generateNetworkLocations,
              },
```

And you can add this to the `switch` subcommand below

2022-09-19 02:27 UTC, SeparateRecords commented on src/m.ts
> +              },
Can reuse the generator from `kill.ts`:
```ts
function getPidIcon(path: string): string {
  const idx = path.indexOf(".app/");
  if (idx === -1) {
    return "fig://icon?type=gear";
  }
  return "fig://" + path.slice(0, idx + 4);
}

const generatePids: Fig.Generator = {
  script: "ps axo pid,comm | sed 1d",
  postProcess: (result) => {
    return result.split("\n").map((line) => {
      const [pid, path] = line.trim().split(/\s+/);
      const name = path.slice(path.lastIndexOf("/") + 1);
      return {
        name: pid,
        description: path,
        displayName: `${pid} (${name})`,
        icon: getPidIcon(path),
      };
    });
  },
};
```

```suggestion
              args: {
                name: "pid",
                description: "Process id",
                generators: generatePids,
              },
```

2022-09-19 02:27 UTC, SeparateRecords commented on src/m.ts
> +            },
```suggestion
            {
              name: "script",
              description: "Path to script",
              isOptional: true,
              template: "filepaths",
            },
```

2022-09-19 02:27 UTC, SeparateRecords commented on src/m.ts
> +          name: "-f",
```suggestion
          name: ["-f", "--force"],
```

2022-09-19 02:27 UTC, SeparateRecords commented on src/m.ts
> +          },
Can make a generator for services:
```ts
const generateServices: Fig.Generator = {
  script: "launchctl list | awk '{ print $3 }'",
  splitOn: "\n",
};
```

And you can use this in the args that take a service

2022-09-19 02:27 UTC, SeparateRecords commented on src/m.ts
> +          },
The user generator we made earlier can be used again here!

2022-09-19 02:27 UTC, SeparateRecords commented on src/m.ts
> +      ],
```suggestion
      args: {
        name: "image",
        description: "Path to the wallpaper",
        template: "filepaths",
      },
```

2022-09-19 02:27 UTC, SeparateRecords commented on src/m.ts
> +          },
We'll reuse the generator from [wifi-password](https://github.com/withfig/autocomplete/blob/68a357150d28094967cb9e963cfbb2640605ca05/src/wifi-password.ts)

```ts
const generateWifiNetworks: Fig.Generator = generators: {
  script:
    "networksetup -listallhardwareports | awk '/Wi-Fi/{getline; print $2}' | xargs networksetup -listpreferredwirelessnetworks | tail -n +2",
  postProcess: (out) =>
    out
      .trim()
      .split("\n")
      .map((line) => ({ name: line.trim() })),
},
```

```suggestion
          args: {
            name: "ESSID",
            description: "ESSID",
            isOptional: true,
            generators: generateWifiNetworks,
          },
```

Can use the same generator for any other place that takes an ssid

2022-09-19 02:27 UTC, SeparateRecords commented on src/m.ts
> +        },
Can merge

2022-09-19 02:27 UTC, SeparateRecords commented on src/m.ts
> +    },
There's some parsing weirdness that happens when you have an option that has no leading dashes, you'd need to add `parserDirectives.flagsArePosixNoncompliant` which makes other things behave strangely. I think it's better overall to add the `help` subcommand to each command, honestly 🙂

2022-09-19 14:12 UTC, BalliAsghar commented on src/m.ts
> +  description: " Swiss Army Knife for macOS",
I would remove the icon entirely/

2022-09-19 15:47 UTC, BalliAsghar commented on src/m.ts
> +      ],
it shows help command through isPersistent at options!

2022-09-20 02:01 UTC, SeparateRecords requested changes
Feedback round 2! Fewer changes this time, should be fine to merge after this. Thanks so much for all the work you're putting into this, it's really paying off 🤩

After it's merged, would you be open to us tweeting about it from [@fig](https://twitter.com/fig)? Happy to give you a shoutout!

2022-09-20 04:57 UTC, BalliAsghar commented
> Feedback round 2! Fewer changes this time, should be fine to merge after this. Thanks so much for all the work you're putting into this, it's really paying off 🤩
> 
> After it's merged, would you be open to us tweeting about it from [@fig](https://twitter.com/fig)? Happy to give you a shoutout!

Sure! shoutout at [@BalliAsghar ](https://twitter.com/balli_asghar) would be great. thanks

2022-09-20 05:42 UTC, SeparateRecords approved these changes
This is so good. Thank you so much for all the work you put into this, it's awesome!!

2022-09-20 05:46 UTC, merged