feat: add dotenv-vault
withfig/autocomplete pull request #1519
Opened 2022-09-25 22:54 UTC by motdotla

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Adding completion spec for [dotenv-vault](https://github.com/dotenv-org/dotenv-vault)

I and others enjoy Fig but have been missing autocompletion for dotenv-vault. Excited to get it into Fig's excellent autocompletion system!

2022-09-25 23:56 UTC, SeparateRecords requested changes
Looks good @motdotla ! Thank you so much. Just left a couple of review comments, should be quick to resolve then we can merge.

2022-09-25 23:56 UTC, SeparateRecords commented on src/dotenv-vault.ts
> +};
Little simplification, you can actually use `persistent: true` on an option, put it on the root command, then it will show up on each subcommand! Means you can just define `--help` inline in the spec and you don't need to reference it in each subcommand.

```ts
const completionSpec: Fig.Spec = {
  name: "dotenv-vault",
  description: "...",
  options: [
    {
      name: "--help",
      description: "Get documentation for the command",
      persistent: true,
    },
  ],
  // ...
}
```

2022-09-25 23:56 UTC, SeparateRecords commented on src/dotenv-vault.ts
> +};
Adding `template: "filepaths"` to an arg gives you `cd`-like suggestions!

```suggestion
const filenameArg = {
  name: "FILENAME",
  description:
    "Set input filename. Defaults to .env for development and .env.{environment} for other environments",
  isOptional: true,
  template: "filepaths",
};
```

2022-09-25 23:56 UTC, SeparateRecords commented on src/dotenv-vault.ts
> +const dotenvVaultArg = {
Absolutely not required but if you add the types you'll get nicer suggestions for the arg properties 🙂
```suggestion
const dotenvVaultArg: Fig.Arg = {
```

2022-09-25 23:56 UTC, SeparateRecords commented on src/dotenv-vault.ts
> +  },
```suggestion
  args: {
    name: "DOTENV_ME",
    description: "Pass .env.me (DOTENV_ME) credential directly",
    template: "filepaths",
  },
```

2022-09-26 00:06 UTC, motdotla commented on src/dotenv-vault.ts
> +};
Handy. Thank you.

2022-09-26 00:08 UTC, motdotla commented on src/dotenv-vault.ts
> +};
This is really great!

Any plans to let me filter the type of files in the filepath? Ideally I would only want to display `.env*` files.

So a glob pattern here would be really wonderful. Something like `template: "filepaths:.env*"`

2022-09-26 00:08 UTC, motdotla commented on src/dotenv-vault.ts
> +  },
Thank you, but this one actually takes a string credential representing a `me_1234` token.

2022-09-26 00:09 UTC, motdotla commented on src/dotenv-vault.ts
> +const dotenvVaultArg = {
I'll skip this for now.

2022-09-26 01:28 UTC, SeparateRecords commented on src/dotenv-vault.ts
> +};
Ahhh yes this is possible! We have `@fig/autocomplete-generators`, you can use a regex.

```ts
import { filepaths } from "@fig/autocomplete-generators";
```

Pretty sure this regex should work for you:
```ts
const filenameArg = {
  name: "FILENAME",
  description:
    "Set input filename. Defaults to .env for development and .env.{environment} for other environments",
  isOptional: true,
  generators: filepaths({ matches: /^\.env\..+$/ }),
};
```

Example from bun:
https://github.com/withfig/autocomplete/blob/ed9580a7e411f9a679a537eaa419e84d8fb7f09c/src/bun.ts#L100

2022-09-26 04:58 UTC, SeparateRecords approved these changes
Amazing, thank you @motdotla ! 😄

2022-09-26 05:01 UTC, merged