Add src/sqlfluff.ts
withfig/autocomplete pull request #1520
Opened 2022-09-25 23:00 UTC by anubhavsharma515

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2022-09-25 23:59 UTC, SeparateRecords requested changes
Having had a look at this, seems like running the auto-fix linter and formatting will fix all the comments I would have!
Here's the command for you to run:
```
npx eslint --fix src/sqlfluff.ts; npx prettier --write src/sqlfluff.ts
```

2022-09-26 00:01 UTC, anubhavsharma515 commented
> Having had a look at this, seems like running the auto-fix linter and formatting will fix all the comments I would have! Here's the command for you to run:
> 
> ```
> npx eslint --fix src/sqlfluff.ts; npx prettier --write src/sqlfluff.ts
> ```

Ah thanks for your quick reply Robert, much appreciated! Just ran the command and pushed the linted file 👍

2022-09-26 00:19 UTC, SeparateRecords requested changes
Thanks for fixing the errors! Had another look and wrote up some comments on the first subcommand. I think it mostly applies to the other subcommands too, basically just need to add `args` to the options that take an argument. Should be pretty quick to do 🙂

2022-09-26 00:19 UTC, SeparateRecords commented on src/sqlfluff.ts
> +        },
```suggestion
        {
          name: ["--format", "-f"],
          description:
            "What format to return the lint result in (default=human)",
          args: {
            name: "format",
            suggestions: ["human", "json", "yaml", "github-annotation", "github-annotation-native"],
          },
        },
```

2022-09-26 00:19 UTC, SeparateRecords commented on src/sqlfluff.ts
> +        },
```suggestion
        {
          name: ["--verbose", "-v"],
          description:
            "Verbosity, how detailed should the output be. This is stackable, so -vv is more verbose than -v. For the most verbose option try -vvvv or -vvvvv",
          isRepeatable: 5,
        },
```

2022-09-26 00:19 UTC, SeparateRecords commented on src/sqlfluff.ts
> +        },
```suggestion
        {
          name: ["--ignore", "-i"],
          description:
            "Ignore particular families of errors so that they don’t cause a failed run. -–ignore behaves somewhat like noqa comments, except it applies globally",
          args: { name: "errors" },
        },
```

2022-09-26 00:19 UTC, SeparateRecords commented on src/sqlfluff.ts
> +        },
```suggestion
        {
          name: ["--templater", "-t"],
          description: "The templater to use (default=jinja)",
          args: {
            name: "name",
            suggestions: ["raw", "jinja", "python", "placeholder"],
          },
        },
```

2022-09-26 00:19 UTC, SeparateRecords commented on src/sqlfluff.ts
> +        },
```suggestion
        {
          name: ["--rules", "-r"],
          description: "Narrow the search to only specific rules",
          args: { name: "name" },
        },
```

2022-09-26 00:19 UTC, SeparateRecords commented on src/sqlfluff.ts
> +        },
```suggestion
        {
          name: ["--exclude-rules", "-e"],
          description:
            "Exclude specific rules. This could either be the allowlist, or the general set if there is no specific allowlist",
          args: { name: "name" },
        },
```

2022-09-26 00:19 UTC, SeparateRecords commented on src/sqlfluff.ts
> +        },
```suggestion
        {
          name: ["--processes", "-p"],
          description:
            "The number of parallel processes to run. Positive numbers work as expected. Zero and negative numbers will work as number_of_cpus - number. e.g -1 means all cpus except one. 0 means all cpus",
          args: { name: "number" },
        },
```

2022-09-26 00:19 UTC, SeparateRecords commented on src/sqlfluff.ts
> +        },
`--version` and `--help` look like they're global flags, you can define these on the root spec itself and set `persistent: true` 🙂

```suggestion
```

```ts
const completionSpec: Fig.Spec = {
  name: "sqlfluff",
  description: "A dialect-flexible and configurable SQL linter",
  options: [
    {
      name: "--version",
      description: "Show the version and exit",
      persistent: true,
    },
    {
      name: ["--help", "-h"],
      description: "Show help for sqlfluff",
      persistent: true,
    },
  ],
  subcommands: [
    // ...
  ],
};
```

2022-09-26 00:19 UTC, SeparateRecords commented on src/sqlfluff.ts
> +        },
```suggestion
```

2022-09-26 00:19 UTC, SeparateRecords commented on src/sqlfluff.ts
> +      },
```suggestion
      args: {
        template: "filepaths",
        isOptional: true,
        isVariadic: true,
      },
```

2022-09-26 00:19 UTC, SeparateRecords commented on src/sqlfluff.ts
> +      },
```suggestion
      args: {
        template: "filepaths",
        isOptional: true,
        isVariadic: true,
      },
```

2022-09-26 00:19 UTC, SeparateRecords commented on src/sqlfluff.ts
> +        },
```suggestion
        {
          name: "--encoding",
          description:
            "Specify encoding to use when reading and writing files. Defaults to autodetect",
          args: { name: "encoding" },
        },
```

2022-09-26 00:19 UTC, SeparateRecords commented on src/sqlfluff.ts
> +        },
```suggestion
        {
          name: "--config",
          description:
            "Include additional config file. By default the config is generated from the standard configuration files described in the documentation. This argument allows you to specify an additional configuration file that overrides the standard configuration files. N.B. cfg format is required",
          args: { name: "file", template: "filepaths" },
        },
```

2022-09-26 00:19 UTC, SeparateRecords commented on src/sqlfluff.ts
> +        },
```suggestion
        {
          name: "--write-output",
          description:
            "Optionally provide a filename to write the results to, mostly used in tandem with --format. NB: Setting an output file re-enables normal stdout logging",
          args: { name: "file", template: "filepaths" },
        },
```

2022-09-26 01:36 UTC, SeparateRecords approved these changes
Awesome, thank you so much @anubhavsharma515! This is fantastic 😊

2022-09-26 01:40 UTC, SeparateRecords commented
My bad, looks like I should've said `isPersistent` 🤦 I'll fix the errors then merge. Thank you again!!

2022-09-26 01:40 UTC, anubhavsharma515 commented
@SeparateRecords, I really appreciate the super specific feedback on this Robert! It's my first open-source contribution and really glad it's on a tool that's made my terminal experience so much more enjoyable!!

2022-09-26 01:44 UTC, SeparateRecords commented
Sure! Our reference docs are auto-generated, https://fig.io/docs/reference/option#isrepeatable

Lots more info there. Some of the _written_ docs are slightly out of date, I'll be reviewing that and updating it soon. But the reference docs for `Subcommand`, `Option`, and `Arg` will be correct

2022-09-26 01:54 UTC, merged

2022-09-26 02:02 UTC, SeparateRecords commented
??? That's... unexpected.

cc @mschrage @fedeci

2022-09-26 03:08 UTC, anubhavsharma515 commented
> Fails
> 🚫	
> Danger failed to run `./dangerfile-invite.ts`.
> 
> ## Error HttpError
> ```
> You must be an admin to add or update an organization membership.
> HttpError: You must be an admin to add or update an organization membership.
>     at /home/runner/work/autocomplete/autocomplete/node_modules/@octokit/request/dist-node/index.js:86:21
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> ```
> 
> ### Dangerfile
> ```
> -----------------------^
> ```
> 
> @anubhavsharma515 Hey! Thanks so much for your contribution!
> 
> As a token of our appreciation, we've invited you to join the Fig GitHub organization. Accepting means you can display Fig's logo on your GitHub profile's list of member orgs. We also have a special #contributors channel in our [community Discord](https://fig.io/community) and we'd love for you to join.
> 
> Excited to have you in the community!
> 
> Matt & Brendan
> 
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [39d9957](https://github.com/withfig/autocomplete/commit/39d995770f4de45aa90c6e25c22bd6ce1043b015)

Hey @SeparateRecords! I was hoping to ask to ask if this invite to the organization is an email I should be looking out for or..?

2022-09-26 04:57 UTC, SeparateRecords commented
This is something we used to have set up, but it got really unmanageable, so we now use the members just for team members (there's 300+ contributors in this repo, you can see the problem 😅)

That's why I was so surprised to see this! I thought this wasn't supposed to get triggered anymore 🤨