feat: add gem subcommands
withfig/autocomplete pull request #1555
Opened 2022-09-30 09:29 UTC by AlanSyue

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature

**What is the current behavior? (You can also link to an open issue here)**
N/A

**What is the new behavior (if this is a feature change)?**
Add more gem subcommands

**Additional info:**
According to the [official document](https://guides.rubygems.org/command-reference/), GEM has the following commands:

- [ ] [gem build](https://guides.rubygems.org/command-reference/#gem-build)
- [ ] [gem cert](https://guides.rubygems.org/command-reference/#gem-cert)
- [ ] [gem check](https://guides.rubygems.org/command-reference/#gem-check)
- [ ] [gem cleanup](https://guides.rubygems.org/command-reference/#gem-cleanup)
- [ ] [gem contents](https://guides.rubygems.org/command-reference/#gem-contents)
- [ ] [gem dependency](https://guides.rubygems.org/command-reference/#gem-dependency)
- [ ] [gem environment](https://guides.rubygems.org/command-reference/#gem-environment)
- [ ] [gem fetch](https://guides.rubygems.org/command-reference/#gem-fetch)
- [ ] [gem generate_index](https://guides.rubygems.org/command-reference/#gem-generate_index)
- [ ] [gem help](https://guides.rubygems.org/command-reference/#gem-help)
- [ ] [gem info](https://guides.rubygems.org/command-reference/#gem-info)
- [ ] [gem install](https://guides.rubygems.org/command-reference/#gem-install)
- [ ] [gem list](https://guides.rubygems.org/command-reference/#gem-list)
- [ ] [gem lock](https://guides.rubygems.org/command-reference/#gem-lock)
- [ ] [gem mirror](https://guides.rubygems.org/command-reference/#gem-mirror)
- [ ] [gem open](https://guides.rubygems.org/command-reference/#gem-open)
- [ ] [gem outdated](https://guides.rubygems.org/command-reference/#gem-outdated)
- [ ] [gem owner](https://guides.rubygems.org/command-reference/#gem-owner)
- [ ] [gem pristine](https://guides.rubygems.org/command-reference/#gem-pristine)
- [ ] [gem push](https://guides.rubygems.org/command-reference/#gem-push)
- [ ] [gem query](https://guides.rubygems.org/command-reference/#gem-query)
- [ ] [gem rdoc](https://guides.rubygems.org/command-reference/#gem-rdoc)
- [ ] [gem search](https://guides.rubygems.org/command-reference/#gem-search)
- [ ] [gem server](https://guides.rubygems.org/command-reference/#gem-server)
- [ ] [gem signin](https://guides.rubygems.org/command-reference/#gem-signin)
- [ ] [gem signout](https://guides.rubygems.org/command-reference/#gem-signout)
- [ ] [gem sources](https://guides.rubygems.org/command-reference/#gem-sources)
- [ ] [gem specification](https://guides.rubygems.org/command-reference/#gem-specification)
- [ ] [gem stale](https://guides.rubygems.org/command-reference/#gem-stale)
- [ ] [gem uninstall](https://guides.rubygems.org/command-reference/#gem-uninstall)
- [ ] [gem unpack](https://guides.rubygems.org/command-reference/#gem-unpack)
- [ ] [gem update](https://guides.rubygems.org/command-reference/#gem-update)
- [ ] [gem which](https://guides.rubygems.org/command-reference/#gem-which)
- [ ] [gem yank](https://guides.rubygems.org/command-reference/#gem-yank)

2022-12-28 15:13 UTC, AlanSyue commented
I have read the CLA Document and I hereby sign the CLA

2022-12-28 15:20 UTC, AlanSyue commented
@SeparateRecords Should we allow some subcommands to be released first? lol

2023-02-07 14:32 UTC, fedeci requested changes
Thanks @AlanSyue for this spec! It looks great, I can see it has been written surgically! I left a ton of suggestions but they are all the same, I think adding `exclusiveOn` will enhance this spec more!

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Only return files in the Gem’s lib_dirs",
```suggestion
          description: "Only return files in the Gem’s lib_dirs",
          exclusiveOn: ["--no-lib-only"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Don’t include installed path prefix",
```suggestion
          description: "Don’t include installed path prefix",
          exclusiveOn: ["--no-prefix"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Include installed path prefix",
```suggestion
          description: "Include installed path prefix",
          exclusiveOn: ["--prefix"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Show only the gem install dir",
```suggestion
          description: "Show only the gem install dir",
          exclusiveOn: ["--no-show-install-dir"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Do not show only the gem install dir",
```suggestion
          description: "Do not show only the gem install dir",
          exclusiveOn: ["--show-install-dir"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Allow prerelease versions of a gem",
```suggestion
          description: "Allow prerelease versions of a gem",
          exclusiveOn: ["--no-prerelease"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Do not allow prerelease versions of a gem",
```suggestion
          description: "Do not allow prerelease versions of a gem",
          exclusiveOn: ["--prerelease"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Include reverse dependencies in the output",
```suggestion
          description: "Include reverse dependencies in the output",
          exclusiveOn: ["--no-reverse-dependencies"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Do not include reverse dependencies in the output",
```suggestion
          description: "Do not include reverse dependencies in the output",
          exclusiveOn: ["--reverse-dependencies"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +      description: "Do not set the verbose level of output",
```suggestion
      description: "Do not set the verbose level of output",
      exclusiveOn: ["--verbose"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +      isPersistent: true,
```suggestion
      isPersistent: true,
      exclusiveOn: ["--no-verbose"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Display detailed information of gem(s)",
```suggestion
          description: "Display detailed information of gem(s)",
          exclusiveOn: ["--no-details"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Do not display detailed information of gem(s)",
```suggestion
          description: "Do not display detailed information of gem(s)",
          exclusiveOn: ["--details"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "[Deprecated] Update local source cache",
```suggestion
          description: "[Deprecated] Update local source cache",
          deprecated: true,
          exclusiveOn: ["--no-update-sources"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "[Deprecated] Do not update local source cache",
```suggestion
          description: "[Deprecated] Do not update local source cache",
          deprecated: true,
          exclusiveOn: ["--update-sources"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Do not allow prerelease versions of a gem",
```suggestion
          description: "Do not allow prerelease versions of a gem",
          exclusiveOn: ["--prerelease"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Allow prerelease versions of a gem",
```suggestion
          description: "Allow prerelease versions of a gem",
          exclusiveOn: ["--no-prerelease"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +            "Do not show any confirmation prompts and behave as if 'yes' was always answered",
```suggestion
            "Do not show any confirmation prompts and behave as if 'yes' was always answered",
          exclusiveOn: ["--no-force"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +            "Show any confirmation prompts and behave as if 'yes' was always answered",
```suggestion
            "Show any confirmation prompts and behave as if 'yes' was always answered",
          exclusiveOn: ["--force"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Do not display detailed information of gem(s)",
```suggestion
          description: "Do not display detailed information of gem(s)",
          exclusiveOn: ["--details"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Display detailed information of gem(s)",
```suggestion
          description: "Display detailed information of gem(s)",
          exclusiveOn: ["--no-details"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Equivalent to --no-installed",
```suggestion
          description: "Equivalent to --no-installed",
          exclusiveOn: ["--installed"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Do not generate RDoc HTML",
```suggestion
          description: "Do not generate RDoc HTML",
          exclusiveOn: ["--rdoc"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Generate RDoc HTML",
```suggestion
          description: "Generate RDoc HTML",
          exclusiveOn: ["--no-rdoc"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Generate RI data",
```suggestion
          description: "Generate RI data",
          exclusiveOn: ["--no-ri"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Do not generate RI data",
```suggestion
          description: "Do not generate RI data",
          exclusiveOn: ["--ri"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Overwrite installed documents",
```suggestion
          description: "Overwrite installed documents",
          exclusiveOn: ["--no-overwrite"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Do not overwrite installed documents",
```suggestion
          description: "Do not overwrite installed documents",
          exclusiveOn: ["--overwrite"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Equivalent to --no-installed",
```suggestion
          description: "Equivalent to --no-installed",
          exclusiveOn: ["--installed"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Display detailed information of gem(s)",
```suggestion
          description: "Display detailed information of gem(s)",
          exclusiveOn: ["--no-details"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Do not display detailed information of gem(s)",
```suggestion
          description: "Do not display detailed information of gem(s)",
          exclusiveOn: ["--details"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Allow prerelease versions of a gem",
```suggestion
          description: "Allow prerelease versions of a gem",
          exclusiveOn: ["--no-prerelease"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Do not allow prerelease versions of a gem",
```suggestion
          description: "Do not allow prerelease versions of a gem",
          exclusiveOn: ["--prerelease"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Suggest alternates when gems are not found",
```suggestion
          description: "Suggest alternates when gems are not found",
          exclusiveOn: ["--no-suggestions"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Do not suggest alternates when gems are not found",
```suggestion
          description: "Do not suggest alternates when gems are not found",
          exclusiveOn: ["--suggestions"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Generate indexes for RubyGems (always true)",
```suggestion
          description: "Generate indexes for RubyGems (always true)",
          exclusiveOn: ["--no-modern"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Do not generate indexes for RubyGems",
```suggestion
          description: "Do not generate indexes for RubyGems",
          exclusiveOn: ["--modern"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Do not fail if unable to satisfy a dependency",
```suggestion
          description: "Do not fail if unable to satisfy a dependency",
          exclusiveOn: ["--strict"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Fail if unable to satisfy a dependency",
```suggestion
          description: "Fail if unable to satisfy a dependency",
          exclusiveOn: ["--no-strict"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +          description: "Rewrite executables with a shebang of /usr/bin/env",
```suggestion
          description: "Rewrite executables with a shebang of /usr/bin/env",
          exclusiveOn: ["--no-env-shebang"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +            "Do not rewrite executables with a shebang of /usr/bin/env",
```suggestion
            "Do not rewrite executables with a shebang of /usr/bin/env",
          exclusiveOn: ["--env-shebang"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +            "Restore gems with extensions in addition to regular gems",
```suggestion
            "Restore gems with extensions in addition to regular gems",
          exclusiveOn: ["--no-extensions"],
```

2023-02-07 14:32 UTC, fedeci commented on src/gem.ts
> +            "Do not restore gems with extensions in addition to regular gems",
```suggestion
            "Do not restore gems with extensions in addition to regular gems",
          exclusiveOn: ["--extensions"],
```

2023-02-09 19:32 UTC, fedeci approved these changes
Thanks!

2023-02-09 19:32 UTC, merged