feat: add supabase completion spec
withfig/autocomplete pull request #1557
Opened 2022-10-01 03:44 UTC by lyqht

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Closes #713 

This spec is autogenerated using cobra.
Thanks @fedeci for pointing out the guide on Fig! 

P.S. please add hacktoberfest label 🐱 

**Screenshots**

![Fig-SupabaseCLI-Demo](https://user-images.githubusercontent.com/35736525/193386032-7b7d2096-eced-42f1-8f02-a60326c08cc1.gif)

2022-10-01 16:40 UTC, fedeci commented
Ref #713

2022-10-01 16:45 UTC, fedeci requested changes
Thanks! Just a couple issues to fix, it would be cool to have generators in the future!

2022-10-01 16:45 UTC, fedeci commented on src/supabase.ts
> +              args: { name: "file" },
```suggestion
              args: {
                name: "file",
                template: "filepaths",
                suggestCurrentToken: true,
              },
```

2022-10-01 16:45 UTC, fedeci commented on src/supabase.ts
> +              args: { name: "env-file" },
```suggestion
              args: {
                name: "env-file",
                template: "filepaths",
              },
```

2022-10-01 16:45 UTC, fedeci commented on src/supabase.ts
> +              args: { name: "env-file" },
```suggestion
              args: {
                name: "env-file",
                template: "filepaths",
              },
```

2022-10-02 03:35 UTC, lyqht commented
Thanks @fedeci, have committed your suggestions.

2022-10-02 17:34 UTC, fedeci approved these changes

2022-10-02 17:35 UTC, fedeci commented
Thanks!

2022-10-02 17:35 UTC, merged