feat: add airflow
withfig/autocomplete pull request #1560
Opened 2022-10-01 20:55 UTC by munyoudoum

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature
**What is the current behavior? (You can also link to an open issue here)**
https://github.com/withfig/autocomplete/issues/1343
**What is the new behavior (if this is a feature change)?**
add airflow CLI
**Additional info:**

2022-10-02 17:41 UTC, fedeci commented
Hi @munyoudoum was this autogenerated through some kind of tool?

2022-10-02 17:59 UTC, munyoudoum commented
@fedeci yeah with argparse. Airflow CLI is using argparse

2022-10-02 18:25 UTC, fedeci commented
> @fedeci yeah with argparse. Airflow CLI is using argparse

Great! This saves me a bunch of time trying to discover nitpicks. I am still giving a look here and there to suggest imporvements.

2022-10-02 18:36 UTC, fedeci reviewed
It looks good. I just don not like the duplicate descriptions on options and arguments but that's likely an integration fault so I will fix it there.

2022-10-02 18:36 UTC, fedeci commented on src/airflow.ts
> +                  "Securing Flower with Basic Authentication. Accepts user:password pairs separated by a comma. Example: flower_basic_auth = user1:password1,user2:password2",
This can use the keyvalue generator with cache, see here for an example: https://github.com/withfig/autocomplete/blob/413e1de4606a1c825ac8de343b0653bedd076622/src/bun.ts#L1

2022-10-03 09:55 UTC, munyoudoum commented on src/airflow.ts
> +                  "Securing Flower with Basic Authentication. Accepts user:password pairs separated by a comma. Example: flower_basic_auth = user1:password1,user2:password2",
Ok. I have added 
```
                generators: keyValueList({
                  separator: ":",
                  keys: ["user"],
                  values: ["password"],
                }),
```

2022-10-03 17:02 UTC, fedeci requested changes

2022-10-03 17:02 UTC, fedeci approved these changes

2022-10-03 17:02 UTC, fedeci commented
Thanks!

2022-10-03 17:05 UTC, merged

2022-10-04 09:34 UTC, munyoudoum commented
@fedeci 
Can I have the `hacktoberfest-accepted` label please btw 😄 🙏

2022-10-04 09:38 UTC, fedeci commented
Of course! However I don't think it is required for PRs against a repo which is already tagged with the hacktoberfest label.