feat(dscl): Add completion specs
withfig/autocomplete pull request #1563
Opened 2022-10-03 07:20 UTC by plibither8

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Adds missing completion specs.

**What is the current behavior? (You can also link to an open issue here)**

Missing completion specs for the `dscl` command.

**What is the new behavior (if this is a feature change)?**

Adds the `dscl` command specs.

**Additional info:**

Closes #1545

2022-10-03 17:22 UTC, fedeci commented on src/dscl.ts
> +    loadSpec: "dscl",
Is `loadSped` here being used to enforce argument before commands?

2022-10-03 18:15 UTC, plibither8 commented on src/dscl.ts
> +    loadSpec: "dscl",
Sorta... yes. `dscl` has an awkward format, it requires the datasource argument before the actual subcommands. This was the best available workaround I could find, can this be done in a better way?

2022-10-04 03:22 UTC, SeparateRecords requested changes

2022-10-04 03:22 UTC, SeparateRecords commented on src/dscl.ts
> +}
We can make this a bit more type-safe to prevent accidental `undefined`s from future editors:

```suggestion
const args = {
  path: {
    name: "path",
    description: "Path to the record",
  } as Fig.Arg,
  key: {
    name: "key",
    description: "Directory Service record attribute type",
  } as Fig.Arg,
  keys: {
    name: "keys",
    description: "Directory Service record attribute type",
    isVariadic: true,
  } as Fig.Arg,
  plistPath: {
    name: "plist path",
    description: "Path to the plist file",
  } as Fig.Arg,
  valueIndex: {
    name: "value index",
    description: "Value index of the key",
  } as Fig.Arg,
  val: {
    name: "val",
    description: "Value of the key",
  } as Fig.Arg,
  vals: {
    name: "vals",
    description: "Value of the key",
    isVariadic: true,
  } as Fig.Arg,
  oldVal: {
    name: "old val",
    description: "Old value of the key",
  } as Fig.Arg,
  newVal: {
    name: "new val",
    description: "New value of the key",
  } as Fig.Arg,
} as const;

const arg = (name: keyof typeof args, merge?: Partial<Fig.Arg>): Fig.Arg => {
  return { ...args[name], ...merge };
}
```

You can use it like so:
```ts
arg("path", { isOptional: true });
```

2022-10-04 03:22 UTC, SeparateRecords commented on src/dscl.ts
> +  },
A generator for DSCL paths:
```ts
const generateDsclPath: Fig.Generator = {
  trigger: "/",
  getQueryTerm: "/",
  custom: async (tokens, executeShellCommand) => {
    const lastToken = tokens[tokens.length - 1];
    if (lastToken === "") {
      return [];
    }
    const dsclIndex = tokens.findIndex((token) => token === "dscl");
    let datasource: string;
    for (let i = dsclIndex + 1; i < tokens.length; i++) {
      const token = tokens[i];
      // skip if the current token is a flag
      if (token.startsWith("-")) {
        continue;
      }
      // skip if the previous token is a flag that takes an argument
      const prev = tokens[i - 1];
      if (prev === "-u" || prev === "-P" || prev === "-f") {
        continue;
      }
      datasource = token;
      break;
    }
    const search = lastToken.slice(0, lastToken.lastIndexOf("/"));
    let command = `dscl ${datasource} -list ${search}`;
    if (search === "") {
      command = `dscl ${datasource} -list /`;
    }
    const lines = await executeShellCommand(command);
    return lines.trim().split("\n").map((line) => ({
      name: line,
      icon: "📁",
      priority: line.slice(line.lastIndexOf("/") + 1).startsWith("_") ? 49 : 50,
    }));
  },
};
```

```suggestion
  path: {
    name: "path",
    description: "Path to the record",
    generators: generateDsclPath,
  },
```

2022-10-04 03:22 UTC, SeparateRecords commented on src/dscl.ts
> +    loadSpec: "dscl",
We can move the subcommands into their own command like this:

```ts
const dsclSubcommands: Fig.Subcommand = {
  name: "dscl",
  subcommands: [
    // ...
  ],
};
```

Then after defining that, reference it in the main spec:

```ts
  args: {
    name: "datasource",
    suggestions: [".", "..", "localhost", "localonly"],
    isOptional: true,
    loadSpec: dsclSubcommands,
  },
```

This is currently broken by the autocomplete engine, will fix this.

2022-10-04 03:22 UTC, SeparateRecords commented on src/dscl.ts
> +      name: ["delete", "-delete", "rm"],
```suggestion
      name: ["delete", "-delete", "rm", "-rm"],
```

2022-10-04 03:22 UTC, SeparateRecords commented on src/dscl.ts
> +      name: ["create", "-create", "mk"],
```suggestion
      name: ["create", "-create", "mk", "-mk"],
```

2022-10-04 03:22 UTC, SeparateRecords commented on src/dscl.ts
> +      name: ["list", "-list", "ls"],
```suggestion
      name: ["list", "-list", "ls", "-ls"],
```

2022-10-04 05:19 UTC, plibither8 commented on src/dscl.ts
> +}
Add `as const` doesn't work here as expected, resorted to a `satisfies` utility function that extracts the exact types.

2022-10-04 05:20 UTC, plibither8 commented on src/dscl.ts
> +  },
This is cool! Made some minor changes to the function to make it future-proof :)

2022-10-04 05:21 UTC, plibither8 commented on src/dscl.ts
> +    loadSpec: "dscl",
Implemented, thanks!

2022-10-04 06:24 UTC, SeparateRecords requested changes
Fantastic! Just a couple of things to change - two of which were mine 😅

2022-10-04 06:24 UTC, SeparateRecords commented on src/dscl.ts
> +        priority: line.slice(line.lastIndexOf("/") + 1).startsWith("_")
Just realized the cleaner+faster way of doing this 😄
Ultimately doesn't _really_ matter but it's still perf increase
```suggestion
        priority: line[line.lastIndexOf("/") + 1] === "_"
```

2022-10-04 06:24 UTC, SeparateRecords commented on src/dscl.ts
> +    const dsclIndex = tokens.findIndex((token) => token === "dscl");
Not sure why I went straight to `findIndex` the first time...
```suggestion
    const dsclIndex = tokens.indexOf("dscl");
```

2022-10-04 06:24 UTC, SeparateRecords commented on src/dscl.ts
> +      ) {
This is really clever!! We could extract this so we don't have to check it every loop, computed on load instead:
```ts

const dsclOptionsWithArgs = new Set<string>(
  dsclOptions
    .filter((option) => option.args !== undefined)
    .flatMap((option) => option.name),
);

const generateDsclPath: Fig.Generator = {
  // ...
```

Then we can just check the Set:

```suggestion
      if (dsclOptionsWithArgs.has(prev)) {
```

2022-10-04 07:09 UTC, plibither8 commented on src/dscl.ts
> +      ) {
Good suggestion! 😄

2022-10-04 12:19 UTC, SeparateRecords approved these changes
LGTM! Thank you so much!!

2022-10-04 12:19 UTC, merged