feat(gem): add update & outdated subcommands
withfig/autocomplete pull request #1565
Opened 2022-10-03 21:26 UTC by cadenkriese

**What kind of change does this PR introduce?**
Adds completion spec for two subcommands of `gem`.

**What is the current behavior?**
Missing completion spec.

**What is the new behavior**
Implemented completion spec.

2022-10-04 03:34 UTC, SeparateRecords commented
Hey @cadenkriese! Thanks for the PR 🙂

So this just adds the `outdated` and `update` subcommands but no options -- this is totally fine! Was wondering if you'd also be able to add their flags? No worries if you don't, we can absolutely merge as-is.

2022-10-04 03:36 UTC, SeparateRecords commented
(also, https://github.com/withfig/autocomplete/pull/1555 is open, but this has a much smaller scope so can be merged sooner)

2022-10-06 08:06 UTC, cadenkriese commented
No problem, I added the options. However, everything after `--prerelease` is duplicated between `gem install` and `gem update`. Should I put them in their own variable to share? Worth noting that I'm not familiar with typescript syntax, so pseudocode is much appreciated.

One other question, a lot of these options have an optional 'no-' prefix, ie. `--no-prerelease` to explicitly disable them, does fig have a convention for this?

2022-10-07 07:06 UTC, SeparateRecords requested changes
> everything after --prerelease is duplicated between gem install and gem update. Should I put them in their own variable to share?

No need! I'm a big fan of WET (write everything twice), no need to simplify it yet. Can be refactored later to clean up 🙂

> Worth noting that I'm not familiar with typescript syntax, so pseudocode is much appreciated.

That's okay! Only thing you really need to know for Fig:
```
const [varname]: [type] = [essentially a json object]
```

For a TypeScript array, just add `[]` after the type name, so a list of Fig options is

```ts
const options: Fig.Option[] = [
  // objects go here
];
```

We've designed the API surface to be as minimal as possible so there's not much to learn, unless you want to get into some _really_ wild and wacky generators like [`deno doc`](https://github.com/withfig/autocomplete/blob/589d8d2d80fb301fb249573483179429941d5a39/src/deno/generators.ts#L7-L184) (provides real-time symbol suggestions)

https://user-images.githubusercontent.com/52195359/194490777-7f814728-59a0-4a61-b516-5f238d0dad45.mp4

> One other question, a lot of these options have an optional 'no-' prefix, ie. --no-prerelease to explicitly disable them, does fig have a convention for this?

There's no convention for this, you've done it perfectly!

2022-10-07 07:06 UTC, SeparateRecords commented on src/gem.ts
> +          },
Do we know ahead of time what types are available? If we do, let's add `suggestions`! It's an array of strings

2022-10-07 07:06 UTC, SeparateRecords commented on src/gem.ts
> +          },
Can add `template: "filepaths"` for file suggestions 🙂

2022-10-08 04:50 UTC, cadenkriese commented on src/gem.ts
> +          },
I could only find the types 'rdoc' and 'ri' so I've added those. 👍

2022-10-10 00:00 UTC, SeparateRecords approved these changes
Looks good to me! Thanks @cadenkriese  🙂

2022-10-10 00:00 UTC, merged