feat(charm): Add completion
withfig/autocomplete pull request #1572
Opened 2022-10-04 13:56 UTC by mamercad

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

New completion for the [Charm](https://charm.sh/) CLI.

**What is the current behavior? (You can also link to an open issue here)**

There is no completion for the Charm CLI.

**What is the new behavior (if this is a feature change)?**

There will be completion for the Charm CLI.

**Additional info:**

2022-10-04 22:36 UTC, SeparateRecords approved these changes
Awesome, thanks @mamercad! One quick fix then it's good to merge.

2022-10-04 22:36 UTC, SeparateRecords commented on src/charm.ts
> +  description: "",
Can you add a description here?

2022-10-04 22:36 UTC, SeparateRecords requested changes
damnit wrong button

2022-10-05 06:54 UTC, SeparateRecords approved these changes
Beautiful, thank you so much and great job as always @mamercad 😄

2022-10-05 06:54 UTC, merged

2022-10-05 12:41 UTC, mamercad commented
> Beautiful, thank you so much and great job as always @mamercad 😄

Hehe, no worries, thanks for the merge!