feat(csdx): add generator
withfig/autocomplete pull request #1582
Opened 2022-10-05 01:49 UTC by davidalpert

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

feature: initial completions for the ContentStack nodejs CLI tool csdx

**Additional info:**

[ContentStack](https://www.contentstack.com/) is a cloud-hosted CMS tool:
> Contentstack is an API-based, headless content management platform that allows developers and content managers to create and manage content simultaneously and independently, to create websites and applications quickly.

It provides a nodejs CLI tool for command-line interaction with your content stacks.
- https://www.contentstack.com/docs/developers/cli/

2022-10-10 23:52 UTC, SeparateRecords requested changes
Looks good! Main feedback is to flip `isOptional` to `isRequired`, you can remove any `isRequired: false`

2022-10-10 23:52 UTC, SeparateRecords commented on src/csdx.ts
> +          isOptional: false,
For options, the default is to be optional, so the flag is `isRequired`. For optional options, you can omit it entirely!

2022-10-10 23:52 UTC, SeparateRecords commented on src/csdx.ts
> +    },
Makes --help show on each subcommand
```suggestion
    {
      name: ["--help", "-h"],
      description: "Show help for csdx",
      isPersistent: true,
    },
```

2022-10-19 08:16 UTC, davidalpert commented on src/csdx.ts
> +          isOptional: false,
@SeparateRecords thank you for this; fixed in a subsequent commit

2022-10-22 17:09 UTC, fedeci approved these changes
Thanks!

2022-10-22 17:16 UTC, merged