:memo: Update Swift options
withfig/autocomplete pull request #1583
Opened 2022-10-05 12:27 UTC by cHaLkdusT

Updated Swift options

2022-10-05 16:21 UTC, fedeci requested changes
Thanks for the PR! I have left a comment to fix before landing this.

2022-10-05 16:21 UTC, fedeci commented on src/swift.ts
> +        description: "The remap source paths in coverage info",
This can use the [keyValue](https://fig.io/docs/reference/generator/prebuilt-generators#keyvalueoptions) generator.

2022-10-05 16:21 UTC, fedeci commented on src/swift.ts
> +      },
Here too

2022-10-05 16:21 UTC, fedeci commented on src/swift.ts
> +      },
Same

2022-10-06 00:47 UTC, cHaLkdusT commented on src/swift.ts
> +      },
Updated

2022-10-06 00:47 UTC, cHaLkdusT commented on src/swift.ts
> +      },
Updated

2022-10-07 11:18 UTC, cHaLkdusT commented on src/swift.ts
> +        description: "The remap source paths in coverage info",
@fedeci yeah, I wasn't able to push it. 😅 Sorry. Should now be okay.

2022-10-08 16:23 UTC, fedeci commented on src/swift.ts
> +          keys: ["prefix", "original"],
```suggestion
```

2022-10-08 16:23 UTC, fedeci commented on src/swift.ts
> +          keys: ["alias_name"],
```suggestion
```

2022-10-08 16:23 UTC, fedeci commented on src/swift.ts
> +          keys: ["prefix", "original"],
These are key keys we suggest when completing the argument, not the description of the argument
```suggestion
```

2022-10-08 16:23 UTC, fedeci commented on src/swift.ts
> +        description: "The remap source paths in debug info",
```suggestion
        name: "prefix=replacement",
        description: "The remap source paths in debug info",
        generators: keyValue({
          separator: "=",
        }),
```

2022-10-09 18:26 UTC, fedeci approved these changes
Thanks!

2022-10-09 18:26 UTC, merged