Initial implementation
withfig/autocomplete pull request #1591
Opened 2022-10-06 01:19 UTC by austinchen12

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Closes #1542 

**What is the current behavior? (You can also link to an open issue here)**
Not implemented

**What is the new behavior (if this is a feature change)?**
![Kapture 2022-10-05 at 21 18 35](https://user-images.githubusercontent.com/59517082/194192653-996ad726-0181-407d-bc38-298421da21d9.gif)

**Additional info:**
Please add hacktoberfest label

2022-10-06 01:34 UTC, SeparateRecords commented
> is it possible to show 2 different descriptions depending on if an keyword argument is being passed? Reference to --pkgs subcommand with REGEXP?

Kinda! Although I think for flags such as `--pkgs=...` it might not work super well because the `=` tricks it into thinking it's in the value, not the key. Can probably fix this in the generator, but would be best to fix in the tokenizer cc @fedeci 

You'd use it like this:

```ts
import { keyValue } from "@fig/autocomplete-generators";

// then, in your spec ...


  args: {
    name: "whatever your arg name is",
    generators: keyValue({
      keys: [
        // list of keys to suggest
      ],
      values: [
        // list of values to suggest
      ]
    });
  },
```

> Please add hacktoberfest label

Repo already has this, PR should be automatically counted for hacktoberfest!

2022-10-06 02:02 UTC, austinchen12 commented
> 
seems like values are for suggestions in `keyValue` is for suggestions, I was thinking description. Also, REGEXP is user input, it wouldn't seem like I can hardcode values for those right? Or did I misunderstand what you meant

2022-10-06 02:29 UTC, SeparateRecords commented
> seems like values are for suggestions in keyValue is for suggestions, I was thinking description

Thanks for clarifying, I misunderstood. You're right, no way to change the description right now outside of some weird hacks (try writing `rich --padding 4,3,2,1` in your terminal to see one of said hacks)

2022-10-06 04:06 UTC, austinchen12 commented
> > seems like values are for suggestions in keyValue is for suggestions, I was thinking description
> 
> Thanks for clarifying, I misunderstood. You're right, no way to change the description right now outside of some weird hacks (try writing `rich --padding 4,3,2,1` in your terminal and watch the description to see one of said hacks - [source](https://github.com/withfig/autocomplete/blob/53833c9276a7964e1503e90968e650be788b6c23/src/rich.ts#L463-L496))
@SeparateRecords any blockers?

2022-10-06 05:11 UTC, SeparateRecords requested changes
Thanks so much for working on this!

One more suggestion: let's add a generator for package-id args!

```ts
const generatePackageIds: Fig.Generator = {
  script: "pkgutil --packages",
  splitOn: "\n",
};
```

Then any arg that takes a `package-id`, add `generators: generatePackageIds` to get a list of all available IDs.

2022-10-06 05:11 UTC, SeparateRecords commented on src/pkgutil.ts
> +        "Extract any BOM files from the flat pkg at path into /tml and return the filename(s)",
Quick typo fix
```suggestion
        "Extract any BOM files from the flat pkg at path into /tmp and return the filename(s)",
```

2022-10-06 05:11 UTC, SeparateRecords commented on src/pkgutil.ts
> +    },
Same for these, both of their args can have a template

2022-10-06 05:11 UTC, SeparateRecords commented on src/pkgutil.ts
> +    },
If you add `requiresSeparator: true` to the option, the arg can only be provided with `=` 🙂

2022-10-10 23:46 UTC, SeparateRecords commented
Hey @austinchen12, looks like you've marked the feedback as resolved, but haven't pushed any commits 🙂 Have you finished the PR locally?

2022-10-11 00:14 UTC, SeparateRecords approved these changes
This is fantastic! Just tried it out locally and it feels great. Thank you so much for working on this 🙂

2022-10-11 00:14 UTC, merged