feat(trap): add trap spec
withfig/autocomplete pull request #1592
Opened 2022-10-06 03:45 UTC by Fall1ngStar

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

New spec

**What is the current behavior? (You can also link to an open issue here)**

#1531

**What is the new behavior (if this is a feature change)?**

Add trap spec

**Additional info:**

2022-10-07 06:44 UTC, SeparateRecords requested changes
`trap` is one of those fun shell-builtin commands where you can never guarantee that the spec is correct - this works for me because I'm also a fish user, but for zsh and bash it's not right 😭

Here's what I'm thinking: let's use `command kill -l` to list the signals (this is the _exact_ same output as fish's `trap -l`), and omit the options entirely. So it'll be like

```ts
args: [
  { name: "function name" },
  { name: "signals", isVariadic: true, generators: /* generator here */ },
]
```

2022-10-07 06:51 UTC, SeparateRecords commented on src/trap.ts
> +    output.split(" ").map((signal) => ({
Also, I think this might be wrong - there can be a newline in the output. More reliable:
```suggestion
    output.split(/\s+/).map((signal) => ({
```

2022-10-07 12:20 UTC, Fall1ngStar commented on src/trap.ts
> +    output.split(" ").map((signal) => ({
No longer needed

2022-10-07 12:20 UTC, Fall1ngStar commented
Howdy fellow fish user 👋 

Looks like output of `command kill -l` has a different format depending on the shell 🙃 

```
bash -c "command kill -l"
 1) SIGHUP	 2) SIGINT	 3) SIGQUIT	 4) SIGILL	 5) SIGTRAP
 6) SIGABRT	 7) SIGEMT	 8) SIGFPE	 9) SIGKILL	10) SIGBUS
```

```
fish -c "command kill -l"
HUP INT QUIT ILL TRAP ABRT EMT FPE KILL BUS SEGV SYS PIPE ALRM TERM URG
STOP TSTP CONT CHLD TTIN TTOU IO XCPU XFSZ VTALRM PROF WINCH INFO USR1 USR2
```
`zsh` output looks like `bash` and `csh` more like `fish`. I added a regex with an optional group for the number before the signal name, should work on most common shells.

2022-10-09 23:57 UTC, SeparateRecords approved these changes
LGTM! Didn't know kill's output differs between shells even when you explicitly use /bin/kill... that's wild. Learned something new 😄

2022-10-09 23:57 UTC, merged