Initial implementation
withfig/autocomplete pull request #1598
Opened 2022-10-06 17:36 UTC by austinchen12

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
dscacheutil spec
**What is the current behavior? (You can also link to an open issue here)**
Not implemented
**What is the new behavior (if this is a feature change)?**
![Kapture 2022-10-06 at 13 35 41](https://user-images.githubusercontent.com/59517082/194381073-16e54ba7-bdda-43dc-af6f-539ba331581a.gif)

**Additional info:**
1. For the -q subcommand, we can improve -a arg suggestions if we can pass in the value passed to -q. Is this possible right now?
2. There seems to be a bug with the -buckets and -entries options in -cachedump since the name of those options are more than 1 character long (excluding the dash), chaining multiple don't work. See the gif below
![Kapture 2022-10-06 at 13 33 30](https://user-images.githubusercontent.com/59517082/194380834-77a85b9e-8de5-4fe7-be8b-67bc3e48248a.gif)

2022-10-07 01:05 UTC, austinchen12 commented
In the second gif, for some reason after typing `dscacheutil -q user -a ` the suggestions come up when you type the `-a` but goes away right when you press space. If someone can take a look and see if I'm doing anything wrong, it seems like adding arguments to `-a` should make it work properly

2022-10-07 06:21 UTC, SeparateRecords requested changes

2022-10-07 06:21 UTC, SeparateRecords commented on src/dscacheutil.ts
> +  subcommands: [
Single-letter options are behaving strangely because of the chaining rules, if you make this change it should be a lot more intuitive!
```suggestion
const completionSpec: Fig.Spec = {
  name: "dscacheutil",
  description: "Utility for managing the Directory Service cache",
  parserDirectives: {
    flagsArePosixNoncompliant: true,
  },
  subcommands: [
```

2022-10-11 00:31 UTC, austinchen12 commented on src/dscacheutil.ts
> +  subcommands: [
Including this change seems to make the `dscacheutil -q user -a uid` command break. The `dscacheutilGenerators.keys` doesn't seem to be called

2022-10-11 19:01 UTC, austinchen12 commented on src/dscacheutil.ts
> +  subcommands: [
@SeparateRecords ^

2022-10-12 01:33 UTC, SeparateRecords approved these changes
LGTM! Thank you @austinchen12 😄

2022-10-12 01:33 UTC, merged