feat(gum): add gum spec
withfig/autocomplete pull request #1599
Opened 2022-10-07 04:12 UTC by Fall1ngStar

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
New spec for `gum`

**What is the current behavior? (You can also link to an open issue here)**

Missing spec for `gum` (#1547)

**What is the new behavior (if this is a feature change)?**

Add spec for `gum`

**Additional info:**

2022-10-07 06:18 UTC, SeparateRecords requested changes
Awesome. Thank you so much for working on this! Just a couple of (hopefully) easy changes then it's ready to merge 🙂

2022-10-07 06:18 UTC, SeparateRecords commented on src/gum.ts
> +  );
This is really smart. Nice work 🤩

2022-10-07 06:18 UTC, SeparateRecords commented on src/gum.ts
> +          args: {},
Could you add a `name` property to the arg object? Same comment for all the args below. If no obvious name for the value jumps out, don't worry about it, but for example with this you could do `{ name: "lines" }`

2022-10-07 06:18 UTC, SeparateRecords commented on src/gum.ts
> +          name: "--afirmative",
Quick typo fix
```suggestion
          name: "--affirmative",
```

2022-10-07 06:18 UTC, SeparateRecords commented on src/gum.ts
> +    },
These options are available on all child commands, you can actually add `isPersistent: true` to make them inherited!

2022-10-07 06:18 UTC, SeparateRecords commented on src/gum.ts
> +  // args: {}
Can be deleted

2022-10-07 12:21 UTC, Fall1ngStar commented on src/gum.ts
> +  );
😊 thank !

2022-10-07 12:54 UTC, Fall1ngStar commented on src/gum.ts
> +          args: {},
Done, hope the naming I gave is matching the Fig style

2022-10-07 12:54 UTC, Fall1ngStar commented on src/gum.ts
> +          name: "--afirmative",
Fixed

2022-10-07 12:54 UTC, Fall1ngStar commented on src/gum.ts
> +    },
Fixed

2022-10-09 23:47 UTC, SeparateRecords approved these changes
Amazing, thank you so much @Fall1ngStar!

2022-10-09 23:47 UTC, merged