[NEXT] Add spec for Next.js CLI
withfig/autocomplete pull request #160
Opened 2021-04-29 18:25 UTC by QuiiBz

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adds the spec for Next.js's CLI

**What is the current behavior? (You can also link to an open issue here)**
There isn't any spec for Next.js's CLI

**What is the new behavior (if this is a feature change)?**
This PR adds the Next.js CLI

**Additional info:**

2021-04-29 19:04 UTC, cstrnt requested changes

2021-04-29 19:04 UTC, cstrnt commented on specs/next.js
> +                },
hose are not args, those are options :)

2021-04-29 19:04 UTC, cstrnt commented on specs/next.js
> +                },
see above

2021-04-29 21:53 UTC, mattschrage commented on dev/next.ts
> +          name: "-p",
`-H` and `-p` should take arguments.

2021-04-30 06:38 UTC, QuiiBz commented on specs/next.js
> +                },
Sorry for the mistake, my brain was struggling a bit 😅

2021-04-30 06:39 UTC, QuiiBz commented
Is this Danger error caused by my changes?

2021-05-02 10:21 UTC, cstrnt commented
> Is this Danger error caused by my changes?

I don't think there are any more errors, right? But either way, it's not your fault 😉

2021-05-02 10:24 UTC, QuiiBz commented
The error disappeared, so that’s fine!

2021-05-02 10:28 UTC, cstrnt requested changes
Just a tiny little wish from my side :wink

2021-05-02 10:28 UTC, cstrnt commented on dev/next.ts
> +      icon: "https://nextjs.org/static/favicon/favicon-16x16.png",
I think it would be great if you define this icon property as a top level const so we would only need to update it once when we want to change it. I also opened #174 because I think it would be great if the icon is inherited

2021-05-02 10:28 UTC, cstrnt commented on dev/next.ts
> +      icon: "https://nextjs.org/static/favicon/favicon-16x16.png",
see above

2021-05-02 10:28 UTC, cstrnt commented on dev/next.ts
> +      icon: "https://nextjs.org/static/favicon/favicon-16x16.png",
see above

2021-05-02 10:28 UTC, cstrnt commented on dev/next.ts
> +      icon: "https://nextjs.org/static/favicon/favicon-16x16.png",
see above

2021-05-02 10:28 UTC, cstrnt commented on dev/next.ts
> +      icon: "https://nextjs.org/static/favicon/favicon-16x16.png",
see above

2021-05-02 10:43 UTC, QuiiBz commented on dev/next.ts
> +      icon: "https://nextjs.org/static/favicon/favicon-16x16.png",
Originally (see https://github.com/withfig/autocomplete/pull/160/commits/1a09891e0ed2f1b634b3d32b8300c169ff2fb698#diff-16de0e0b934e0e5053f31155e3160ab60c2565f6bf37d867ea1ab708a85de232R2-R5), the `icon` was set to the top-level, but as you said the sub-commands don't inherit it, so I had to put them in each.

Let's see if this can be improved in #174

2021-05-02 10:55 UTC, cstrnt commented on dev/next.ts
> +      icon: "https://nextjs.org/static/favicon/favicon-16x16.png",
I mean I would just prefer having a const called `nextIcon` at the top of the file and then referencing that const over and over

2021-05-02 11:02 UTC, QuiiBz commented on dev/next.ts
> +      icon: "https://nextjs.org/static/favicon/favicon-16x16.png",
Never mind, I didn't understand what you said. Let me fix this!

2021-05-05 10:05 UTC, QuiiBz commented
Can we merge this @cstrnt?

2021-05-05 10:07 UTC, cstrnt commented
@QuiiBz I think it's good to merge, but you could for example extract the shared options like `-p` and `--host` into a top-level const in order to reduce duplication, but that's just my personal preference

2021-05-05 10:14 UTC, QuiiBz commented
Good advice! Just updated it.

2021-05-06 12:22 UTC, cstrnt requested changes

2021-05-06 12:22 UTC, cstrnt commented on dev/next.ts
> +        },
This should be the `dirArgument` as well

2021-05-08 07:15 UTC, QuiiBz commented on dev/next.ts
> +        },
Updated

2021-05-08 20:18 UTC, cstrnt approved these changes
Awesome 😄 Thank you very much, Tom :)

2021-05-08 20:33 UTC, merged