feat: add spec for Jamf Connect authchanger
withfig/autocomplete pull request #1600
Opened 2022-10-07 15:08 UTC by JacobHearst

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature: Autocomplete support for authchanger binary from Jamf Connect

**Additional info:**
authchanger is a commandline tool for interacting with macOS's authorization database. It's included as a part of the Jamf Connect product

2022-10-07 16:07 UTC, teeweizhong10 approved these changes

2022-10-08 16:39 UTC, fedeci requested changes
Thanks! Just one more change to make the spec working and then we can merge it!

2022-10-08 16:39 UTC, fedeci commented on src/authchanger.ts
> +  name: "authchanger",
```suggestion
  name: "authchanger",
  parserDirectives: {
    flagsArePosixNoncompliant: true,
  },
```

2022-10-09 18:28 UTC, fedeci approved these changes
LGTM, Thanks again @JacobHearst!

2022-10-09 23:52 UTC, merged