feat: add spec for JMeter
withfig/autocomplete pull request #1601
Opened 2022-10-08 02:49 UTC by QAInsights

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Feature: Autocomplete support for Apache JMeter

**Additional info:**
Apache JMeter is an open source performance testing tool written in Java.

2022-10-09 19:40 UTC, fedeci requested changes
Thanks for the PR @QAInsights! Can you run `npm run lint:fix` to get the CI to pass?

2022-10-09 19:56 UTC, fedeci requested changes

2022-10-09 19:56 UTC, fedeci commented on src/jmeter.ts
> +        description: "Your jmeter property file",
```suggestion
        description: "Your jmeter property file",
        template: "filepaths",
```

2022-10-09 19:56 UTC, fedeci commented on src/jmeter.ts
> +        name: "addprop",
```suggestion
        name: "files...",
        template: "filepaths",
        isVariadic: true,
```

2022-10-09 19:56 UTC, fedeci commented on src/jmeter.ts
> +        description: "the jmeter test(.jmx) file to run. \"-t LAST\" will load last used file ",
Actually this could use the [`filepaths()`](https://fig.io/docs/reference/generator/prebuilt-generators#filepathsoptions) generator to allow specifying the file extension
```suggestion
        description: "the jmeter test(.jmx) file to run. \"-t LAST\" will load last used file ",
        template: "filepaths",
```

2022-10-09 19:56 UTC, fedeci commented on src/jmeter.ts
> +        description: "the file to log samples to",
```suggestion
        description: "the file to log samples to",
        template: "filepaths",
        suggestCurrentToken: true,
```

2022-10-09 19:56 UTC, fedeci commented on src/jmeter.ts
> +        description: "jmeter logging configuration file",
```suggestion
        description: "jmeter logging configuration file",
        template: "filepaths",
```

2022-10-09 19:56 UTC, fedeci commented on src/jmeter.ts
> +        description: "jmeter run log file",
```suggestion
        description: "jmeter run log file",
        template: "filepaths",
        suggestCurrentToken: true,
```

2022-10-09 19:56 UTC, fedeci commented on src/jmeter.ts
> +      description: "Set a proxy server for JMeter to use",
```suggestion
      description: "Set a proxy server for JMeter to use",
      args: {
        name: "server",
      },
```

2022-10-09 19:56 UTC, fedeci commented on src/jmeter.ts
> +      description: "Set proxy server port for JMeter to use",
```suggestion
      description: "Set proxy server port for JMeter to use",
      args: {
        name: "port",
      },
```

2022-10-09 19:56 UTC, fedeci commented on src/jmeter.ts
> +        description: "additional system property file(s)",
```suggestion
        description: "additional system property file(s)",
        template: "filepaths",
```

2022-10-09 19:56 UTC, fedeci commented on src/jmeter.ts
> +        name: "loglevel",
This should use the [`keyValue`](https://fig.io/docs/reference/generator/prebuilt-generators#keyvalueoptions) generator
```suggestion
        name: "loglevel",
        generators: keyValue({
	        values: ["INFO", "WARN", "DEBUG"],
	      }),
```

2022-10-09 19:56 UTC, fedeci commented on src/jmeter.ts
> +      description: "Start these remote servers (overrides remote_hosts)",
```suggestion
      description: "Start these remote servers (overrides remote_hosts)",
      args: {
        name: "servers",
        isVariadic: true,
      },
```

2022-10-09 19:56 UTC, fedeci commented on src/jmeter.ts
> +        description: "the jmeter home directory to use",
```suggestion
```

2022-10-09 19:56 UTC, fedeci commented on src/jmeter.ts
> +      },
```suggestion
```

2022-10-09 19:56 UTC, fedeci commented on src/jmeter.ts
> +        description: "output folder for report dashboard",
```suggestion
        description: "output folder for report dashboard",
        template: "folders",
```

2022-10-09 20:13 UTC, fedeci commented
For reviewers: k6 is still to be done!

2022-10-10 00:15 UTC, QAInsights commented
Thanks @fedeci for reviewing. I incorporated the changes and ran lint.

2022-10-12 02:38 UTC, QAInsights commented
@fedeci could you please let me know any changes are required?

2022-10-20 16:22 UTC, QAInsights commented
@fedeci @mschrage @SeparateRecords Bumping up as the requested changes are already done. Please check. Thanks!

2022-10-20 16:41 UTC, fedeci commented
We still have to review k6. I'll do that in a couple hours likely!

2022-10-20 16:42 UTC, fedeci commented
Sorry for late response!

2022-10-22 17:51 UTC, fedeci approved these changes

2022-10-22 17:51 UTC, fedeci commented
Thanks @QAInsights!

2022-10-22 17:51 UTC, merged