[NX] add Spec for Nx CLI
withfig/autocomplete pull request #161
Opened 2021-04-29 22:34 UTC by ronderksen

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
Fig currently has no spec for use with the Nx CLI.

**What is the new behavior (if this is a feature change)?**
Introduces autocomplete support for the Nx CLI. The CLI has quite a few commands, which can be hard to remember. 

**Additional info:**
There's still a few commands missing. I will add them in the next few days.

2021-05-02 10:21 UTC, cstrnt requested changes
What a huge PR! Thank you very much 😊

2021-05-02 10:21 UTC, cstrnt commented on dev/nx.ts
> +const nxGenerators: Record<string, Fig.Generator> = {
using Record<string, Fig.Generator> causes TypeScript to also allow nxGenerators.nonExistingProperty. Even though it looks hacky, I would prefer not typing the object itself but rather each value as` Fig.Generator`

2021-05-02 10:21 UTC, cstrnt commented on dev/nx.ts
> +    },
This is basically the same as the generator for `localSchematics`.  I would prefer referencing the cache and postProcess stuff from the `localSchematics` generator to reduce code doublication

2021-05-02 10:21 UTC, cstrnt commented on dev/nx.ts
> +    },
```suggestion
    script: "nx list" ,
```

2021-05-02 10:21 UTC, cstrnt commented on dev/nx.ts
> +    },
The cache property is re-used. I would prefer to create a top-level const with the type `Fig.Cache`

2021-05-02 10:21 UTC, cstrnt commented on dev/nx.ts
> +    },
see above

2021-05-03 07:43 UTC, QuiiBz commented on dev/nx.ts
> +const processGenerators: PostProcessFn = function (out) {
Shouldn't this be a `() => {...}` instead of a `function`, since you mostly used them?

2021-05-03 07:44 UTC, QuiiBz commented on dev/nx.ts
> +    postProcess: function (out) {
Same here, I would prefer not to mix the two and instead choose one.

2021-05-03 08:14 UTC, QuiiBz approved these changes

2021-05-04 04:54 UTC, mattschrage reviewed
This looks great! Thanks for contributing @ronderksen :)

I had one small question, but I think this is about ready to merge in.

2021-05-04 04:54 UTC, mattschrage commented on dev/nx.ts
> +    script: "cat workspace.json",
I am not super familiar with the `nx` tool - is it possible to run `nx` commands from child directories of the root folder that contains the `workspace.json` file?

If this is the case, you might be able to adapt the same script that the `npm` CLI uses to find the `package.json` file:

```
until [[ -f package.json ]] || [[ $PWD = '/' ]]; do cd ..; done; cat package.json
```

2021-05-04 07:53 UTC, ronderksen commented on dev/nx.ts
> +    script: "cat workspace.json",
No, it only works from the root folder.

2021-05-11 22:18 UTC, mattschrage commented
@ronderksen sorry for the delay on this! Everything looks good to me. Going to merge now!

2021-05-11 22:18 UTC, merged