feat(yarn): add options
withfig/autocomplete pull request #1612
Opened 2022-10-10 15:10 UTC by vatana7

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adding more specs to yarn

**Important**
This is a code solution submitted  for Closes #1611

2022-10-10 20:06 UTC, fedeci requested changes
Thanks for the PR! I left a few things to get fixed before merging this in.

2022-10-10 20:06 UTC, fedeci commented on src/yarn.ts
> +        },
```suggestion
      options: [{
        name: "--rc",
        description: "Download the latest rc release",
      }],
        },
```

2022-10-10 20:06 UTC, fedeci commented on src/yarn.ts
> +            isOptional: true,
```suggestion
```

2022-10-10 20:06 UTC, fedeci commented on src/yarn.ts
> +            isOptional: true,
```suggestion
```

2022-10-10 20:06 UTC, fedeci commented on src/yarn.ts
> +            isOptional: true,
```suggestion
```

2022-10-10 20:06 UTC, fedeci commented on src/yarn.ts
> +            isOptional: true,
```suggestion
```

2022-10-10 20:06 UTC, fedeci commented on src/yarn.ts
> +          },
```suggestion
          args: [{
            name: "<scope:team>",
          }, {
            name: "<user>",
          }],
```

2022-10-11 02:35 UTC, vatana7 commented
Thanks! Can you label this as hacktoberfest PR please 🤟🏻

2022-10-11 03:30 UTC, SeparateRecords commented
@vatana7 PRs are automatically counted for hacktoberfest because the repo itself has the label 🙂

2022-10-11 03:57 UTC, vatana7 commented
Everything should be able to merge now. Thanks for the suggestion!

2022-10-11 04:28 UTC, SeparateRecords commented
Just one thing to fix up first! Either prettier or eslint is unhappy. Easy fix: `npx eslint --fix src/yarn.ts; npx prettier -w src/yarn.ts`

2022-10-11 05:58 UTC, vatana7 commented
What version of node does this project use?

2022-10-11 06:21 UTC, fedeci commented
That's not strictly relevant. I believe node@16 is good.

2022-10-11 06:44 UTC, SeparateRecords commented
Any version of node should be fine for this. Personally I just use the latest (node@18) and only change per project if required

2022-10-11 10:36 UTC, fedeci approved these changes
Thanks!

2022-10-11 10:36 UTC, fedeci commented on src/yarn.ts
> +          },
```suggestion
          args: [
            {
              name: "<scope:team>",
            },
            {
              name: "<user>",
            },
          ],
```

2022-10-11 10:37 UTC, merged