[Firebase]: add project alias generator
withfig/autocomplete pull request #162
Opened 2021-04-29 23:31 UTC by dereklowlind

Added a generator to the firebase.js spec. Not fully working. The goal was to add a generator like for git getting the local branches but getting the user's firebase projects. The command "firebase use <project alias>" is the target for the generator. Getting the user's projects is done using the "firebase projects:list" command which calls the firebase servers and takes almost 10 seconds to complete on my internet. The generator is currently able to grab only the first project in the list and display it as an option. I am not sure if it is because the "firebase projects:list" command does not return the complete list or because my code is having an issue (can I console log in the generator function?). 

Due to the server lag this may or may not be useful addition. It is slow but from a workflow standpoint but it is faster than entering the "firebase projects:list" command then copying the project's alias (which is my current workflow).

2021-04-29 23:34 UTC, falky97 requested changes
Hey Derek - this generator looks fine! Do you think it's a your internet problem or is it always this slow? You could add the option to cache the spec?

We will honestly probably approve this, however, all Fig specs must be done by editing the typescript file (in this case `dev/firebase.ts`). Want to make literally the exact same changes you already did, then run `npm run build` to compile, and then push?

2021-04-29 23:44 UTC, dereklowlind commented
Can you try running the "firebase projects:list" command. My internet is pretty good ~300mbps, it might also be something backend at firebase with auth and stuff.

Any ideas on why it only picks up only the first of the ten firebase projects I have?

Yep I can do the changes to the ts file instead.

2021-05-02 10:10 UTC, cstrnt requested changes

2021-05-02 10:10 UTC, cstrnt commented on dev/firebase.ts
> +      var aliasesRaw = Array.from(out.matchAll(getAliasRegex));
I would prefer using `const` here :)

2021-05-02 10:10 UTC, cstrnt commented on dev/firebase.ts
> +const firestoreGenerators: Record<string, Fig.Generator> = {
using `Record<string, Fig.Generator>` causes TypeScript to also allow ` firestoreGenerators.nonExistingProperty`. Even though it looks hacky, I would prefer not typing the object itself but rather each value `as Fig.Generator` cc @QuiiBz

2021-05-02 10:41 UTC, QuiiBz commented on dev/firebase.ts
> +const firestoreGenerators: Record<string, Fig.Generator> = {
Agree, but in this case since there is only one generator, you can simply do this:
```typescript
const projectAliasesGenerator: Fig.Generator = {
  script: "firebase projects:list", // this calls to a firebase server and is therefore slow
  postProcess: (out) => {
      ...
  },
};
```

2021-05-21 16:16 UTC, merged