Feat/Add spec for pytest
withfig/autocomplete pull request #1621
Opened 2022-10-12 03:08 UTC by sri-go

Add spec file for pytest

Additional info:
The [pytest](https://docs.pytest.org/en/7.1.x/) framework makes it easy to write small, readable tests, and can scale to support complex functional testing for applications and libraries.

2022-10-12 03:22 UTC, SeparateRecords requested changes
Thanks for the PR @sri-go!

Left some feedback, stopped part way through the file (but I did read all of it). The feedback applies to the whole thing.

Hopefully it's simple changes! Summarizing here:
1. Add `template` property to args that take a file or folder
2. Replace multiline descriptions with single lines to remove possible whitespace issues
3. For args with known values (eg. yes/no), add `suggestions` property to show them!

You've done a great job on this spec. Thank you so much for working on it!!

2022-10-12 03:22 UTC, SeparateRecords commented on src/pytest.ts
> +  },
Let's add `template: ["filepaths", "folders"]` so this suggests files and folders!

2022-10-12 03:22 UTC, SeparateRecords commented on src/pytest.ts
> +                    test modules on import to provide assert expression information",
This could probably be a single line description, it's more readable _as code_ over multiple lines but I'd favor simplicity instead of line continuations.

Plus for tools that don't directly render the description to DOM, such as https://fig.io/manual or https://shell.how, this could cause problems:
<img width="1732" alt="CleanShot 2022-10-12 at 14 13 47@2x" src="https://user-images.githubusercontent.com/52195359/195241357-b1608492-4e76-420d-be25-8cbcb69e65f2.png">

2022-10-12 03:22 UTC, SeparateRecords commented on src/pytest.ts
> +      },
There are known modes (plain, rewrite), let's add `suggestions: ["plain", "rewrite"]` so it suggests them!

2022-10-12 03:22 UTC, SeparateRecords commented on src/pytest.ts
> +      },
Filepaths template to suggest files

```suggestion
      args: {
        name: "File",
        template: "filepaths",
      },
```

2022-10-12 03:22 UTC, SeparateRecords commented on src/pytest.ts
> +      description: "",
This option is missing its description

2022-10-12 03:22 UTC, SeparateRecords commented on src/pytest.ts
> +        description: "",
Can probably be omitted

2022-10-12 03:22 UTC, SeparateRecords commented on src/pytest.ts
> +      },
Same here, can you add `suggestions`?

2022-10-12 03:22 UTC, SeparateRecords commented on src/pytest.ts
> +        name: "",
Was this supposed to have a name? Empty name can be omitted, but I think it's clearer if it has one

2022-10-12 03:22 UTC, SeparateRecords commented on src/pytest.ts
> +        description: "{yes,no}",
Same thing as above, let's do `suggestions`!

2022-10-12 03:24 UTC, SeparateRecords commented on src/pytest.ts
> +        name: "",
Oh also, for this option, you might want to add `dependsOn: ["--color"]` (I'm guessing based on the description). It'll have its priority boosted if `--color` is provided

2022-10-12 17:33 UTC, fedeci commented on src/pytest.ts
> +      description: "Show cache contents, don't perform collection or tests. Optional argument: glob (default: '*').",
```suggestion
      description: "Show cache contents, don't perform collection or tests. Optional argument: glob (default: '*')",
```

2022-10-12 17:49 UTC, fedeci requested changes
Thanks for this PR! I left some comments to solve before merging too.

2022-10-12 17:49 UTC, fedeci commented on src/pytest.ts
> +      description: "(deprecated) alias to --strict-markers",
This can use the deprecated property: https://fig.io/docs/reference/option#deprecated

2022-10-12 17:49 UTC, fedeci commented on src/pytest.ts
> +        suggestions: ["a", "A", "E", "f", "N", "p", "P", "s", "w", "x", "X"],
This needs a custom list generator. I am writing it rn. I will update it when it is available!

2022-10-12 17:49 UTC, fedeci commented on src/pytest.ts
> +        template: "filepaths"
```suggestion
        template: "filepaths",
        suggestCurrentToken: true,
```

2022-10-12 17:49 UTC, fedeci commented on src/pytest.ts
> +      description: "Increase verbosity",
```suggestion
      description: "Increase verbosity",
      isRepeatable: true,
```

2022-10-12 17:49 UTC, fedeci commented on src/pytest.ts
> +      description: "Increase verbosity",
I use this all the time :)

2022-10-13 03:00 UTC, SeparateRecords requested changes
Awesome, this is looking really good. Thanks again for taking this on, pytest has a _huge_ number of options, this is getting super close to being ready to merge!!

2022-10-14 00:47 UTC, SeparateRecords approved these changes
Fantastic! No complaints 🙂 Thank you so much for all the effort @sri-go, this will be hugely appreciated by every python user!!

2022-10-14 00:48 UTC, merged