Missing `curl` spec
withfig/autocomplete pull request #1623
Opened 2022-10-12 07:24 UTC by MengsokunVeng

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2022-10-12 17:57 UTC, fedeci requested changes
Thanks for the PR! There are a couple things to fix before merging this, can you handle those please?

2022-10-12 17:57 UTC, fedeci commented on src/zzz.ts
> +  description: "",
Is this the correct description?
```suggestion
  description: "A command-line MacOS sleep program (like SleepNow)",
```

2022-10-12 17:57 UTC, fedeci commented on src/zzz.ts
> +  // args: {}
```suggestion
```

2022-10-18 13:32 UTC, MengsokunVeng commented
Sorry for late reply and I noticed that i pushed the tested file right after i cloned the project. Thank you.

2022-10-18 20:23 UTC, fedeci commented
@MengsokunVeng  is the zzz file supposed to be deleted?

2022-10-19 00:19 UTC, SeparateRecords commented
> @MengsokunVeng is the zzz file supposed to be deleted?

I think this was just a file for testing how completions work and wasn't supposed to be included, in the tutorial we push to create a simple test spec

2022-10-19 02:28 UTC, MengsokunVeng commented
Yes, it was just a file to test whether i set up the project correctly or
not.


On Wed, 19 Oct 2022 at 07:19, Robert ***@***.***> wrote:

> @MengsokunVeng <https://github.com/MengsokunVeng> is the zzz file
> supposed to be deleted?
>
> I think this was just a file for testing how completions work and wasn't
> supposed to be included, in the tutorial we push to create a simple test
> spec
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/withfig/autocomplete/pull/1623#issuecomment-1283168842>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2PXDOFEWUJYBJXR7L3AHMLWD45CBANCNFSM6AAAAAARC7UR6A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-19 09:50 UTC, fedeci approved these changes
Thanks!

2022-10-19 09:50 UTC, merged