[LN]: add command
withfig/autocomplete pull request #163
Opened 2021-04-30 04:43 UTC by dereklowlind

Created a template for the ln command as I noticed there was not one yet

2021-04-30 06:44 UTC, QuiiBz commented
Hi, thanks for contributing for the first time to Fig! Did you planned to add the `args` for ln? It takes two args: `source_file` and `link_name`, or a variadic option `linkname_dir`.

2021-04-30 06:44 UTC, QuiiBz requested changes

2021-04-30 06:44 UTC, QuiiBz commented on dev/ln.ts
> +      name: ["-F"],
You can remove the `[]` since there is only one name.

2021-04-30 16:56 UTC, dereklowlind commented on dev/ln.ts
> +      name: ["-F"],
Hi @QuiiBz I removed those brackets and added the args.

2021-04-30 18:34 UTC, QuiiBz commented on dev/ln.ts
> +      // template: ["filepaths", "folders"], // is there an absolute path version of this? ln requires absolute path
@mattschrage Do you have any plan on adding this template? It should combine `filepaths` and `folders` templates.

2021-05-02 10:07 UTC, cstrnt requested changes

2021-05-02 10:07 UTC, cstrnt commented on dev/ln.ts
> +      ],
Those args are reused over and over. I would prefer having a top-level const of the type `Fig.Args[]` and you can just re-use it

2021-05-02 19:54 UTC, dereklowlind commented on dev/ln.ts
> +      ],
@cstrnt  thank you for the feedback, changes are implemented and pushed

2021-05-06 06:57 UTC, QuiiBz requested changes

2021-05-06 06:57 UTC, QuiiBz commented on dev/ln.ts
> +    // template: ["filepaths", "folders"], // is there an absolute path version of this? ln requires absolute path
We can stay with `["filepaths", "folders"],` since `ln` [does not](https://linuxize.com/post/how-to-create-symbolic-links-in-linux-using-the-ln-command/#creating-symlink-to-a-file) require absolute paths

2021-05-06 18:47 UTC, dereklowlind commented on dev/ln.ts
> +const source_dest_args: Fig.Arg[] = [
Added the change and pushed

2021-05-06 18:47 UTC, dereklowlind commented on dev/ln.ts
> +    // template: ["filepaths", "folders"], // is there an absolute path version of this? ln requires absolute path
Added the change and pushed

2021-05-06 18:55 UTC, QuiiBz approved these changes

2021-05-21 16:19 UTC, merged