feat: ```add rvm.ts```
withfig/autocomplete pull request #1631
Opened 2022-10-13 06:10 UTC by vatana7

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
PR dedicated for #1616

2022-10-13 07:14 UTC, SeparateRecords requested changes
Looks good! Couple of simple changes then should be ready

2022-10-13 07:14 UTC, SeparateRecords commented on src/rvm.ts
> +    options: [...options],
Can use shorthand syntax here because it's the same array for each interpreter! (apply to others too)
```suggestion
    options,
```

2022-10-13 07:14 UTC, SeparateRecords commented on src/rvm.ts
> +      subcommands: [...interpreters],
Don't need to spread the array here (apply below too)
```suggestion
      subcommands: interpreters,
```

2022-10-13 07:14 UTC, SeparateRecords commented on src/rvm.ts
> +  description: "",
Missing description

2022-10-13 07:14 UTC, SeparateRecords commented on src/rvm.ts
> +    },
If `--help` is available on all subcommands, you can use `isPersistent` to make it show up
```suggestion
    {
      name: ["--help", "-h"],
      description: "Show help for rvm",
      isPersistent: true,
    },
```

2022-10-13 16:56 UTC, vatana7 commented on src/rvm.ts
> +  description: "",
Resolved

2022-10-13 16:57 UTC, vatana7 commented
Should be able to merge now! Thanks! 😊

2022-10-13 21:25 UTC, fedeci requested changes

2022-10-13 21:25 UTC, fedeci commented on src/rvm.ts
> +    name: "C",
```suggestion
    name: "-C",
```

2022-10-13 21:25 UTC, fedeci commented on src/rvm.ts
> +    options: [...options],
Spreads are not required here since you do not need to copy that object. Same for interpreters below.
```suggestion
    options,
```

2022-10-13 21:25 UTC, fedeci commented on src/rvm.ts
> +    options: [...options],
```suggestion
    options,
```

2022-10-13 21:25 UTC, fedeci commented on src/rvm.ts
> +    options: [...options],
```suggestion
    options,
```

2022-10-13 21:25 UTC, fedeci commented on src/rvm.ts
> +    options: [...options],
```suggestion
    options,
```

2022-10-13 21:25 UTC, fedeci commented on src/rvm.ts
> +    options: [...options],
```suggestion
    options,
```

2022-10-13 21:27 UTC, fedeci requested changes

2022-10-13 21:27 UTC, fedeci commented on src/rvm.ts
> +    },
Interpreters are also valid main subcommands:
```suggestion
    },
    ...interpreters,
```

2022-10-14 04:04 UTC, vatana7 commented
Thanks for the suggestion!

2022-10-14 05:23 UTC, SeparateRecords commented on src/rvm.ts
> +      subcommands: [...interpreters],
Just for consistency, can you also fix up this and the spreads below?
```suggestion
      subcommands: interpreters,
```

2022-10-14 06:44 UTC, vatana7 commented on src/rvm.ts
> +      subcommands: [...interpreters],
Done!

2022-10-14 07:22 UTC, SeparateRecords approved these changes
Fantastic, thank you @vatana7!!

2022-10-14 07:22 UTC, merged