feat: add `visudo` spec
withfig/autocomplete pull request #1649
Opened 2022-10-14 10:26 UTC by victorpatru

**What kind of change does this PR introduce?**

Pull request for issue #1528 using [visudo's publicly available documentation](https://www.sudo.ws/docs/man/visudo.man/)

_Making my first contribution to Fig's Autocomplete Repo. Happy to make any changes if needed!_

2022-10-14 19:42 UTC, fedeci requested changes
Thanks for the spec! I left a couple comments to address before merging this PR.

2022-10-14 19:42 UTC, fedeci commented on src/visudo.ts
> +        description: "Specify the alternate sudoers file location",
```suggestion
        description: "Specify the alternate sudoers file location",
        template: "filepaths",
```

2022-10-14 19:42 UTC, fedeci commented on src/visudo.ts
> +        name: "Output file name",
```suggestion
        name: "Output file name",
        template: "filepaths",
        suggestCurrentToken: true,
```

2022-10-15 09:56 UTC, victorpatru commented
Thanks @fedeci. Merged the comments! Lmk if there is anything else required before merging.

2022-10-16 17:20 UTC, fedeci approved these changes
Thanks!

2022-10-16 17:24 UTC, merged