feat(plutil): Added completion spec for plutil
withfig/autocomplete pull request #1652
Opened 2022-10-15 21:57 UTC by duncanlutz

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
No completion spec for plutil currently exists ([https://github.com/withfig/autocomplete/issues/1541](issue that requested this change))

**What is the new behavior (if this is a feature change)?**
Added completion spec for plutil

2022-10-16 14:04 UTC, fedeci requested changes
Thanks! Just two comments about some improvements that can be done to the spec!

2022-10-16 14:04 UTC, fedeci commented on src/plutil.ts
> +    description: "File to check the syntax of or convert",
```suggestion
    description: "File to check the syntax of or convert",
    template: "filepaths",
```

2022-10-16 14:04 UTC, fedeci commented on src/plutil.ts
> +        name: "path",
```suggestion
        name: "path",
        template: "filepaths",
        suggestCurrentToken: true,
```

2022-10-17 00:11 UTC, SeparateRecords requested changes
Thanks @duncanlutz! Got some comments on the general structure

Some of `plutil`'s options aren't _really_ options. It takes some "command options" which we can model as subcommands.

Some subcommands are `-convert`, `-extract`, etc.

This also allows us to model the behavior more closely too

```ts
  subcommands: [
    {
      name: "-extract",
      icon: "fig://icon?type=option", // makes it look like an option
      args: [
        { name: "keypath" },
        { name: "format", suggestions: ["xml1", "binary1", "json", "swift", "objc", "raw"] },
        { name: "file", template: "filepaths", suggestions: [{ name: "-", hidden: true }] },
      ],
      options: [
        {
          name: "-expect",
          args: {
            name: "type",
            suggestions: ["-bool", "-integer", "-float", /* ... */ ],
          },
        },
      ],
    }
  ]
```

2023-09-29 00:02 UTC, mschrage approved these changes

2023-09-29 00:02 UTC, merged