Add secrets subcommand for Nextflow specification
withfig/autocomplete pull request #1663
Opened 2022-10-21 12:58 UTC by mribeirodantas

- feat(nextflow): Add secrets subcommand
- feat(nextflow): Add generator for secret names

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
It adds autocomplete to the secrets subcommand in the nextflow CLI and a generator
for autocompleting the argument of the `nextflow secrets get` subcommand.

2022-10-22 17:08 UTC, fedeci requested changes

2022-10-22 17:08 UTC, fedeci commented on src/nextflow.ts
> +  postProcess: (output) => {
Could this be implemented using "nextflow secrets list" as the script?

2022-10-22 17:08 UTC, fedeci commented on src/nextflow.ts
> +            "Allows deleting an existing secret e.g. nextflow secrets delete FOO",
```suggestion
            "Allows deleting an existing secret e.g. nextflow secrets delete FOO",
          isDangerous: true,
          args: {
             name: "secret name",
             generators: secretname,
           },
```

2022-10-22 17:08 UTC, fedeci commented on src/nextflow.ts
> +            name: "secret name and value",
```suggestion
            name: "secret name and value",
            generators: secretname,
            suggestCurrentToken: true,
```

2022-10-22 17:08 UTC, fedeci commented on src/nextflow.ts
> +            "Allows creating a new secret or overriding an existing one e.g. nextflow secrets set FOO 'Hello world'",
```suggestion
            "Allows creating a new secret or overriding an existing one e.g. nextflow secrets set FOO 'Hello world'",
          isDangerous: true,
```

2022-10-23 20:40 UTC, mribeirodantas commented on src/nextflow.ts
> +  postProcess: (output) => {
Unfortunately, I'm unable to run nextflow commands in the script field of generators on Fig. That's what I get:

```
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

[31m/Users/mribeirodantas/.local/bin/nextflow: line 287: /bin/java: No such file or directory(B[m
[33mNOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /bin/java
 NXF_OPTS: 
(B[m
```

That's why I'm always using ShellScript to scrap the info for the generators.

2022-10-23 20:57 UTC, mribeirodantas commented
Is there a bot in this repository to automatically fix linting issues? Something like commenting `@bot-this fix linting` and it'd commit the fix.

2022-10-24 01:39 UTC, SeparateRecords commented
> Is there a bot in this repository to automatically fix linting issues? Something like commenting @bot-this fix linting and it'd commit the fix.

This isn't implemented but we have a command to fix it:
```bash
yarn lint:fix
# ... or `npm run lint:fix`, etc.
```

2022-10-24 02:24 UTC, mribeirodantas commented
Yeah, I knew this one. Thanks anyway! :)

2022-10-24 16:59 UTC, fedeci commented
> Is there a bot in this repository to automatically fix linting issues? Something like commenting `@bot-this fix linting` and it'd commit the fix.

Sounds like a good addition! Do you know any OSS project using a bot like that?

2022-10-24 21:23 UTC, mribeirodantas commented
> Sounds like a good addition! Do you know any OSS project using a bot like that?

Sure. We have `@nf-core-bot fix linting` in https://github.com/nf-core/nf-co.re.
Check here, for example: https://github.com/nf-core/nf-co.re/pull/1404#issuecomment-1285162283

2022-10-24 21:25 UTC, closed without merging

2022-10-24 21:26 UTC, mribeirodantas commented
Oh, my... I did something wrong on my side 🤦

2022-10-24 23:03 UTC, SeparateRecords commented on src/nextflow.ts
> +  postProcess: (output) => {
Maybe for the script you could try `"sh -c 'JAVA_CMD=$(which java) ...'"` where ... is the logic? Not sure if that would work.