feat: Add aws --profile support
withfig/autocomplete pull request #1670
Opened 2022-10-23 00:18 UTC by joeheyming

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
In this commit, we want to make it so aws --profile auto completes
with the list of profiles you have available.

**What is the current behavior? (You can also link to an open issue here)**
Currently the aws command doesn't know about --profiles

**What is the new behavior (if this is a feature change)?**
Generally these profiles live inside a credentials file
but instead of directly looking at the credentials file,
we ask aws to give us a list of the profiles using
`aws configure list-profiles`

**Additional info:**

2022-10-23 14:15 UTC, fedeci requested changes
Thanks for the improvement to this spec @joeheyming!

2022-10-23 14:15 UTC, fedeci commented on src/aws.ts
> +  postProcess: function (out, [awsClient]) {
nit:
```suggestion
  postProcess: function (out) {
```

2022-10-23 14:15 UTC, fedeci commented on src/aws.ts
> +    return [];
`trycatch` does nothing in this case and `String.prototype.split` always returns an array of at least one value if the string exists:
```suggestion
    const lines = out.split("\n");
    return lines.map((line) => {
      return {
        name: line,
      };
    });
```

2022-10-23 18:21 UTC, joeheyming commented
![Screen Shot 2022-10-23 at 11 20 25 AM](https://user-images.githubusercontent.com/1858116/197409022-b2a4fc7d-a0a4-43cf-9bc8-aa5deab9a686.png)

2022-10-24 16:55 UTC, fedeci approved these changes
Thanks!

2022-10-24 16:55 UTC, merged