feat(z) updated z autocomplete to include current directory folders and cleaned up code
withfig/autocomplete pull request #1673
Opened 2022-10-23 19:32 UTC by sghsri

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
Have the z history only in the z autocompletion.

**What is the new behavior (if this is a feature change)?**
Updated the z autocompletion script to also include the current directory's folders (Not just the z history). 

**Additional info:**

2022-10-24 17:29 UTC, fedeci requested changes

2022-10-24 17:29 UTC, fedeci commented on src/z.ts
> +  return (
```suggestion
  const insertedTermsMap = new Set(insertedTerms)
  return (
```

2022-10-24 20:19 UTC, sghsri commented on src/z.ts
> +}
I tried to get it working but the problem is that if I set the folders template, it didn't seem to use the generator :/

2022-10-24 20:20 UTC, sghsri commented on src/z.ts
> +      .filter(({ name }) => !searchPath.includes(name))
Good suggestion!

2022-10-24 20:20 UTC, sghsri commented on src/z.ts
> +        }, []);
It didn't remove the duplicates unfortunately without it, is there something I'm doing wrong?

2022-10-24 20:44 UTC, fedeci commented on src/z.ts
> +        }, []);
It has just been repushed since it was failing sometimes

2022-10-24 20:47 UTC, sghsri commented on src/z.ts
> +        }, []);
oh ok so it should work now if I try? just to clarify, What are the properties that need to be the same for the de-duping?

2022-10-26 10:28 UTC, fedeci commented on src/z.ts
> +        }, []);
The dedupe logic is shared between all types that inherits from the `Fig.Suggestion` one. For example `Fig.Subcommand` or `Fig.Option` have the `args` property. If a property does not show up in vscode suggestion it means it is not typed so it gets evaluated as missing.
> If any of these is missing it is not a problem (it must be missing from both the suggestions)

2022-10-26 10:50 UTC, fedeci commented on src/z.ts
> +}
I have just created a PR that enables this behaviour! I just have to test it a little before pushing it!

2022-10-26 14:39 UTC, sghsri commented on src/z.ts
> +        }, []);
oooh ok, thanks that makes sense!

2022-10-27 15:26 UTC, fedeci commented on src/z.ts
> +}
I am closing that PR since it would be confusing in some cases. The key to make it work is this:
```ts
args: {
  name: "directory",
  generators: [{ template: "folders"}, { /* ... the current custom generator */}]
}
```

2022-12-12 17:02 UTC, fedeci approved these changes

2022-12-12 18:25 UTC, sghsri commented
I have read the CLA Document and I hereby sign the CLA

2022-12-12 20:34 UTC, fedeci commented
@sghsri, just one more thing, can you run `npm run lint:fix`?

2022-12-12 23:11 UTC, sghsri commented
@fedeci , I believe I ran it in this commit!
<img width="853" alt="image" src="https://user-images.githubusercontent.com/13592854/207177908-90bba301-7de2-4870-942d-d4f0fccca05a.png">

2022-12-13 01:27 UTC, merged