PHPUnit watcher plugin
withfig/autocomplete pull request #168
Opened 2021-05-01 10:52 UTC by binaryk

**Plugin for [*phpunit-watcher*](https://github.com/spatie/phpunit-watcher)

![image](https://user-images.githubusercontent.com/6833714/116780296-74fbdc00-aa84-11eb-8cad-3d91c61203d1.png)

2021-05-01 11:05 UTC, QuiiBz requested changes

2021-05-01 11:05 UTC, QuiiBz commented on specs/phpunit-watch.js
> +
Please remove this generated spec, since the right one is https://github.com/withfig/autocomplete/blob/adb02aafe07fc383f50bbe5bf5e7b98f4e764795/specs/phpunit-watcher.js

2021-05-01 13:00 UTC, binaryk commented on specs/phpunit-watch.js
> +
Addressed, thanks!

2021-05-01 13:00 UTC, binaryk commented on dev/phpunit-watcher.ts
> +var tests = {
Addressed, thanks!

2021-05-01 13:08 UTC, QuiiBz requested changes

2021-05-01 13:08 UTC, QuiiBz commented on dev/phpunit-watcher.ts
>  const tests: Record<string, Fig.Generator> = {
This should only be a `Fig.Generator`, not a `Record<string, Fig.Generator>`. `Fig.Generator` type contains both the `script` and `postProcess` fields.

2021-05-02 09:51 UTC, cstrnt commented on dev/phpunit-watcher.ts
> +          description: line.substring(line.indexOf("::") + 2, line.length),
Does it make sense that the name and the description are the same?

2021-05-05 15:49 UTC, binaryk commented on dev/phpunit-watcher.ts
> +          description: line.substring(line.indexOf("::") + 2, line.length),
Yes.

2021-05-05 15:51 UTC, binaryk commented on dev/phpunit-watcher.ts
>  const tests: Record<string, Fig.Generator> = {
Addressed @QuiiBz . Thank you!

2021-05-05 15:58 UTC, QuiiBz approved these changes

2021-05-05 15:58 UTC, QuiiBz commented
Thanks for your first contribution!

2021-05-05 15:58 UTC, merged