[EXA] Add spec for exa
withfig/autocomplete pull request #169
Opened 2021-05-01 12:07 UTC by alexnaiman

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Added new spec for exa 
**What is the current behavior? (You can also link to an open issue here)**
There isn't any spec for exa
**What is the new behavior (if this is a feature change)?**
This PR adds the exa
**Additional info:**

2021-05-01 20:40 UTC, cstrnt requested changes

2021-05-01 20:40 UTC, cstrnt commented on dev/exa.ts
> +      name: ["-L", "--level DEPTH"],
I think DEPTH should not be included in the name because it is in fact an argument, right?

2021-05-01 20:40 UTC, cstrnt commented on dev/exa.ts
> +            name: "Name",
Does is make a difference for exa?

2021-05-01 20:40 UTC, cstrnt commented on dev/exa.ts
> +      name: ["-I", "--ignore-glob"],
I think here is an `arg` required

2021-05-01 20:40 UTC, cstrnt commented on dev/exa.ts
> +      name: ["-t", "--time FIELD"],
Missing arg

2021-05-01 21:12 UTC, alexnaiman commented on dev/exa.ts
> +      name: ["-L", "--level DEPTH"],
My bad, I generated the spec using a script and some things I had to manually correct

2021-05-01 21:17 UTC, alexnaiman commented on dev/exa.ts
> +            name: "Name",
Yes, it actually does 😄 

>  Fields starting with a capital letter will sort uppercase before  lowercase:  'A'  then 'B' then 'a' then 'b'.  Fields starting with a lowercase letter will mix them: 'A' then 'a' then 'B' then 'b'.

2021-05-01 21:24 UTC, alexnaiman commented on dev/exa.ts
> +      name: ["-I", "--ignore-glob"],
Added right below

2021-05-02 09:51 UTC, cstrnt commented on dev/exa.ts
> +      name: ["-L", "--level DEPTH"],
No worries 😄

2021-05-02 09:52 UTC, cstrnt approved these changes
Awesome!

2021-05-02 10:35 UTC, QuiiBz approved these changes

2021-05-04 04:19 UTC, mattschrage approved these changes
This is awesome! Thanks for contributing @alexnaiman 🎉

2021-05-04 04:19 UTC, merged