feat(fig): update spec
withfig/autocomplete pull request #1695
Opened 2022-11-07 23:11 UTC by mschrage

PR generated automatically from push-to-fig-autocomplete-action.

2022-11-07 23:13 UTC, SeparateRecords commented
oh you're kidding, it removed all the generators 😭😭😭😭

2022-11-07 23:22 UTC, SeparateRecords commented
am fixing generators now, one-time effort until cli 3.0 😉

Will merge when done

2022-11-07 23:48 UTC, SeparateRecords commented
@grant0417 any generators obviously missing?

2022-11-08 09:51 UTC, fedeci commented
@SeparateRecords generators removed are a known issue not solvable with the current approach 😕, we need to use ASTs modifications in order to keep them.

2022-11-08 17:56 UTC, fedeci requested changes
@grant0417 can you check the two comments I left, please?

2022-11-08 17:56 UTC, fedeci commented on src/fig/2.0.0.ts
> +  name: "fig_cli",
```suggestion
  name: "fig",
```

2022-11-08 17:56 UTC, fedeci commented on src/fig/2.0.0.ts
> +              isRepeatable: true,
This does not sound right to me, is this option really repeatable?
Same for a bunch of other options like the ones from the `query-index` subcommand.
```suggestion
              isRepeatable: true,
```

2022-11-08 18:03 UTC, fedeci commented
@mschrage I used filemerge to get diffs between the old and new specs. 
Should I build a web tool that calculates diffs from automatic PRs bumping majors and that publishes those diffs to an html accessible by everyone?

2022-11-08 18:16 UTC, mschrage commented
@fedeci that would be useful, but I don't think that many people besides us use this tooling - so no need to over optimize it right now!

2022-11-09 20:12 UTC, grant0417 commented on src/fig/2.0.0.ts
> +              isRepeatable: true,
Yeah, that doesnt look right, hmm, an issue with the clap generator perhaps

2022-11-10 03:04 UTC, SeparateRecords commented on src/fig/2.0.0.ts
> +              isRepeatable: true,
Let's fix this in an update to the spec - imo for now we should just land this PR. If it's an error in the clap generator, we'll remove it later, if it's in the CLI itself then we'll fix it with semver

2022-11-10 08:37 UTC, fedeci commented
> @fedeci that would be useful, but I don't think that many people besides us use this tooling - so no need to over optimize it right now!

Sounds good, eventually I'll implement it in my free time!

2022-11-10 08:38 UTC, fedeci commented on src/fig/2.0.0.ts
> +              isRepeatable: true,
Great! @SeparateRecords if everything looks good to you feel free to merge.

2022-11-10 08:38 UTC, fedeci approved these changes

2022-11-10 18:31 UTC, grant0417 commented
Going to merge the changes!

2022-11-10 18:32 UTC, merged