[ADB] Added adb spec
withfig/autocomplete pull request #170
Opened 2021-05-01 14:06 UTC by alexnaiman

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adds the spec for adb CLI
**What is the current behavior? (You can also link to an open issue here)**
There isn't any spec for adb CLI
**What is the new behavior (if this is a feature change)?**
This PR adds the adb CLI
**Additional info:**

2021-05-01 14:55 UTC, QuiiBz commented on dev/adb.ts
> +          name: ["-l"],
You can safely remove the array and simply write `"-l"` since it has no other names. Same for below.

2021-05-01 14:55 UTC, QuiiBz commented on dev/adb.ts
> +
Please remove this empty line.

2021-05-01 14:55 UTC, QuiiBz commented on dev/adb.ts
> +
Same, please remove the empty line.

2021-05-01 19:14 UTC, alexnaiman commented
@QuiiBz done with the changes

2021-05-01 20:37 UTC, cstrnt requested changes
Looks good to me! But there is quite some repetition in the code. Maybe you could create some shared options / args to it easier :)

2021-05-01 20:37 UTC, cstrnt commented on specs/adb.js
> +                    name: "REMOTE",
I'm just wondering how this plays together with fig cc @mattschrage @falky97

2021-05-01 20:37 UTC, cstrnt commented on specs/adb.js
> +                    name: "REMOTE",
Because there are two args but one of them is variadic

2021-05-01 20:37 UTC, cstrnt commented on specs/adb.js
> +                            insertValue: "jdwp:",
I think all of those should have the colon (`:`) removed from the name because they are already in the insertvalue

2021-05-01 20:37 UTC, cstrnt commented on specs/adb.js
> +                            name: "tcp:",
See above

2021-05-01 20:55 UTC, alexnaiman commented on specs/adb.js
> +                    name: "REMOTE",
Yeah, I didn't see that. It just ignores the second param. It always suggest the "LOCAL" argument 

<img width="299" alt="Screen Shot 2021-05-01 at 11 54 51 PM" src="https://user-images.githubusercontent.com/25799714/116794810-a0101b00-aad8-11eb-88b9-95c6a90e0157.png">

2021-05-01 21:14 UTC, alexnaiman commented on specs/adb.js
> +                    name: "REMOTE",
This is the last requested change that I don't know how to tackle and I also don't know if it can be tackled in the way the command works.

2021-05-04 04:23 UTC, mattschrage commented on specs/adb.js
> +                    name: "REMOTE",
Sorry for the slow response here. I don’t think we have good answer for this right now.

The workaround would probably be to have the first argument be non-variadic and have the second suggest both - with something like this: `name: “file | remote”`

The second would be variadic and have the same  generator as the first.

2021-05-04 04:45 UTC, mattschrage approved these changes
This is massive! Nice work - android devs everywhere will be grateful :)

Two small things:
- As @cstrnt, we don't really have a great solution for a variadic argument followed by *other* argument. There are workarounds but really this should be addressed at the core autocomplete logic rather than in individual completion specs. I opened an issue for this #177.

- There are some places where the argument is a shell command. If you annotate these arguments with `isCommand: true` then Fig will continue to provide autocompletion!

2021-05-05 19:45 UTC, cstrnt requested changes
Hey Alex, thanks for this huge PR. I just left some comments which I think might improve this spec 😄

2021-05-05 19:45 UTC, cstrnt commented on dev/adb.ts
> +const installOptions = [
Hey alex, any chance you could type this so we can catch errors in the future? 
```suggestion
const installOptions:Fig.Option[] = [
```

2021-05-05 19:45 UTC, cstrnt commented on dev/adb.ts
> +const compressionOptions = [
see above

2021-05-05 19:45 UTC, cstrnt commented on dev/adb.ts
> +const forwardConnectionSuggestions = [
See above, but type this as `Fig.Suggestion[]`

2021-05-05 19:45 UTC, cstrnt commented on dev/adb.ts
> +const reverseConnectionSuggestions = [
see above

2021-05-05 19:45 UTC, cstrnt commented on dev/adb.ts
> +        name: "FILE",
I think you could add `template: filepaths` here to get nice autocompletion for the file here 😊

2021-05-05 19:45 UTC, cstrnt commented on dev/adb.ts
> +          isOptional: true,
see above

2021-05-05 19:45 UTC, cstrnt commented on dev/adb.ts
> +          description: "choose escape character, or `none` default '~'",
I think this takes an optional argument, right?

2021-05-05 19:45 UTC, cstrnt commented on dev/adb.ts
> +        name: "COMMANDS ...",
should this be variadic?

2021-05-05 19:45 UTC, cstrnt commented on dev/adb.ts
> +        name: "host name",
should be optional, right?

2021-05-05 19:45 UTC, cstrnt commented on dev/adb.ts
> +        name: "port",
see above

2021-05-05 19:45 UTC, cstrnt commented on dev/adb.ts
> +        "listen on given socket for adb server [default=tcp:localhost:5037]",
see above

2021-05-11 22:12 UTC, mattschrage commented on dev/adb.ts
> +        name: "FILE",
This is definitely correct! However, not necessary to add before we merge. We are just trying to ensure the CLI skeleton is correct - we can always add/update generators later!

2021-05-11 22:15 UTC, mattschrage commented
I think we can merge this in @cstrnt. Seems like the skeleton is correct.

2021-05-12 12:22 UTC, alexnaiman commented
@mattschrage @cstrnt Hello! thanks for all the feedback. I was really busy these past weeks and I didn't get to do all the changes. I will try at the beginning of the next week to do all the changes you requested, and in case you merged this PR all the fixes will be in a new one.

2021-05-21 16:27 UTC, merged