Bitwarden CLI tool definition
withfig/autocomplete pull request #1701
Opened 2022-11-11 09:28 UTC by atjbramley

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Feature update - support and definitions for Bitwarden CLI tool
(https://bitwarden.com/help/cli/)

**Additional info:**

Thanks for the help with the spec - sorry this took so long!

2022-11-11 09:48 UTC, atjbramley commented
👍

2022-11-11 10:04 UTC, atjbramley commented
Sorry - I've realised that 3 more files have been included in this along with the bw.ts - just stuff I used for testing 🤦

Luckily nothing important - please get rid of these obviously!

2022-11-11 17:48 UTC, mschrage requested changes
This look great! Can you remove the extraneous files from the PR and make the changes below, so we can get this merged in?

2022-11-11 17:48 UTC, mschrage commented on src/bw.ts
> +import { collapseTextChangeRangesAcrossMultipleVersions } from "typescript";
```suggestion
```

2022-11-11 17:48 UTC, mschrage commented on src/bw.ts
> +      icon: "https://bitwarden.com/images/icon_32x32.png",
Can you pull this icon URL into a constant? 
```suggestion
      icon: "https://bitwarden.com/images/icon_32x32.png",
```

2022-11-14 17:45 UTC, mschrage approved these changes

2022-12-07 20:32 UTC, fedeci commented
recheck

2022-12-08 08:13 UTC, atjbramley commented
I have read the CLA Document and I hereby sign the CLA

2022-12-08 20:33 UTC, fedeci commented
recheck

2022-12-20 18:49 UTC, merged