Addition of spec for Bookmark directories and move to them
withfig/autocomplete pull request #1706
Opened 2022-11-14 11:14 UTC by a1ecbr0wn

Usage: bcd [OPTIONS] [BOOKMARK]

Arguments:
  [BOOKMARK]  Bookmarked directory to change to

Options:
  -s, --store <STORE>    Store the current directory as a bookmark STORE
  -r, --remove <REMOVE>  Remove a specified bookmark REMOVE
  -l, --list             List the stored bookmarks
  -V, --version          Print version information
  -h, --help             Print help information command from https://bcd.noser.net

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
new application support

**What is the current behavior? (You can also link to an open issue here)**
N/A

**What is the new behavior (if this is a feature change)?**
Support for `bcd` command line tool

**Additional info:**
File automatically generated using `clap_complete_fig` as a part of the build.

2022-11-14 11:17 UTC, a1ecbr0wn commented
👍

2022-11-14 17:21 UTC, mschrage approved these changes

2022-11-22 19:31 UTC, fedeci requested changes
Thanks, just a couple descriptions to fix!

2022-11-22 19:31 UTC, fedeci commented on src/bcd.ts
> +      description: "Store the current directory as a bookmark STORE",
```suggestion
      description: "Store the current directory as a bookmark",
```

2022-11-22 19:31 UTC, fedeci commented on src/bcd.ts
> +      description: "Remove a specified bookmark REMOVE",
```suggestion
      description: "Remove a specified bookmark",
```

2022-11-22 22:22 UTC, a1ecbr0wn commented
Changes requested by fedeci complete

2022-11-23 17:29 UTC, fedeci approved these changes
Thanks!

2022-11-23 17:35 UTC, merged