add several generators to secretsmanager 🚧  Work in progress 🚧
withfig/autocomplete pull request #171
Opened 2021-05-01 15:40 UTC by nagypeterjob

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

- [x] cancel-rotate-secret
- [x] create-secret
- [x] delete-resource-policy
- [x] delete-secret
- [x] describe-secret
- [x] get-random-password
- [x] get-resource-policy
- [ ] get-secret-value (partially)
- [x] list-secret-version-ids
- [ ] list-secrets (partially)
- [ ] put-resource-policy (partially)
- [ ] put-secret-value (partially)
- [ ] remove-regions-from-replication (partially)
- [ ] replicate-secret-to-regions (partially)
- [ ] restore-secret (partially)
- [ ] rotate-secret (partially)
- [ ] stop-replication-to-replica (partially)
- [ ] tag-resource (partially)
- [ ] untag-resource (partially)
- [ ] update-secret (partially)
- [ ] update-secret-version-stage (partially)
- [ ] validate-resource-policy (partially)

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2021-05-02 02:51 UTC, falky97 commented
This checklist is an excellent format for what needs to be done.

2021-05-02 06:14 UTC, QuiiBz commented
Hi! @nagypeterjob already made the `delete-secret` generator in #166, which one should be kept?

2021-05-02 11:44 UTC, nagypeterjob commented
Hi @QuiiBz 👋🏻
I will close #166 in favour of this PR.

2021-05-02 11:55 UTC, QuiiBz commented
Alright!

2021-05-11 23:02 UTC, mattschrage requested changes
Overall looks great. A couple things to note:
1. There is a much easier approach for suggesting `json` files.
2. For really large CLI tools, it is best to define all generators at the top of the file. Seems like you do this for the most part.
3. How did you decide the `priority` level to grant various options?

If you just replace the `inputJSONGenerator` and `getBlobsGenerator` we can merge this in!

2021-05-12 15:11 UTC, nagypeterjob commented on dev/aws/secretsmanager.ts
> +  inputJSONGenerator: {
The function name was unlucky, now I see it could lead to confusion. I have added comments & renamed the function to be more clearer of why I do it this way. 
Context: https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-parameters-file.html
Some options need the `file://` or `fileb://` prefix when providing a filepath. Basically this functionality is  the reason why @falky97 created that example trigger script. 

Alternatively, I could just use the `filepaths` template, and just append a prefix on insert time using the `insertValue` property, but I feel this is the right way. 

I hope I cleared up some confusion.

2021-05-12 15:11 UTC, nagypeterjob commented on dev/aws/secretsmanager.ts
> +  getBlobsGenerator: {
see above comment

2021-05-12 15:12 UTC, nagypeterjob commented on dev/aws/secretsmanager.ts
> +                try {
noted, I moved up the generator

2021-05-12 15:14 UTC, nagypeterjob commented
To address the priority stuff: I have gave high priority to options which are not optional, or have some kind of dependency between them.
e.g: `aws secretmanager cancel-rotate-secret` won't do anything without `--secret-id`, so I have added it a 100 priority to get to the top.

2021-05-21 16:51 UTC, cstrnt requested changes
Here is my Code Review! I have no experience with AWS and trust you that it is right 😛

2021-05-21 16:51 UTC, cstrnt commented on dev/aws/secretsmanager.ts
> +  var whatHasUserTyped = tokens[tokens.length - 1];
I would prefer using `const` over `var` :)

2021-05-21 16:51 UTC, cstrnt commented on dev/aws/secretsmanager.ts
> +    } else folderPath = whatHasUserTyped.slice(0, lastSlashIndex + 1);
Could you please add some curly brackets here, this is hard to read imho

2021-05-21 16:51 UTC, cstrnt commented on dev/aws/secretsmanager.ts
> +    var other_arr = [];
`const` pls

2021-05-21 16:51 UTC, cstrnt commented on dev/aws/secretsmanager.ts
> +  var final_array = [];
const :)

2021-05-21 16:51 UTC, cstrnt commented on dev/aws/secretsmanager.ts
> +      ttl: 30000,
This is reused 7 times in this spec. I think it would make sense to create a top-level const for this which makes feature changes easier

2021-05-21 16:51 UTC, cstrnt commented on dev/aws/secretsmanager.ts
> +const generators: Record<string, Fig.Generator> = {
The problem with using `Record<string, Fig.Generator` is that TypeScript doesn't warn you if you access a property that doesn't exist! If I use `generators.cstrntIsADeveloper` TypeScript thinks it's a valid property because `cstrntIsADeveloper` is a string! Therefore I would recommend either splitting the generators up to individual variables or using a string union like this `Record<'secretIdsGenerator' | 'kmsKeyIdGenerator' | ..., Fig.Generator>`

2021-05-21 16:51 UTC, cstrnt commented on dev/aws/secretsmanager.ts
> +              name: "Region=" + region + ",KmsKeyId=" + secret.KeyId,
I would prefer using a Template String here 
`Region=${region},KmsKeyId=${secret.KeyId}`
Makes it more readable imho

2021-05-21 16:51 UTC, cstrnt commented on dev/aws/secretsmanager.ts
> +        var out = await executeShellCommand(
Const :) (I know I'm annoying, sorry)

2021-05-21 16:51 UTC, cstrnt commented on dev/aws/secretsmanager.ts
> +        var out = await executeShellCommand(
const 😊

2021-05-21 16:51 UTC, cstrnt commented on dev/aws/secretsmanager.ts
> +        var out = await executeShellCommand(
const :D

2021-05-24 07:30 UTC, cstrnt approved these changes
Apart from the `Record<string, Fig.Generator` this looks good to be merged imo

2021-06-30 07:10 UTC, QuiiBz approved these changes
Let's merge this amazing PR!

2021-06-30 07:10 UTC, merged