feat: add asr completion spec
withfig/autocomplete pull request #1711
Opened 2022-11-18 00:47 UTC by SerpentBytes

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Fixes #945 by adding completion spec for `asr`

**What is the current behavior? (You can also link to an open issue here)**
Missing completion spec for `asr`. See #945.

**What is the new behavior (if this is a feature change)?**
Completion spec for `asr` are added

**Additional info:**
- Deprecated options were not included
- See `man` page references here: https://keith.github.io/xcode-man-pages/asr.8.html#erase

2022-12-08 20:41 UTC, fedeci commented
recheck

2022-12-08 20:43 UTC, SerpentBytes commented
I have read the CLA Document and I hereby sign the CLA

2022-12-08 20:47 UTC, SerpentBytes commented
@fedeci, To clarify: My name is Taimoor Dawami; however my GitHub username is SerpentBytes

2022-12-08 20:48 UTC, SerpentBytes commented
recheck

2022-12-08 21:24 UTC, SerpentBytes commented
recheck

2022-12-08 21:27 UTC, SerpentBytes commented
I have read the CLA Document and I hereby sign the CLA

2022-12-10 09:42 UTC, fedeci requested changes
Thanks for the PR @SerpentBytes! I left one suggestion to address.

2022-12-10 09:42 UTC, fedeci commented on src/asr.ts
> +            description: "Configuration file in standard property list format",
Here you can use the `filepaths` template function to provide file suggestion with the correct extensions. (https://fig.io/docs/reference/generator/prebuilt-generators#filepathsoptions)

2022-12-10 17:01 UTC, SerpentBytes commented on src/asr.ts
> +            description: "Configuration file in standard property list format",
Great catch! working on it 👍🏼

2022-12-10 17:15 UTC, SerpentBytes commented on src/asr.ts
> +            description: "Configuration file in standard property list format",
@fedeci, I resolved this in [e51566b](https://github.com/withfig/autocomplete/pull/1711/commits/e51566bda2f664b82d04a270cb64a3be7f0bbe37).

2022-12-12 16:52 UTC, fedeci approved these changes
Thanks!

2022-12-12 16:52 UTC, merged