feat: add taplo completion spec
withfig/autocomplete pull request #1713
Opened 2022-11-20 07:51 UTC by batunpc

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Fixes https://github.com/withfig/autocomplete/issues/1532 

**What is the current behavior? (You can also link to an open issue here)**
The completion spec does not exist for taplo 

**What is the new behavior (if this is a feature change)?**
autocomplete will be supported for taplo 

**Additional info:**
I used `taplo --help` as reference to work with all the subcommands and options. Also used the 
`taplo <subcommand> --help` which produces different manual for each corresponding subcommands and option(s) in taplo.

2022-11-21 22:22 UTC, fedeci requested changes
Thanks @batunpc! I left some comments to solve before merging the PR, but overall it seems good to me!

2022-11-21 22:22 UTC, fedeci commented on src/taplo.ts
> +            "Print this message or the help of the given subcommand(s)",
```suggestion
            "Print this message or the help of the given subcommand(s)",
          args: {
            template: "help",
          },
```

2022-11-21 22:22 UTC, fedeci commented on src/taplo.ts
> +        isOptional: true,
```suggestion
        isOptional: true,
        isVariadic: true,
```

2022-11-21 22:22 UTC, fedeci commented on src/taplo.ts
> +            suggestCurrentToken: true,
```suggestion
            suggestCurrentToken: true,
            template: "filepaths",
```

2022-11-21 22:22 UTC, fedeci commented on src/taplo.ts
> +            suggestCurrentToken: true,
```suggestion
            suggestCurrentToken: true,
            isVariadic: true,
```

2022-11-21 22:22 UTC, fedeci commented on src/taplo.ts
> +        template: "filepaths",
```suggestion
        template: "filepaths",
        isVariadic: true,
```

2022-11-21 22:22 UTC, fedeci commented on src/taplo.ts
> +      ],
```suggestion
      name: "--colors",
      args: {
        suggestions: ["auto", "always", "never"],
      },
```

2022-11-22 03:51 UTC, batunpc commented on src/taplo.ts
> +      ],
Done 👍

2022-11-22 03:54 UTC, batunpc commented on src/taplo.ts
> +            suggestCurrentToken: true,
Here `template: "filepaths",` is above the suggestCurrentToken
Would you like me to swap their places ?

2022-11-22 03:57 UTC, batunpc commented
Thank you @fedeci I have addressed the requested changes in my last commit https://github.com/withfig/autocomplete/pull/1713/commits/9d4467f77fe2e6214d3954053a201415a1764450 and left a comment for https://github.com/withfig/autocomplete/pull/1713#discussion_r1028567117

2022-11-23 17:34 UTC, fedeci commented on src/taplo.ts
> +            suggestCurrentToken: true,
It is indifferent in a JS object. For styles we want to enforce we create eslint rules, so it `npm run lint` does not complain it is good to go!

2022-11-23 17:34 UTC, fedeci approved these changes
Thanks!

2022-11-23 17:38 UTC, merged