Spec hyperfine
withfig/autocomplete pull request #1714
Opened 2022-11-20 08:42 UTC by saminarp

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Fixes https://github.com/withfig/autocomplete/issues/1549 to add new autocompletion spec for `hyperfine`

**What is the current behavior? (You can also link to an open issue here)**
Currently, fig does not have support to autocomplete hyperfine

**What is the new behavior (if this is a feature change)?**
Autocomplete for `hyperfine`

**Additional info:**
First contribution to Fig :)

2022-11-21 22:28 UTC, fedeci reviewed
Thanks @saminarp! This looks great, can you just give me a feedback on the comment I left, please?

2022-11-22 02:55 UTC, grant0417 commented on src/hyperfine.ts
> +  // Only uncomment if hyperfine takes an argument
```suggestion
```

Not sure you want this in here

2022-11-22 02:56 UTC, grant0417 commented on src/hyperfine.ts
> +          name: "CMD",
This should only be an argument for the top level command

2022-11-22 20:34 UTC, saminarp commented on src/hyperfine.ts
> +          name: "CMD",
Hi! Thank you for your feedback. :) 
I am a little unsure about what it means by top-level command. Please let me know and I will fix the issues right away.

2022-11-23 20:52 UTC, saminarp commented on src/hyperfine.ts
> +        },
@fedeci  I am unclear about the top level argument, if you could explain me I will fix it right away :)

2022-12-05 20:53 UTC, fedeci commented on src/hyperfine.ts
> +        },
Sorry for the late response @saminarp, by top-level command we mean the arg added directly as a property of the `completionSpec` object.

2022-12-07 20:34 UTC, saminarp commented
I have read the CLA Document and I hereby sign the CLA

2022-12-07 20:44 UTC, fedeci commented on src/hyperfine.ts
> +        },
Thanks!

2022-12-10 03:54 UTC, grant0417 requested changes
These are the same argument as on line 288, these dont need to be here

2022-12-10 03:54 UTC, grant0417 commented on src/hyperfine.ts
> +        },
```suggestion
```

2022-12-10 03:54 UTC, grant0417 commented on src/hyperfine.ts
> +      dependsOn: ["--parameter-scan", "-P"],
```suggestion
      args: [
        {
          name: "delta",
        },
      ],
      dependsOn: ["--parameter-scan", "-P"],
```

2022-12-10 03:54 UTC, grant0417 commented on src/hyperfine.ts
> +        },
```suggestion
```

2022-12-10 03:55 UTC, grant0417 commented
Just add the suggestion, fix the lints, then good to merge

2022-12-10 04:20 UTC, saminarp commented
Hello, @grant0417 I have implemented the suggested changes, please let me know if it looks okay :)

2022-12-10 04:21 UTC, saminarp commented on src/hyperfine.ts
> +        },
Done

2022-12-10 04:26 UTC, grant0417 requested changes
Okay, looked at every subcommand now, these are my final changes, sorry for so many reviews!

2022-12-10 04:26 UTC, grant0417 commented on src/hyperfine.ts
> +      ],
```suggestion
        },
      ],
```

2022-12-10 04:26 UTC, grant0417 commented on src/hyperfine.ts
> +    },
```suggestion
        "Print the stdout and stderr of the benchmark instead of suppressing it",
    },
```

2022-12-10 04:26 UTC, grant0417 commented on src/hyperfine.ts
> +      ],
```suggestion
        },
      ],
```

2022-12-10 04:26 UTC, grant0417 commented on src/hyperfine.ts
> +    },
```suggestion
          template: "filepaths",
        },
      ],
    },
```

2022-12-10 04:26 UTC, grant0417 commented on src/hyperfine.ts
> +      ],
```suggestion
        },
      ],
```

2022-12-10 04:26 UTC, grant0417 commented on src/hyperfine.ts
> +    },
```suggestion
    },
```

2022-12-10 04:26 UTC, grant0417 commented on src/hyperfine.ts
> +        },
```suggestion
```

2022-12-10 04:26 UTC, grant0417 commented on src/hyperfine.ts
> +        name: "CMD",
```suggestion
        name: "CMD",
        isCommand: true,
```

2022-12-10 04:26 UTC, grant0417 commented on src/hyperfine.ts
> +        isVariadic: true,
```suggestion
        isCommand: true,
```

2022-12-10 04:28 UTC, saminarp commented
No worries at all @grant0417, I will be implementing them :)

2022-12-10 04:32 UTC, saminarp commented on src/hyperfine.ts
> +    },
Done

2022-12-10 04:33 UTC, saminarp commented on src/hyperfine.ts
> +      ],
Done

2022-12-10 04:34 UTC, saminarp commented on src/hyperfine.ts
> +    },
Done

2022-12-10 04:35 UTC, saminarp commented on src/hyperfine.ts
> +    },
Done

2022-12-10 04:38 UTC, saminarp commented on src/hyperfine.ts
> +      ],
Done

2022-12-10 04:48 UTC, merged

2022-12-10 04:49 UTC, grant0417 commented
Thank you so much, use hyperfine a bunch. Glad to have a spec for it.