[EXPO] Fix `expo web` aliase to `expo start:web`
withfig/autocomplete pull request #173
Opened 2021-05-02 06:38 UTC by QuiiBz

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Fixes #159 

**What is the current behavior? (You can also link to an open issue here)**
`expo web` is not recognized

**What is the new behavior (if this is a feature change)?**
`expo web` is recognized

**Additional info:**
<img width="241" alt="Screenshot 2021-05-02 at 08 37 44" src="https://user-images.githubusercontent.com/43268759/116804753-abd3ff80-ab21-11eb-8799-9dacd1d58bc9.png">
I also removed all empty arrays of `subcommands` since that wasn't needed.

2021-05-02 09:56 UTC, cstrnt requested changes

2021-05-02 09:56 UTC, cstrnt commented on dev/expo.ts
> +    description: "output usage information\n  \n  \n",
I think we don't need the `\n`s here

2021-05-02 09:56 UTC, cstrnt commented on dev/expo.ts
> +    args: {},
Wouldn't it make sense to add `tunnel` `lan` and `localhost` as suggestions here?

2021-05-02 10:25 UTC, QuiiBz commented
I copy/pasted the existing spec, didn’t noticed that there were some issues in it. Let me fix them

2021-05-02 10:29 UTC, cstrnt commented
Thank you very much, Tom 😊

2021-05-02 10:51 UTC, QuiiBz commented on dev/expo.ts
> +    description: "output usage information\n  \n  \n",
Fixed thanks to the power of regex  😄

2021-05-02 10:52 UTC, QuiiBz commented on dev/expo.ts
> +    args: {},
Done, looks cool!
<img width="375" alt="Screenshot 2021-05-02 at 12 51 52" src="https://user-images.githubusercontent.com/43268759/116810637-2e21eb00-ab45-11eb-828b-f9c53e896d71.png">

2021-05-04 04:15 UTC, mattschrage submitted a review, later dismissed
Love the addition of the `host` suggestions and thanks for stripping the newline literals!

You can add an alias to a subcommand just by include an array of names in the `name` prop.

So `name: "web"` can become `name: ["start:web", "web"]` 

This just saves you from needing to extract all of the shared options and is a little cleaner! We might need to document this a bit better 😅

2021-05-04 07:34 UTC, QuiiBz commented
> Love the addition of the `host` suggestions and thanks for stripping the newline literals!
> 
> You can add an alias to a subcommand just by include an array of names in the `name` prop.
> 
> So `name: "web"` can become `name: ["start:web", "web"]`
> 
> This just saves you from needing to extract all of the shared options and is a little cleaner! We might need to document this a bit better 😅

I see! But currently, the `Subcommand` interface only accepts a string. We will need to update this first in order to change this spec:
![Screenshot 2021-05-04 at 09 33 58](https://user-images.githubusercontent.com/43268759/116972798-dbb70a80-acbb-11eb-82f5-1293d8743c68.png)
Based on. what you said, the type of `name` should be changed to: `SingleOrArray<string>`

2021-05-04 19:24 UTC, cstrnt commented
@mattschrage this is new, right? Because I remember bumping into that problem and it didn't work back then.

@QuiiBz I think so!

2021-05-04 21:52 UTC, mattschrage commented
> @mattschrage this is new, right? Because I remember bumping into that problem and it didn't work back then.

I just tested it and you're totally right - having an array for the `name` field in a Subcommand isn't currently supported. cc @falky97

2021-05-04 23:05 UTC, falky97 commented
^^ Yes this is fixed as matt outlined above

2021-05-05 06:41 UTC, QuiiBz commented
Sweet! Just updated, ready to merge in.

2021-05-05 19:31 UTC, cstrnt approved these changes

2021-05-05 19:31 UTC, cstrnt commented
Well done, Tom

2021-05-05 19:58 UTC, merged