chore: add CLA verification
withfig/autocomplete pull request #1731
Opened 2022-12-03 19:43 UTC by fedeci

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2022-12-04 07:46 UTC, mschrage approved these changes

2022-12-06 07:04 UTC, sasial-dev commented
A CLA will work for all new PR's, but what about all the old code by the 300+ contributors who _haven't_ signed the CLA?

2022-12-07 05:10 UTC, brendanfalk requested changes

2022-12-07 05:10 UTC, brendanfalk commented on cla/cla.md
> +You accept and agree to the following terms and conditions for Your present and future Contributions submitted to Fig. Except for the license granted herein to Fig and recipients of software distribu
```suggestion
You accept and agree to the following terms and conditions for Your Contributions submitted to Fig. Except for the license granted herein to Fig and recipients of software distributed by Fig, You reserve all right, title, and interest in and to Your Contributions.
```

2022-12-07 05:15 UTC, brendanfalk approved these changes

2022-12-07 05:16 UTC, merged

2022-12-07 05:21 UTC, brendanfalk commented
> A CLA will work for all new PR's, but what about all the old code by the 300+ contributors who _haven't_ signed the CLA?

My understanding is the CLA applies to all contributions. In saying that, the CLA doesn't mean Fig "owns" your code. You still own your contributions and do what you want with them. The CLA just allows us to use these contributions for things in the future (like if we decide to relicense, or if we decide to use some of the withfig/autocomplete code in our own private codebase).

We spoke to a lot of very well known devtools founders recently and they all **highly** suggested we use a CLA. It's a quick easy process, very contributor friendly, and not doing it can only come back to bite us in the future.

2022-12-07 06:49 UTC, fedeci commented on .github/workflows/verify-cla.yml
> +    types: [created]
This is because PRs comments are issues. They get filtered later in the action.