Wail
withfig/autocomplete pull request #1744
Opened 2022-12-09 21:21 UTC by Wail-Mohammed

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature (Spec feature added for helmfile)
**What is the current behavior? (You can also link to an open issue here)**
https://github.com/withfig/autocomplete/issues/1201 
**What is the new behavior (if this is a feature change)?**
Fig autocomplete can now auto complete helmfile commands and flags.
**Additional info:**
This PR is aiming to close issue # 1201 by adding helmfile.ts to the src folder in order to add helmfile commands to autocomplete.

2022-12-09 21:54 UTC, mschrage commented on src/helmfile.ts
> +      description: "DEPRECATED: delete releases from state file (helm delete)",
Please use the `[deprecated](https://fig.io/docs/reference/suggestion#deprecated)` field to signify this type of information.

2022-12-10 05:26 UTC, Wail-Mohammed commented
I have read the CLA Document and I hereby sign the CLA

2022-12-10 09:53 UTC, fedeci requested changes

2022-12-10 09:53 UTC, fedeci commented on src/helmfile.ts
> +  description: "",
```suggestion
  description: "Deploy helm charts.",
```

2022-12-10 09:55 UTC, fedeci commented on src/helmfile.ts
> +    {
```suggestion
```

2022-12-12 16:52 UTC, fedeci approved these changes

2022-12-12 16:53 UTC, fedeci commented
Thanks!

2022-12-12 16:53 UTC, merged