feat: add spec for spring cli #1341
withfig/autocomplete pull request #1745
Opened 2022-12-09 21:26 UTC by tmwrnr

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature

**What is the current behavior? (You can also link to an open issue here)**
n/a

**What is the new behavior (if this is a feature change)?**
Adds a new spec for [spring](https://docs.spring.io/spring-boot/docs/current/reference/html/cli.html)

**Additional info:**

2022-12-10 02:31 UTC, grant0417 requested changes
Looks pretty good! Just a few comments

2022-12-10 02:31 UTC, grant0417 commented on target/npmlist.json
> +{
Why did you add this file?

2022-12-10 02:31 UTC, grant0417 commented on src/spring.ts
> +  icon: "https://spring.io/images/favicon-9d25009f65637a49ac8d91eb1cf7b75e.ico",
Is there a `.jpg` or `.png` version? This is fine just prefer those formats.

2022-12-10 02:31 UTC, grant0417 commented on src/spring.ts
> +        name: dependency.id + ",",
Swapping this to just `dependency.name` and adding `insertValue` might be a better way to do this.

2022-12-10 07:16 UTC, tmwrnr commented on target/npmlist.json
> +{
I actually don't know where this file came from. Is removed in the next commit

2022-12-10 07:33 UTC, tmwrnr commented on src/spring.ts
> +        name: dependency.id + ",",
I need to use `dependency.id`, because this is the actual name. `dependency.name` is a display name:

```json
{
  "description": "Java library to generate text output (HTML web pages, e-mails, configuration files, source code, etc.) based on templates and changing data.",
  "id": "freemarker",
  "name": "Apache Freemarker"
}
```
I tried to find a good solution for the `","` problem. My aim was that the command looks like that:

```sh
spring init -d=freemarker,lombok,datadog
```
But I ran into multiple problems. When I used `requiresSeparator` the `=` was printed, but the suggestions for the dependencies only triggered after typing a space after the `=`. I noticed that the CLI can also handle the argument without a separator so I removed it. 

The next problem was, that the dependencies need to be separated with a `,`. I could not find a right parameter for that use case. I tried `replaceValue` but this only added an `,` after the first dependency.  I am unsure how  `inserValue` can help me with this problem.

Could you give a me an example how I can improve this?

2022-12-23 05:36 UTC, tmwrnr commented on src/spring.ts
> +        name: dependency.id + ",",
@grant0417 Any update on this?

2022-12-23 16:30 UTC, grant0417 commented on src/spring.ts
> +        name: dependency.id + ",",
Ah, didn't see it before. @fedeci might ahve a better idea on how to use `requiresSeparator` with a list.

2022-12-26 17:42 UTC, fedeci commented on src/spring.ts
> +        name: dependency.id + ",",
@tmwrnr we provide the `valueList` generator from the `@fig/autocomplete-generators` package but it only supports static values at the moment. I would suggest you to copy its implementation and integrate in it the methods required to get the package list.
```ts
// implementation
export function valueList({
  delimiter = ",",
  values = [],
  cache = false,
  insertDelimiter = false,
  allowRepeatedValues = false,
}: ValueListInit): Fig.Generator {
  return {
    trigger: (newToken, oldToken) =>
      newToken.lastIndexOf(delimiter) !== oldToken.lastIndexOf(delimiter),

    getQueryTerm: (token) => token.slice(token.lastIndexOf(delimiter) + delimiter.length),

    custom: async (...init) => {
      const out = await getSuggestions(values, insertDelimiter ? delimiter : "", cache, init);
      if (allowRepeatedValues) {
        return out;
      }
      const [tokens] = init;
      const valuesInList = tokens[tokens.length - 1]?.split(delimiter);
      return removeRepeatSuggestions(valuesInList, out);
    },
  };
}
```

2022-12-27 06:38 UTC, tmwrnr commented on src/spring.ts
> +        name: dependency.id + ",",
@grant0417 @fedeci I improved the generator. Is this how you imagined it?

2023-01-14 06:34 UTC, tmwrnr commented on src/spring.ts
> +        name: dependency.id + ",",
@grant0417 @fedeci Anything new for this?

2023-01-14 07:12 UTC, grant0417 commented on src/spring.ts
> +        name: dependency.id + ",",
I think this is fine, going to merge and sorry for the delay on this, thanks for the contribution!

2023-01-14 07:12 UTC, merged