WIP: Update circleci cli autocomplete
withfig/autocomplete pull request #1748
Opened 2022-12-10 17:38 UTC by jerdog

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2022-12-10 17:40 UTC, jerdog commented
I have read the CLA Document and I hereby sign the CLA

2022-12-12 16:59 UTC, fedeci commented
@jerdog please ping me when this is ready!

2022-12-12 17:15 UTC, jerdog commented
Will do @fedeci - ran into a wall with timing this weekend but will work on it this week

2022-12-12 17:16 UTC, fedeci commented
Don't worry man, no pressure!

2022-12-13 04:08 UTC, jerdog commented
@fedeci this should be good to go now!

2023-01-14 07:11 UTC, grant0417 commented on src/circleci.ts
> +              args: [
These would be better with this: https://fig.io/docs/reference/option#requiresequals

2023-02-04 16:38 UTC, fedeci commented on src/circleci.ts
> +              name: "--context string",
```suggestion
              name: "--context",
```

2023-02-04 17:07 UTC, fedeci commented on src/circleci.ts
> +              name: "--context string",
Same for all the other options that are affected by the same problem. That 'string' should be added as an argument of the option

e.g.
```
{
	 name: "--context",
	 description: "Policy context for decision, default is 'config'",
	 dependsOn: ["policy_dir_path"],
   args: {
     name: "string"
   }
},
```

2023-02-04 17:14 UTC, fedeci requested changes

2023-02-04 17:14 UTC, fedeci commented on src/circleci.ts
> +              name: "--context string",
I have added a lint rule to prevent this issues from happening again :)

2023-02-04 17:14 UTC, fedeci commented on src/circleci.ts
> +            },
```suggestion
              name: "--enabled",
              requiresSeparator: true,
              description:
                "Enable/disable policy decision evaluation in build pipeline",
              args: {
              	name: "boolean",
              	isOptional: true,
              	suggestions: ["true", "false"],
              },
            },
```

2023-02-06 03:43 UTC, grant0417 commented
@fedeci looks like the linter is broken

2023-02-06 10:08 UTC, fedeci commented
@grant not our fault https://github.com/amilajack/eslint-plugin-compat/issues/528

2023-02-06 11:59 UTC, jerdog commented
You mean, lint failed lint? 🤣😭

On Mon, Feb 6, 2023, 04:09 Federico Ciardi ***@***.***> wrote:

> @grant <https://github.com/grant> not our fault
> amilajack/eslint-plugin-compat#528
> <https://github.com/amilajack/eslint-plugin-compat/issues/528>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/withfig/autocomplete/pull/1748#issuecomment-1418826947>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACIPIDHOM7HGYQA62U6ZQTWWDEUDANCNFSM6AAAAAAS2MQQYQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-06 16:44 UTC, fedeci commented
I mean, the lint for this PR is failing because of problems, but there is a dependency issue that is making all the other PRs and the master branch fail too. That one is not our fault :(

2023-02-06 17:10 UTC, fedeci commented on src/circleci.ts
> +              dependsOn: ['--namespace'],
```suggestion
```

2023-02-06 17:10 UTC, fedeci commented on src/circleci.ts
> +              dependsOn: ['namespace/orb'],
```suggestion
```

2023-02-06 17:10 UTC, fedeci commented on src/circleci.ts
> +          },
```suggestion
          args: {
            name: 'policy_dir_path',
            description: 'Policy file or directory path',
          },
```

2023-02-06 17:11 UTC, fedeci approved these changes

2023-02-06 17:18 UTC, merged