feat(zipcloak): add zipcloak completion spec
withfig/autocomplete pull request #1769
Opened 2022-12-27 05:03 UTC by SawanSrivastava1210

2022-12-27 05:07 UTC, SawanSrivastava1210 commented
I have read the CLA Document and I hereby sign the CLA

2022-12-27 11:41 UTC, fedeci commented on src/zipcloak.ts
> +import { filepaths } from "@fig/autocomplete-generators";
This is not required when using the `template: ` sugar.
```suggestion
```

2023-01-02 22:04 UTC, fedeci requested changes
Thanks, I left a couple comments to fix.

2023-01-02 22:04 UTC, fedeci commented on src/zipcloak.ts
> +    template: ["filepaths"],
```suggestion
    template: ["filepaths"],
    suggestCurrentToken: true,
```

2023-01-02 22:04 UTC, fedeci commented on src/zipcloak.ts
> +        template: ["filepaths"],
Same suggestCurrentToken requirement here.

2023-01-11 20:58 UTC, fedeci commented
@sa1sr1 the CI is failing, can you run `npm run lint:fix` in your local repo clone and push the changes?

2023-01-14 07:06 UTC, grant0417 commented
Thanks for the contrib!

2023-01-14 07:06 UTC, merged