feat: add cdk8s completion spec
withfig/autocomplete pull request #1784
Opened 2023-01-06 14:10 UTC by petar-cvit

Adds [cdk8s](https://cdk8s.io/) completion spec

2023-01-06 14:11 UTC, petar-cvit commented
I have read the CLA Document and I hereby sign the CLA

2023-01-07 10:14 UTC, fedeci requested changes
Thanks for the spec @petar-cvit! I have added some arguments with generators as suggestions, they really make autocomplete powerful! I would suggest you to add some for the `--language` options too!

2023-01-07 10:14 UTC, fedeci commented on src/cdk8s.ts
> +          name: ["--app", "--a"],
```suggestion
          name: ["--app", "-a"],
```

2023-01-07 10:14 UTC, fedeci commented on src/cdk8s.ts
> +          description: "Output directory",
```suggestion
          description: "Output directory",
          args: {
            template: "folders",
            suggestCurrentToken: true,
          },
```

2023-01-07 10:14 UTC, fedeci commented on src/cdk8s.ts
> +          description: "Apply validation plugins on the resulting manifests",
```suggestion
          description: "Apply validation plugins on the resulting manifests",
          exclusiveOn: ["--no-validate"],
```

2023-01-07 10:14 UTC, fedeci commented on src/cdk8s.ts
> +          description: "Disable validation",
```suggestion
          description: "Disable validation",
          exclusiveOn: ["--validate"],
```

2023-01-07 10:14 UTC, fedeci commented on src/cdk8s.ts
> +          description: "Output directory",
```suggestion
          description: "Output directory",
          args: {
            template: "folders",
            suggestCurrentToken: true,
          },
```

2023-01-07 10:14 UTC, fedeci commented on src/cdk8s.ts
> +          description: "A prefix to add to all generated class names",
```suggestion
          description: "A prefix to add to all generated class names",
          exclusiveOn: ["--no-class-prefix"],
```

2023-01-07 10:14 UTC, fedeci commented on src/cdk8s.ts
> +          description: "Does not add a prefix to generated class names",
```suggestion
          description: "Does not add a prefix to generated class names",
          exclusiveOn: ["--class-prefix"],
```

2023-01-07 10:14 UTC, fedeci commented on src/cdk8s.ts
> +            "Do not import types that match these regular expressions",
```suggestion
            "Do not import types that match these regular expressions",
          args: {
            name: "regexp",
          },
```

2023-01-07 10:14 UTC, fedeci commented on src/cdk8s.ts
> +        description: "Path to the CRD schema",
```suggestion
        description: "Path to the CRD schema",
        args: {
           template: "filepaths",
        },
```

2023-01-07 10:14 UTC, fedeci commented on src/cdk8s.ts
> +            "File to write a JSON representation of the validation reports to",
```suggestion
            "File to write a JSON representation of the validation reports to",
          args: {
            template: "filepaths",
            suggestCurrentToken: true,
          },
```

2023-01-11 21:09 UTC, fedeci approved these changes
Thanks!

2023-01-11 21:10 UTC, merged