[brew] - alias subcommand
withfig/autocomplete pull request #1791
Opened 2023-01-09 20:45 UTC by seenukarthi

This PR adds `alias` subcommand to brew.

Closes #1790

2023-01-11 21:07 UTC, fedeci requested changes

2023-01-11 21:07 UTC, fedeci commented on src/brew.ts
> +});
```suggestion
const generatorAlias: Fig.Generator = {
  script: 'find ~/.brew-aliases/ -type f ! -name "*.*" -d 1 | sed "s/.*\\///"',
  postProcess: function (out) {
    return out
      .split("\n")
      .filter((line) => line && line.trim() !== "")
      .map((line) => ({
        name: line,
        icon: "fig://icon?type=command",
        description: `Execute alias ${line}`,
      }));
  },
};
```

2023-01-11 21:07 UTC, fedeci commented on src/brew.ts
> +        generators: generatorAlias(),
```suggestion
        generators: generatorAlias,
```

2023-01-11 21:07 UTC, fedeci commented on src/brew.ts
> +    generators: generatorAlias(),
```suggestion
    generators: generatorAlias,
```

2023-01-14 16:17 UTC, AlanSyue approved these changes

2023-01-14 16:17 UTC, AlanSyue commented on src/brew.ts
> +const generatorAlias: Fig.Generator = {
[nit, discussion]
Wouldn't this name be more concise?
```suggestion
const alias: Fig.Generator = {
```

2023-01-14 16:27 UTC, seenukarthi commented on src/brew.ts
> +const generatorAlias: Fig.Generator = {
@AlanSyue I was following the convention in the file.

May be I could change is to `generateAlias` instead of `generatorAlias`

2023-01-14 16:37 UTC, AlanSyue commented on src/brew.ts
> +const generatorAlias: Fig.Generator = {
I think `generateAliases` is nice 😀

2023-01-15 14:57 UTC, AlanSyue approved these changes

2023-01-18 18:53 UTC, fedeci approved these changes
Thanks!

2023-01-18 18:54 UTC, merged