feat: add `elm-json` completion spec
withfig/autocomplete pull request #1808
Opened 2023-01-17 21:10 UTC by wolfadex

### What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

**Feature**: Support for [elm-json](https://github.com/zwilias/elm-json)

### What is the new behavior (if this is a feature change)?

Support all of the publicly shown elm-json commands as of version 0.2.13.

2023-01-18 02:08 UTC, mschrage approved these changes

2023-01-18 02:09 UTC, mschrage requested changes

2023-01-18 13:46 UTC, wolfadex commented on src/elm-json.ts
> +    "curl -sH 'accept-encoding: gzip' https://package.elm-lang.org/search.json | gunzip",
Very happy to make this change! Should I do the same for `src/elm.ts`? I originally wrote that almost 2 years ago and just copied from it.

2023-01-18 18:52 UTC, fedeci requested changes
Thanks for the PR @wolfadex! I left some comments to address before merging this!

2023-01-18 18:52 UTC, fedeci commented on src/elm-json.ts
> +    ttl: 100 * 24 * 60 * 60 * 3, // 3 days
milliseconds :)
```suggestion
    ttl: 1000 * 24 * 60 * 60 * 3, // 3 days
```

2023-01-18 18:52 UTC, fedeci commented on src/elm.ts
>      ttl: 100 * 24 * 60 * 60 * 3, // 3 days
```suggestion
    ttl: 1000 * 24 * 60 * 60 * 3, // 3 days
```

2023-01-18 18:52 UTC, fedeci commented on src/elm-json.ts
> +        description: "The elm.json file to upgrade [default: elm.json]",
https://fig.io/docs/reference/generator/prebuilt-generators#filepathsoptions
```suggestion
        description: "The elm.json file to upgrade [default: elm.json]",
        generators: [filepaths({ extensions: ["json"] })]
```

2023-01-18 18:52 UTC, fedeci commented on src/elm-json.ts
> +        },
This is likely not required, because we should already be providing the parent args as suggestions

2023-01-18 18:52 UTC, fedeci commented on src/elm-json.ts
> +const packageList: Fig.Generator = {
```suggestion
import { filepaths } from "@fig/autocomplete-generators";

const packageList: Fig.Generator = {
```

2023-01-18 19:00 UTC, fedeci commented on src/elm-json.ts
> +        },
I meant "parent subcommand", my bad!

2023-01-18 19:00 UTC, fedeci commented on src/elm-json.ts
> +        generators: [filepaths({ extensions: ["json"] })]
```suggestion
        generators: filepaths({ extensions: ["json"] })
```

2023-01-18 19:03 UTC, fedeci commented on src/elm-json.ts
> +        },
e.g. you type `elm-json subcommand subcommand-arg-1[space]` after the space we add all suggestions that may be relevant included the ones of the parent subcommands. In this case the parent subcommand arg uses a filepaths generator so filepaths will be among the suggestions!

2023-01-18 19:05 UTC, fedeci commented on src/elm-json.ts
> +        generators: filepaths({ extensions: ["json"] })
```suggestion
        generators: filepaths({ extensions: ["json"] }),
```

2023-01-18 19:06 UTC, wolfadex commented on src/elm-json.ts
> +        },
If I comment out lines 135-138 then I don't see `-- INPUT` as part of the suggestion for what to type next with `elm-json uninstall. Though after typing the package I don't see it as a suggestion either. Is there a way to make it a suggestion, maybe something I've missed in the docs?

2023-02-09 20:37 UTC, fedeci approved these changes
Thanks!

2023-02-09 20:37 UTC, merged