Added specs for the cut command
withfig/autocomplete pull request #181
Opened 2021-05-05 08:05 UTC by colwin

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adds specs for the cut command
**What is the current behavior? (You can also link to an open issue here)**
No specs exist for the cut command
**What is the new behavior (if this is a feature change)?**
cut command autocompletion is enabled
**Additional info:**
<img width="413" alt="Screenshot 2021-05-05 at 1 23 59 PM" src="https://user-images.githubusercontent.com/811817/117112474-bb17af00-ada6-11eb-9ac6-3c6e0bc2268f.png">

2021-05-05 16:04 UTC, QuiiBz requested changes

2021-05-05 16:04 UTC, QuiiBz commented on dev/cut.ts
> +      description: "byte positions as a comma or - separated list of numbers",
This shouldn't be a `subcommands`, but an `option`. See the [docs](https://withfig.com/docs/autocomplete/guides/building-first-spec#3-adding-options-and-args) for a good example, or check an existing spec to see how it's implemented.

2021-05-05 16:04 UTC, QuiiBz commented on dev/cut.ts
> +      description: "column positions as a comma or - separated list of numbers",
Same as above. Also, you can safely remove the brackets around the same, since you have only one value:
```suggestion
 {
      name: "-c",
      description: "column positions as a comma or - separated list of numbers",
```

2021-05-05 16:04 UTC, QuiiBz commented on dev/cut.ts
> +      description: "field positions as a comma or - separated list of numbers",
Same as above

2021-05-05 18:10 UTC, colwin commented
Got it. I’ll update the PR in the morning. I couldn’t find an example where an option had multiple arguments. But I’ll try making that a list under the option and update the PR. 

Thank you for taking the time to review and provide feedback @QuiiBz

2021-05-05 18:34 UTC, QuiiBz commented
The `Fig.Option` object provides an `args` option, which can take a single `Fig.Arg` object or an array of them (docs: https://withfig.com/docs/autocomplete/api#option-object). Feel free to join the [Slack community](Community) if you need more help!

2021-05-06 04:07 UTC, colwin commented on dev/cut.ts
> +      description: "byte positions as a comma or - separated list of numbers",
Updated this to be an option. Updated name to not have [] around it anymore

2021-05-06 04:07 UTC, colwin commented on dev/cut.ts
> +      description: "column positions as a comma or - separated list of numbers",
Updated this to be an option. Updated name to not have [] around it anymore

2021-05-06 04:07 UTC, colwin commented on dev/cut.ts
> +      description: "field positions as a comma or - separated list of numbers",
Updated this to be an option. Updated name to not have [] around it anymore

2021-05-06 04:09 UTC, colwin commented
@QuiiBz  - Have updated the PR to address your review comments! Please let me know if there is anything else I need to change to bring it up to spec for a merge.

2021-05-06 18:18 UTC, QuiiBz approved these changes
I'm not very familiar with the `cut` CLI, but this looks good to me. Let's wait for another approbation just to make sure everything is correct.

2021-05-07 18:02 UTC, falky97 commented
Needs to be changed... I will update and add info to docs

2021-05-09 06:14 UTC, colwin commented
@falky97 - Updated to address your feedback. Can you please take another look and approve if its good to merge?

2021-05-11 17:37 UTC, cstrnt requested changes
Hey there, I know this is a really tricky spec and kinda hard to mirror the behaviour into fig :)

2021-05-11 17:37 UTC, cstrnt commented on dev/cut.ts
> +        },
Hey there, I know this is kinda tricky, but as a rule of thumb: everything that starts with a `-` or `--` is an option

2021-05-11 17:37 UTC, cstrnt commented on dev/cut.ts
> +        },
See above

2021-05-11 17:37 UTC, cstrnt commented on dev/cut.ts
> +          isOptional: true,
This should be an option and it also takes an argument called `delim`
![Screenshot 2021-05-11 at 19 36 12](https://user-images.githubusercontent.com/20679094/117860072-258d8b00-b290-11eb-83a9-76c70fcd9df6.png)

2021-05-12 04:19 UTC, colwin commented on dev/cut.ts
> +        },
I've converted them all to options instead of args

2021-05-12 04:19 UTC, colwin commented on dev/cut.ts
> +        },
converted to options

2021-05-12 04:20 UTC, colwin commented on dev/cut.ts
> +          isOptional: true,
converted to options

2021-05-12 04:21 UTC, colwin commented
@QuiiBz @falky97 Pushed a new commit fixing your review comments. The - arguments are now all options to cut

2021-05-21 16:58 UTC, cstrnt submitted a review, later dismissed
Hey there :) Just a little change which would make this Spec even better :)

2021-05-21 16:58 UTC, cstrnt commented on dev/cut.ts
> +        },
This is reused three times, I would prefer having a top-level const called 
`const listArg: Fig.Arg = { // Code goes here }` which is then referenced

2021-05-23 01:58 UTC, mattschrage approved these changes
Looks good to me!

2021-05-23 01:59 UTC, mattschrage commented on dev/cut.ts
> +        },
This is nice to have but not essential for us to merge in!

2021-05-23 02:00 UTC, merged