fix         : Fixed `tldr` spec.
withfig/autocomplete pull request #1827
Opened 2023-01-27 15:54 UTC by seenukarthi

This PR fixes the completion spec `tldr`
 
Closes #1826

Sgned-off-by: Karthikeyan Vaithilingam <seenukarthi@gmail.com>

2023-01-29 14:49 UTC, AlanSyue commented on src/tldr.ts
> +      insertValue: "--platform={cursor}",
Maybe we can use `requiresSeparator` instead.
```suggestion
      requiresSeparator: true,
```
https://github.com/withfig/autocomplete-tools/blob/main/types/index.d.ts#L713-L725

2023-02-01 13:26 UTC, AlanSyue commented on src/tldr.ts
> +        suggestions: ["linux", "osx", "sunos", "windows", "common"],
[nit]
Maybe we should declare a variable to gather these keywords?

https://github.com/withfig/autocomplete/pull/1827/files#diff-50bd02ab6f158b81b333c17f0cc4c4058f28dbdb7e710d9d0acb4cca77a99a13R140

2023-02-01 13:26 UTC, AlanSyue approved these changes

2023-02-02 04:24 UTC, seenukarthi commented on src/tldr.ts
> +        suggestions: ["linux", "osx", "sunos", "windows", "common"],
@AlanSyue Yes have made the suggestions constant.

2023-02-02 04:29 UTC, AlanSyue approved these changes

2023-02-04 14:45 UTC, fedeci requested changes
Thanks @seenukarthi! I left a comment to solve before merging this.

2023-02-04 18:54 UTC, seenukarthi commented on src/tldr.ts
> +    },
@fedeci the option `-p` expects a white space between `-p` and the argument, on the other hand `--platform` need a `=` between option and the argument that's the reason I made it as desperate options.

2023-02-05 19:03 UTC, fedeci commented on src/tldr.ts
> +    },
`--platform` is not requiring the equals nor `-p` requires a space.

2023-02-06 09:41 UTC, merged