Add leaf php autocomplete spec
withfig/autocomplete pull request #1861
Opened 2023-02-19 16:21 UTC by neo773

This PR adds auto complete spec for [Leaf PHP](https://leafphp.dev/) CLI

https://user-images.githubusercontent.com/62795688/219960742-3e75dc91-4cd4-4708-b777-7adf61bdc722.mp4

2023-02-19 16:25 UTC, neo773 commented
I have read the CLA Document and I hereby sign the CLA

2023-02-19 16:25 UTC, neo773 commented
recheck

2023-02-20 14:11 UTC, fedeci requested changes
Thanks @neo773! I left some comments, I'll wait for a feedback!

2023-02-20 14:11 UTC, fedeci commented on src/leaf.ts
> +  description: "",
```suggestion
  description: "Create and interact with your leaf projects",
```

2023-02-20 14:11 UTC, fedeci commented on src/leaf.ts
> +    },
These are two different options, one opposite of the other and must be listed separately:
```suggestion
    {
      name: "--ansi",
      description: "Force ANSI output",
      exclusiveOn: ["--no-ansi"],
    },
    {
      name: "--no-ansi",
      description: "Disable ANSI output",
      exclusiveOn: ["--ansi"],
    },
```

2023-02-20 14:11 UTC, fedeci commented on src/leaf.ts
> +      },
If you want this may be improved with a custom generator.

2023-02-20 14:11 UTC, fedeci commented on src/leaf.ts
> +    },
This gets run with the following command, is it intended? `leaf test test:setup`

2023-04-05 16:41 UTC, fedeci commented
@neo773 I am reopening and committing this one, thanks for the work!

2023-04-05 16:54 UTC, fedeci commented
See [3604f26](https://github.com/withfig/autocomplete/commit/3604f26df60b2a3d800704bafdbbc96710833be0)

2023-04-05 16:55 UTC, closed without merging