s3 ls initial commit
withfig/autocomplete pull request #187
Opened 2021-05-07 18:37 UTC by nagypeterjob

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2021-05-12 17:21 UTC, QuiiBz requested changes

2021-05-12 17:21 UTC, QuiiBz commented on dev/aws/s3.ts
> +
I would prefer camel case for variable names.

2021-05-12 17:21 UTC, QuiiBz commented on dev/aws/s3.ts
> +      var lastSlashIndex = whatHasUserTyped.lastIndexOf("/");
Please use `const` or `let` (when you need to re-assign it later) for variables.

2021-05-12 17:21 UTC, QuiiBz commented on dev/aws/s3.ts
> +        return false;
Can be simplified:
```suggestion
        return oldToken.startsWith(_prefix_file));
```

2021-05-12 17:21 UTC, QuiiBz commented on dev/aws/s3.ts
> +      } else return false;
Same:
```suggestion
      return newToken.lastIndexOf("/") !== oldToken.lastIndexOf("/"));
```

2021-05-12 17:21 UTC, QuiiBz commented on dev/aws/s3.ts
> +    },
This script is repeated 3 times and is almost identical. I believe we can simplify and make it more generic.

2021-05-12 17:21 UTC, QuiiBz commented on dev/aws/s3.ts
> +        return false;
Same:
```suggestion
        return oldToken.startsWith(_prefix_fileb));
```

2021-05-12 17:21 UTC, QuiiBz commented on dev/aws/s3.ts
> +      } else return false;
Same:
```suggestion
      return newToken.lastIndexOf("/") !== oldToken.lastIndexOf("/"));
```

2021-05-12 17:21 UTC, QuiiBz commented on dev/aws/s3.ts
> +    },
Looks like this function is also repeated few times, we should extract it and use it everywhere instead of copy/pasting.

2021-05-12 21:47 UTC, nagypeterjob commented
Hey @QuiiBz 

I do agree with most part of your review & I've addressed them where it made sense. Hope you will like it!

2021-05-21 17:07 UTC, cstrnt requested changes
Again, just a code review in terms of JS/TS Code, I have no clue about AWS 😆

2021-05-21 17:07 UTC, cstrnt commented on dev/aws/s3.ts
> +    } else folderPath = whatHasUserTyped.slice(0, lastSlashIndex + 1);
I would love to have some curly brackets here to create blocks and make the code more readable

2021-05-21 17:07 UTC, cstrnt commented on dev/aws/s3.ts
> +      else other_arr.push(elm);
same here! I'm really big on blocks 😆

2021-05-21 17:07 UTC, cstrnt commented on dev/aws/s3.ts
> +    if (!(item === "" || item === null || item === undefined)) {
You can actually do `item != null` which checks for null **and** undefined at the same time ;)

2021-05-21 17:07 UTC, cstrnt commented on dev/aws/s3.ts
> +const _prefixFileb = "fileb://";
This is just some personal preference but I like making actual `consts` in Uppercase like `PREFIX_S3` do mark them as global, unchangeable consts

2021-05-21 17:07 UTC, cstrnt commented on dev/aws/s3.ts
> +          if (parts[1] == "PRE") {
```suggestion
          if (parts[1] === "PRE") {
```

2021-05-21 17:07 UTC, cstrnt commented on dev/aws/s3.ts
> +            name: "string",
```suggestion
            name: "region",
```

2021-05-24 13:34 UTC, cstrnt commented on dev/aws/s3.ts
> +      ttl: 30000,
Same as the other PR with the top-level ttl :)

2021-06-29 16:41 UTC, QuiiBz approved these changes
Let's merge this big PR! Could you copy/paste the generators which are duplicated and reviewed in each AWS PR (#315, #297, #287, #244)?

2021-07-01 06:41 UTC, QuiiBz commented on dev/aws/s3.ts
> +// TODO: suggest available s3 endpoints
Is this todo completed?

2021-07-01 21:08 UTC, nagypeterjob commented on dev/aws/s3.ts
> +// TODO: suggest available s3 endpoints
no, probably would be overkill. I don't think its a blocker

2021-07-02 06:36 UTC, QuiiBz commented on dev/aws/s3.ts
> +// TODO: suggest available s3 endpoints
Alright, thanks!

2021-07-02 06:36 UTC, merged