feat(space): create `space` CLI spec
withfig/autocomplete pull request #1872
Opened 2023-02-28 13:25 UTC by BogDAAAMN

**What kind of change does this PR introduce?**

Create the specs for the [Deta Space CLI](https://github.com/deta/space-cli) at its latest commit [`aa93f14`](https://github.com/deta/space-cli/commit/aa93f1476e56268fab0c4444db1e6326feb8f59f). 

I just used the [Fig cobra integration](https://github.com/withfig/autocomplete-tools/tree/main/integrations/cobra) like this, all the fields and descriptions seemed in place: 

```
package cmd

import (
	cobracompletefig "github.com/withfig/autocomplete-tools/integrations/cobra"
)

func init() {
	rootCmd.AddCommand(cobracompletefig.CreateCompletionSpecCommand())
}
```

Pinging @rohanshiva @abdelhai @aavshr @BetaHuhn if you wanna review the spec or integrate the Cobra integration in the CLI for future releases ☺️ 

**Additional info**

![Space CLI working with Fig autocomplete](https://user-images.githubusercontent.com/22895284/221867129-767b36ae-13bb-4338-91d1-7429b0f298b9.png)

2023-02-28 13:27 UTC, BogDAAAMN commented
I have read the CLA Document and I hereby sign the CLA

2023-03-09 20:10 UTC, fedeci commented
> Pinging @rohanshiva @abdelhai @aavshr @BetaHuhn if you wanna review the spec or integrate the Cobra integration in the CLI for future releases ☺️

I am happy to provide support for this!

2023-03-09 20:16 UTC, fedeci requested changes
Thanks @BogDAAAMN! I left a some improvements to merge in then this can be merged.

2023-03-09 20:16 UTC, fedeci commented on src/space.ts
> +          args: { name: "dir", default: "./" },
@BogDAAAMN this can eventually be configured via cobra so that it gets autogenerated when the integration is run.
```suggestion
          args: { name: "dir", default: "./", template: "folders" },
```

2023-03-09 20:16 UTC, fedeci commented on src/space.ts
> +          args: { name: "dir", default: "./" },
```suggestion
          args: { name: "dir", default: "./", template: "folders" },
```

2023-03-09 20:16 UTC, fedeci commented on src/space.ts
> +          args: { name: "dir", default: "./" },
```suggestion
          args: { name: "dir", default: "./", template: "folders" },
```

2023-03-09 20:16 UTC, fedeci commented on src/space.ts
> +          args: { name: "dir", default: "./" },
```suggestion
          args: { name: "dir", default: "./", template: "folders" },
```

2023-03-09 20:16 UTC, fedeci commented on src/space.ts
> +          args: { name: "dir", default: "./" },
```suggestion
          args: { name: "dir", default: "./", template: "folders" },
```

2023-03-10 11:23 UTC, BogDAAAMN commented
Thank you @fedeci!! Completely forgot about the templates 🤦🏼 Is there an easy way to configure this in Cobra?

There is an update to the Space CLI already. I will commit your suggestions, add in the new commands 🙌🏼

2023-03-21 12:37 UTC, BogDAAAMN commented
Hey @fedeci @pomdtr I updated the specs to add latest Space CLI changes and the dir templates.

2023-03-22 14:45 UTC, pomdtr commented
Thanks @BogDAAAMN ! Since we are using cobra in the `space` cli, feel free to add a pr to autogenerate the fig specs!

2023-04-14 17:13 UTC, fedeci approved these changes

2023-04-14 17:13 UTC, fedeci commented
Thanks!

2023-04-14 17:13 UTC, merged