add ftc completion
withfig/autocomplete pull request #1883
Opened 2023-03-12 09:17 UTC by el2zay

2023-03-12 09:23 UTC, el2zay commented
I have read the CLA Document and I hereby sign the CLA

2023-03-12 09:25 UTC, AlanSyue commented on README.md
> -<p align="center">
Why clear the content of the README file 🤔

2023-03-12 09:26 UTC, el2zay commented on README.md
> -<p align="center">
I didn't touch it

2023-03-12 14:30 UTC, AlanSyue commented on .vscode/settings.json
> +  "[typescript]": {
The project currently has a unified formatter. May I ask what is the purpose of adding this line? Thanks!

2023-03-12 14:35 UTC, el2zay commented on .vscode/settings.json
> +  "[typescript]": {
I think it was inserted automatically by a plugin, I didn't touch anything except my own file.  I delete the modification?

2023-03-12 14:38 UTC, AlanSyue commented on .vscode/settings.json
> +  "[typescript]": {
OK, I think there's no need to make this change. Thank you.

2023-03-12 14:41 UTC, AlanSyue commented
I couldn't find any documentation related to the "ftc" command. Would it be possible for you to provide it if it's convenient?

2023-03-13 07:24 UTC, fedeci commented
Also, docs should be standardized in US english language, can you translate them please?

2023-03-13 17:17 UTC, el2zay commented
Actually I have not made any documentation on freetranscli because it is not yet completely finished. In the autocompletion everything is in French because the service can only be used by French people for the moment (because the API used is the one of a French operator). 

If you want a documentation of ftc and it's necessary tell me.

2023-03-15 18:08 UTC, fedeci requested changes
Here are some requested changes to address before merging this, I am still not 100% sold on the French descriptions.

2023-03-15 18:08 UTC, fedeci commented on src/ftc.ts
> +  description: "",
Here a description should be provided:
```suggestion
  description: "",
```

2023-03-15 18:08 UTC, fedeci commented on src/ftc.ts
> +const completionSpec: Fig.Spec = {
@el2zay I would like to get a reference url to the cli tool download page/github repo/website as a comment on the top of this file.

2023-03-15 18:08 UTC, fedeci commented on .vscode/settings.json
> +  "[typescript]": {
Friendly ping on this :)

2023-03-16 19:15 UTC, el2zay reviewed
I think everything is good

2023-03-19 15:46 UTC, el2zay commented
Why ?

2023-03-25 14:51 UTC, closed without merging