feat: add snaplet command completion spec
withfig/autocomplete pull request #1887
Opened 2023-03-20 07:51 UTC by avallete

Hey there !

Snaplet is a tool to help user deal with their database: https://www.snaplet.dev/

I love Fig so I though I want this tool to have those superpower as well !

2023-04-14 16:30 UTC, fedeci requested changes
Thanks @avallete! I left a couple notes to fix before merging, sorry for the late review!

2023-04-14 16:30 UTC, fedeci commented on src/snaplet.ts
> +  description: "",
Can you please provide a description for the tool?

2023-04-14 16:30 UTC, fedeci commented on src/snaplet.ts
> +    name: ["--help", "-h"],
With this property the option becomes automatically available to all subcommands. In such way you don't have to worry about adding `options: [...commonCommandsOptions]`. Can you please remove those?
```suggestion
    name: ["--help", "-h"],
    isPersistent: true,
```

2023-04-14 16:30 UTC, fedeci commented on src/snaplet.ts
> +    description: "Show version number",
```suggestion
    description: "Show version number",
    isPersistent: true,
```

2023-04-15 11:39 UTC, avallete commented on src/snaplet.ts
> +    name: ["--help", "-h"],
Oh nice ! I was sure they were a better way to do it. Thank's for the suggestion !

2023-04-15 12:39 UTC, avallete commented on src/snaplet.ts
> +  description: "",
Done 👍

2023-04-15 12:43 UTC, avallete commented
> Thanks @avallete! I left a couple notes to fix before merging, sorry for the late review!

Hey there! No worries, I see the number of PRs on the repo 😂. I can imagine how busy things must be, so I truly appreciate you taking the time to review my contribution and for the insightful suggestions you provided!

I've made the necessary changes based on your feedback.

2023-04-22 06:44 UTC, fedeci approved these changes
Thanks!

2023-04-22 06:45 UTC, fedeci commented on src/snaplet.ts
> +          isRequired: false,
```suggestion
```

2023-04-22 07:03 UTC, merged