[WIP] feat: Add sudo spec
withfig/autocomplete pull request #189
Opened 2021-05-08 08:23 UTC by CastaChick

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Add spec for `sudo` 

**What is the current behavior? (You can also link to an open issue here)**
#176 

**What is the new behavior (if this is a feature change)?**
Show autocompletes after `sudo`

<img width="386" alt="スクリーンショット 2021-05-08 17 22 19" src="https://user-images.githubusercontent.com/44726163/117532332-f4a81e80-b021-11eb-8e7a-23feeb3e65ee.png">

**Additional info:**

2021-05-08 13:43 UTC, CastaChick commented
This is my first contribution to Fig ✨
If I should fix something, I'm willing to fix it 😃

2021-05-08 20:16 UTC, cstrnt requested changes
Hey there, thank you very much for contributing! This is a really nice PR which will make our autocompletion even better 😊 I left some comments which are just some minor improvements.

2021-05-08 20:16 UTC, cstrnt commented on dev/sudo.ts
> +  subcommands: [],
this can safely be removed 😊

2021-05-08 20:16 UTC, cstrnt commented on dev/sudo.ts
> +      name: ["-g"],
I think it would be awesome if you could also add the long variant (--group) here

2021-05-08 20:16 UTC, cstrnt commented on dev/sudo.ts
> +      name: ["-h"],
```suggestion
      name: ["-h", "--help"],
```

2021-05-08 20:16 UTC, cstrnt commented on dev/sudo.ts
> +      name: ["-g"],
```suggestion
      name: ["-g", "--group"],
```

2021-05-08 20:16 UTC, cstrnt commented on dev/sudo.ts
> +      name: ["-u"],
```suggestion
      name: ["-u", "--other-user"],
```

2021-05-09 03:02 UTC, CastaChick commented on dev/sudo.ts
> +      name: ["-u"],
Is it suitable `--user` instead of `--other-user`?
I fixed it by adding `--user`😃

2021-05-09 03:05 UTC, CastaChick commented
@cstrnt Thanks for your review!
I've fixed proposed changes 👍

2021-05-10 08:55 UTC, cstrnt approved these changes
Thank you very much for your contribution!

2021-05-10 12:24 UTC, QuiiBz approved these changes
Thanks for your first contribution!

2021-05-10 12:24 UTC, merged