feat: add `aws-vault` spec
withfig/autocomplete pull request #1892
Opened 2023-03-25 07:08 UTC by swallowtail62

This PR adds [aws-vault](https://github.com/99designs/aws-vault) completion spec.

2023-03-25 07:11 UTC, swallowtail62 commented
I have read the CLA Document and I hereby sign the CLA

2023-03-25 09:46 UTC, fedeci requested changes
Thanks @swallowtail62! I left a couple minor issues to solve but the spec looks good overall.

2023-03-25 09:46 UTC, fedeci commented on src/aws-vault.ts
> +const profilesGeneratro: Fig.Generator = {
typo:
```suggestion
const profilesGenerator: Fig.Generator = {
```

2023-03-25 09:46 UTC, fedeci commented on src/aws-vault.ts
> +        suggestions: helpSuggestions,
This is a nice sugar we provide :)
```suggestion
        template: "help",
```

2023-03-25 09:52 UTC, swallowtail62 commented on src/aws-vault.ts
> +const profilesGeneratro: Fig.Generator = {
Oops, sorry. Thanks for pointing that out!

2023-03-25 09:59 UTC, swallowtail62 commented on src/aws-vault.ts
> +        suggestions: helpSuggestions,
@fedeci 
Thanks! I fixed it, check it out.

2023-03-26 19:38 UTC, fedeci approved these changes

2023-03-26 19:38 UTC, fedeci commented
Thanks @swallowtail62!

2023-03-26 19:40 UTC, merged