aws iam initial
withfig/autocomplete pull request #191
Opened 2021-05-09 10:05 UTC by nagypeterjob

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

- [x] add-client-id-to-open-id-connect-provider
- [x] add-role-to-instance-profile
- [x] add-user-to-group
- [x] attach-group-policy
- [x] attach-role-policy
- [x] attach-user-policy
- [x] change-password
- [x] create-access-key
- [x] create-account-alias
- [x] create-group
- [x] create-instance-profile
- [x] create-login-profile
- [x] create-open-id-connect-provider
- [x] create-policy
- [x] create-policy-version
- [x] create-role
- [x] create-saml-provider
- [ ] create-service-linked-role
- [ ] create-service-specific-credential
- [ ] create-user
- [ ] create-virtual-mfa-device
- [ ] deactivate-mfa-device
- [ ] delete-access-key
- [ ] delete-account-alias
- [ ] delete-account-password-policy
- [ ] delete-group
- [ ] delete-group-policy
- [ ] delete-instance-profile
- [ ] delete-login-profile
- [ ] delete-open-id-connect-provider
- [ ] delete-policy
- [ ] delete-policy-version
- [ ] delete-role
- [ ] delete-role-permissions-boundary
- [ ] delete-role-policy
- [ ] delete-saml-provider
- [ ] delete-server-certificate
- [ ] delete-service-linked-role
- [ ] delete-service-specific-credential
- [ ] delete-signing-certificate
- [ ] delete-ssh-public-key
- [ ] delete-user
- [ ] delete-user-permissions-boundary
- [ ] delete-user-policy
- [ ] delete-virtual-mfa-device
- [ ] detach-group-policy
- [ ] detach-role-policy
- [ ] detach-user-policy
- [ ] enable-mfa-device
- [ ] generate-credential-report
- [ ] generate-organizations-access-report
- [ ] generate-service-last-accessed-details
- [ ] get-access-key-last-used
- [ ] get-account-authorization-details
- [ ] get-account-password-policy
- [ ] get-account-summary
- [ ] get-context-keys-for-custom-policy
- [ ] get-context-keys-for-principal-policy
- [ ] get-credential-report
- [ ] get-group
- [ ] get-group-policy
- [ ] get-instance-profile
- [ ] get-login-profile
- [ ] get-open-id-connect-provider
- [ ] get-organizations-access-report
- [ ] get-policy
- [ ] get-policy-version
- [ ] get-role
- [ ] get-role-policy
- [ ] get-saml-provider
- [ ] get-server-certificate
- [ ] get-service-last-accessed-details
- [ ] get-service-last-accessed-details-with-entities
- [ ] get-service-linked-role-deletion-status
- [ ] get-ssh-public-key
- [ ] get-user
- [ ] get-user-policy
- [ ] list-access-keys
- [ ] list-account-aliases
- [ ] list-attached-group-policies
- [ ] list-attached-role-policies
- [ ] list-attached-user-policies
- [ ] list-entities-for-policy
- [ ] list-group-policies
- [ ] list-groups
- [ ] list-groups-for-user
- [ ] list-instance-profile-tags
- [ ] list-instance-profiles
- [ ] list-instance-profiles-for-role
- [ ] list-mfa-device-tags
- [ ] list-mfa-devices
- [ ] list-open-id-connect-provider-tags
- [ ] list-open-id-connect-providers
- [ ] list-policies
- [ ] list-policies-granting-service-access
- [ ] list-policy-tags
- [ ] list-policy-versions
- [ ] list-role-policies
- [ ] list-role-tags
- [ ] list-roles
- [ ] list-saml-provider-tags
- [ ] list-saml-providers
- [ ] list-server-certificate-tags
- [ ] list-server-certificates
- [ ] list-service-specific-credentials
- [ ] list-signing-certificates
- [ ] list-ssh-public-keys
- [ ] list-user-policies
- [ ] list-user-tags
- [ ] list-users
- [ ] list-virtual-mfa-devices
- [ ] put-group-policy
- [ ] put-role-permissions-boundary
- [ ] put-role-policy
- [ ] put-user-permissions-boundary
- [ ] put-user-policy
- [ ] remove-client-id-from-open-id-connect-provider
- [ ] remove-role-from-instance-profile
- [ ] remove-user-from-group
- [ ] reset-service-specific-credential
- [ ] resync-mfa-device
- [ ] set-default-policy-version
- [ ] set-security-token-service-preferences
- [ ] simulate-custom-policy
- [ ] simulate-principal-policy
- [ ] tag-instance-profile
- [ ] tag-mfa-device
- [ ] tag-open-id-connect-provider
- [ ] tag-policy
- [ ] tag-role
- [ ] tag-saml-provider
- [ ] tag-server-certificate
- [ ] tag-user
- [ ] untag-instance-profile
- [ ] untag-mfa-device
- [ ] untag-open-id-connect-provider
- [ ] untag-policy
- [ ] untag-role
- [ ] untag-saml-provider
- [ ] untag-server-certificate
- [ ] untag-user
- [ ] update-access-key
- [ ] update-account-password-policy
- [ ] update-assume-role-policy
- [ ] update-group
- [ ] update-login-profile
- [ ] update-open-id-connect-provider-thumbprint
- [ ] update-role
- [ ] update-role-description
- [ ] update-saml-provider
- [ ] update-server-certificate
- [ ] update-service-specific-credential
- [ ] update-signing-certificate
- [ ] update-ssh-public-key
- [ ] update-user
- [ ] upload-server-certificate
- [ ] upload-signing-certificate
- [ ] upload-ssh-public-key
- [ ] wait

2021-05-20 07:19 UTC, cstrnt requested changes
I never used AWS therefore this is just a code-side review from me :)

2021-05-20 07:19 UTC, cstrnt commented on dev/aws/iam.ts
> +import { FileTextChanges } from "typescript";
We don't need this

2021-05-20 07:19 UTC, cstrnt commented on dev/aws/iam.ts
> +    const merged = Array.prototype.concat.apply([], list) as Fig.Suggestion[];
What does this line do? I think we should either add a comment here or use more human-readable code. I think you might be looking for `.flat()` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat)

2021-05-20 07:19 UTC, cstrnt commented on dev/aws/iam.ts
>    var whatHasUserTyped = tokens[tokens.length - 1];
Could you please use `const` over `var`

2021-05-20 08:02 UTC, nagypeterjob commented on dev/aws/iam.ts
>    var whatHasUserTyped = tokens[tokens.length - 1];
done

2021-05-20 08:02 UTC, nagypeterjob commented on dev/aws/iam.ts
> +    const merged = Array.prototype.concat.apply([], list) as Fig.Suggestion[];
thanks, fixed

2021-05-20 08:02 UTC, nagypeterjob commented on dev/aws/iam.ts
> +import { FileTextChanges } from "typescript";
hmm you have checked some outdated commit :D

2021-05-25 11:20 UTC, cstrnt requested changes

2021-05-25 11:20 UTC, cstrnt commented on dev/aws/iam.ts
> +  }
Just a tiny change, but reverting the if allows us to omit  the else block and make the code more readable imho
```suggestion
  if (!whatHasUserTyped.startsWith(prefix)) {
     return `echo '${prefix}'`;
  } 
  whatHasUserTyped = whatHasUserTyped.slice(prefix.length);
```

2021-05-25 11:20 UTC, cstrnt commented on dev/aws/iam.ts
> +  const final_array = [];
I think @QuiiBz mentioned it once: We really don't have any variable naming conventions, but in the JS/TS World we mostly use camelCase for variables

2021-05-25 11:20 UTC, cstrnt commented on dev/aws/iam.ts
> +    });
```ts
    return policies.map((elm) => childKey ? elm[childKey] : elm)
```

2021-05-25 11:20 UTC, cstrnt commented on dev/aws/iam.ts
> +    });
possible readability improvement

2021-05-25 11:20 UTC, cstrnt commented on dev/aws/iam.ts
> +    });
see above

2021-05-25 11:20 UTC, cstrnt commented on dev/aws/iam.ts
> +    return list.flat();
Does this need to run sequentially? If not we could use `Promise.all` to run them in parallel which could be a performance gain

2021-05-25 11:20 UTC, cstrnt commented on dev/aws/iam.ts
> +      ttl: 30000,
Same as in the other Spec. I think we should create a const for the cache TTL

2021-06-29 07:26 UTC, QuiiBz commented
Hello, is this PR still in WIP?

2021-06-29 08:25 UTC, nagypeterjob commented
> Hello, is this PR still in WIP?

Not anymore, I just cannot assign / modify labels

2021-06-29 16:45 UTC, QuiiBz commented
> 
> Not anymore, I just cannot assign / modify labels

Alright thanks, apologize for the delay on this PR. We're going to merge this asap!

2021-06-29 16:47 UTC, QuiiBz approved these changes
Such a huge PR, thank you so much! This is going to be really helpful

2021-07-01 16:34 UTC, merged