feat: add yomo completion spec
withfig/autocomplete pull request #1916
Opened 2023-04-13 13:28 UTC by fanweixiao

Hi Fig!

YoMo is an open source Streaming Serverless Framework to help developers with their Geo-distributed Applications. `yomo` is the CLI tool. Our community members love Fig so we want to Fig can help our developers too!

More about YoMo can be found here: https://github.com/yomorun/yomo

2023-04-13 13:29 UTC, fanweixiao commented
I have read the CLA Document and I hereby sign the CLA

2023-04-14 16:34 UTC, fedeci requested changes
Thanks @fanweixiao! There are a couple improvements it would be great to have here, can you commit them?

2023-04-14 16:34 UTC, fedeci commented on src/yomo.ts
> +        description: "The .go file to build",
See https://fig.io/docs/reference/generator/prebuilt-generators#figautocomplete-generators
```suggestion
        description: "The .go file to build",
        generators: filepaths({ extensions: ["go"] }),
```

2023-04-14 16:34 UTC, fedeci commented on src/yomo.ts
> +const completionSpec: Fig.Spec = {
```suggestion
import { filepaths } from "@fig/autocomplete-generators"

const completionSpec: Fig.Spec = {
```

2023-04-14 16:34 UTC, fedeci commented on src/yomo.ts
> +          description: "Custom go.mod filepath",
```suggestion
          description: "Custom go.mod filepath",
          args: {
            name: "module",
            generators: filepaths({ extensions: ["mod"] }),
          },
```

2023-04-14 16:34 UTC, fedeci commented on src/yomo.ts
> +        description: "The .wasm file to run",
```suggestion
        description: "The .wasm file to run",
        generators: filepaths({ extensions: ["wasm"] }),
```

2023-04-15 01:14 UTC, fanweixiao commented on src/yomo.ts
> +const completionSpec: Fig.Spec = {
oh, thanks @fedeci

2023-04-17 15:06 UTC, fanweixiao commented
Thanks @fedeci

2023-04-17 15:07 UTC, fedeci commented
I am merging the PR as soon as the checks are green!

2023-04-17 15:07 UTC, fedeci commented
@fanweixiao, can you run `npm run lint:fix` and push the changes please?

2023-04-17 15:11 UTC, fanweixiao commented
@fedeci I‘ve fixed this: 

```bash
$ npx prettier --check 'src/yomo.ts' --parser typescript
Checking formatting...
All matched files use Prettier code style!
```

2023-04-17 15:12 UTC, merged