feat(ncu): add support for npm-check-updates
withfig/autocomplete pull request #1927
Opened 2023-04-20 09:26 UTC by ikosta

Adds support for https://www.npmjs.com/package/npm-check-updates aka `ncu`

2023-04-22 07:03 UTC, fedeci requested changes
Thanks @ikosta! I left some notes to fix before merging. I am wondering why you have decided to implement the the options in a separate object and not directly in the spec? (Just curiosity it is fine to me)

2023-04-22 07:16 UTC, ikosta commented
> Thanks @ikosta! I left some notes to fix before merging. I am wondering why you have decided to implement the the options in a separate object and not directly in the spec? (Just curiosity it is fine to me)

I think it's easier to maintain if there are changes in the cli and new functionality uses same options.

Since this spec has no subcommands it seems overpowered but only future will proof we wrong.

Thanks for the comments I will check them out.

2023-04-23 06:25 UTC, ikosta commented
@fedeci just checked all the requested changes and these make completely sense. Thanks!

2023-04-23 09:34 UTC, fedeci approved these changes

2023-04-23 09:34 UTC, merged