"feat: add mising flags to k6 completion spec issue  #1921"
withfig/autocomplete pull request #1931
Opened 2023-04-23 10:35 UTC by oscarsjlh

Fixing issue  #1921 missing version flag, along that version missing, saw three more that were missing and added them.

-  Scale
-  Stats
- Status 
- Version

I didn't make this one from scratch, just followed the pattern that was created before.
Hope everything is correct, any issues, please let me know.

2023-04-23 10:42 UTC, oscarsjlh commented
I have read the CLA Document and I hereby sign the CLA

2023-04-23 10:55 UTC, oscarsjlh commented
recheck

2023-04-23 11:20 UTC, fedeci requested changes
Thanks! I left some comments to fix before merging the PR!

2023-04-23 11:20 UTC, fedeci commented on src/k6.ts
> +
```suggestion
```

2023-04-23 11:20 UTC, fedeci commented on src/k6.ts
> +      },
```suggestion
```

2023-04-23 11:20 UTC, fedeci commented on src/k6.ts
> +      },
```suggestion
```

2023-04-23 11:20 UTC, fedeci commented on src/k6.ts
> +      },
```suggestion
```

2023-04-23 11:20 UTC, fedeci commented on src/k6.ts
> +      },
```suggestion
```

2023-04-23 11:20 UTC, fedeci commented on src/k6.ts
> +          description: "Max avalible virtual users",
```suggestion
          description: "Max available virtual users",
```

2023-04-23 11:20 UTC, fedeci commented on src/k6.ts
> +            description: "Max avalible virtual users",
```suggestion
            description: "Max available virtual users",
```

2023-04-23 11:34 UTC, oscarsjlh commented
I saw the changes and saw that you removed:
```

 args: {
        name: "x",
        description: "description",
      },

```
But in that file all the previous commands follow that pattern, is that wrong?, if so, should I remove it from other commands that have that pattern?
```

{
  name: "", 
  description: "",
  args: {
   name: "", 
   description: "",
   },
  subcommnads: [
  "if needed"
],
}
```` 

```

2023-04-24 11:13 UTC, fedeci requested changes

2023-04-24 11:13 UTC, fedeci commented on src/k6.ts
> +      subcommands: [
I missed this one 🤦‍♂️ 
```suggestion
      options: [
```

2023-04-24 11:13 UTC, fedeci commented on src/k6.ts
> +      subcommands: [
```suggestion
      options: [
```

2023-04-24 11:13 UTC, fedeci commented on src/k6.ts
> +      subcommands: [
```suggestion
      options: [
```

2023-04-24 11:13 UTC, fedeci commented on src/k6.ts
> +      subcommands: [
```suggestion
      options: [
```

2023-04-24 11:17 UTC, fedeci commented
> I saw the changes and saw that you removed:
> 
> ```
> 
> 
> 
>  args: {
> 
>         name: "x",
> 
>         description: "description",
> 
>       },
> 
> 
> 
> ```
> 
> But in that file all the previous commands follow that pattern, is that wrong?, if so, should I remove it from other commands that have that pattern?
> 
> ```
> 
> 
> 
> {
> 
>   name: "", 
> 
>   description: "",
> 
>   args: {
> 
>    name: "", 
> 
>    description: "",
> 
>    },
> 
>   subcommnads: [
> 
>   "if needed"
> 
> ],
> 
> }
> 
> ```` 
> 
> 
> 
> ```

It is not wrong for a command to have args, but it was wrong for the commands added in this PR to have them. I am not sure if the commands already present should have args or not, but this can be easily checked via the man pages of the k6 cli.

2023-04-24 20:12 UTC, fedeci approved these changes

2023-04-24 20:12 UTC, merged