Added support for SuiteCloud CLI
withfig/autocomplete pull request #1935
Opened 2023-04-26 17:49 UTC by felixdivall

Used for NetSuite development with SDF

2023-04-26 18:15 UTC, fedeci commented
@felixdivall can you please sign the CLA?

2023-04-26 18:21 UTC, felixdivall commented
Yes. Will do either later or tomorrow


Vänliga hälsningar/ Best regards

FELIX DIVALL

***@***.******@***.***>

+46 735 04 15 62





***@***.***

www.suitespot.se<http://www.suitespot.se/>

<https://aka.ms/o0ukef>
________________________________
From: Federico Ciardi ***@***.***>
Sent: Wednesday, April 26, 2023 8:15:21 PM
To: withfig/autocomplete ***@***.***>
Cc: Felix Divall ***@***.***>; Mention ***@***.***>
Subject: Re: [withfig/autocomplete] feat: add support for SuiteCloud CLI (PR #1935)


@felixdivall<https://github.com/felixdivall> can you please sign the CLA?

—
Reply to this email directly, view it on GitHub<https://github.com/withfig/autocomplete/pull/1935#issuecomment-1523853208>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AZRDLFV4WFEVMP4JL3GHIGLXDFQ3TANCNFSM6AAAAAAXMYUVTY>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-04-26 19:30 UTC, fedeci requested changes
Thanks @felixdivall! I found a lot of missing args and I added them as suggestions, you can just review my suggestions and commit them. Also I left a couple notes on which I would like to get some feedback before merging this PR!

2023-04-26 19:30 UTC, fedeci commented on src/suitecloud.ts
> +            "Specifies the NetSuite domain of the account you want to use. You only need to specify the NetSuite domain if you are not using a production account",
Is this description correct?

2023-04-26 21:01 UTC, felixdivall commented
I have read the CLA Document and I hereby sign the CLA

2023-04-26 21:13 UTC, felixdivall commented on src/suitecloud.ts
> +            "Specifies the NetSuite domain of the account you want to use. You only need to specify the NetSuite domain if you are not using a production account",
Yes. But I see how it can be confusing. 
<img width="1207" alt="SCR-20230426-w8g" src="https://user-images.githubusercontent.com/107099542/234704079-fa767c07-3fd5-4817-b337-05f77bec1c18.png">

2023-04-26 21:21 UTC, felixdivall commented
Thanks for the feedback! I got Fig today, so haven't played around too much with it yet. Great get this response and fix my errors. I've commited most of your suggestions.

2023-04-27 15:55 UTC, fedeci commented on src/suitecloud.ts
> +          name: "--account",
Ping :)

2023-04-27 15:58 UTC, fedeci commented
I missed some comma or some newline so prettier is complaining, can you please run `npm run lint:fix` and push the changes?

2023-04-27 19:34 UTC, fedeci approved these changes

2023-04-27 19:34 UTC, fedeci commented
Thanks!

2023-05-10 09:11 UTC, felixdivall commented
When will this be merged?

2023-05-10 20:01 UTC, fedeci commented
Now, I was waiting for the CI and forgot to push this, sorry!

2023-05-10 20:01 UTC, merged