Change task generator to get nested and root tasks
withfig/autocomplete pull request #1964
Opened 2023-05-13 01:29 UTC by ddanielcruzz

Current Fig Generator doesn't work when having nested Taskfiles and also doesn't list root tasks. 

### Before

I have my Taskfiles split in different files, and reference them all in one file at the root of my project, current autocompletion doesn't get the tasks in my root as nor the tasks until I get into the directory containing all my Taskfiles.  

https://github.com/withfig/autocomplete/assets/20308945/5bc2d32f-86db-48cf-8eef-4b552df91439

### After

My new approach works as expected with the root tasks while maintaining previous behavior

https://github.com/withfig/autocomplete/assets/20308945/f4661727-458c-42e0-9320-1b01c9382a1c

2023-05-13 01:32 UTC, ddanielcruzz commented
I have read the CLA Document and I hereby sign the CLA

2023-05-15 16:37 UTC, fedeci approved these changes
Thanks! LGTM. @AlanSyue, I've seen you wrote this spec, can you give me a feedback on whether context still matters when using `--list-all`? I am not an user of go-task but from what I have seen in the docs this spec should be good.

2023-05-16 02:01 UTC, AlanSyue commented
@fedeci Sorry, I haven't used `go-task` before. Last time, I only used linter to format this spec.

2023-05-16 04:57 UTC, fedeci commented
My bad, I've actually inspected the commit history , but the 5mins that elapsed between the inspection and the review were enough to make me forget who created and who edited it😅 @yoavbls you are the creator, any feedback on this?

2023-05-28 00:48 UTC, yoavbls requested changes
It looks good and indeed works with nested and root tasks!
I left a few comments. Let me know what you think 🙂

2023-05-28 00:48 UTC, yoavbls commented on src/task/go-task.ts
> +          icon: "🎯",
I found this icon a little bit wierd, what about using `"fig://icon?type=command"` instead to be aligned with all the other fig commands?
or use the `go-task` icon: `https://taskfile.dev/img/favicon.ico`

2023-05-28 00:48 UTC, yoavbls commented on src/task/go-task.ts
> +  script: "task -a",
Great! you can also add the `task -a` command to the completion spec

2023-05-28 00:48 UTC, yoavbls commented on src/task/go-task.ts
> +          description: description.join(" ") || "Task",
I know that nobody likes regex but becaue you're already using it for the name let me suggest this thing instead:

```typescript
const { name, description } = task.match(
  /\* (?<name>[\w\:\-]+): +(?<description>[\w\s]+)/
).groups;

return {
    name,
    description,
    ...
}
```

2023-05-28 00:48 UTC, yoavbls commented on src/task/go-task.ts
> +          description: description.join(" ") || "Task",
If you don't like the regex you can try this which is more clear in my opinion:

```typescript 
const [namePart, descriptionPart] = task.split(": ");
return {
    name: namePart.slice(2);
    description: descriptionPart.trim() || undefined;
    ...
}

```

2023-05-28 00:48 UTC, yoavbls commented on src/task/go-task.ts
> +          description: description.join(" ") || "Task",
Keep notice that in both cases when there isn't a description it returns undefined which is more correct than "Task" here. fig will display "No description" automatically

2023-05-31 07:45 UTC, fedeci commented on src/task/go-task.ts
> +  script: "task -a",
Yeah, it should be together with `--list-all`

2023-06-01 23:47 UTC, ddanielcruzz commented
@fedeci Sure, I'll do it tomorrow.

2023-06-02 17:04 UTC, ddanielcruzz commented on src/task/go-task.ts
> +          icon: "🎯",
Done, I went with `"fig://icon?type=command"`

2023-06-02 17:04 UTC, ddanielcruzz commented on src/task/go-task.ts
> +  script: "task -a",
Added!

2023-06-02 17:08 UTC, ddanielcruzz commented on src/task/go-task.ts
> +          description: description.join(" ") || "Task",
I ended up with this 
```ts
 const [name, description] = taskInfo.split(": ");

        return {
          name: name.replace(/:$/, ""),
          description: description?.trim(),
          icon: "fig://icon?type=command",
          priority: TASKS_PRIORITY,
        };
```

I kept the `replace` since the colon was present in root tasks

Left is the previous approach, right is the one you suggested, see how `formatwrite` still has a colon. 
<img width="493" alt="Screenshot 2023-06-02 at 10 55 04" src="https://github.com/withfig/autocomplete/assets/20308945/c6f4191f-4251-43bb-9ff6-362659a54792">

2023-06-02 22:21 UTC, yoavbls approved these changes
@ddanielcruzz  Looks good to me 🙂

2023-06-03 09:51 UTC, fedeci commented
Thanks!

2023-06-03 09:52 UTC, merged