docs: replace npm metions for yarn in contribute section
withfig/autocomplete pull request #1971
Opened 2023-05-15 22:03 UTC by ddanielcruzz

Since `yarn.lock` was introduced in this commit https://github.com/withfig/autocomplete/commit/aec6acad7d2c286ecf930dc4321c757353ae3b66

I think docs should be updated accordingly 😄

2023-05-15 22:51 UTC, mschrage approved these changes

2023-05-16 05:04 UTC, fedeci requested changes
Yarn v3 comes bundled with the repo in the `.yarn/` folder, users only need yarn@1 to access it

2023-05-16 05:04 UTC, fedeci commented on README.md
> +1. Make sure you have `yarn` v3 [installed](https://yarnpkg.com/getting-started/install), as that's the package manager used in this repo.
```suggestion
1. Make sure you have `yarn` [installed](https://classic.yarnpkg.com/lang/en/docs/install), as that's the package manager used in this repo. 
```

2023-05-16 05:04 UTC, fedeci commented on README.md
> +- Node and Yarn v3
```suggestion
- Node and Yarn
```

2023-05-16 16:15 UTC, ddanielcruzz commented
> Yarn v3 comes bundled with the repo in the `.yarn/` folder, users only need yarn@1 to access it

Cool, I applied your suggestions.

2023-05-17 18:30 UTC, fedeci approved these changes

2023-05-17 18:30 UTC, fedeci commented
Thanks!

2023-05-17 18:31 UTC, merged