wip: added sidekiq cli options
withfig/autocomplete pull request #1982
Opened 2023-05-22 17:43 UTC by omarluq

Hello everyone 😄 
I'm working on adding an autocompletion spec for [sidekiq](https://github.com/sidekiq)!
Feel free to pitch into this since sidqkiq doesn't have the best CLI docs out there :)

2023-05-22 20:28 UTC, omarluq commented
I have read the CLA Document and I hereby sign the CLA

2023-05-25 03:02 UTC, omarluq commented
Hey @fedeci @mschrage! if you guys are okay with this PR I would like to make a series of PRs adding some more missing rails cli commands that would be nice to have! thinking of adding [ViewComponents](https://github.com/ViewComponent/view_component)  generators next 🚀

2023-05-31 08:28 UTC, fedeci requested changes
Thanks @omarluq! It would be great to get some rails completions, I'll be happy to review those too!

2023-05-31 08:28 UTC, fedeci commented on src/sidekiq.ts
> +const completionSpec: Fig.Spec = {
```suggestion
import { filepaths } from "@fig/autocomplete-generators";

const completionSpec: Fig.Spec = {
```

2023-05-31 08:28 UTC, fedeci commented on src/sidekiq.ts
> +      args: { name: "PATH|DIR" },
```suggestion
      args: { name: "PATH|DIR", template: ["folders", "filepaths"] },
```

2023-05-31 15:24 UTC, omarluq commented
@fedeci Awesome, I implemented the changes you recommended! 
I also will have another PR up in a few days hopefully 😄

2023-06-02 10:43 UTC, fedeci approved these changes

2023-06-02 10:43 UTC, fedeci commented
Thanks!

2023-06-02 10:53 UTC, merged