feat: add `palera1n` completion spec
withfig/autocomplete pull request #1987
Opened 2023-05-27 21:21 UTC by itsnebulalol

palera1n is a jailbreaking tool for iOS/iPadOS 15.x-16.x arm64.

https://github.com/palera1n/palera1n

2023-05-27 22:03 UTC, itsnebulalol commented
I have read the CLA Document and I hereby sign the CLA

2023-05-31 07:54 UTC, fedeci requested changes
Thanks @itsnebulalol! I left a couple suggestions that would be great to have committed before shipping this PR.

2023-05-31 07:54 UTC, fedeci commented on src/palera1n.ts
> +      args: { name: "FILE" },
Can you make this change for all the args that has a FILE type?
```suggestion
      args: { name: "FILE", suggestions: "filepaths" },
```

2023-05-31 07:54 UTC, fedeci commented on src/palera1n.ts
> +      name: ["--version", ""],
```suggestion
      name: "--version",
```

2023-05-31 07:54 UTC, fedeci commented on src/palera1n.ts
> +      name: ["--force-revert", ""],
```suggestion
      name: "--force-revert",
```

2023-06-02 10:57 UTC, fedeci approved these changes

2023-06-02 10:57 UTC, fedeci commented
Thanks @itsnebulalol!

2023-06-02 11:04 UTC, merged