Feat/add poetry spec
withfig/autocomplete pull request #201
Opened 2021-05-15 15:02 UTC by CastaChick

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature

**What is the current behavior? (You can also link to an open issue here)**
no spec for poetry

**What is the new behavior (if this is a feature change)?**
add new spec for poetry

**Additional info:**
poetry is package manager for Python

2021-05-15 15:23 UTC, QuiiBz approved these changes
Thanks for this contribution! (Weird GitHub bug for the last PR, it's resolved now)

2021-05-16 14:57 UTC, cstrnt requested changes
Thank you very much for your contribution

2021-05-16 14:57 UTC, cstrnt commented on dev/poetry.ts
> +      description: "Debug various elements of Peotry",
typo

2021-05-16 14:57 UTC, cstrnt commented on dev/poetry.ts
> +            suggestions: ["requirements.txt"],
I think rather than having this suggestion, I would use `template: filepaths` to suggest files

2021-05-17 14:49 UTC, CastaChick commented
Thank you for your review! I fixed them☺️

2021-05-17 15:08 UTC, QuiiBz commented
> Today, when I run `npm run build`, the output file is differ from the previous one. Is it OK?

Looks like it only affects spacing, it looks OK to me.

2021-05-17 18:08 UTC, cstrnt approved these changes
Well done :)

2021-05-17 18:37 UTC, merged