BOSH CLI Introduction
withfig/autocomplete pull request #202
Opened 2021-05-16 08:33 UTC by hjaffan

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
This introduces the BOSH cli to the mix of commands that are known to autocomplete 
**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**
BOSH CLI auto complete
**Additional info:**

2021-05-16 14:22 UTC, cstrnt requested changes
Hey there, thank you very much for contributing :) Just a little side-note: the `name` prop should **never** end with an `=`, because Fig takes care of this internally

2021-05-17 04:22 UTC, hjaffan commented on dev/bosh.ts
> +import { descriptionRule } from "danger/distribution/commands/init/default-dangerfile";
Removed it in the Updated Commit

2021-05-17 04:23 UTC, hjaffan commented on dev/bosh.ts
> +var deployments = {
Resolved in updated PR

2021-05-17 04:23 UTC, hjaffan commented on dev/bosh.ts
> +      description: "Filter to show only given column(s)",
resovled

2021-05-17 04:24 UTC, hjaffan commented on dev/bosh.ts
> +      name: ["--config="],
It takes a file path currently.

2021-05-17 06:45 UTC, QuiiBz reviewed
Thanks for your contribution. Could you run `npm run build` to generate the needed JS spec file, and push it?

2021-05-17 06:45 UTC, QuiiBz commented on dev/bosh.ts
> +      name: ["--version"],
You can set a plain string instead of an array since there is only one value. Same for each underneath.

2021-05-17 07:13 UTC, cstrnt commented on dev/bosh.ts
> +      name: ["--config="],
That's good! This means adding an empty arg object in Fig if you are lazy or adding `args: { template: "filePaths" }`which will make Fig display suggestions for files

2021-05-22 13:45 UTC, cstrnt commented
Closing this in favor of #218

2021-05-22 13:45 UTC, closed without merging