[TMUX] Add Tmux spec
withfig/autocomplete pull request #207
Opened 2021-05-19 06:50 UTC by QuiiBz

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
No spec for `tmux` cli

**What is the new behavior (if this is a feature change)?**
Add a spec for `tmux`

**Additional info:**

2021-05-22 14:25 UTC, cstrnt commented
@QuiiBz is this still in Draft?

2021-05-22 14:36 UTC, QuiiBz commented
Yes, I didn't push yet my local commits. The `tmux `spec has tons of subcommand so this will take a little longer than expected.

2021-05-22 14:39 UTC, cstrnt commented
No worries, take your time, Tom 😊

2021-05-31 06:46 UTC, QuiiBz commented
Ready for a review!

2021-06-01 06:44 UTC, cstrnt requested changes
What a big PR!

2021-06-05 08:44 UTC, QuiiBz commented
Could we get this merged? GitHub marked few comments in the above review as not outdated, but the changes have been made underneath.

2021-06-07 08:46 UTC, cstrnt requested changes

2021-06-07 08:46 UTC, cstrnt commented on dev/tmux.ts
> +          description: "THe key table to use",
```suggestion
          description: "The key table to use",
```

2021-06-07 08:46 UTC, cstrnt commented on dev/tmux.ts
> +      description: "Wait for an event or trigger it",
This should take an argument, right?

2021-06-07 08:46 UTC, cstrnt commented on dev/tmux.ts
> +      name: ["unbind", "unbind-key"],
This should take an argument as well

2021-06-10 17:21 UTC, cstrnt approved these changes
LGTM

2021-06-10 17:21 UTC, merged