Fill out completion spec for code (VS Code)
withfig/autocomplete pull request #211
Opened 2021-05-19 13:05 UTC by Tyriar

This implements the whole spec for `code` based on `code --help`

Fixes #210

2021-05-19 14:30 UTC, QuiiBz reviewed
Thanks for your contribution!

2021-05-19 14:30 UTC, QuiiBz commented on dev/code.ts
> +      },
I think we should add `name` and `description` to all arguments, to get better feedback in the autocomplete box. Same for all other `args` objects.

2021-05-19 18:24 UTC, cstrnt requested changes
Hey there 👋 
thank you very much for you contribution :) I just left some comments, but apart from that that's a really nice PR for a really great IDE 😉

2021-05-19 18:24 UTC, cstrnt commented on dev/code.ts
> +            "Show versions of installed extensions, when using --list-extensions.",
Hey there, this might sound weird, but those are `options`and not `args`. We don't offer the option to have conditional `options`

2021-05-19 18:24 UTC, cstrnt commented on dev/code.ts
> +            "Show versions of installed extensions, when using --list-extensions.",
As a rule of thumb: If it starts with `-` or `--` it's an option

2021-05-19 18:24 UTC, cstrnt commented on dev/code.ts
> +    args: {
This should be option because it has a default value if omited

2021-05-19 18:24 UTC, cstrnt commented on dev/code.ts
> +    description: "Max memory size for a window (in Mbytes).",
This should take an argument

2021-05-19 18:24 UTC, cstrnt commented on dev/code.ts
> +          description: "Filters installed extensions by provided category",
this should take an argument, right?

2021-05-19 18:26 UTC, Tyriar commented on dev/code.ts
> +    args: {
The wording is a little awkward, but I think this is correct as mandatory. It's calling out the default log level if you do not specify `--log`

2021-05-19 18:28 UTC, Tyriar commented on dev/code.ts
> +            "Show versions of installed extensions, when using --list-extensions.",
How do I specify nested options? These 2 are only valid when --list-extensions is provided

2021-05-19 18:30 UTC, Tyriar commented on dev/code.ts
> +          description: "Filters installed extensions by provided category",
Yep, pending nesting options question

2021-05-19 18:32 UTC, Tyriar commented on dev/code.ts
> +            "Show versions of installed extensions, when using --list-extensions.",
If these don't exist I can just make it top level

2021-05-20 13:06 UTC, Tyriar commented
Fixed this up, also added suggestions for `--category`

2021-05-20 14:53 UTC, cstrnt commented on dev/code.ts
> +            "Show versions of installed extensions, when using --list-extensions.",
There are no nested options as of right now :/

2021-05-20 17:34 UTC, QuiiBz commented on dev/code.ts
> +    },
Shouldn't this be `variadic`? Since the description contains "folder(s)".

2021-05-22 11:51 UTC, Tyriar commented on dev/code.ts
> +    },
I added `variadic: true` but the file template is still showing up?

<img width="486" alt="Screen Shot 2021-05-22 at 4 50 31 AM" src="https://user-images.githubusercontent.com/2193314/119225558-44bec080-bab9-11eb-99c5-fa775c2bddda.png">
<img width="507" alt="Screen Shot 2021-05-22 at 4 50 37 AM" src="https://user-images.githubusercontent.com/2193314/119225561-46888400-bab9-11eb-9f44-63e932349d33.png">

2021-05-22 13:07 UTC, QuiiBz commented on dev/code.ts
> +    },
[Variadic](https://fig.io/docs/autocomplete/schemas/arg#variadic) means that an argument repeats infinitely, so it should autocomplete folders infinitely. It does not work?

2021-05-22 14:01 UTC, Tyriar commented on dev/code.ts
> +    },
Yeah it didn't work, it may be a bug with fig? I committed the change regardless as it seems like it's correct.

2021-05-22 14:31 UTC, cstrnt commented on dev/code.ts
> +    },
That's really weird and seems to be a bug! We'll investigate!

2021-05-22 14:33 UTC, cstrnt commented
@Tyriar 
Hey there, if you like you could merge in the current master and remove the `code.js` from the git index (`git rm -f --cached specs/code.js`:) I think this PR is ready to get merged though, because it's a Bug with Fig itself and not your Spec!

2021-05-22 14:35 UTC, QuiiBz approved these changes
Thanks for this PR, ready to merge @cstrnt

2021-05-22 14:37 UTC, cstrnt commented
Opened #219

2021-05-23 10:51 UTC, merged