Update fastly spec to 0.30.0
withfig/autocomplete pull request #214
Opened 2021-05-19 16:30 UTC by kailan

0.30.0 adds a `fastly compute pack` command for packaging compiled binaries into Fastly-ready packages.

2021-05-19 16:35 UTC, kailan commented
I think your linting rules have changed, hence the massive diff on the js file.

2021-05-19 17:33 UTC, QuiiBz requested changes

2021-05-19 17:33 UTC, QuiiBz commented on dev/fastly.ts
> +          subcommands: [],
You can safely remove `subcommands` since it's empty.

2021-05-19 18:19 UTC, cstrnt approved these changes
Apart from Tom's comment this looks good to me :)

2021-05-19 18:19 UTC, cstrnt commented on dev/fastly.ts
> +          subcommands: [],
#205 will fix this :)

2021-05-20 09:36 UTC, kailan commented
Cool, I'll wait on #205 and then rebase this PR on the new changes.

2021-05-22 02:40 UTC, mattschrage commented
@kailan just merged #205 - you're good to go!

2021-06-01 12:58 UTC, QuiiBz commented on dev/fastly.ts
> +          options: [
Looks like an empty line as popped here, could you remove it?

2021-06-02 13:59 UTC, kailan commented on dev/fastly.ts
> +          options: [
Every other entry in the file is like this – this must have been changed in the recent linting update.

I didn't add the line break myself, it must have been done by the linting tool when I ran `--fix`.

2021-06-02 14:11 UTC, QuiiBz commented on dev/fastly.ts
> +          options: [
Strange, we will look into this. Let's merge this!

2021-06-02 14:11 UTC, QuiiBz approved these changes

2021-06-02 14:11 UTC, merged