[GIT] add subcommands
withfig/autocomplete pull request #215
Opened 2021-05-20 15:18 UTC by Alexanderchen929

Exact subcommands are fetch, merge, pull, status, stage, rebase

Also resolved issue 136

2021-05-23 04:14 UTC, mattschrage approved these changes
Wow! Great work - didn't realize how many options were were missing!

2021-05-23 04:14 UTC, mattschrage commented on dev/git.ts
> +import { isOptionalChain, transpileModule } from "typescript";
Is this `import` intentional?

2021-05-23 10:39 UTC, cstrnt requested changes
Damn, git is such a big tool 😆  I think in general we have loads of code duplication in here and maybe we should think of a way of not repeating ourselves everytime we add something new

2021-05-23 10:39 UTC, cstrnt commented on dev/git.ts
> +import { isOptionalChain, transpileModule } from "typescript";
Nope, those imports are unused. Maybe we should add `noUnusedLocals": true` to our `tsconfig.json`

2021-05-23 10:39 UTC, cstrnt commented on dev/git.ts
> +          name: ["-x", "--exec"],
In the docs they always add "" around the commands. Should we add `insertValue: "-x "{cursor}"` here?
![Screenshot 2021-05-23 at 12 31 39](https://user-images.githubusercontent.com/20679094/119256824-d403cb00-bbc2-11eb-8c8c-4dd12666fcf2.png)

2021-05-23 10:39 UTC, cstrnt commented on dev/git.ts
> +      description: "Add file contents to the staging area",
Shouldn't we create a top-level const for the options and args of `git add` because they are the same?

2021-05-23 17:55 UTC, Alexanderchen929 commented on dev/git.ts
> +import { isOptionalChain, transpileModule } from "typescript";
agreed, think it was vscode trying to be helpful for my typos, will remove

2021-05-23 17:56 UTC, Alexanderchen929 commented on dev/git.ts
> +          name: ["-x", "--exec"],
that sounds good! Thank you for this suggestion

2021-05-23 17:57 UTC, Alexanderchen929 commented on dev/git.ts
> +      description: "Add file contents to the staging area",
yes, was talking to brendan about this, will change around now. Thank you again!

2021-06-08 07:21 UTC, Ashraf-Ali-aa commented
Hi, I was wondering is it possible to add the following commands.
```
	git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
	git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --name-status -p
```

2021-06-10 17:24 UTC, cstrnt approved these changes
Did some quick checks and it seems to be good! Well done, Alex 😊

2021-06-13 08:21 UTC, merged