Create spec for barnard59
withfig/autocomplete pull request #2217
Opened 2023-12-28 09:47 UTC by tpluscode

https://github.com/zazuko/barnard59/

2023-12-28 09:53 UTC, tpluscode commented
I have read the CLA Document and I hereby sign the CLA

2023-12-28 09:56 UTC, tpluscode commented
recheck

2024-01-18 23:49 UTC, grant0417 requested changes
Looks good besides a lot of instances of `default: "[object Map]"`

2024-01-18 23:49 UTC, grant0417 commented on src/barnard59.ts
> +          args: { name: "name=value", default: "[object Map]" },
This is likely a wrong default.

2024-01-18 23:49 UTC, grant0417 commented on src/barnard59.ts
> +              args: { name: "name=value", default: "[object Map]" },
Same here

2024-01-18 23:49 UTC, grant0417 commented on src/barnard59.ts
> +              args: { name: "name=value", default: "[object Map]" },
Same here

2024-01-20 20:24 UTC, tpluscode commented
Thank you for the review @grant0417 . As you can see, this was generated...

About the bogus defaults. We have options with custom transforms which build a `Map` object. The default is an empty map, hence the JavaScript's default string representation that object. I would not like to alter the code to account for fig's autocomplete as it requires additional guards in multiple places to handle a possible undefined value for that option. 

What about the linting problems? I can fix some casing but it also complains about `display help for command` which is generated the commander itself. And I don't know what to do about these which say `If `X` is a single value it should not be enclosed in square brackets`. I think that needs fixing in `@fig/complete-commander`

2024-02-08 10:28 UTC, tpluscode commented
ping @grant0417

2024-05-31 18:57 UTC, grant0417 commented
Hey @tpluscode, I have updated the `@fig/complete-commander` package with the fixes for the `[object Map]` default, can you regenerate your spec and submit again?

2024-06-06 07:42 UTC, tpluscode commented
Done @grant0417

2024-06-06 08:03 UTC, closed without merging