feat(arduino-cli): add completion spec
withfig/autocomplete pull request #2231
Opened 2024-01-12 23:44 UTC by lukejans

## arduino-cli completion spec 
- arduino-cli documentation used for spec: [link](https://arduino.github.io/arduino-cli/0.35/commands/arduino-cli/)

![Screenshot 2024-01-12 at 6 20 18 PM](https://github.com/withfig/autocomplete/assets/91230392/e3f9b169-3ed8-4c52-af8f-16093e5ee578)

2024-01-12 23:45 UTC, lukejans commented
I have read the CLA Document and I hereby sign the CLA

2024-01-16 21:09 UTC, mschrage commented
Hi @lukejans! Love this contribution, thanks for submitting - can you remove the yarn.lock file from this PR, so we can get this merged in?

2024-01-18 23:40 UTC, grant0417 commented
Sorry, to clarify don't delete the `yarn.lock` just revert the changes to it with `git fetch && git checkout master -- yarn.lock`.

2024-01-18 23:42 UTC, grant0417 commented on src/arduino-cli.ts
> +    "Arduino Command Line Interface (arduino-cli), example: 'arduino-cli <command> [flags...]'",
```suggestion
    "Arduino Command Line Interface",
```

2024-01-18 23:46 UTC, grant0417 requested changes
Spec looks good, one change I would suggest before merge is to remove all the `example` in description where it is the full CLI command. Left some comments as examples.

2024-01-18 23:46 UTC, grant0417 commented on src/arduino-cli.ts
> +        "Arduino board commands, example: 'arduino-cli board <command> [flags]'",
```suggestion
        "Arduino board commands",
```

2024-01-18 23:46 UTC, grant0417 commented on src/arduino-cli.ts
> +            "Sets the default values for port and FQBN. If no port or FQBN are specified, the current default port and FQBN are displayed, example: 'arduino-cli board attach [-p <port>] [-b <FQBN>] [
```suggestion
            "Sets the default values for port and FQBN. If no port or FQBN are specified, the current default port and FQBN are displayed",
```

2024-01-18 23:46 UTC, grant0417 commented on src/arduino-cli.ts
> +            "Show information about a board, in particular if the board has options to be specified in the FQBN, example: 'arduino-cli board details -b <FQBN> [flags]'",
```suggestion
            "Show information about a board, in particular if the board has options to be specified in the FQBN'",
```

2024-01-18 23:46 UTC, grant0417 commented on src/arduino-cli.ts
> +                "Max time to wait for port discovery, example: '30s, 1m (default 1s)'",
This is fine

2024-01-18 23:46 UTC, grant0417 commented on src/arduino-cli.ts
> +                "Fully Qualified Board Name, example: 'arduino:avr:uno'",
This is fine

2024-01-18 23:46 UTC, grant0417 commented on src/arduino-cli.ts
> +            "Sets the default values for port and FQBN. If no port or FQBN are specified, the current default port and FQBN are displayed, example: 'arduino-cli board attach [-p <port>] [-b <FQBN>] [
This has the full cli command

2024-01-18 23:46 UTC, grant0417 commented on src/arduino-cli.ts
> +        "Arduino board commands, example: 'arduino-cli board <command> [flags]'",
This has the full cli command

2024-01-18 23:46 UTC, grant0417 commented on src/arduino-cli.ts
> +    "Arduino Command Line Interface (arduino-cli), example: 'arduino-cli <command> [flags...]'",
This has the full cli command

2024-01-19 20:41 UTC, grant0417 approved these changes
LGTM, thanks!

2024-01-19 20:43 UTC, merged