feat(q): Add Q spec
withfig/autocomplete pull request #2322
Opened 2024-04-19 23:25 UTC by chaynabors

2024-04-19 23:33 UTC, chaynabors commented
recheck

2024-04-25 18:57 UTC, grant0417 requested changes

2024-04-25 18:57 UTC, grant0417 commented on src/q.ts
> +  name: "q_cli",
```suggestion
  name: "q",
```

2024-04-25 18:57 UTC, grant0417 commented on src/q.ts
> +  description: "Top level cli commands",
```suggestion
  description: "The Amazon Q CLI",
```

2024-04-25 18:57 UTC, grant0417 commented on src/q.ts
> +      name: ["chat", "q"],
```suggestion
      name: "chat",
```

2024-04-25 19:03 UTC, grant0417 approved these changes

2024-04-25 19:03 UTC, merged