Add Zapier spec
withfig/autocomplete pull request #241
Opened 2021-05-27 21:40 UTC by xavdid

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Add spec for the [Zapier CLI](https://github.com/zapier/zapier-platform). It was generated using [the oclif plugin](https://github.com/withfig/oclif-plugin).

We can probably make a fancier version that includes the args, but this is a good first step.

2021-05-28 09:17 UTC, QuiiBz requested changes
Thanks a lot for your first contribution here!

2021-05-28 09:17 UTC, QuiiBz commented on dev/zapier.ts
> +            isOptional: false,
No need to set `isOptional` to false, since Fig assumes by default that args are mandatory. Same for underneath

2021-05-28 09:17 UTC, QuiiBz commented on dev/zapier.ts
> +          isOptional: false,
I think you can use the `folders` template here ([doc](https://fig.io/docs/reference/arg#template))

2021-05-28 09:17 UTC, QuiiBz commented on dev/zapier.ts
> +            suggestions: ["plain", "json", "raw", "row", "table"],
You can extract this suggestion to a top-level const since it's repeated many times underneath.

2021-05-28 09:17 UTC, QuiiBz commented on dev/zapier.ts
> +          isOptional: true,
I believe this arg should be [variadic](https://fig.io/docs/reference/arg#variadic)?

2021-05-28 09:17 UTC, QuiiBz commented on dev/zapier.ts
> +          isOptional: true,
Same as above

2021-05-28 09:17 UTC, QuiiBz commented on dev/zapier.ts
> +        },
You can extract this arg to a top-level const to avoid duplication.

2021-05-28 09:17 UTC, QuiiBz commented on dev/zapier.ts
> +            isOptional: false,
You can add the `filepaths` template here.

2021-05-28 09:17 UTC, QuiiBz commented on dev/zapier.ts
> +          description: "",
Please fill in this description.

2021-05-28 09:17 UTC, QuiiBz commented on dev/zapier.ts
> +          isOptional: false,
I assume this arg could have a `folders` template?

2021-05-28 17:41 UTC, xavdid commented
@QuiiBz thanks for the review! 

I put this together on a call with @mattschrage yesterday using the `oclif-plugin`. I'm happy to make the manual changes you suggested. But, it would also be great to be able to fully automate the process. In the future when we re-generate the spec, it would be great to not need to re-make these changes. Maybe a problem for another day.

That said, those plugin commands can be removed, they aren't meant to be there.

2021-05-29 07:08 UTC, cstrnt requested changes

2021-05-29 07:10 UTC, cstrnt commented
Hey @xavdid I totally agree with you, that those changes shouldn't be done each time the spec is generated, but on the other hand it will be kinda hard to guess stuff like `template: "filePaths"` just from the naming of the argument. We humans are good at doing that, but oclif-plugins aren't 😆

2021-06-01 18:26 UTC, xavdid commented
Cool, i've made changes that _should_ address everything mentioned. Thanks y'all!

2021-06-04 07:19 UTC, cstrnt requested changes

2021-06-04 07:19 UTC, cstrnt commented on dev/zapier.ts
> +const formatFlag = {
could you please type this variable 
```suggestion
const formatFlag: Fig.Option = {
```

2021-06-04 07:19 UTC, cstrnt commented on dev/zapier.ts
> +const debugFlag = {
see above

2021-06-04 18:26 UTC, xavdid commented
@cstrnt done!

2021-06-10 07:26 UTC, QuiiBz requested changes
Hi! Could you fix those small issues, so we can get this merged in? Thanks a lot for this huge contribution!

2021-06-10 07:26 UTC, QuiiBz commented on dev/zapier.ts
> +          },
I think this can have a template of `folders`

2021-06-10 07:26 UTC, QuiiBz commented on dev/zapier.ts
> +        },
Maybe this should be dangerous?

2021-06-10 07:26 UTC, QuiiBz commented on dev/zapier.ts
> +            "Skips confirmation. Useful for running programatically.",
Same as above

2021-06-10 17:16 UTC, xavdid commented
Sure, good catch!

2021-06-10 17:59 UTC, QuiiBz approved these changes
Thanks a lot for your contribution!

2021-06-13 08:27 UTC, QuiiBz commented
@cstrnt could we merge this?

2021-06-13 19:28 UTC, cstrnt commented
Linting fails for some reason though! @xavdid could you please run `npm run lint:fix` and push again? 😊

2021-06-13 20:26 UTC, xavdid commented
I tried both `lint` and `lint:fix` and there were no changes locally 🤔 

```
% npm run lint

> linter@1.0.0 lint /Users/david/projects/autocomplete
> eslint '**/*.ts' && npx prettier --check '**/*.ts'

Checking formatting...
All matched files use Prettier code style!
```

node version is `14.16.1`.

2021-06-18 07:32 UTC, merged