[AWS] [Lambda] Spec
withfig/autocomplete pull request #244
Opened 2021-05-30 22:43 UTC by nagypeterjob

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Feature

**What is the current behavior? (You can also link to an open issue here)**

Missing spec

**What is the new behavior (if this is a feature change)?**

Added lambda autocompletion

**Additional info:**

- [x] add-layer-version-permission
- [] add-permission
- [] create-alias
- [] create-code-signing-config
- [] create-event-source-mapping
- [] create-function
- [] delete-alias
- [] delete-code-signing-config
- [] delete-event-source-mapping
- [] delete-function
- [] delete-function-code-signing-config
- [] delete-function-concurrency
- [] delete-function-event-invoke-config
- [] delete-layer-version
- [] delete-provisioned-concurrency-config
- [] get-account-settings
- [] get-alias
- [] get-code-signing-config
- [] get-event-source-mapping
- [] get-function
- [] get-function-code-signing-config
- [] get-function-concurrency
- [] get-function-configuration
- [] get-function-event-invoke-config
- [] get-layer-version
- [] get-layer-version-by-arn
- [] get-layer-version-policy
- [] get-policy
- [] get-provisioned-concurrency-config
- [] invoke
- [] list-aliases
- [] list-code-signing-configs
- [] list-event-source-mappings
- [] list-function-event-invoke-configs
- [] list-functions
- [] list-functions-by-code-signing-config
- [] list-layer-versions
- [] list-layers
- [] list-provisioned-concurrency-configs
- [] list-tags
- [] list-versions-by-function
- [] publish-layer-version
- [] publish-version
- [] put-function-code-signing-config
- [] put-function-concurrency
- [] put-function-event-invoke-config
- [] put-provisioned-concurrency-config
- [] remove-layer-version-permission
- [] remove-permission
- [] tag-resource
- [] untag-resource
- [] update-alias
- [] update-code-signing-config
- [] update-event-source-mapping
- [] update-function-code
- [] update-function-configuration
- [] update-function-event-invoke-config
- [] wait

2021-06-10 07:21 UTC, QuiiBz commented
Hello, could you update this branch by merging master in it? We updated how the completion specs are compiled, and so the `specs` directory doesn't exist anymore.

2021-06-11 17:05 UTC, nagypeterjob commented
> Hello, could you update this branch by merging master in it? We updated how the completion specs are compiled, and so the `specs` directory doesn't exist anymore.

Well, I did merge master into the branch, but I guess it wasn't a great idea after all. This PR was opened against `mschrange/aws` which is also outdated compared to `master`. I think we should open this PR against `master`

2021-06-28 18:01 UTC, QuiiBz commented
> 
> Well, I did merge master into the branch, but I guess it wasn't a great idea after all. This PR was opened against `mschrange/aws` which is also outdated compared to `master`. I think we should open this PR against `master`

Sorry for the delay. I agree with you, could you re-open this PR against the current `master`?

2021-06-29 07:28 UTC, QuiiBz commented
I merged master into this PR and fixed the conflicts

2021-06-29 07:33 UTC, QuiiBz requested changes

2021-06-29 07:33 UTC, QuiiBz commented on specs/aws/iot-data.js
> +var completionSpec = {
Any reason why there is this file in the lambda PR?

2021-06-29 07:33 UTC, QuiiBz commented on dev/git.ts
> +        generators: [gitGenerators.files_for_staging, gitGenerators.commits],
Let's remove this from the PR since it's not related to the lambda spec.

2021-06-30 21:10 UTC, closed without merging