[GIT] Ignore warning message
withfig/autocomplete pull request #252
Opened 2021-06-02 06:44 UTC by seonggwonyoon

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix

**What is the current behavior? (You can also link to an open issue here)**
https://github.com/withfig/fig/issues/107

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2021-06-02 07:04 UTC, QuiiBz commented
Hi, thanks a lot for your first contribution! Based on Matt's comment (https://github.com/withfig/fig/issues/107#issuecomment-852730125), shouldn't it filter out anything starting with `error` too, not only `warning`?

2021-06-02 07:09 UTC, seonggwonyoon commented
> Hi, thanks a lot for your first contribution! Based on Matt's comment ([withfig/fig#107 (comment)](https://github.com/withfig/fig/issues/107#issuecomment-852730125)), shouldn't it filter out anything starting with `error` too, not only `warning`?

Thank you @QuiiBz 
I missed `error` option! just added.

2021-06-02 07:23 UTC, QuiiBz reviewed
I think we can simplify this and create a top-level function to avoid duplication. Something like this (not tested):

```ts
const filter = (out: string): string => {
  return (out.startsWith("warning:") || out.startsWith("error:"))
    ? out = out.split("\n").slice(1).join("\n")
    : out;
}
```

So we will only call `filter` this way:

```ts
out = filter(out);
```

2021-06-02 13:41 UTC, seonggwonyoon commented
> I think we can simplify this and create a top-level function to avoid duplication. Something like this (not tested):
> 
> ```ts
> const filter = (out: string): string => {
>   return (out.startsWith("warning:") || out.startsWith("error:"))
>     ? out.split("\n").slice(1).join("\n")
>     : out;
> }
> ```
> 
> So we will only call `filter` this way:
> 
> ```ts
> out = filter(out);
> ```

As you said, I applied the filter function!

2021-06-02 13:43 UTC, QuiiBz approved these changes
That's cleaner!

2021-06-02 20:48 UTC, cstrnt requested changes

2021-06-02 20:48 UTC, cstrnt commented on dev/git.ts
> +const filter = (out: string): string => {
I honestly would prefer being more verbose here: Maybe `filterWarnings`? I think functions having the same name as builtins might confuse other contributors

2021-06-03 03:57 UTC, seonggwonyoon commented on dev/git.ts
> +const filter = (out: string): string => {
Fix `filter` to `filterWarnings`!

2021-06-03 11:35 UTC, cstrnt requested changes

2021-06-03 11:35 UTC, cstrnt commented on dev/git.ts
> +      out = filterWarnings(out);
Could you please create a const here. Re-assigning to a parameter is a code smell imho

2021-06-03 11:35 UTC, cstrnt commented on dev/git.ts
> +      out = filterWarnings(out);
see above

2021-06-03 11:35 UTC, cstrnt commented on dev/git.ts
> +      out = filterWarnings(out);
see above

2021-06-03 11:35 UTC, cstrnt commented on dev/git.ts
> +      output = filterWarnings(output);
see above

2021-06-03 15:11 UTC, QuiiBz commented on dev/git.ts
> +      out = filterWarnings(out);
Btw, this function’s name not only filters warnings but also errors. Shouldn’t we rename it to something more generic?

2021-06-03 15:29 UTC, seonggwonyoon commented on dev/git.ts
> +      out = filterWarnings(out);
@QuiiBz Yes, it filters out warnings and errors.
Let's think about changing it to a more generic name.

2021-06-03 15:30 UTC, seonggwonyoon commented on dev/git.ts
> +      out = filterWarnings(out);
@cstrnt I agree with the saying Re-assigning to a parameter is a code smell.
But I don't understand the phrase `create a const here' Can you explain a bit more?

2021-06-03 16:03 UTC, seonggwonyoon commented on dev/git.ts
> +      out = filterWarnings(out);
@cstrnt You mean this code?
```typescript
postProcess: function (out) {
      const ?? = filterWarnings(out);
      if (??.startsWith("fatal:")) {
        return [];
      }
```

2021-06-03 19:24 UTC, cstrnt commented on dev/git.ts
> +      out = filterWarnings(out);
hey @seonggwonyoon, sorry for not replying :/ That's exactly what I mean :)

2021-06-04 05:55 UTC, seonggwonyoon commented on dev/git.ts
> +      out = filterWarnings(out);
@cstrnt Create const is done!
@QuiiBz Fix filterWarnings to filterMessages

2021-06-04 06:10 UTC, QuiiBz approved these changes
LGTM

2021-06-04 07:16 UTC, cstrnt commented
Hey sorry to be annoying, but could you please run `npm run lint:fix` in order to to fix the styling :) After this is done, we will merge the PR 😊

2021-06-04 07:32 UTC, seonggwonyoon commented
> Hey sorry to be annoying, but could you please run `npm run lint:fix` in order to to fix the styling :) After this is done, we will merge the PR 😊

Fixed it. Thanks @cstrnt

2021-06-04 08:37 UTC, merged