feat: add Gatsby CLI completion spec
withfig/autocomplete pull request #264
Opened 2021-06-05 08:35 UTC by indie-ridge-dev

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2021-06-06 08:13 UTC, cstrnt requested changes
Hey there :)
Could you please take a look at all `args` here? I just left a comment for some, but I seems that you added `args` for everything, even though they don't take any args!


Here is a little explainer, what an argument is:

`cd /some/folder`

`cd` is the command itself and `/some/folder`is the argument which is passed. Another example from this spec is `gatsby develop -H 3000` where the `-H`is the option and `3000` is the argument from the option

2021-06-06 08:28 UTC, QuiiBz commented on dev/gatsby.ts
> +    },
Based on the [documentation](https://www.gatsbyjs.com/docs/reference/gatsby-cli/#repl), I don't think that the REPL takes any options nor arguments. `gatsby repl` will open a REPL, where you can type the commands.

2021-06-06 17:37 UTC, indie-ridge-dev commented on dev/gatsby.ts
> +    },
yes, you are right of course. I have just pushed a new version without the repl options and without the args for the sub commands.

2021-06-10 07:19 UTC, QuiiBz requested changes
Could you remove all `args: {}` where they are not needed, and add a `name` property to each one that really exists?

2021-06-10 07:19 UTC, QuiiBz commented on dev/gatsby.ts
> +      args: {},
Could you remove this argument, as Tim mentioned?

2021-06-10 07:19 UTC, QuiiBz commented on dev/gatsby.ts
> +        },
I would love to see `name` filled up in each argument

2021-06-18 07:41 UTC, merged