feat: add volta completion spec
withfig/autocomplete pull request #269
Opened 2021-06-07 06:59 UTC by Monkeyank

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature
**What is the current behavior? (You can also link to an open issue here)**
No completion spec for `volta`
**What is the new behavior (if this is a feature change)?**
Add a completion spec for `volta`. 
**Additional info:**
- [Volta Docs](https://docs.volta.sh/reference/)
- Fulfills #240

2021-06-10 07:12 UTC, QuiiBz requested changes
Thanks a lot for your first contribution! I left some changes before we can get this merged in.

2021-06-10 07:12 UTC, QuiiBz commented on dev/volta.ts
> +const defaultOptions = [
I would love to see this typed as a `Fig.Option[]`

2021-06-10 07:12 UTC, QuiiBz commented on dev/volta.ts
> +      },
Doesn't this can have a template of `filepaths`?

2021-06-10 18:24 UTC, Monkeyank commented on dev/volta.ts
> +      },
Good catch! Didn't notice it at first glance

2021-06-13 19:30 UTC, cstrnt approved these changes
Thank you very much :blush

2021-06-14 06:16 UTC, QuiiBz approved these changes
Let's get this merged in!

2021-06-14 06:16 UTC, merged