Cloudflare Wrangler CLI Support
withfig/autocomplete pull request #271
Opened 2021-06-08 00:00 UTC by nwhitmont

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature: Support for the Cloudflare Workers `wrangler` CLI tool.

**What is the current behavior? (You can also link to an open issue here)**
No `wrangler` support.

**What is the new behavior (if this is a feature change)?**
Adds completion spec for `wrangler` - all commands.

**Additional info:**
- https://www.npmjs.com/package/@cloudflare/wrangler
- https://github.com/cloudflare/wrangler#readme
- https://workers.cloudflare.com/

2021-06-08 09:13 UTC, cstrnt requested changes
Hey there and thank you very much for opening a PR!
Wrangler is actually a tool I love to use and I'm really happy that you started creating a spec.
It is well done overall, but is missing some key things in order to make it work with Fig as awesome as possible!

You please have a look at the arguments:
![image](https://user-images.githubusercontent.com/20679094/121158214-791cd580-c84a-11eb-9fae-8556356798ba.png)

The docs are pretty good here in showing whether they are optional or mandatory!

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +const OPTION_CONFIG = {
Could you please add Typescript types here (`OPTION_CONFIG:  Fig.Option`)

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +const OPTION_ENV = {
see above

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +const OPTION_HELP = {
see above

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +const OPTION_VERBOSE = {
see above

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +        },
Could you please make those args optional (using `isOptional`)!

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +            name: "site",
this arg should be optional as well

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +            name: "type",
see above

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +          name: "create",
this actually takes a mandatory arg

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +              description: "Key whose value to get",
```suggestion
              description: "Key whose value to delete",
```

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +          description: "Get a key's value from a namespace",
this takes a mandatory argument

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +          description: "Put a key-value pair into a namespace",
see above

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +          description: "Delete multiple keys and their values from a namespace",
see above

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +          description: "Upload multiple key-value pairs to a namespace",
see above; also when you add the `arg` here it would be great if you add `template: "filePaths"` here, because Fig will automatically show suggestions for files

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +          description: "Delete a route by ID",
this needs an argument

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +          description: "Delete a secret variable from a script",
this takes an argument

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +          description: "Create or update a secret variable for a script",
see above

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +          description: "The name of your worker! [default: worker]",
this is Optional

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +            name: "site",
I don't this that this takes an argument, but rather it is a flag

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +            name: "type",
this is optional as well

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +          name: "method",
this is optional

2021-06-08 09:13 UTC, cstrnt commented on dev/wrangler.ts
> +          description: "Body string to post to your preview worker request",
see above

2021-06-09 16:47 UTC, nwhitmont commented on dev/wrangler.ts
> +              description: "Key whose value to get",
Oddly, this appears to be a typo in the actual help text, which I copied here directly.  I do agree it should be "delete" as "get" doesn't make sense in this context!

2021-06-09 16:57 UTC, nwhitmont commented on dev/wrangler.ts
> +            name: "site",
Fig doesn't appear to differentiate between "flag" and "option"(?)  -- The same question occurred to me during development. (aka "are flags different than options in Fig?")

2021-06-09 18:25 UTC, cstrnt commented on dev/wrangler.ts
> +            name: "site",
I'm sorry for my wording! Flags are in fact options! I think most people use the term flag for options that don't require any arguments (e.g. `--force`)

2021-06-10 06:51 UTC, QuiiBz commented on dev/wrangler.ts
> +            name: "site",
Based on their [documentation](https://developers.cloudflare.com/workers/cli-wrangler/commands#init), `--site` doesn't take any arguments (so it's simply an option - a flag)

2021-06-10 07:01 UTC, QuiiBz requested changes

2021-06-10 07:01 UTC, QuiiBz commented on dev/wrangler.ts
> +            "Specifies a log to report (e.g. --log=1619728882567.log)",
I assume that this can have a `filepaths` template?

2021-06-14 18:02 UTC, nwhitmont commented on dev/wrangler.ts
> +            name: "site",
arg removed

2021-06-15 07:01 UTC, QuiiBz approved these changes
LGTM

2021-06-19 07:38 UTC, merged