[Serverless] add serverless CLI, support subcmd: deploy, info, invoke
withfig/autocomplete pull request #277
Opened 2021-06-09 16:51 UTC by deathemperor

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
Serverless not supported

**What is the new behavior (if this is a feature change)?**
Serverless supported

**Additional info:**
I added all subcommands and worked basic suggestions for deploy, info, invoke subcommand. Hopefully I can improve it with color and value suggestions, this is my first PR on this repo.

Hopefully can finish all about `serverless` CLI!

2021-06-13 08:02 UTC, QuiiBz requested changes
Thanks a lot for your first contribution! I left some comments, mostly for suggestions and templates.

2021-06-14 03:54 UTC, deathemperor commented on dev/serverless.ts
> +    },
agree! such feature is what I need to learn more on how to do it with fig. Will add that.

2021-06-14 03:54 UTC, deathemperor commented on dev/serverless.ts
> +    },
sure

2021-06-21 16:27 UTC, QuiiBz commented
Hi, I resolved the review and added suggestions for the regions.

2021-06-21 16:27 UTC, QuiiBz approved these changes

2021-06-21 16:27 UTC, merged

2021-06-21 16:32 UTC, deathemperor commented
awesome! thanks! I'll add more options when I have time