Add auto generator of completion spec files
withfig/autocomplete pull request #283
Opened 2021-06-11 00:25 UTC by Alonely0

Now by using the command `CMD=YOUR_COMMAND npm run auto-fig-command` you can create a completion spec file of that command based on its man page. The use of this script it's not intended to replace the manual created spec files, the objective of this script is to help in their creation and create rudimentary command spec files.

2021-06-13 07:50 UTC, QuiiBz commented
Really cool! As mentioned on Discord, I think those sorts of tooling should be in a separate repo. @falky97 @mattschrage what's your thought on this?

2021-06-13 09:18 UTC, fedeci commented
`@fig/cli` sounds good to me😄

2021-06-13 19:38 UTC, cstrnt requested changes

2021-06-13 19:38 UTC, cstrnt commented on package.json
> +    "fs": "^0.0.1-security",
!!!! fs isn't a depedency and comes with node! Please be careful when installing packages mindlessly

2021-06-13 19:38 UTC, cstrnt commented on scripts/auto-fig-command.ts
> +const removeTrailingSpaces = require("remove-trailing-spaces");
Any reason why you are using `require` over `import`?

2021-06-13 19:38 UTC, cstrnt commented on scripts/auto-fig-command.ts
> +      (err: never) => {
I don't think errors never happen! I think the type should be infered here

2021-06-13 19:38 UTC, cstrnt commented on scripts/auto-fig-command.ts
> +);
I would prefer creating an async function, maybe even called run to avoid .then callbacks

2021-06-13 19:38 UTC, cstrnt commented on scripts/auto-fig-command.ts
> +    name: process.argv[2],
maybe create a top level variable called specName because this is used multiple times along this file

2021-06-13 19:38 UTC, cstrnt commented on scripts/auto-fig-command.ts
> +    execSh(
this package actually offers a promise-based option which would reduce the callback hell here as well 😆

2021-06-14 22:03 UTC, Alonely0 commented on scripts/auto-fig-command.ts
> +const removeTrailingSpaces = require("remove-trailing-spaces");
because some packages can't be imported and have to be required (the linter throws me an error)

2021-06-14 22:04 UTC, Alonely0 commented on package.json
> +    "fs": "^0.0.1-security",
Ok, thanks!

2021-06-14 22:04 UTC, Alonely0 commented on scripts/auto-fig-command.ts
> +      (err: never) => {
Could happen a write error because of lack of permissions for example.

2021-06-14 22:08 UTC, Alonely0 commented on scripts/auto-fig-command.ts
> +    name: process.argv[2],
Ok!

2021-06-14 22:46 UTC, Alonely0 commented on scripts/auto-fig-command.ts
> +const removeTrailingSpaces = require("remove-trailing-spaces");
No, I'm just more used to require, but I'm going to change them.

2021-06-14 22:55 UTC, Alonely0 commented
https://github.com/withfig/man-page-scraper/pull/1

2021-06-14 22:55 UTC, closed without merging