wp cli autocomplete v0.1
withfig/autocomplete pull request #285
Opened 2021-06-11 12:07 UTC by floq-design

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
**NEW** autocomplete set for `wp-cli`

**What is the current behavior? (You can also link to an open issue here)**
_N/A_

**What is the new behavior (if this is a feature change)?**
_N/A_

**Additional info:**
I've labelled this as a v0.1 release as it's not had much testing - yet!
My intention is to go through and double check all args & options over next few days.
In mean time I thought be good to get it out there for people to feedback on.
Also intend to add some generators for parts like activating/deactivating plugins with dynamic plugin list.

Cheers
James

2021-06-13 21:57 UTC, floq-design commented
### UPDATE
**Release** `v0.2`

- Double-checking of args / options is complete.
- Added descriptions to everything.
- Fixed some typos, added & removed options where appropriate.

Generators to come if I find the time - invested over 20 hours in this already!

Enjoyed putting it together but maybe time for someone else to inject some :heart:

Cheers
James

2021-06-18 07:05 UTC, QuiiBz requested changes

2021-06-18 07:05 UTC, QuiiBz commented on dev/wp.ts
> +  },
I think this can have a template of `filepaths`

2021-06-18 07:05 UTC, QuiiBz commented on dev/wp.ts
> +      args: [{}],
You can just set an empty object here. But does `wp cache` takes any arguments?

2021-06-18 07:05 UTC, QuiiBz commented on dev/wp.ts
> +      args: [{}],
Same as above

2021-06-18 07:05 UTC, QuiiBz commented on dev/wp.ts
> +                  args: { name: "path" },
Could this arg have a template of `filepaths`?

2021-06-18 07:05 UTC, QuiiBz commented on dev/wp.ts
> +              args: { name: "path" },
Could this arg have a template of `filepaths`?

2021-06-18 07:05 UTC, QuiiBz commented on dev/wp.ts
> +          args: { name: "dirname" },
Could this arg have a template of `folders`?

2021-06-18 09:06 UTC, floq-design commented on .eslintrc.js
> +    "quotes": ["error", "double"],
I added it to over-ride my global setting.. I've reverted it in latest commit

2021-06-18 09:06 UTC, floq-design commented on dev/wp.ts
> +  name: "--path",
👍

2021-06-18 09:07 UTC, floq-design commented on dev/wp.ts
> +  },
👍

2021-06-18 09:09 UTC, floq-design commented on dev/wp.ts
> +      args: [{}],
Tried changing to `args: {},` but got error for following `option: ...` & `suggestions: ...` so left as is.

`wp cache` has no arguments - only options & subcommands.
https://developer.wordpress.org/cli/commands/cache/

2021-06-18 09:10 UTC, floq-design commented on dev/wp.ts
> +      args: [{}],
Ditto - same as `wp cache`

2021-06-18 09:10 UTC, floq-design commented on dev/wp.ts
> +                  args: { name: "path" },
👍

2021-06-18 09:10 UTC, floq-design commented on dev/wp.ts
> +              args: { name: "path" },
👍

2021-06-18 09:10 UTC, floq-design commented on dev/wp.ts
> +          args: { name: "dirname" },
👍

2021-06-18 19:16 UTC, QuiiBz commented on dev/wp.ts
> +      args: [{}],
Alright, then you can remove it completely

2021-06-19 17:09 UTC, floq-design commented on dev/wp.ts
> +      args: [{}],
Removed all empty `args`

2021-06-21 16:29 UTC, QuiiBz approved these changes
Thank you so much for this contribution!

2021-06-24 07:10 UTC, merged

2021-06-24 07:10 UTC, QuiiBz commented
Merged 🚀 thanks a lot for this one!