add generators
withfig/autocomplete pull request #287
Opened 2021-06-11 20:00 UTC by nagypeterjob

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

- [x] create-app
- [x] create-backend-environment
- [x] create-branch
- [x] create-deployment
- [x] create-domain-association
- [x] create-webhook
- [x] delete-app
- [x] delete-backend-environment
- [x] delete-branch
- [x] delete-domain-association
- [x] delete-job
- [x] delete-webhook
- [x] generate-access-logs
- [x] get-app
- [x] get-artifact-url
- [x] get-backend-environment
- [x] get-branch
- [x] get-domain-association
- [x] get-job
- [x] get-webhook
- [x] list-apps
- [x] list-artifacts
- [x] list-backend-environments
- [x] list-branches
- [x] list-domain-associations
- [x] list-jobs
- [ ] list-tags-for-resource
- [ ] list-webhooks
- [ ] start-deployment
- [ ] start-job
- [ ] stop-job
- [ ] tag-resource
- [ ] untag-resource
- [ ] update-app
- [ ] update-branch
- [ ] update-domain-association
- [ ] update-webhook

2021-06-28 17:49 UTC, QuiiBz requested changes

2021-06-28 17:49 UTC, QuiiBz commented on dev/aws/amplify.ts
> +            ],
Could you move those duplicated suggestions to a top-level const, to avoid duplication? https://github.com/withfig/autocomplete/pull/287/files#diff-533b8bbc7b6f12af0d3b7ce8a31a362291b606b023a770cdd92e02c9a04af56dR638-R641

2021-06-30 21:19 UTC, nagypeterjob commented on dev/aws/amplify.ts
> +            ],
done

2021-07-01 06:37 UTC, QuiiBz approved these changes
Amazing! Again apologize for the delay on those AWS PRs!

2021-07-01 06:37 UTC, merged