feat: enhance yarn workspace
withfig/autocomplete pull request #294
Opened 2021-06-13 07:12 UTC by Nutlope

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature

**What is the current behavior? (You can also link to an open issue here)**
no autocomplete for yarn workspace

**What is the new behavior (if this is a feature change)?**
add autocomplete for yarn workspace

**Additional info:**
- Recorded a [loom video](https://www.loom.com/share/0ca49e6ec5fc4e0f93bdf16b1c23ef1f) to show demo working
- Fulfills #274

2021-06-13 07:34 UTC, QuiiBz commented
Very cool! Just tried out and found an edge case:

If you set the workspaces to something like `packages/*` (which is very common), it will autocomplete `packages/*` instead of the actual packages inside `packages/`:

![Screenshot 2021-06-13 at 09 27 58](https://user-images.githubusercontent.com/43268759/121798956-a6da9380-cc29-11eb-9565-60b618912d74.png)

This is caused by the previous generator here https://github.com/withfig/autocomplete/blob/d92f28fefe9f4b08d93499e373ced23eb2ec3364/dev/yarn.ts#L1005 and so break this new generator too.

It would be really helpful if you could fix this issue along with this neat feature.

2021-06-13 16:12 UTC, Nutlope commented
> Very cool! Just tried out and found an edge case:
> 
> If you set the workspaces to something like `packages/*` (which is very common), it will autocomplete `packages/*` instead of the actual packages inside `packages/`:
> 
> ![Screenshot 2021-06-13 at 09 27 58](https://user-images.githubusercontent.com/43268759/121798956-a6da9380-cc29-11eb-9565-60b618912d74.png)
> 
> This is caused by the previous generator here
> 
> https://github.com/withfig/autocomplete/blob/d92f28fefe9f4b08d93499e373ced23eb2ec3364/dev/yarn.ts#L1005
> 
> and so break this new generator too.
> It would be really helpful if you could fix this issue along with this neat feature.

Thanks! I have no real experience with yarn workspaces so it's interesting to learn about edge cases like this. If I'm understanding this correctly, we want to autocomplete `packages` when workspaces is set to something like `packages/*`? 

If so, would a simple if statement be appropriate in the first generator, to loop through all the workspaces and if any of them are set to `SOMETHING/*`, replace the suggestion with `SOMETHING`?

2021-06-13 17:35 UTC, QuiiBz commented
The `packages/*` notation means « all folders inside packages/ are part of the workspace ». In your example (the loom video), you could put workspace-1 and workspace-2 inside a `packages` folder, and set `workspaces` in the main `package.json` to `packages/*`, and it will do the same.

Did you understand my example and see a bit more how workspaces works?

2021-06-14 04:16 UTC, Nutlope commented
Ahh I see, yes that makes sense. So for the example you just mentioned, if the package.json workspaces were set to `packages/*`, we'd want to autocomplete `yarn workspace` with a list of folders inside the packages folder?
 
So `workspace-1` and `workspace-2` (assuming these are the two folders inside the `packages` folder)?

2021-06-14 06:19 UTC, QuiiBz commented
> Ahh I see, yes that makes sense. So for the example you just mentioned, if the package.json workspaces were set to `packages/*`, we'd want to autocomplete `yarn workspace` with a list of folders inside the packages folder?
> 
> So `workspace-1` and `workspace-2` (assuming these are the two folders inside the `packages` folder)?

Exactly! As you can see it's going to be a bit more challenging than the current implementation. Do not hesitate if you need help.

2021-06-14 16:53 UTC, brendanfalk requested changes

2021-06-14 16:53 UTC, brendanfalk commented on dev/yarn.ts
> +              return `cat ${context[2]}/package.json`;
Rather than `context[2]` I would use `context[context.length-2]`. 

Why? If a user input `yarn -a workspace abc[space]` then `context[2]` would yield `workspace` not `abc`. 

In general, when using script as a function, always work your way backwards in the context array not forwards

2021-06-15 03:30 UTC, Nutlope commented on dev/yarn.ts
> +              return `cat ${context[2]}/package.json`;
Makes perfect sense, thanks for the explanation! Added a commit for this

2021-06-28 17:29 UTC, QuiiBz commented
Hello @Nutlope, do you want to continue working on this PR?

2021-06-28 21:20 UTC, Nutlope commented
Hey @QuiiBz, completely forgot about this, thanks for the reminder! Will work on this later this week.

2021-06-29 07:14 UTC, QuiiBz commented
Alright! Feel free to ask if you need any help.

2021-07-13 01:39 UTC, Nutlope commented
Created a cleaner PR #361 , closing this one

2021-07-13 01:39 UTC, closed without merging