Stripe
withfig/autocomplete pull request #308
Opened 2021-06-17 08:06 UTC by Monkeyank

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Add Stripe Completion Spec
**What is the current behavior? (You can also link to an open issue here)**
#307 
**What is the new behavior (if this is a feature change)?**

**Additional info:**

2021-06-18 06:54 UTC, QuiiBz requested changes
Awesome CLI! I left some comments

2021-06-18 06:54 UTC, QuiiBz commented on dev/stripe.ts
> +    },
I think this can have a template of `filepaths`

2021-06-18 06:54 UTC, QuiiBz commented on dev/stripe.ts
> +  },
We can add `isDangerous` here

2021-06-18 06:54 UTC, QuiiBz commented on dev/stripe.ts
> +          },
Could this arg provide suggestions for the list of events? Looks like they are defined here: https://github.com/withfig/autocomplete/pull/308/files#diff-e38baeee0f96b87459e1901e70e24b9f815f6a3a4ddd9b7e27f811f7dadf4408R508

2021-06-18 06:54 UTC, QuiiBz commented on dev/stripe.ts
> +            "Skip certificate verification when forwarding to HTTPS endpoints",
We can also add `isDangerous` here

2021-06-19 08:07 UTC, QuiiBz commented
Are those suggestions the same?

https://github.com/withfig/autocomplete/pull/308/files#diff-e38baeee0f96b87459e1901e70e24b9f815f6a3a4ddd9b7e27f811f7dadf4408R451-R1235

https://github.com/withfig/autocomplete/pull/308/files#diff-e38baeee0f96b87459e1901e70e24b9f815f6a3a4ddd9b7e27f811f7dadf4408R1296-R1342

2021-06-19 08:09 UTC, Monkeyank commented
> Are those suggestions the same?
> 
> https://github.com/withfig/autocomplete/pull/308/files#diff-e38baeee0f96b87459e1901e70e24b9f815f6a3a4ddd9b7e27f811f7dadf4408R451-R1235
> 
> https://github.com/withfig/autocomplete/pull/308/files#diff-e38baeee0f96b87459e1901e70e24b9f815f6a3a4ddd9b7e27f811f7dadf4408R1296-R1342

They're not the same, because one of them is just all/general events, while the other is specific to webhook events.

2021-06-19 08:19 UTC, QuiiBz commented
> They're not the same, because one of them is providing suggestions for all/general events, while the other is providing suggestions specific to webhook events.

Alright, then it would be better not to duplicate the webhooks events and put them in a top-level const Fig.Suggestion[]. Then, you can use this const for the webhooks events suggestions and spread it for the general events suggestions.

2021-06-20 06:45 UTC, QuiiBz approved these changes
LGTM!

2021-06-21 16:30 UTC, merged