feat: add rustc + cargo rustc spec
withfig/autocomplete pull request #314
Opened 2021-06-19 07:06 UTC by Monkeyank

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature
**What is the current behavior? (You can also link to an open issue here)**
#292 No support for rustc or cargo rustc
**What is the new behavior (if this is a feature change)?**
Adds support for rustc and cargo rustc
**Additional info:**

2021-06-19 07:35 UTC, QuiiBz requested changes
Rustaceans will be very happy to have those specs!

2021-06-19 07:35 UTC, QuiiBz commented on dev/cargo.ts
> +                        "Search for all library kinds in this directory",
I think it's hard to understand the name of the suggestions with this `KIND=`. Let's simply write `dependency`, `crate`, `native`...

2021-06-19 07:35 UTC, QuiiBz commented on dev/cargo.ts
> +                },
Looks like this can have a template of folders?

2021-06-19 07:35 UTC, QuiiBz commented on dev/cargo.ts
> +                    },
Same as above

2021-06-19 07:35 UTC, QuiiBz commented on dev/cargo.ts
> +        description: "Additional files to compile",
Based on this description, it seems that this arg is variadic

2021-06-19 07:35 UTC, QuiiBz commented on dev/cargo.ts
> +          name: "--examples  ",
2 extra spaces

2021-06-19 07:35 UTC, QuiiBz commented on dev/cargo.ts
> +          },
Can this arg have a template of `folders`?

2021-06-19 07:35 UTC, QuiiBz commented on dev/cargo.ts
> +          },
Based on the description, this arg can have a template of `filepaths`

2021-06-19 07:35 UTC, QuiiBz commented on dev/rustc.ts
> +  subcommands: [],
No need to set an empty array if this command doesn't have any subcommands

2021-06-19 07:35 UTC, QuiiBz commented on dev/rustc.ts
> +            },
Same as above for this `KIND=` thing

2021-06-19 07:35 UTC, QuiiBz commented on dev/rustc.ts
> +      },
Looks like this arg can have a template of `folders`

2021-06-19 07:54 UTC, Monkeyank commented on dev/cargo.ts
> +                        "Search for all library kinds in this directory",
The required argument value provided has to be `KIND="type"`, so instead should I change the name to `dependency`, `crate`, `native` ... . Then, add the insert value prop, and add the full value, ex: `KIND=crate`?

2021-06-21 16:33 UTC, QuiiBz commented on dev/cargo.ts
> +                        "Search for all library kinds in this directory",
Agree, that would be better for the users to have a clear and concise name. Let's do this!

2021-06-24 07:02 UTC, QuiiBz approved these changes
LGTM!

2021-06-26 06:48 UTC, merged