[AWS] [Beanstalk] generators
withfig/autocomplete pull request #315
Opened 2021-06-19 10:50 UTC by nagypeterjob

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

- [x] abort-environment-update
- [x] apply-environment-managed-action
- [x] associate-environment-operations-role
- [x] check-dns-availability
- [x] compose-environments
- [ ] create-application
- [ ] create-application-version
- [ ] create-configuration-template
- [ ] create-environment
- [ ] create-platform-version
- [ ] create-storage-location
- [ ] delete-application
- [ ] delete-application-version
- [ ] delete-configuration-template
- [ ] delete-environment-configuration
- [ ] delete-platform-version
- [ ] describe-account-attributes
- [ ] describe-application-versions
- [ ] describe-applications
- [ ] describe-configuration-options
- [ ] describe-configuration-settings
- [ ] describe-environment-health
- [ ] describe-environment-managed-action-history
- [ ] describe-environment-managed-actions
- [ ] describe-environment-resources
- [ ] describe-environments
- [ ] describe-events
- [ ] describe-instances-health
- [ ] describe-platform-version
- [ ] disassociate-environment-operations-role
- [ ] list-available-solution-stacks
- [ ] list-platform-branches
- [ ] list-platform-versions
- [ ] list-tags-for-resource
- [ ] rebuild-environment
- [ ] request-environment-info
- [ ] restart-app-server
- [ ] retrieve-environment-info
- [ ] swap-environment-cnames
- [ ] terminate-environment
- [ ] update-application
- [ ] update-application-resource-lifecycle
- [ ] update-application-version
- [ ] update-configuration-template
- [ ] update-environment
- [ ] update-tags-for-resource
- [ ] validate-configuration-settings
- [ ] wait

2021-06-24 07:00 UTC, QuiiBz requested changes
Huge PR! I left you some comments

2021-06-24 07:00 UTC, QuiiBz commented on dev/aws/elasticbeanstalk.ts
> +              "RefreshedAt",
Looks like there is some duplication with https://github.com/withfig/autocomplete/pull/315/files#diff-2a4ea91ac31625210d11e2a6f87fa5f677d5c8225534a50ff66410b9ce134d51R2092-R2104. Would love to separate the common suggestions in a top-level const (of type `Fig.Suggestion[]`), and spread it where it is used to avoid duplication.

2021-06-24 07:00 UTC, QuiiBz commented on dev/aws/elasticbeanstalk.ts
> +    arr.map((elm) => {
Same as above

2021-06-26 09:04 UTC, nagypeterjob commented on dev/aws/elasticbeanstalk.ts
> +    return list.map((elm) => {
these are generic functions, with generic "elements", but I tried to come up with a more descriptive name

2021-06-26 09:06 UTC, nagypeterjob commented on dev/aws/elasticbeanstalk.ts
> +const postProcessFiles = (out: string, prefix: string): Fig.Suggestion[] => {
I am not sure what you mean by copying. I have checked vue's spec on master and it doesn't even have generators 🤔  Could you elaborate more?

2021-06-28 17:39 UTC, QuiiBz commented on dev/aws/elasticbeanstalk.ts
> +const postProcessFiles = (out: string, prefix: string): Fig.Suggestion[] => {
I was talking about the core VueJS app - the one which is renderer on top of your terminal. Sorry for the misunderstanding!

This app uses a code that is very similar to this function, to suggest files and folders for their respective `template`. I was asking if there here any reason why not using those templates?

2021-06-30 17:04 UTC, QuiiBz approved these changes
Thanks for this huge PR!

2021-06-30 17:05 UTC, merged