Add missing options for git branch spec
withfig/autocomplete pull request #319
Opened 2021-06-22 00:05 UTC by Monkeyank

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Completion Spec Update

**What is the current behavior? (You can also link to an open issue here)**
#312 
`git branch` is currently missing certain options such as `-r`

**What is the new behavior (if this is a feature change)?**
Adds missing options for `git branch`

**Additional info:**

2021-06-24 06:51 UTC, QuiiBz requested changes
The git spec is getting really big! Left you some comments

2021-06-24 06:51 UTC, QuiiBz commented on dev/git.ts
> +              isOptional: true,
Any reason why there is an `isOptional` here?

2021-06-24 06:51 UTC, QuiiBz commented on dev/git.ts
> +          args: [
Looks like we can add an `exclusive: ["-t", "--track"]` here. And the invert for `--track` option

2021-06-24 20:41 UTC, Monkeyank commented on dev/git.ts
> +              isOptional: true,
The 2nd generator is supposed to be commits, which defines the start-point for tracking, which is an optional arg.

2021-06-26 04:45 UTC, mattschrage approved these changes
Looks good to me! 👍

2021-06-26 04:45 UTC, merged