chore(eslint): add no-duplicate-options-subcommands rule
withfig/autocomplete pull request #325
Opened 2021-06-23 16:25 UTC by fedeci

Closes #323 
Failing tests are related as I have not yet updated all the specs. I'll wait for a review to do that.

2021-06-23 17:50 UTC, QuiiBz requested changes

2021-06-23 17:50 UTC, QuiiBz commented on scripts/eslint-plugin-fig-linter/rules/no-duplicate-options-subcommands.js
> +            names.forEach((v) => {
I would prefer a more verbose name for `v` - looks like it's a `node`

2021-06-23 22:06 UTC, mattschrage approved these changes
This is awesome and by the looks of things will help catch a lot of common errors. Thanks so much for contributing @fedeci 🎉

Everything looks good to me. Once you've addressed @QuiiBz's comment, we can get this merged in :)

2021-06-24 06:37 UTC, QuiiBz commented
That's going to be very helpful! Also, before merging this could you run `fig lint:fix` so this new rule can remove the duplicated options/subcommands that are failing right now?

2021-06-24 07:20 UTC, fedeci commented
@QuiiBz nope, I have to do it manually. An autofixer would not make sense in this case because we can't predict which option is correct or wrong.

2021-06-24 07:27 UTC, QuiiBz commented
> @QuiiBz nope, I have to do it manually. An autofixer would not make sense in this case because we can't predict which option is correct or wrong.

You're right, I was thinking about something else. Let's do this so we can get this merged!

2021-06-24 08:47 UTC, fedeci commented on dev/expo-cli.ts
> -        },
It was mentioned twice in the `expo` docs. I guess that this is a secondary result.

2021-06-24 08:47 UTC, fedeci commented on dev/heroku.ts
> -      name: "oauth:create",
This file was such a mess, full of these non-existent commands. I may have missed something. But reviewing 5000 lines of file is mindblowing. We should provide some tool to pretty output current subcommands structure.

2021-06-24 11:55 UTC, QuiiBz commented
There is an issue in the current implementation:

For example, in the `gh` spec, the rule detected `-h` which is an aliase of `--help` - it shouldn't flag aliases.
Same for the `git` spec, the rule detected `-n` from `--dry-run` and `--no-tags`, while those are not in the same subcommand/option.

2021-06-24 13:18 UTC, fedeci commented
@QuiiBz `-h` is not a valid alias for subcommands. 
e.g. `gh repo create`
```bash
FLAGS
  -y, --confirm               Skip the confirmation prompt
  -d, --description string    Description of the repository
      --enable-issues         Enable issues in the new repository (default true)
      --enable-wiki           Enable wiki in the new repository (default true)
  -h, --homepage URL          Repository home page URL
      --internal              Make the new repository internal
      --private               Make the new repository private
      --public                Make the new repository public
  -t, --team name             The name of the organization team to be granted access
  -p, --template repository   Make the new repository based on a template repository

INHERITED FLAGS
  --help   Show help for command
```
Note that just `--help` is inherited.

2021-06-24 13:32 UTC, fedeci commented on dev/git.ts
>            description: "Do nothing; only show what would happen",
`-n` used by `--no-checkout` (git clone)

2021-06-24 13:33 UTC, fedeci commented on dev/git.ts
> +          name: "--no-tags",
`-n` used by `--no-stat`(git pull)

2021-06-24 13:34 UTC, QuiiBz commented
I tough you only removed duplicated options/subcommands caught by this new rule, sorry for this.

2021-06-26 04:27 UTC, mattschrage commented on dev/heroku.ts
> -      name: "oauth:create",
Can you expand on this? There is definitely room to improve the tooling around the completion specs. 

We could definitely add something like this to the repo. Is this what you're imagining?

`npm run list-subcommands <cli>`

2021-06-26 04:34 UTC, mattschrage commented
So this looks good to me. What do you think @cstrnt?

2021-06-28 20:31 UTC, cstrnt reviewed
So the rule itself is pretty awesome! Good job! Also the selector for which looks like css is mindblowing to me! I would prefer splitting up those manual changes to another PR because they are kinda unrelated to the eslint rule

2021-06-28 20:31 UTC, cstrnt commented on dev/heroku.ts
> -      name: "oauth:create",
This was autogenerated from the source code of the heroku cli.

2021-06-28 20:31 UTC, cstrnt commented on dev/psql.ts
> +      name: ["-1", "--single-transaction"],
Uhm was this done by you or the rule?

2021-06-28 20:31 UTC, cstrnt commented on dev/serverless.ts
>      },
This was also done manually, right?

2021-06-29 04:01 UTC, fedeci commented on dev/psql.ts
> +      name: ["-1", "--single-transaction"],
The flag was duplicate and checking on the `psql` docs I discovered it was wrong.

2021-06-29 04:04 UTC, fedeci commented on dev/serverless.ts
>      },
Yes it was, cause I had to remove a duplicate `plugin` subcommand and from what I can understand from the docs it does not only `install/uninstall` plugins.

2021-06-29 04:05 UTC, fedeci commented on dev/heroku.ts
> -      name: "oauth:create",
@mattschrage yes it is

2021-06-30 06:39 UTC, QuiiBz commented
@fedeci could you add back the `heroku` OAuth subcommands that have been removed? Thanks

2021-06-30 07:08 UTC, fedeci commented
Is there any place in the docs that still mentions those? It seems to me that they have been replaced by `client:create...`.

2021-06-30 07:14 UTC, QuiiBz commented
> Is there any place in the docs that still mentions those? It seems to me that they have been replaced by `client:create...`.

Just checked the documentation and you're right, apologize for this.

2021-06-30 07:17 UTC, QuiiBz requested changes

2021-06-30 07:17 UTC, QuiiBz commented on dev/heroku.ts
> -      options: [
This subcommand still exists: https://devcenter.heroku.com/articles/heroku-cli-commands#heroku-run-detached

2021-06-30 07:17 UTC, QuiiBz commented on dev/heroku.ts
> -      options: [
This subcommand still exists: https://devcenter.heroku.com/articles/heroku-cli-commands#heroku-run

2021-06-30 07:17 UTC, QuiiBz commented on dev/heroku.ts
> -      options: [
Those 2 subcommands still exist: https://devcenter.heroku.com/articles/heroku-cli-commands#heroku-clients & https://devcenter.heroku.com/articles/heroku-cli-commands#heroku-clients-info-id

2021-06-30 07:17 UTC, QuiiBz commented on dev/heroku.ts
> -      options: [
This subcommand still exists: https://devcenter.heroku.com/articles/heroku-cli-commands#heroku-authorizations

2021-06-30 07:18 UTC, fedeci commented on dev/heroku.ts
> -      options: [
They was all duplicates.

2021-06-30 07:21 UTC, QuiiBz commented on dev/heroku.ts
> -      options: [
I see, thanks for the clarification.

2021-06-30 07:29 UTC, QuiiBz approved these changes
LGTM!

For more information, the removed subcommands in the `heroku` spec were either duplicated, either renamed in the new versions of the CLI, so everything is good.

2021-06-30 07:40 UTC, fedeci commented on dev/heroku.ts
> -      options: [
You're welcome!

2021-06-30 16:24 UTC, merged