[Ripgrep] Add Completion Spec
withfig/autocomplete pull request #332
Opened 2021-06-28 06:42 UTC by Monkeyank

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature
**What is the current behavior? (You can also link to an open issue here)**
#103 
**What is the new behavior (if this is a feature change)?**
Adds basic Ripgrep completion spec
**Additional info:**

2021-06-28 17:03 UTC, QuiiBz requested changes
Excited about this spec! I left you some comments

2021-06-28 17:03 UTC, QuiiBz commented on dev/rg.ts
> +        variadic: true,
Based on the description, I think this arg can have a `template: ["filepaths", "folders"]`

2021-06-28 17:03 UTC, QuiiBz commented on dev/rg.ts
> +      description: "Seaches case insensitively if the pattern is all lowercase",
Type at `Seaches` -> `Searches`

2021-06-28 17:03 UTC, QuiiBz commented on dev/rg.ts
> +      },
I would love to see the args moved to a top-level const to avoid duplication!

2021-06-28 21:51 UTC, Monkeyank commented on dev/rg.ts
> +        description: "{type}:{attribute}:{value}, ex: `match:fg:magenta`",
The` {type}:{attribute}:{value}` isn't 3 separate arguments, rather it's one argument, and you can supply multiple of these.
Ex:  `rg --colors 'line:bg:yellow' 'match:fg:magenta'`

2021-06-29 18:51 UTC, QuiiBz approved these changes
LGTM!

2021-06-29 18:52 UTC, merged