Add prisma
withfig/autocomplete pull request #347
Opened 2021-07-05 08:05 UTC by xlanex6

Add prisma autocomplete based on CLI docs reference 
https://www.prisma.io/docs/reference/api-reference/command-reference

2021-07-05 14:51 UTC, xlanex6 commented
👍🏻

2021-07-05 17:07 UTC, QuiiBz requested changes
Thanks a lot for this contribution! I left you some comments to resolve before merging this.

Also, could you add `prisma` to this array? https://github.com/withfig/autocomplete/blob/c6c5e9ad75b1d7971b538c28837cf0a154f57fe8/dev/yarn.ts#L130
This is similar to `npx prisma ...`, but for yarn. It allows autocomplete while typing `yarn prisma ...` if the current project has prisma installed.

2021-07-05 17:07 UTC, QuiiBz commented on dev/prisma.ts
> +            },
I would prefer to avoid duplication by using a top-level const of `Fig.Options[]`. The same options are duplicated here: https://github.com/withfig/autocomplete/pull/347/files#diff-5d922d2aefb78ba4c511d31448c65e489ffa0975ca389832ebcb486b6e5d5748R127-R134

2021-07-05 17:07 UTC, QuiiBz commented on dev/prisma.ts
> +              description: "Skip the confirmation prompt",
Same for the `isDangerous` flag

2021-07-05 17:07 UTC, QuiiBz commented on dev/prisma.ts
> +                isOptional: false,
You don't have to specify `isOptional` if the value is false. Same at https://github.com/withfig/autocomplete/pull/347/files#diff-5d922d2aefb78ba4c511d31448c65e489ffa0975ca389832ebcb486b6e5d5748R197 and https://github.com/withfig/autocomplete/pull/347/files#diff-5d922d2aefb78ba4c511d31448c65e489ffa0975ca389832ebcb486b6e5d5748R46

2021-07-05 17:07 UTC, QuiiBz commented on dev/prisma.ts
> +          isDangerous: true,
I don't think we need `isDangerous` here

2021-07-05 17:07 UTC, QuiiBz commented on dev/prisma.ts
> +      subcommands: [
These aren't subcommands but rather options - same for https://github.com/withfig/autocomplete/pull/347/files#diff-5d922d2aefb78ba4c511d31448c65e489ffa0975ca389832ebcb486b6e5d5748R263

2021-07-05 21:48 UTC, xlanex6 commented on dev/prisma.ts
> +      isOptional: true,
By default, is `./schema.prisma` || `./prisma/schema.prisma`, if decide to change default, you have to specify path. 

https://www.prisma.io/docs/reference/api-reference/command-reference#arguments-4

Here's the reason why I suggest `isOptional: true`

2021-07-05 22:02 UTC, xlanex6 commented on dev/prisma.ts
> +          isDangerous: true,
`isDangerous` was here to notice this command is `--preview-feature` on Prisma CLI and is not recommended for use in production environments.

https://www.prisma.io/docs/reference/api-reference/command-reference#db-seed-preview

2021-07-05 22:31 UTC, xlanex6 commented
@QuiiBz 
I made all your suggestions. 
Free to talk about `isOptional` for schema option.  https://github.com/withfig/autocomplete/pull/347#discussion_r664052551

2021-07-06 06:16 UTC, QuiiBz commented on dev/prisma.ts
> +          isDangerous: true,
Thanks for the clarification!

2021-07-06 06:19 UTC, QuiiBz commented on dev/prisma.ts
> +      isOptional: true,
Is it possible to only have the `--schema` option without the path argument? If so, `isOptional` makes sense, but reading the docs makes me think that whenever you specify `--schema`, we need a path argument.

2021-07-06 07:04 UTC, xlanex6 commented on dev/prisma.ts
> +      isOptional: true,
True, my bad.
You're right.

2021-07-06 07:10 UTC, xlanex6 commented
@QuiiBz I remove `isOptional`, you're right. If you provide  `--schema` option, you need to pass file path schema. 
My bad

2021-07-06 07:16 UTC, QuiiBz commented
> @QuiiBz I remove `isOptional`, you're right. If you provide `--schema` option, you need to pass file path schema.
> My bad

That's fine, no worries!

2021-07-06 07:20 UTC, QuiiBz approved these changes
LGTM!

2021-07-07 06:56 UTC, merged