[git] switch subcommand
withfig/autocomplete pull request #352
Opened 2021-07-09 01:19 UTC by Monkeyank

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
`switch` subcommand for `git`

**What is the current behavior? (You can also link to an open issue here)**
#351

2021-07-09 06:29 UTC, QuiiBz requested changes

2021-07-09 06:29 UTC, QuiiBz commented on dev/git.ts
> +          },
Based on the description, it seems like there is another argument named `start-point`

2021-07-09 06:29 UTC, QuiiBz commented on dev/git.ts
> +          },
Same as above

2021-07-09 06:29 UTC, QuiiBz commented on dev/git.ts
> +            "If <branch> is not found but there does exist a tracking branch in exactly one remote (call it <remote>) with a matching name",
Same as about for `branch`

2021-07-09 06:29 UTC, QuiiBz commented on dev/git.ts
> +            "Proceed even if the index or the working tree differs from HEAD. Both the index and working tree are restored to match the switching target",
These options can have an `isDangerous` option

2021-07-09 08:29 UTC, Monkeyank commented on dev/git.ts
> +            "If <branch> is not found but there does exist a tracking branch in exactly one remote (call it <remote>) with a matching name",
I don't think this actually has `args`, but guesses the what the `branch-name` is supposed to be

2021-07-09 16:15 UTC, QuiiBz commented
Could you resolve the conflict so we can get this merged?

2021-07-12 06:55 UTC, QuiiBz approved these changes
LGTM!

2021-07-12 06:55 UTC, merged