Add Django Spec
withfig/autocomplete pull request #354
Opened 2021-07-10 08:21 UTC by wilhelmklopp

**What kind of change does this PR introduce?**
This PR adds the Django spec, meaning auto complete for `django-admin <command>` and `python manage.py <command>`

Closes #298 

**Additional info:**

I originally went down the path of dynamically auto generating this whole spec at runtime based on the help output provided by `django-admin` script. This has the benefit that we'd show suggestions for exactly those commands that are available, including custom-defined management commands. 

But I think there are some problems with that dynamic approach at the moment. Notably, from a user's perspective, it's slower and requires regular manual set up (ie running `fig set:path`). So i've decided to just stick to a fully static spec for now and circle back to the dynamic approach in the future. If you're curious, [this PR](https://github.com/wilhelmklopp/autocomplete/pull/1) contains some of my explorations in the more dynamic world.

I opened a couple of issues that would pave the path a little bit more towards making dynamic at-runtime generated specs work super well:
- https://github.com/withfig/fig/issues/225
- https://github.com/withfig/fig/issues/250

2021-07-11 07:16 UTC, QuiiBz requested changes
Thanks a lot for this big PR! I left some comments to resolve before merging this.

2021-07-11 07:16 UTC, QuiiBz commented on dev/django-admin.ts
> +      name: "PYTHONPATH",
When an argument is a path, you can use the [template](https://fig.io/docs/reference/arg#template) property to provide suggestions for a real path. In this case, the `folders` template can be used!

2021-07-11 07:16 UTC, QuiiBz commented on dev/django-admin.ts
> +          name: "{CRITICAL,ERROR,WARNING,INFO,DEBUG}",
Based on the arg's name, I think we can also add `suggestions` here

2021-07-11 07:16 UTC, QuiiBz commented on dev/django-admin.ts
> +        description: "Display all settings, regardless of their value. In",
Incomplete description?

2021-07-11 07:16 UTC, QuiiBz commented on dev/django-admin.ts
> +        description: "{hash,unified}",
Looks like this option takes an argument. Also, we can provide `suggestions` for `hash` and `unified`

2021-07-11 07:16 UTC, QuiiBz commented on dev/django-admin.ts
> +          name: "{ipython,bpython,python}",
Can this arg have `suggestions`?

2021-07-11 07:16 UTC, QuiiBz commented on dev/django-admin.ts
> +        isOptional: false,
There is no need to specify `isOptional` when the value is `false` - it's assumed by default. Same for underneath

2021-07-11 07:16 UTC, QuiiBz commented on dev/django-admin.ts
> +        },
Does this arg need a path to a folder? If so, we can use a `template` of `folders`

2021-07-11 07:16 UTC, QuiiBz commented on dev/django-admin.ts
> +      })),
Each command will lose other properties such as `args`, `description`, etc. It should be better to spread `command` and keep the `icon` property.

2021-07-11 07:55 UTC, wilhelmklopp commented on dev/django-admin.ts
> +    priority: 49,
Yeah, my intention with setting `49` as a priority is so that these options (which are available for every single subcommand) show up below the options that are specific to each command.

IMHO the command specific options tend to be more relevant than the always-present ones, so should be shown first.

As an example, when I type `python manage.py test ` I care more about options like `--failfast` ( Tells Django to stop running the test suite after first failed test.) or `--keepdb` (Preserves the test DB between runs.) than I care about `--version` or `--verbosity`

2021-07-11 08:04 UTC, wilhelmklopp commented on dev/django-admin.ts
> +      })),
Ah good point! I think I actually don't want subcommands here I want "suggestions", but can still keep around name, description, and icon 💡

2021-07-11 10:15 UTC, wilhelmklopp commented on dev/django-admin.ts
> +      name: "{0,1,2,3}",
Ah sweet, great idea!! 💡

2021-07-11 10:21 UTC, wilhelmklopp commented on dev/django-admin.ts
> +      name: "PYTHONPATH",
ahhh, very cool ⭐ 😎

2021-07-11 10:31 UTC, wilhelmklopp commented on .vscode/settings.json
> +  "editor.formatOnSave": true
So for this one, I am actually intentionally suggesting this as an addition to the `.vscode/settings.json` workspace settings. I think having this set enables a better default, works out-of-the-box editing experience for Fig specs, irrespective of what Fig spec authors already have enabled in their global vscode user settings.

But definitely happy to remove this if you all feel differently. What do you think?

2021-07-11 10:32 UTC, wilhelmklopp commented
Thanks so much for the review @QuiiBz 🙌 

Have made a bunch of improvements and responded to your comments, so I think this is ready for another review 👀

2021-07-11 10:33 UTC, wilhelmklopp commented on dev/django-admin.ts
> +        description: "Display all settings, regardless of their value. In",
good catch! Have fixed this up

2021-07-11 12:37 UTC, QuiiBz commented on .vscode/settings.json
> +  "editor.formatOnSave": true
Agree with you, but I think it should be done in a separate PR. Could you remove this from this PR and open another with this addition?

2021-07-11 12:44 UTC, QuiiBz commented on dev/django-admin.ts
> +    priority: 49,
Thanks for the clarification on this. I'm not 100% sure if it's best to have this, since all options with a priority equal or lower than 49 will always be at the bottom, even if we selected one of those option before. It's very useful to have recently selected options at the top, but with a priority of 49 it will break this feature.

2021-07-11 12:48 UTC, QuiiBz requested changes

2021-07-11 12:48 UTC, QuiiBz commented on dev/django-admin.ts
> +        description: "Nominates the database to use. Defaults to the",
Unfinished sentence?

2021-07-11 12:48 UTC, QuiiBz commented on dev/django-admin.ts
> +        },
Is there a pre-defined list of locales for this option, or can we set anything? It would be cool to have suggestions for it

2021-07-11 12:50 UTC, QuiiBz commented on dev/django-admin.ts
> +      })),
Apologise for this, I didn't saw that it was for the `help` subcommand - it's totally fine like this!

2021-07-11 14:48 UTC, wilhelmklopp commented on dev/django-admin.ts
> +        },
I'm pretty unfamiliar with the Internationalisation piece in Django to be honest. I had a quick look but couldn't find a "definitive" list. This is probably the best I was able to find: https://stackoverflow.com/a/3191729/2162900

2021-07-11 14:56 UTC, wilhelmklopp commented on .vscode/settings.json
> +  "editor.formatOnSave": true
Done ✅ 

https://github.com/withfig/autocomplete/pull/356

2021-07-11 14:59 UTC, wilhelmklopp commented on dev/django-admin.ts
> +    priority: 49,
ahh interesting, yeah that doesn't seem good that it's overriding the "recently selected options" feature.

Is there a way for me to specify that these generic options should have lower priority than the command-specific options, without breaking the recently selected options feature?

2021-07-12 07:03 UTC, QuiiBz commented on dev/django-admin.ts
> +    priority: 49,
Sadly, it's not currently possible. This behavior might change in the future since we are currently porting the core app over to TypeScript, so we might add this feature later. For now, I think we should prioritize what users expected to have: recently selected options at the top (so without a priority <= 49)

2021-07-12 07:06 UTC, QuiiBz commented on dev/django-admin.ts
> +        },
Alright, then I don't think we should add this gigantic list of suggestions!

2021-07-12 13:32 UTC, wilhelmklopp commented on dev/django-admin.ts
> +    priority: 49,
@QuiiBz Just thinking about this one some more:

![image](https://user-images.githubusercontent.com/7718702/125295958-b24ed680-e31d-11eb-92a5-88a70d13879c.png)


Could I get the desired behaviour by:
- removing the current setting of priority 49 for the "always available" options (meaning Fig gives them a default of 50)
- setting the priority of all "command specific" options to **51**

Setting them to 51 means they should show up ahead of the "always available" options, unless those have been used previously, right?

I _think_ this could work 🤞

2021-07-12 13:42 UTC, wilhelmklopp commented on dev/django-admin.ts
> +    priority: 49,
Just implemented this in 52eeecaa6a32bbd2a527ff8fd982975db2fce5dc and it seems to work for me locally 🎉

2021-07-13 00:13 UTC, mattschrage commented on dev/django-admin.ts
> +    priority: 49,
Honestly the number should probably be an implementation detail. We could define constants, like `HIGH`, `MEDIUM`, `LOW`, with `LOW` being the default.

2021-07-13 00:20 UTC, mattschrage commented on dev/django-admin.ts
> +      },
Since this is one or more emails, I don't think it is optional.

```suggestion
      {
        name: "email",
        description: "One or more email addresses to send a test email to.",
        variadic: true,
      },
```

2021-07-13 07:52 UTC, QuiiBz commented on dev/django-admin.ts
> +    priority: 49,
That would be great to implement this feature instead of numbers, which are not very easy to understand.

2021-07-13 08:51 UTC, wilhelmklopp commented on dev/django-admin.ts
> +    priority: 49,
Nice, I like LOW, MEDIUM, HIGH 👍 

For the purposes of this PR, how should we proceed? I'm happy with how it works now, I think it checks all the boxes of what we were looking for – but happy to leave off the priority number entirely for now if you all prefer

2021-07-13 08:54 UTC, wilhelmklopp commented on dev/django-admin.ts
> +      },
Just checked this out 👀 

As I understand it, you're right that it's not optional UNLESS you pass the --managers or --admin options:
```bash
manage.py sendtestemail: error: You must specify some email recipients, or pass the --managers or --admin options.
```

So does that mean it should stay as `isOptional: true`? Or how can this sort of dynamic be best expressed in a Fig spec?

2021-07-13 16:46 UTC, QuiiBz commented on dev/django-admin.ts
> +    priority: 49,
I think your current implementation is fine - it's a bit hacky but it's working really well. We can then update it later if we implement the above constants.

2021-07-13 16:55 UTC, QuiiBz commented on dev/django-admin.ts
> +      },
This could be done using `generateSpec` (see https://fig.io/docs/reference/subcommand#generatespec). This function gives a variable named `context`, which is an array of the previous subcommands/options/args. We could then check if this array includes `managers` or `admin`, and return the corresponding subcommand.

Not sure if my explanation was clear enough - tell me if it wasn't the case!

2021-07-13 17:33 UTC, mattschrage commented on dev/django-admin.ts
> +      },
Ah I see @wilhelmklopp! Thanks for clarifying. I would add a comment here that makes a note of this and keep your original code.

@QuiiBz is right that you could use the under-documented `generateSpec` function on `sendtestemail ` to dynamically configure the value of `isOptional`.  My understanding is that `generateSpec` is somewhat expensive, so I'm not sure if it's worth running it for such a small change. cc @brendanfalk

2021-07-13 18:08 UTC, wilhelmklopp commented on dev/django-admin.ts
> +      },
> I would add a comment here that makes a note of this and keep your original code.

Was just about to write this comment, but then GitHub Copilot started trolling me with its suggestion hahaha 😆 

![image](https://user-images.githubusercontent.com/7718702/125503224-cfe1b77c-4a16-40cc-af5d-c4d602bb9d27.png)

2021-07-13 18:12 UTC, wilhelmklopp commented on dev/django-admin.ts
> +      },
Comment added in ce51309 ✅

2021-07-13 18:38 UTC, mattschrage commented on dev/django-admin.ts
> +    priority: 49,
I agree! Just opened a new issue for this. #364

2021-07-13 18:55 UTC, mattschrage requested changes
Looks good to me! Found 2 small things but after that, lets get this merged in! 🎉

2021-07-13 18:55 UTC, mattschrage commented on dev/django-admin.ts
> +        },
Is this a shell command? If so, add `isCommand: true` and then Fig will continue to provide autocompletion on this argument.
```suggestion
        args: {
          name: "COMMAND",
          isCommand: true,
        },
```

2021-07-13 18:55 UTC, mattschrage commented on dev/django-admin.ts
> +      },
It seems like `--add-location` takes an argument! (I've added it here as a suggestion, but the linter might complain!)

```suggestion
        name: "--add-location",
        description:
          "[{full,file,never}] Controls '#: filename:line' lines. If the option is 'full' (the default if not given), the lines include both file name and line number. If it's 'file', the line number is omitted. If it's 'never', the lines are suppressed (same as --no-location). --add-location requires gettext 0.19 or newer.",
        args: {
           name: "location",
           isOptional: true,
           default: 'full'
           suggestions: [
               { name: "full", description: "the lines include both file name and line number" },
               { name: "file", description: "the line number is omitted" },
               { name: "never", description: "the lines are suppressed (same as --no-location)"},
           ],
        },
      },
```

2021-07-13 19:11 UTC, wilhelmklopp commented on dev/django-admin.ts
> +        },
Just tested this out and it looks like "command" is a bit of a misleading name for this (though it is the one Django uses).

It looks like this takes a python statement and evaluates it, so you can do something like `python manage.py shell -c 'print(2 + 2)'` and it will return `4`

but if you try and do something like `python manage.py shell -c 'echo "hello world"'` it throws a SyntaxError

So that means it should probably stay as it is?

2021-07-13 19:14 UTC, wilhelmklopp commented on dev/django-admin.ts
> +      },
ooo, great catch! ✨

2021-07-14 06:55 UTC, QuiiBz commented on dev/django-admin.ts
> +        },
In this case I think it would be better to not use `isCommand` since it's not a shell command but a python command.

2021-07-16 11:07 UTC, wilhelmklopp commented
This should be ready for a final review @QuiiBz @mschrage 🥳

2021-07-16 11:18 UTC, QuiiBz approved these changes
Thanks @wilhelmklopp, looks good to me!

2021-07-19 18:45 UTC, wilhelmklopp commented
This PR should be ready to merge 💃 – @mschrage want to take a final look?

2021-07-20 05:08 UTC, mschrage approved these changes

2021-07-20 05:08 UTC, merged