[FEAT] Add support for pnpm cli
withfig/autocomplete pull request #357
Opened 2021-07-11 23:38 UTC by kevinfaveri

**What kind of change does this PR introduce? (Bugfix, feature, docs update, ...)**

Feature: this PR introduces support for pnpm cli: https://pnpm.io

**What is the current behavior? (You can also link to an open issue here)**
Fig doesn't support autocomplete for the pnpm cli: https://pnpm.io

**What is the new behavior (if this is a feature change)?**
Autocomplete file `pnpm.ts` added to the repo, introducing support for autocomplete with the pnpm cli: https://pnpm.io/cli/add

**Additional info:**
I tried to cover all places of their docs for the `pnpm cli`, including workspaces support and recursivity. This is done by reusing `constants`. If there is a way we can improve this PR, please suggest it here. It is pretty usable right now, but maybe I missed something that can make this one better.

2021-07-12 07:29 UTC, QuiiBz requested changes
Thanks a lot for this PR, excited to support `pnpm`! I'm not very familiar with it, even if it looks quite similar to `npm` or `yarn`. I left some comments to fix before merging.

Feel free to ask if you need more information on specific options, args, etc

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +    return temp;
Let's remove the `var` and return directly the output of `map`:
```suggestion
      return JSON.parse(out).results.map(
        (item) =>
          ({
            name: item.package.name,
            description: item.package.description,
          } as Fig.Suggestion)
      ) as Fig.Suggestion[];
    } catch (e) {
      return [];
    }
```

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +      \n ndjson - the most verbose reporter. Prints all logs in ndjson format`,
Looks like this option takes an argument, and we can also provide suggestions for it! Here is the documentation for [args](https://fig.io/docs/reference/option#args) and [suggestions](https://fig.io/docs/reference/arg#suggestions)

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +        name: ["--global"],
Not sure about this for `pnpm`, but doesn't this option has an `-g` alias?

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +      debounce: true,
`debounce` is not needed here.

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +      debounce: true,
`debounce` is not needed here.

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +        debounce: true,
`debounce` is not needed here.

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +        debounce: true,
`debounce` is not needed here.

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +        debounce: true,
`debounce` is not needed here.

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +        debounce: true,
`debounce` is not needed here.

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +      debounce: true,
`debounce` is not needed here.

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +      debounce: true,
`debounce` is not needed here.

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +      debounce: true,
`debounce` is not needed here.

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +    debounce: true,
`debounce` is not needed here.

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +      isOptional: true,
Doesn't `pnpm add` always need at least one argument?

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +        ],
I think this should be `suggestions` inside `args`, not multiple args.

The expected behavior is: `pnpm audit --audit-level <low OR moderate OR high OR critical>`
But the current implementation behaves like this: `pnpm audit --audit-level <low> <moderate> <high> <critical>`

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +        args: [{ name: "<public|restricted>" }],
We could also add suggestions here! Also, you can specify directly an `arg` object when there is a single value in the array. `args` allow both an arg object or an array of arg objects.

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +            args: [{ name: "bool" }],
Does this option really take an argument? Usually, booleans options don't take arguments - if the option is specified, CLIs assume that it's `true`, and `false` else.

2021-07-12 07:29 UTC, QuiiBz commented on dev/pnpm.ts
> +            args: [{ name: "<auto | tcp | ipc>" }],
Would love to see suggestions here too!

2021-07-12 19:50 UTC, mattschrage commented on dev/pnpm.ts
> +        args: [{ name: "<public|restricted>" }],
Something like this would work @kevinfaveri

```
args: {
  name: "access",
  suggestions: [ "public", "restricted" ]
}
```

2021-07-13 03:39 UTC, Monkeyank commented on dev/pnpm.ts
> +  script: () => `cat package.json`,
I think it'd be nice to check if there's a package.json in the enclosing directory.

For reference: https://github.com/withfig/autocomplete/blob/05f52678515324618251aa41139d203692aedb19/dev/yarn.ts#L28-L31

2021-07-17 14:17 UTC, kevinfaveri commented on dev/pnpm.ts
> +        name: ["--global"],
It does accept it, but it is not documented https://pnpm.io/cli/add#--global

2021-07-17 14:34 UTC, kevinfaveri commented
Another suggestion while I'm reviewing the PR comments: have suggestions which is just a type, like:
```typescript
--port

args: [
name: 'Port',
suggestion: [
'auto',
ANY_NUMBER
]
]
```

I can think of ANY_NUMBER, ANY_ALPHANUMERIC, ANY_STRING, ANY_BOOLEAN. If the user typed anything other than what is specified in the suggestion, it would trigger a warning like 'suggestion not supported'

2021-07-17 14:37 UTC, kevinfaveri commented on dev/pnpm.ts
> +            args: [{ name: "bool" }],
Yeah. Since it is only bool, we can hide the args here.

2021-07-17 15:08 UTC, kevinfaveri commented
It would be interesting to also have the ability to create new templates so we can reuse generators

2021-07-17 16:56 UTC, kevinfaveri commented
Okay, guys, I did some reorganizing of the code and tackled the review points. 
Everything is working as expected now.

Support for --publish branch arg has been added.

Besides what I suggested above for improving DX, I would:
- Have a 'shared' or 'utils' folder in the dev folder for reusing generators, utility functions, options, subcommands, anything

2021-07-17 17:55 UTC, QuiiBz commented
> Besides what I suggested above for improving DX, I would:
> 
> * Have a 'shared' or 'utils' folder in the dev folder for reusing generators, utility functions, options, subcommands, anything

We are going to implement a very similar feature soon, you will be able to import and export anything across any spec!

2021-07-17 18:01 UTC, QuiiBz commented on dev/pnpm.ts
> +      \n By default, any new package is installed as a production dependency.`,
You can remove every `\n` from the descriptions, since we render them inline

2021-07-17 19:57 UTC, kevinfaveri commented
That's cool to hear, @QuiiBz! Btw I've updated the branch

2021-07-19 12:21 UTC, QuiiBz approved these changes
LGTM, thanks a lot for this spec!

2021-07-19 12:21 UTC, merged