[npx] Local Package Support
withfig/autocomplete pull request #359
Opened 2021-07-13 01:05 UTC by Monkeyank

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature
**What is the current behavior? (You can also link to an open issue here)**
#348

2021-07-13 01:29 UTC, kevinfaveri commented on dev/npx.ts
> +        `until [[ -d node_modules/ ]] || [[ $PWD = '/' ]]; do cd ..; done; ls -1 node_modules/.bin/`
Alternative solution for getting the dependencies...

https://github.com/withfig/autocomplete/pull/357/files#diff-bf5ffaedcd1f66b9d30632707ab23d8b88f80e98c0cd6e797a3b9929c5f20f6fR25

2021-07-13 01:31 UTC, Monkeyank commented on dev/npx.ts
> +        `until [[ -d node_modules/ ]] || [[ $PWD = '/' ]]; do cd ..; done; ls -1 node_modules/.bin/`
Good catch, thanks!

2021-07-13 04:06 UTC, Monkeyank commented on dev/npx.ts
> +        `until [[ -d node_modules/ ]] || [[ $PWD = '/' ]]; do cd ..; done; ls -1 node_modules/.bin/`
In this case I'm not getting dependencies, but the executables from the modules.

2021-07-13 04:11 UTC, Monkeyank commented
Do we want to get rid of subcommand suggestions that we can't load a spec for? 
Ex: `acorn` (which isn't a cli).

2021-07-13 06:49 UTC, QuiiBz commented
Hi, not sure if we really need this. Instead of `yarn <cli>`, `npx <cli>` can be used without any `package.json`, so it will broke this feature.

2021-07-13 06:54 UTC, Monkeyank commented
> Hi, not sure if we really need this. Instead of `yarn <cli>`, `npx <cli>` can be used without any `package.json`, so it will broke this feature.

I thought that the issue referenced in #348, wanted suggestions based on packages installed locally for `npx`. Obviously this doesn't cover everything, because `npx` can also run packages not installed locally.

2021-07-13 07:49 UTC, QuiiBz commented
`npx` already has default subcommands (see https://github.com/withfig/autocomplete/blob/master/dev/npx.ts#L4-L31), so I believe that this feature doesn't change the suggestions.

2021-07-17 06:49 UTC, QuiiBz requested changes

2021-07-17 06:49 UTC, QuiiBz commented on dev/npx.ts
> +        out.split("\n");
Useless split here

2021-07-17 06:49 UTC, QuiiBz commented on dev/npx.ts
> +        ];
We can avoid duplicating those specs with something like this:
```suggestion
        const cli = [...suggestions].reduce((acc, { name }) => [...acc, name], []);
```

2021-07-19 12:22 UTC, QuiiBz commented
Could you fix the conflict so we can get this PR merged in? Thanks!

2021-07-20 06:34 UTC, QuiiBz commented on .github/ISSUE_TEMPLATE/main_issue_template.yml
>  description: All issues relating to specific CLI tools (e.g. `git`, `kubectl`, `chmod`)
Could you remove those modifications in this file? It will be done in #388. After that, we will be ready to merge!

2021-07-20 07:12 UTC, QuiiBz approved these changes
LGTM!

2021-07-20 07:12 UTC, merged

2021-07-20 07:17 UTC, fedeci commented on dev/npx.ts
> +        );
Why not an hash Map? `.has` in constant time complexity while `.includes` is linear.

2021-07-20 10:25 UTC, QuiiBz commented on dev/npx.ts
> +        );
I don't really understand why you want to use a `Set` here. We just need to grab the `name` property of each `suggestions` in an array.

2021-07-20 10:39 UTC, fedeci commented on dev/npx.ts
> +        );
Consider that the complexity of `Array.prototype.includes` is `O(n)`. We are running it `n` times in `filter` so we can estimate about a quadratic time complexity.
Furthermore `[...suggestions]` is an unused copy of all the items in a new array. We should only run a map on top of the existing suggestions. Both get fixed in #394

2021-07-20 10:52 UTC, QuiiBz commented on dev/npx.ts
> +        );
I agree that `cli` can and should be moved to a top-level const instead of being calculated in each `postProcess` call. However, the gain in terms of performances is ridiculous, and I think we should really not focus on over-optimizing stuff, but rather covering as many CLIs as possible (while of course not forgetting to optimize generators)