feat: enhance yarn workspace
withfig/autocomplete pull request #361
Opened 2021-07-13 01:38 UTC by Nutlope

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature

**What is the current behavior? (You can also link to an open issue here)**
no autocomplete for yarn workspace

**What is the new behavior (if this is a feature change)?**
add autocomplete for yarn workspace

**Additional info:**

* Recorded a [loom video](https://www.loom.com/share/0ca49e6ec5fc4e0f93bdf16b1c23ef1f) to show demo working
* Fulfills #274
* Accounted for corner case @QuiiBz mentioned in this [old PR](https://github.com/withfig/autocomplete/pull/294)

2021-07-13 01:45 UTC, Nutlope commented
Hi @QuiiBz, got around to fixing the edge case you mentioned in #294. I ended up using generateSpec to do this. Mind reviewing this PR?

2021-07-13 07:09 UTC, QuiiBz requested changes
I tested it and it works incredibly well, congrats! I left you some comments to resolve before merging

2021-07-13 07:09 UTC, QuiiBz commented on dev/yarn.ts
> +        return scriptKeys;
We can improve this with a `map`:
```suggestion
        return Object.keys(scripts).map(script => ({ name: script }))
```

2021-07-13 07:09 UTC, QuiiBz commented on dev/yarn.ts
> +          const workspaces = packageContent["workspaces"];
We should check if `workspaces` is not undefined to avoid the `try ... catch`

2021-07-13 07:09 UTC, QuiiBz commented on dev/yarn.ts
> +        } as Fig.Spec;
No need to cast as `Fig.Spec`, it's inferred from the `generateSpec` function!

2021-07-13 07:09 UTC, QuiiBz commented on package-lock.json
>  {
Could you reset this file? We use lockfile version 2, not 1

2021-07-14 21:27 UTC, Nutlope commented
Hi @QuiiBz, apologies for the delay! Doing a lot of onboarding stuff this week so it's busy. Thanks for the detailed feedback! I just implemented everything and it's ready for your review again.

2021-07-15 06:58 UTC, QuiiBz approved these changes
LGTM! Excited for this addition, it's going to be really useful!

2021-07-15 07:08 UTC, merged