feat: add eslint completion spec
withfig/autocomplete pull request #362
Opened 2021-07-13 02:09 UTC by fwesss

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
No autocomplete for eslint

**What is the new behavior (if this is a feature change)?**
Autocompletion added for eslint

**Additional info:**

2021-07-13 07:16 UTC, Monkeyank commented on dev/eslint.ts
> +        template: ["folders"],
Should this be `filepaths`?

2021-07-13 07:42 UTC, QuiiBz requested changes
Thanks a lot for this PR, `eslint` is really useful!

Could you also add `eslint` here: https://github.com/withfig/autocomplete/blob/05f52678515324618251aa41139d203692aedb19/dev/yarn.ts#L130 and here: https://github.com/withfig/autocomplete/blob/05f52678515324618251aa41139d203692aedb19/dev/npx.ts#L4

This will allow autocompletion with `yarn eslint` and `npx eslint`!

2021-07-13 07:42 UTC, QuiiBz commented on dev/eslint.ts
> +        default: ".js",
Looks like the environments are defined here: https://eslint.org/docs/user-guide/configuring/language-options#specifying-environments

2021-07-13 07:42 UTC, QuiiBz commented on dev/eslint.ts
> +        default: ".js",
Could you add a `name` property (something like `"extension"`)

2021-07-13 07:42 UTC, QuiiBz commented on dev/eslint.ts
> +    },
We can use the [exclusive](https://fig.io/docs/reference/option#exclusive) property for those options

2021-07-16 15:15 UTC, fwesss commented on dev/eslint.ts
> +        default: ".js",
I've added the envs as static suggestions. The user can also add multiple envs separated by a comma as indicated in the eslint docs.

2021-07-16 15:18 UTC, fwesss commented on dev/eslint.ts
> +        default: ".js",
Name property added

2021-07-16 15:19 UTC, fwesss commented on dev/eslint.ts
> +        template: ["folders"],
That's correct! I've pushed the change.

2021-07-16 16:57 UTC, QuiiBz requested changes

2021-07-16 16:57 UTC, QuiiBz commented on dev/eslint.ts
> +            },
That's smart, but we can avoid running a dummy script using `custom`. This property is a function that also takes the context, and should also return a list of suggestions. Here is an example implementation:
```suggestion
            /*
             * Multiple envs can be set with a ',' seperator.
             * We want to filter over this static list of suggestions
             * so we don't suggest envs that have already been entered.
             * */
            filterTerm: ",",
            trigger: ",",
            custom: async (ctx) => {
              const suggestions = [
                "browser",
                "node",
                "commonjs",
                "shared-node-browser",
                "es6",
                "ecmaVersion",
                "es2017",
                "es2020",
                "es2021",
                "worker",
                "amd",
                "mocha",
                "jasmine",
                "jest",
                "phantomjs",
                "protractor",
                "qunit",
                "jquery",
                "prototypejs",
                "shelljs",
                "meteor",
                "mongo",
                "applescript",
                "nashorn",
                "servicerworker",
                "atomtest",
                "embertest",
                "webextensions",
                "greasemonkey",
              ];

              const currentToken = [ctx[ctx.length - 1]][0];

              // Return suggestions minus those that have already been entered
              return suggestions
                .filter((sugg) => !currentToken.split(",").includes(sugg))
                .map((sugg) => ({ name: sugg }));
            },
```

2021-07-16 18:16 UTC, fwesss commented on dev/eslint.ts
> +            },
Thanks for the suggestion! That's perfect since I was just looking for a way to get the context but didn't care about any actual output. I saw custom in the docs but didn't think to apply it here so that's a helpful example.

2021-07-16 18:23 UTC, Monkeyank commented on dev/eslint.ts
> +      description: "A folder where plugis should be resolved from",
Typo: `plugins`

2021-07-16 18:27 UTC, Monkeyank requested changes

2021-07-16 18:27 UTC, Monkeyank commented on dev/eslint.ts
> +        "Pattern of files to ignore (in addition to those in .eslintignore",
```suggestion
        "Pattern of files to ignore (in addition to those in .eslintignore)",
```

2021-07-16 18:27 UTC, Monkeyank commented on dev/eslint.ts
> +      description: "A folder where plugis should be resolved from",
```suggestion
      description: "A folder where plugins should be resolved from",
```

2021-07-16 19:56 UTC, QuiiBz commented on dev/eslint.ts
> +            // dummy script to get postProcess to execute
You can safely remove this comment since we now use `custom`. After this, I think we will be ready to merge!

2021-07-16 23:39 UTC, fwesss commented on dev/eslint.ts
> +            // dummy script to get postProcess to execute
Just removed the comment. Thanks for being so patient and making sure this was a clean PR. Next one will be much better!

2021-07-17 06:50 UTC, QuiiBz approved these changes
LGTM! Thanks a lot for this amazing PR @fwesss, this is going to be really useful!

2021-07-17 06:50 UTC, merged