Add composer autocompletion spec
withfig/autocomplete pull request #366
Opened 2021-07-13 20:45 UTC by zeo

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
This PR introduces a new autocompletion spec, Composer. Composer is a dependency manager for PHP, you can find more information about it [here](https://getcomposer.org/).

**What is the current behavior? (You can also link to an open issue here)**
There currently is no behavior, as the spec did not exist yet.

**What is the new behavior (if this is a feature change)?**
It adds autocompletion for composer subcommands.

**Additional info:**

2021-07-14 07:08 UTC, QuiiBz requested changes
Whoa, that's really handy to have all the subcommands, options and args generated this way! Thanks a lot for this PR. I left some comments on things to update.

2021-07-14 07:08 UTC, QuiiBz commented on dev/php/composer.ts
> +              name: [option.name, option.shortcut],
Is there always a `shortcut` property defined on each option? This might render `undefined` into Fig if it's not the case.

2021-07-14 07:08 UTC, QuiiBz commented on dev/php/composer.ts
> +      //
Could you add a `console.error(err)` here?

2021-07-14 07:15 UTC, QuiiBz commented
Could you also run the lint script to make sure everything is formatted the good way?

2021-07-15 10:26 UTC, zeo commented on dev/php/composer.ts
> +      debounce: true,
I added it since the existing laravel spec, figured Fig would perform better this way. I'll remove this as it's not the case.

2021-07-15 10:29 UTC, zeo commented on dev/php/composer.ts
> +              name: [option.name, option.shortcut],
After some further looking, it seems that when the shortcut is missing, composer just providers an empty string. I'll modify the code to remove the shortcut if it's empty.

2021-07-15 10:29 UTC, zeo commented on dev/php/composer.ts
> +      //
Yep sure!

2021-07-15 19:04 UTC, QuiiBz approved these changes
LGTM! Thank you a lot, this spec is going to be really useful for PHP developers!

2021-07-15 19:17 UTC, merged