[aws] [configure] prioritize when credentials aren't set up
withfig/autocomplete pull request #368
Opened 2021-07-14 08:14 UTC by Monkeyank

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Enhancement

#321 
**What is the new behavior (if this is a feature change)?**
Prioritizes the `configure` subcommand, when `~/.aws/credentials` or `~/.aws/config` don't exist (user doesn't have credentials set up).

2021-07-14 08:19 UTC, Monkeyank commented
Any suggestions to make this more robust?

Do you think that `aws sts get-caller-identity` might be a better approach in case a user's config/credential files aren't in the default location?

When we use this command, we can check if the user has an account and increase priority based on that.

https://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html

2021-07-15 07:07 UTC, QuiiBz commented
I think `aws sts get-caller-identity` is going to be significantly slower than a `ls`. Is there another way to find the location of the config file?

2021-07-16 14:32 UTC, QuiiBz requested changes

2021-07-16 14:32 UTC, QuiiBz commented on dev/aws.ts
> +          priority: prioritize && 100,
I think it can be cool to have an `alert` icon to visually see that we didn't configured aws yet.

Here is a preview of it:
![Screenshot 2021-07-16 at 16 32 05](https://user-images.githubusercontent.com/43268759/125964072-f882f74a-8544-4c0e-b9f6-a39e5fa8de34.png)

2021-07-16 18:22 UTC, Monkeyank commented
> I think `aws sts get-caller-identity` is going to be significantly slower than a `ls`. Is there another way to find the location of the config file?

I tried `aws configure list-profiles`. Although this is faster than `aws sts get-caller-identity` it still takes a significant amount of time to load. If the config/credentials file is not in the default location, then you have to use an `aws` command to find the location.

2021-07-16 19:54 UTC, QuiiBz commented
Alright. Let's keep `ls` for this. Could you add an alert icon as shown in my review above?

2021-07-17 06:36 UTC, QuiiBz approved these changes
LGTM!

2021-07-17 06:37 UTC, merged