[HUGO] feat: Add spec for Hugo v0.85.0
withfig/autocomplete pull request #370
Opened 2021-07-14 19:24 UTC by danpoynor

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature

**What is the current behavior? (You can also link to an open issue here)**
No autocomplete spec for Hugo CLI commands

**What is the new behavior (if this is a feature change)?**
Adds a comprehensive autocompletion spec for Hugo CLI commands

**Additional info:**
References:
- [Hugo CLI documentation on gohugo.io](https://gohugo.io/commands/)
- [Hugo hugo/tree/master/commands/ source code on github](https://github.com/gohugoio/hugo/tree/master/commands)
- `hugo help` output

2021-07-14 20:16 UTC, QuiiBz requested changes
Thanks a lot for this huge spec! I'm not familiar with Hugo so some points in my review might be wrong.

You can also remove every `insertValue` properties since they are using the default behaviour of Fig.

2021-07-14 20:16 UTC, QuiiBz commented on dev/hugo.ts
> +const config = {
Would love to see a type of `Fig.Option` here! Same for option objects each underneath

2021-07-14 20:16 UTC, QuiiBz commented on dev/hugo.ts
> +  insertValue: "--config {cursor}",
No need to specify `insertValue` here, Fig will handle this behaviour automatically. Same for option objects each underneath

2021-07-14 20:16 UTC, QuiiBz commented on dev/hugo.ts
> +    template: "filepaths",
I think the template here should be `folders` , not `filepaths`

2021-07-14 20:16 UTC, QuiiBz commented on dev/hugo.ts
> +const globalOptions = [
Could you add a type of `Fig.Option[]` here?

2021-07-14 20:16 UTC, QuiiBz commented on dev/hugo.ts
> +  insertValue: '--baseURL="{cursor}"',
Same as above, no need for `insertValue`, and would love to see a `Fig.Option` type! Same for other objects underneath

2021-07-14 20:16 UTC, QuiiBz commented on dev/hugo.ts
> +    name: "hostname and path",
Does this option takes two arguments, hostname and path? Or is it a single argument?

2021-07-14 20:16 UTC, QuiiBz commented on dev/hugo.ts
> +    suggestions: [
I think this arg can be `variadic` (see https://fig.io/docs/reference/arg#variadic)

2021-07-14 20:16 UTC, QuiiBz commented on dev/hugo.ts
> +      { name: "true", icon: "✅" },
This is kind of strange. Usually, those options doesn't takes an argument at all. If the option is present, the cli assume that its value is true, and false else. I'm not very familiar with Hugo, so is this the expected behaviour?

2021-07-14 20:16 UTC, QuiiBz commented on dev/hugo.ts
> +          insertValue: "--maxDeletes {cursor}",
No need for `insertValue` here, same for other options underneath

2021-07-14 20:16 UTC, QuiiBz commented on dev/hugo.ts
> +                  { name: "bash", description: "default" },
We can add a `default` property of `bash` in this arg!

2021-07-14 20:16 UTC, QuiiBz commented on dev/hugo.ts
> +                  { name: "friendly", description: "default" },
Same as above

2021-07-14 20:16 UTC, QuiiBz commented on dev/hugo.ts
> +            },
Can those args have a template of `folders` or `filepaths`?

2021-07-14 20:16 UTC, QuiiBz commented on dev/hugo.ts
> +                name: "format",
Could we have suggestions for the format option?

2021-07-15 00:23 UTC, danpoynor commented on dev/hugo.ts
> +                  { name: "bash", description: "default" },
@QuiiBz When I add the `default` property I don't see anything indicating that bash is the default value. I'm not sure what I'm suppose to see when using that property though.

Using the description property to literally state what the default is might be more user friendly.

2021-07-15 00:37 UTC, danpoynor commented on dev/hugo.ts
> +  insertValue: "--config {cursor}",
@QuiiBz If I remove the `insertValue` property, users are required to type a `space` before the `template` property is invoked - which doesn't seem as automated as could be.

If I leave the `insertValue` property, users are not required to enter a `space` and the `template` is automatically invoked - which seems more like a more automated behavior.

I'm not sure if removing `insertValue` (so the ux is less automated) is a Fig standard or a preference.

2021-07-15 05:23 UTC, mattschrage commented on dev/hugo.ts
> +import { stdout } from "node:process";
Seems like this was imported accidentally?

2021-07-15 06:52 UTC, QuiiBz commented on dev/hugo.ts
> +  insertValue: "--config {cursor}",
All other specs don't use `insertValue` for this behaviour. I don't think that's an issue to press space - and not adding a space also make it easy to come back and edit the inserted value in case of a mistake. cc @mattschrage

2021-07-15 16:50 UTC, danpoynor commented on dev/hugo.ts
> +                  { name: "bash", description: "default" },
@QuiiBz `default: "bash"` added. I'm not sure if it's doing what it's suppose to do though (not sure how to test this).

2021-07-15 16:59 UTC, danpoynor commented
@QuiiBz Thanks for the thorough review and feedback!

I think all the issues are resolved if you could take another look.

2021-07-15 18:13 UTC, mschrage commented on dev/hugo.ts
> +  insertValue: "--config {cursor}",
If the argument that the `--config` flag takes is not optional, Fig will automatically insert a space for the user.

2021-07-15 18:59 UTC, QuiiBz requested changes

2021-07-15 18:59 UTC, QuiiBz commented on dev/hugo.ts
> +        { name: "true", icon: "✅" },
I'm still wondering about this. Usually, those options don't take an argument at all. If the option is present, the cli assumes that its value is true, and false else. I'm not very familiar with Hugo, so is this the expected behavior?

2021-07-15 18:59 UTC, QuiiBz commented on dev/hugo.ts
> +    insertValue: "--config=",
You can safely remove every `insertValue` in this spec, as mentioned in the previous review.

2021-07-16 07:16 UTC, QuiiBz approved these changes
LGTM!

2021-07-16 07:18 UTC, merged