Git prioritize unstaged files
withfig/autocomplete pull request #380
Opened 2021-07-15 21:54 UTC by dereklowlind

This adds the ability to prioritize unstaged files in the suggestions for git add. This feature was suggested in https://github.com/withfig/autocomplete/issues/376

2021-07-16 07:13 UTC, QuiiBz requested changes
Cool change! Left some simplifications changes

2021-07-16 07:13 UTC, QuiiBz commented on dev/git.ts
> +        }
We can simplify since by assigning directly `alreadyAdded`:
```suggestion
        // From "git status --short"
        // M  dev/github.ts // test file that was added
        //  M dev/kubectl.ts // test file that was not added
        // A  test2.txt // new added and tracked file
        // ?? test.txt // new untracked file
        const alreadyAdded = file.charAt(0) === "M" || file.charAt(0) === "A";
```

2021-07-16 07:13 UTC, QuiiBz commented on dev/git.ts
> +          }
Same as above:
```suggestion
          // If the current file already is already added
          // we want to lower the priority
          const priority = item.alreadyAdded || context.some(ctx => ctx.includes(file))
            ? 50
            : 100;
```

2021-07-16 08:31 UTC, fedeci approved these changes

2021-07-16 08:31 UTC, fedeci commented on dev/git.ts
> +          // If the current file already is already added
typo:
```suggestion
          // If the current file is already added
```

2021-07-16 08:31 UTC, fedeci commented on dev/git.ts
> +          alreadyAdded: alreadyAdded,
nitpick:
```suggestion
          alreadyAdded,
```

2021-07-16 08:31 UTC, fedeci commented on dev/git.ts
> +            priority: priority,
nit:
```suggestion
            priority,
```

2021-07-16 18:10 UTC, Monkeyank commented
While we're doing this can we also change `git status --short` to `git status --porcelain`?

<img width="664" alt="Screen Shot 2021-07-16 at 11 08 42 AM" src="https://user-images.githubusercontent.com/40261054/125990914-d79f2147-258e-4a5f-a631-c3c87ca82d3d.png">

2021-07-16 18:47 UTC, dereklowlind commented
@Monkeyank yes the --porcelain change can totally be made! The output is very similar but the file paths displayed are different
![image](https://user-images.githubusercontent.com/38629827/125993858-c6192603-19bc-4382-99bf-70873eb200c2.png)

Is there a way to change the fig suggestion window size? This is only a problem for repos like this bazel tutorial one with a lot of sub directories but it leads to not being able to read the file name.
-- with git status --short
![image](https://user-images.githubusercontent.com/38629827/125994574-df695565-d70c-4df6-8ee0-0c092566e585.png)
-- with git status --porcelain
![image](https://user-images.githubusercontent.com/38629827/125994672-77095ac4-e54a-40cc-a103-158171f467b1.png)

2021-07-16 18:53 UTC, Monkeyank commented
@dereklowlind 
On second thought I think the way the paths are displayed are better in `--short`. I think we can separate this into a different PR if we'd like to to do this in the future.

Also you can change your own Fig window size through the settings!

2021-07-18 06:36 UTC, dereklowlind commented
@QuiiBz I merged in your suggested changes. Do you have to rereview them for the pull request to get merged?

2021-07-19 12:50 UTC, QuiiBz requested changes

2021-07-19 12:50 UTC, QuiiBz commented on dev/git.ts
> +        const alreadyAdded = file.charAt(0) === "M" || file.charAt(0) === "A";
This might be a bit overkill but we can simplify it with:
```suggestion
        const alreadyAdded = ["M", "A"].includes(file.charAt(0));
```

2021-07-19 21:05 UTC, dereklowlind commented on dev/git.ts
> +        const alreadyAdded = file.charAt(0) === "M" || file.charAt(0) === "A";
You're making Linus Torvalds proud! 😄

2021-07-20 06:28 UTC, QuiiBz approved these changes
LGTM! Thanks a lot for this fix!

2021-07-20 06:29 UTC, merged