[git] [diff] Suggest staged & unstaged files
withfig/autocomplete pull request #386
Opened 2021-07-17 00:49 UTC by Monkeyank

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature Enhancement
**What is the current behavior? (You can also link to an open issue here)**
#374 
**What is the new behavior (if this is a feature change)?**
Adds staged & unstated file suggestions to `git diff`

2021-07-17 07:00 UTC, QuiiBz requested changes

2021-07-17 07:00 UTC, QuiiBz commented on dev/git.ts
> +    postProcess: (out, context) => {
Looks like this `postProcess` is the same as above. Would love to see this moved to a top-level const and be used as a variable here and above, instead of duplicating it.

2021-07-18 00:47 UTC, Monkeyank commented on dev/git.ts
> +        return { working: arr[0], file: arr.slice(1).join(" ").trim() };
This makes the `arr` into a string and then gets rid of the spaces.

2021-07-18 00:51 UTC, Monkeyank commented
Converting this to a draft, while I improve the speed (combine generators).

2021-07-19 12:42 UTC, QuiiBz approved these changes
LGTM!

2021-07-19 12:42 UTC, merged