feat: fix bugs in npm uninstall
withfig/autocomplete pull request #392
Opened 2021-07-20 00:26 UTC by Nutlope

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
- Bug fixes

**What is the current behavior? (You can also link to an open issue here)**
- Various bugs

**What is the new behavior (if this is a feature change)?**
- Add aliases of npm uninstall
- Changed icon & description of npm uninstall to make more sense
- Made npm uninstall variatic to process multiple uninstalls
- Fixed bug with npm uninstall not working with packages including @, by using a displayName

**Additional info:**
- Addresses #390 and #391

2021-07-20 06:49 UTC, QuiiBz requested changes
Nice fixes! I left some code improvement suggestions, feel free to discuss about them

2021-07-20 06:49 UTC, QuiiBz commented on dev/npm.ts
> +const npmInstallOptions = [
Would love to see a  `Fig.Option[]` type here!

2021-07-20 06:49 UTC, QuiiBz commented on dev/npm.ts
> +  },
I personally use yarn, but I think you forgot the `-P` option for peerDependencies

2021-07-20 06:49 UTC, QuiiBz commented on dev/npm.ts
>      },
Instead of duplicating those subcommands (uninstall, remove, rm, r), we can set the `name` property to an array. Those will represent the aliases of the subcommands, in this case:
```ts
{
  name: ["uninstall", "remove", "rm", "r"],
  description: "Remove a package",
  ...
```

2021-07-20 06:49 UTC, QuiiBz commented on dev/npm.ts
> +          .filter(function (pkg) {
Small improvement:
```suggestion
        return Object.keys(dependencies);
          .filter((pkg) => {
```

2021-07-20 06:49 UTC, QuiiBz commented on dev/npm.ts
> +            };
Small improvement:
```suggestion
          .map((name) => {
            const scope = name.indexOf("/") + 1;
            const version = name.indexOf("@");
            const displayName =
              (scope !== -1 ? name.substring(scope) : name) ||
              (version !== -1 ? name.substring(version) : name);
            return {
              name,
              displayName,
              description: "dependency",
            };
```

2021-07-20 06:49 UTC, QuiiBz commented on dev/npm.ts
> +            return !isListed;
I think we can simplify this a bit, not tested but something like:
```suggestion
            const isListed = context.some((current) => current === pkg);
            return !isListed;
```

2021-07-20 07:03 UTC, fedeci commented on dev/npm.ts
> +            return !isListed;
It is also strange that the iteration was starting with `i = 3` 🤔

2021-07-20 07:14 UTC, QuiiBz commented on dev/npm.ts
> +            return !isListed;
> It is also strange that the iteration was starting with `i = 3` 🤔

I think it's because we want to skip the first two tokens, which are `npm <uninstall/remove/rm/r>`

2021-07-20 07:21 UTC, fedeci commented on dev/npm.ts
> +            return !isListed;
I thought at that but I believe it is fairly confusing.

2021-07-20 18:22 UTC, Nutlope commented on dev/npm.ts
> +  },
I looked into it and the -P option seems to be for just saving as a regular dependency, so it's the default behavior. So unless I'm mistaken, it doesn't seem to be necessary?

2021-07-20 18:25 UTC, Nutlope commented on dev/npm.ts
>      },
Yes but the user experience isn't great when we do this so I explicitly did them separately. See the example below. What do you think?
![image](https://user-images.githubusercontent.com/63742054/126376130-47fac130-3a31-4f63-a46b-1e7bfb7427c5.png)

2021-07-20 18:35 UTC, Nutlope commented on dev/npm.ts
> +            return !isListed;
Wow @QuiiBz, great suggestion! I swear I learn something new every time you review my PRs, thanks for making me a better JS programmer! @fedeci yeah, I wanted to skip the first 2 tokens but agreed, it is definitely confusing. Replacing with Tom's suggestion :)

2021-07-21 06:31 UTC, QuiiBz commented on dev/npm.ts
> +            return !isListed;
Thanks for those kind words @Nutlope!

2021-07-21 06:32 UTC, QuiiBz commented on dev/npm.ts
>      },
Personally, I don't think that is an issue. cc @cstrnt

2021-07-21 06:37 UTC, QuiiBz commented on dev/npm.ts
> +  },
Found this in the docs, looks like it's not really documented, but `--save-peer` does exist. You're right for `-P`, it's an alias for `--save-prod`, sorry for this! So let's add the `--save-peer` option

<img width="627" alt="Screenshot 2021-07-21 at 08 35 02" src="https://user-images.githubusercontent.com/43268759/126442497-ac4982c8-bee7-4e2e-9b75-eeee2d2ff1a9.png">

2021-07-21 10:12 UTC, fedeci commented on dev/npm.ts
> +          })
nit:
```suggestion
          .filter((pkg) => !context.some((current) => current === pkg))
```

2021-07-21 17:43 UTC, QuiiBz commented on dev/npm.ts
> +          })
Agree for the arrow function, but we should keep `isListed` - we understand better what's happening.

Just a quick note, we can use `every` instead of `some` to remove the logical NOT.

2021-07-21 18:07 UTC, fedeci commented on dev/npm.ts
> +          })
I agree on the `every` but would use a comment to understand what we are doing.

2021-07-26 23:38 UTC, Nutlope commented on dev/npm.ts
> +  },
Looked into --save-peer, it seems like it doesn't do anything. It's both not documented and doesn't save a package as a peer dependency (just tested it out with a new project). So seems a bit useless to add a command that doesn't actually do anything & is not documented, unless i'm missing something. Thoughts?

2021-07-26 23:43 UTC, Nutlope commented on dev/npm.ts
>      },
It's a very used command so I think it's better to separate. Gonna keep it like this for now

2021-07-27 00:17 UTC, merged