feat: add gcc skeleton
withfig/autocomplete pull request #396
Opened 2021-07-21 03:32 UTC by Nutlope

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature
**What is the current behavior? (You can also link to an open issue here)**
no gcc spec
**What is the new behavior (if this is a feature change)?**
gcc spec!
**Additional info:**

2021-07-21 06:52 UTC, Monkeyank requested changes
Good first pass! There's a lot of descriptions missing for options. Also add suggestions, defaults, and template suggestions (filepaths/folders) as needed!

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +        "Static analyzer report output format (html|plist|plist-multi-file|plist-html|sarif|text).",
`html|plist|plist-multi-file|plist-html|sarif|text` Make these suggestions for the arg

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +        " OpenCL only. Sets -cl-finite-math-only and -cl-unsafe-math-optimizations, and defines __FAST_RELAXED_MATH__.",
Delete extra spaces at the start of strings (applies to multiple spots in the PR)

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "directory", description: "directory" },
Add a template of `folders`

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "file", description: "file" },
Add a `template` of `filepaths`

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +    { name: "-fcaret-diagnostics", description: " " },
Add description

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "directory", description: "directory", isOptional: true },
`template: "folders"`

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "value", description: "value" },
template of folders

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "value", description: "value" },
Add a template

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +    { name: "-fgnu-inline-asm", description: "" },
Add description

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "value", description: "value" },
Add `default: "4.2.1"` to args

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "value", description: "value", isOptional: true },
Suggestions of `full` or `thin`

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "<name", description: "<name" },
Template of `filepaths`

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "file", description: "file" },
Template of `filepaths`

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "file", description: "file" },
Template of `filepaths`

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "value", description: "value" },
Suggestions for `best` and `all`

2021-07-21 06:52 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "value", description: "value" },
Add 
` 
default: "uninitialized",
suggestions: ["uninitialized", "pattern"]
`

2021-07-21 07:00 UTC, QuiiBz requested changes
That's such a huge spec! I reviewed the first part of it (0-1k lines), most of the issues are missing `template` so it should be very quick to resolve

2021-07-21 07:06 UTC, Monkeyank requested changes

2021-07-21 07:06 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "value", description: "value" },
Template of `filepaths`

2021-07-21 07:06 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "value", description: "value" },
suggestions of `12`, `24`, `32`, `48`
You can also provide descriptions for suggestions (like this one), but you don't always have to!

2021-07-21 07:06 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "value", description: "value" },
Template of `filepaths`

2021-07-21 07:06 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "file", description: "file" },
Template of `filepaths`

2021-07-21 07:06 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "value", description: "value" },
template

2021-07-21 07:06 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "value", description: "value" },
Template of `filepaths` (also variadic)

2021-07-21 07:07 UTC, Monkeyank commented
I also prob missed a lot of the `suggestions` and `templates` to add to options, so please make sure to go through all of them!

2021-07-21 17:29 UTC, Nutlope commented
Thanks so much for the detailed review @Monkeyank and @QuiiBz! Have some higher priority stuff I'm working on rn but will address these updates later this week

2021-07-26 20:18 UTC, Nutlope commented on dev/gcc.ts
> +      name: "-ffixed-x14",
I guess we could but any specific advantage to doing it that way? It seems like loading the spec will take longer with running a for loop as opposed to having them hardcoded.

2021-07-26 20:19 UTC, Nutlope commented
@QuiiBz @Monkeyank ready for your re-review. Addressed nearly all your comments besides descriptions (~50 missing descriptions, not in the --help file and not easily findable online so I think I'll just keep them blank).

2021-07-27 06:30 UTC, QuiiBz commented on dev/gcc.ts
> +      name: "-ffixed-x14",
We can use both, a for loop shouldn't be slow and even noticeable for the end-users.

2021-07-28 05:44 UTC, Monkeyank requested changes

2021-07-28 05:44 UTC, Monkeyank commented on dev/gcc.ts
> +      description: "CUDA installation path",
`template` of `folders` ?

2021-07-28 05:44 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "value", description: "value", suggestions: ["-"] },
Template of `filepaths`?

2021-07-28 05:44 UTC, Monkeyank commented on dev/gcc.ts
> +      args: { name: "value", description: "value" },
Template of folders?

2021-07-28 17:33 UTC, Nutlope commented
Thanks for the additional review @Monkeyank! Addressed all your changes

2021-07-28 17:33 UTC, merged