[gradle] Add Spec
withfig/autocomplete pull request #399
Opened 2021-07-22 07:06 UTC by Monkeyank

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature
**What is the new behavior (if this is a feature change)?**
Adds `gradle` spec. (Although `./gradlew` doesn't work 😢)

2021-07-23 06:45 UTC, QuiiBz requested changes
Entering the Java world! Almost a perfect PR, but I think we should add a generator for the tasks. See the comment on this below

2021-07-23 06:45 UTC, QuiiBz commented on dev/gradle.ts
> +        "enable color and other rich output like the rich, but output task names and outcomes at the lifecycle log level, as is done by default in Gradle 3.5 and earlier",
```suggestion
        "Enable color and other rich output like the rich, but output task names and outcomes at the lifecycle log level, as is done by default in Gradle 3.5 and earlier",
```

2021-07-23 06:45 UTC, QuiiBz commented on dev/gradle.ts
> +  // name: ["gradle", "./gradlew"],
I think gradlew should be in a separate spec

2021-07-23 06:45 UTC, QuiiBz commented on dev/gradle.ts
> +  // There isn't a generator for gradle tasks (takes too long)
We can read the `build.gradle` file and put a regex to find all the tasks - I don't think that would be slow

2021-07-23 21:42 UTC, Monkeyank commented on dev/gradle.ts
> +  // There isn't a generator for gradle tasks (takes too long)
I don't think the build.gradle contains all the tasks. At least based on some of my projects that I've checked out

2021-07-24 08:29 UTC, QuiiBz commented on dev/gradle.ts
> +  // There isn't a generator for gradle tasks (takes too long)
Yes, we can add the default tasks as suggestions and additional tasks from the build.gradle file using a generator

2021-08-05 09:42 UTC, QuiiBz approved these changes
LGTM!

2021-08-05 09:42 UTC, merged