Add Flutter 2.0.1 CLI Autocompletion
withfig/autocomplete pull request #40
Opened 2021-03-11 09:19 UTC by ampersanda

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
Flutter 2.0.1 command autocompletion is not implemented yet

**What is the new behavior (if this is a feature change)?**
Add Flutter 2.0.1 command autocompletion

**Additional info:**
None

2021-03-19 23:24 UTC, rolandtshen commented on specs/flutter.js
> +                deviceTimeout,
looks like the docs say there's a -d option that takes a device id as an argument

2021-03-19 23:26 UTC, rolandtshen commented on specs/flutter.js
> +                },
These seem to be suggestions that would go under a suggestions array in the args object, instead of options

2021-03-19 23:34 UTC, rolandtshen requested changes

2021-03-19 23:34 UTC, rolandtshen commented on specs/flutter.js
> +                    description: "Specify the type of project to create. [app]                (default) Generate a Flutter application. [module]             Generate a project to add a Flutter module
Large spacing

2021-03-19 23:34 UTC, rolandtshen commented on specs/flutter.js
> +                    description: "Set how to print test results.\n[compact] (default)         A single line, updated continuously.\n[expanded]                  A separate line for each update.\n[json
large spacing

2021-03-20 05:20 UTC, ampersanda commented on specs/flutter.js
> +                deviceTimeout,
Oh yeah, I missed that, I should better use `globalOpts` instead.

2021-03-20 05:33 UTC, ampersanda commented on specs/flutter.js
> +                    description: "Set how to print test results.\n[compact] (default)         A single line, updated continuously.\n[expanded]                  A separate line for each update.\n[json
Thanks for pointing out. Removed in latest commit 👏

2021-03-20 05:33 UTC, ampersanda commented on specs/flutter.js
> +                    description: "Specify the type of project to create. [app]                (default) Generate a Flutter application. [module]             Generate a project to add a Flutter module
Removed in latest commit

2021-03-20 05:33 UTC, ampersanda commented on specs/flutter.js
> +                },
Ah sure, I replaced this to `suggestions` instead of `options` in the latest commit

2021-03-25 23:37 UTC, rolandtshen commented
Thanks for making the changes! This was a big PR so thanks for the awesome contribution

2021-03-25 23:37 UTC, merged