[xcodebuild] Add Spec
withfig/autocomplete pull request #414
Opened 2021-07-28 23:27 UTC by Monkeyank

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the new behavior (if this is a feature change)?**
Adds `xcodebuild`
**Additional info:**

2021-07-28 23:39 UTC, fedeci reviewed
This command is also available as an `xcrun` subcommand, we should also add it there.

2021-07-29 07:28 UTC, QuiiBz requested changes
Mostly uppercase at the beginning of sentences to fix

2021-07-29 07:28 UTC, QuiiBz commented on dev/xcodebuild.ts
> +        name: "ARCH",
Could we provide suggestions for the arch?

2021-07-29 07:28 UTC, QuiiBz commented on dev/xcodebuild.ts
> +      description: "turn the undefined behavior sanitizer on or off",
```suggestion
      description: "Turn the address sanitizer on or off",
      args: {
        name: "mode",
        suggestions: ["YES", "NO"],
      },
    },
    {
      name: "-enableThreadSanitizer",
      description: "Turn the thread sanitizer on or off",
      args: {
        name: "mode",
        suggestions: ["YES", "NO"],
      },
    },
    {
      name: "-enableUndefinedBehaviorSanitizer",
      description: "Turn the undefined behavior sanitizer on or off",
```

2021-07-29 07:28 UTC, QuiiBz commented on dev/xcodebuild.ts
> +      description: "turn code coverage on or off when testing",
```suggestion
        "Specifies a path to a plist file that configures archive exporting",
      args: {
        name: "PATH",
        template: "filepaths",
      },
    },
    {
      name: "-enableCodeCoverage",
      description: "Turn code coverage on or off when testing",
```

2021-07-29 07:28 UTC, QuiiBz commented on dev/xcodebuild.ts
> +        "Constrains testing by specifying tests to exclude, but including other tests",
Can this option exclude `-only-testing:` and `-only-testing`?

2021-07-29 07:28 UTC, QuiiBz commented on dev/xcodebuild.ts
> +        "Which implementation to use for Git operations (system/xcode)",
I think this option takes an arg

2021-07-30 13:12 UTC, QuiiBz approved these changes
LGTM!

2021-07-30 13:12 UTC, merged