[expo cli] auto generate scheme
withfig/autocomplete pull request #419
Opened 2021-07-29 20:29 UTC by EvanBacon

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

The `expo` and `expo-cli` schemas were a bit behind and lacking in features. Given the size of the expo-cli, we have a script that we use to generate the documentation, I've updated that script to support generating a fig file automatically https://github.com/expo/expo-cli/pull/3727 -- the test plan in the expo-cli PR applies to this PR as well. 

**Additional info:**

Some notes about my experience:

 - `xcodebuild -project ios/*.xcodeproj -list -json` doesn't always work when run in the generator, not sure how to debug or improve this. The closest comparison I can think of is VSCode's toast element which shows errors that don't really have a dedicated UI space.
 - The API `https://api.npms.io/v2/search` (based on the npm and yarn files) isn't very robust, it can't find packages like `expo-camera` (failing after `expo-c`). If there's a better API, I'd be happy to implement that.
- `expo run:ios --device` takes too long to load devices, a cold run of Apple's `time xcrun xctrace list devices` can take upwards of 10s (11.822s just now). Because `--device` is optional, other options are loaded in and the devices never show up. Perhaps fig could provide some async API for presenting loading options.
- The [icon docs](https://fig.io/docs/reference/suggestion/icon-api) say to open an issue for missing icons. As you may notice, I use a lot of different icons here. Could be nice to have icons for: login/logout/whoami, cloud/publish, help (--help), version (--version), true/false, number (for port and max-workers), skip (for things like no-install, and yes), and maybe something destructive for clear, and clean type options.
  - I attempted to make a "number" icon using `fig://template?color=2ecc71&badge=#` but it doesn't work, the `#` symbol doesn't render.

All-in-all, I'm really impressed with the DX/contributing of this repo and think the team has done a great job!

2021-07-30 04:56 UTC, Monkeyank requested changes
Great PR! Really liked how you used `yarn introspect fig`. 

There's a few places where I believe you can add suggestions for filepaths. If you could just go through once and change those up, that'd be great.

Also I think you can move repeating options/args to top level consts, but since this spec is being generated automatically by `yarn introspect fig` you don't have to bother with it.

@QuiiBz Will probably have some additional comments 🙂

2021-07-30 04:56 UTC, Monkeyank commented on dev/expo-cli.ts
> +          },
Add `suggestions: ["archive", "simulator"]

2021-07-30 04:56 UTC, Monkeyank commented on dev/expo-cli.ts
> +            ],
Can we create a top level const encompassing this arg so we can reuse it!

2021-07-30 04:56 UTC, Monkeyank commented on dev/expo-cli.ts
> +            "Path to your Distribution Certificate P12 (set password as EXPO_IOS_DIST_P12_PASSWORD environment variable).",
Seems like this argument should be taking a path rather than a boolean.
Add `template: "filepaths"` and remove the other suggestions.

2021-07-30 04:56 UTC, Monkeyank commented on dev/expo-cli.ts
> +          description: "Path to your Push Key .p8 file.",
Seems like this argument should be taking a path rather than a boolean.
Add `template: "filepaths"` and remove the other suggestions.

2021-07-30 04:56 UTC, Monkeyank commented on dev/expo-cli.ts
> +          description: "Path to your Provisioning Profile.",
Seems like this argument should be taking a path rather than a boolean.
Add `template: "filepaths"` and remove the other suggestions.

2021-07-30 04:56 UTC, Monkeyank commented on dev/expo-cli.ts
> +          description: "Path to your Keystore.",
Seems like this argument should be taking a path rather than a boolean.
Add `template` and remove the other suggestions.

2021-07-30 05:05 UTC, Monkeyank requested changes

2021-07-30 05:05 UTC, Monkeyank commented on dev/expo-cli.ts
> +            isOptional: false,
Specifying: `isOptional: false`, isn't required as that's the default.

2021-07-30 05:05 UTC, Monkeyank commented on dev/expo-cli.ts
> +            isOptional: false,
`suggestions: ["app-bundle", "apk"]`

2021-07-30 13:29 UTC, QuiiBz commented
Thanks a lot for this PR! Some toughts on your feedback:

> * `expo run:ios --device` takes too long to load devices, a cold run of Apple's `time xcrun xctrace list devices` can take upwards of 10s (11.822s just now). Because `--device` is optional, other options are loaded in and the devices never show up. Perhaps fig could provide some async API for presenting loading options.

We currently set a timeout of 5 seconds for generators to avoid dead-locks. It should be fairly easy to implement a custom timeout for each generator, but the speed of this command would depend on the speed of the user's device. @sullivan-sean any ideas on this?

> * The [icon docs](https://fig.io/docs/reference/suggestion/icon-api) say to open an issue for missing icons. As you may notice, I use a lot of different icons here. Could be nice to have icons for: login/logout/whoami, cloud/publish, help (--help), version (--version), true/false, number (for port and max-workers), skip (for things like no-install, and yes), and maybe something destructive for clear, and clean type options.

We will definitely add those icons to the list!

>   * I attempted to make a "number" icon using `fig://template?color=2ecc71&badge=#` but it doesn't work, the `#` symbol doesn't render.

I think that it's due to the browser interpreting the `#` as a URL fragment. Not sure if the escaped string would work (`%23`). You can also use an URL to a png/svg/ico file instead of the `fig://` schem.

2021-07-30 18:31 UTC, EvanBacon commented on dev/expo-cli.ts
> +          description: "Path to your Provisioning Profile.",
yup finding a handful of invalid args in the CLI, commander isn't very well typed. Catching these issues is how I'm justifying spending so much time on the generation script :]

2021-07-30 22:31 UTC, EvanBacon commented
@QuiiBz thanks for the response, I ended up creating custom icons for everything (as you may have noticed from the bot comment :] ). Thanks for the feedback!

2021-07-31 12:59 UTC, QuiiBz requested changes
Small suggestions for useless properties, this PR seems good overall! We will be ready to merge after those changes.

2021-07-31 12:59 UTC, QuiiBz commented on dev/expo-cli.ts
> +          variadic: false,
You don't have to specify `variadic` when it's false - it's assumed by default!

2021-07-31 12:59 UTC, QuiiBz commented on dev/expo-cli.ts
> +            isOptional: false,
`isOptional` is false by default so you don't have to specify it

2021-08-03 08:45 UTC, QuiiBz approved these changes
LGTM! Thanks a lot for this amazing PR!

2021-08-03 08:46 UTC, merged