[FIG] feat: add theme comamnd to fig spec
withfig/autocomplete pull request #422
Opened 2021-07-30 07:28 UTC by cstrnt

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
Completions for `fig theme` don't exist yet

**What is the new behavior (if this is a feature change)?**
`fig theme` works!

**Additional info:**

2021-07-30 13:10 UTC, QuiiBz reviewed
Looks good, only a personal readability issue!

2021-07-30 13:10 UTC, QuiiBz commented on dev/fig.ts
> +        ?.options ?? []) as string[];
This might be a bit hard to read and understand. I would prefer something like (not tested):
```suggestion
      const settings: Settings[] = JSON.parse(
        await executeShellCommand(`cat ${SETTINGS_PATH}`)
      ) || [];
      
      const builtInThemes: string[] = settings.find(({ settingName }) => settingName === "autocomplete.theme")?.options ?? [] 
```

2021-07-31 02:57 UTC, mschrage requested changes
I think this is overcomplicating things. The theme command is just switching between locally json files locally installed in the `~/.fig/themes` folder. I think we can just list the files in that directory, unless I'm missing something?

2021-08-07 20:29 UTC, cstrnt commented
closing this in favor of #445

2021-08-07 20:30 UTC, closed without merging