feat: add create-react-native-app spec
withfig/autocomplete pull request #425
Opened 2021-07-30 22:24 UTC by EvanBacon

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Adds support for `create-react-native-app`. Utilizes the icons added for https://github.com/withfig/autocomplete/pull/419 (I maintain both tools).

2021-07-30 22:26 UTC, EvanBacon commented
Heads up, external contributors cannot interact with checkboxes on comments from this bot.

2021-07-31 06:47 UTC, Monkeyank requested changes
Thanks so much for this spec! Just a little nit!

2021-07-31 06:47 UTC, Monkeyank commented on dev/create-react-native-app.ts
> +        name: "name",
Add `template: "folders"`

2021-07-31 13:06 UTC, QuiiBz commented on dev/create-react-native-app.ts
> +        name: "name",
I don't think that this template is appropriated. Based on the description, the path refers to the github repo, not the user's computer.

2021-07-31 13:07 UTC, QuiiBz approved these changes
LGTM!

2021-08-02 17:51 UTC, cstrnt approved these changes

2021-08-02 17:51 UTC, merged