[cmake] Add Spec
withfig/autocomplete pull request #432
Opened 2021-08-03 06:47 UTC by Monkeyank

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature
**What is the current behavior? (You can also link to an open issue here)**
#429 
**What is the new behavior (if this is a feature change)?**
Adds `cmake` spec

2021-08-03 09:19 UTC, QuiiBz requested changes
Cool spec! Only a few things to fix before merging it.

2021-08-03 09:19 UTC, QuiiBz commented on dev/cmake.ts
> +            "Use a build preset to specify build options. The project binary directory is inferred from the configurePreset key",
Wrong description?

2021-08-03 09:19 UTC, QuiiBz commented on dev/cmake.ts
> +            "Checkif file1 is same as file2. If fails are the same, then returns 0, if not returns 1. In case of invalid arguments, it returns 2",
```suggestion
            "Check if file1 is the same as file2. If fails are the same, then returns 0, if not returns 1. In case of invalid arguments, it returns 2",
```

2021-08-03 09:19 UTC, QuiiBz commented on dev/cmake.ts
> +                "Extract to disk from the archive. The <pathname>... argument could be used to extract only selected files or directories. When extracting selected files or directories, you must prov
Looks like there is an argument (pathname) for this option?

2021-08-03 09:19 UTC, QuiiBz commented on dev/cmake.ts
> +                "List archive contents. The <pathname>... argument could be used to list only selected files or directories",
Same as above

2021-08-03 09:19 UTC, QuiiBz commented on dev/cmake.ts
> +            name: "command",
Should we add `isCommand` here?

2021-08-03 09:19 UTC, QuiiBz commented on dev/cmake.ts
> +  // args: {}
We can remove this

2021-08-04 07:13 UTC, Monkeyank commented on dev/cmake.ts
> +                "Extract to disk from the archive. The <pathname>... argument could be used to extract only selected files or directories. When extracting selected files or directories, you must prov
This refers to the optional argument passed to tar

2021-08-04 07:13 UTC, Monkeyank commented on dev/cmake.ts
> +                "List archive contents. The <pathname>... argument could be used to list only selected files or directories",
Same as above

2021-08-04 11:11 UTC, QuiiBz commented on dev/cmake.ts
> +                "Extract to disk from the archive. The <pathname>... argument could be used to extract only selected files or directories. When extracting selected files or directories, you must prov
I see, thanks for the clarification!

2021-08-04 11:11 UTC, QuiiBz approved these changes
Amazing spec, LGTM!

2021-08-04 11:11 UTC, merged