added completion spec for hardhat
withfig/autocomplete pull request #435
Opened 2021-08-04 01:36 UTC by Nutlope

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
add completion spec for hardhat
**What is the current behavior? (You can also link to an open issue here)**
no completion spec for hardhat
**What is the new behavior (if this is a feature change)?**
new completion spec for hardhat
**Additional info:**
https://hardhat.org/hardhat-network/

2021-08-04 07:07 UTC, Monkeyank requested changes

2021-08-04 07:07 UTC, Monkeyank commented on dev/hardhat.ts
> +          description: "The URL of the JSON-RPC server to fork from",
Seems like this takes an arg

2021-08-04 07:07 UTC, Monkeyank commented on dev/hardhat.ts
> +          description: "The block number to fork from",
Seems like this takes an arg

2021-08-04 07:07 UTC, Monkeyank commented on dev/hardhat.ts
> +          description: "The host to which to bind to for new connections",
Seems like this takes an arg

2021-08-04 07:07 UTC, Monkeyank commented on dev/hardhat.ts
> +            "The port on which to listen for new connections (default: 8545)",
Seems like this takes an arg

2021-08-04 07:07 UTC, Monkeyank commented on package-lock.json
> +  "packages": {
Are these changes on purpose?

2021-08-04 11:13 UTC, QuiiBz requested changes

2021-08-04 11:13 UTC, QuiiBz commented on dev/hardhat.ts
> +    { name: "config", description: "A Hardhat config file" },
Looks like this option takes an argument with a template of `filepaths`

2021-08-04 11:13 UTC, QuiiBz commented on dev/hardhat.ts
> +      description: "The maximum amount of memory that Hardhat can use",
Looks like this option takes an argument

2021-08-04 11:13 UTC, QuiiBz commented on dev/hardhat.ts
> +    { name: "--network", description: "The network to connect to" },
Same as above

2021-08-05 07:04 UTC, Monkeyank commented
Also use the `export default` syntax from now on

2021-08-11 00:25 UTC, merged