TypeScript
withfig/autocomplete pull request #44
Opened 2021-03-12 07:56 UTC by QuiiBz

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
As in https://github.com/withfig/autocomplete/issues/43, I started a PR to add TypeScript support to Fig.

**What is the current behavior? (You can also link to an open issue here)**
Hard to write error-prone specs without IDEs auto-completion.

**What is the new behavior (if this is a feature change)?**
Provide types for the specs, allowing for awesome auto-completion and faster development of new specs.

**Additional info:**
I'm still working on it, so expect type bugs for now.

2021-03-12 09:09 UTC, QuiiBz commented
I've added `TODO` comments to remove lines/files when the migration to TS is ready.

The specs now compile to the `dist` folder, so I changed the `copy.sh` to include files in it. I've allowed JS along with TS, so JS specs are still working great.

The new command to "lint" the specs is `typecheck`. The old one `test` is still working, but only on `.js` files, instead of the new one which works on both JS and TS specs.

You can take a look at how to write specs in TS with the types here: https://github.com/withfig/autocomplete/pull/44/commits/3b3d751c620a8f4a091967f11122179e23d84342#diff-6f6f4fc563a4439827032c3278ba487e9d4fa6c24a7ec4c6e41ca21005c726f4 Has you can see, it's very simple:
- Rename the extension to `.ts`
- Change the `var completionSpec` to `const <specName>: Fig.Spec`: This prevent errors from the TypeScript compiler to to find many variables with the same name (`completionSpec`).

And now you will get auto-completion and errors warning, thanks to the added type `Spec` from the `Fig` namespace.

I've also make sure that the existing JS specs still work great, along with added support to new/migrated specs in TS.

2021-03-12 09:22 UTC, cstrnt commented on package.json
> +    "dist": "tsc"
I think `build` would be a more fitting name imo

2021-03-12 09:22 UTC, cstrnt commented on schemas/fig.d.ts
> +    export type SingleOrArray<T> = T | T[];
Maybe move this one to the top of the file? I don't like using something before it's defined (Completion uses this)

2021-03-12 09:22 UTC, cstrnt commented on tsconfig.json
> +    "lib": ["dom", "ESNext"],
I don't think we need `dom` here, right?

2021-03-12 09:28 UTC, QuiiBz commented on package.json
> +    "dist": "tsc"
Instead of the `dist` command? Both are used, let's wait for the maintainer's choice.

2021-03-12 09:29 UTC, QuiiBz commented on tsconfig.json
> +    "lib": ["dom", "ESNext"],
I added it because there was some `console.log` in the `fig` spec. I don't know if they should be removed or not.

2021-03-12 09:30 UTC, QuiiBz commented on schemas/fig.d.ts
> +    export type SingleOrArray<T> = T | T[];
Right, let's change it.

2021-03-12 09:43 UTC, QuiiBz commented
The generated specs written TS are not working in fig: I found that changing the name of the spec (initially to `completionSpec`, changed to the name of the spec) make fig not using theses specs. I tried manually changing back to `completionSpec` and it work properly:
`cd` spec generated from TS, with name set to `cd`, not working:
```js
var cd = {
    name: "cd",
    description: "Change the shell working directory",
    args: {
        template: "folders"
    }
};
```
After setting the name back to `completionSpec`, it work:
```js
var completionSpec = {
    name: "cd",
    description: "Change the shell working directory",
    args: {
        template: "folders"
    }
};
```

We have two solutions:
- Change the fig app to allow any variable name for the spec
- Use the TypeScript compiler API to change the variable name back to `completionSpec` when compiling from TS to JS

2021-03-12 21:08 UTC, cstrnt requested changes

2021-03-12 21:08 UTC, cstrnt commented on schemas/fig.d.ts
> +    export type Function<T = void, R = void> = (param: T) => R;
Could you please move the declaration before it's being used? :)

2021-03-12 21:08 UTC, cstrnt commented on schemas/fig.d.ts
> +        postProcess?: StringOrFunction<string, Suggestion[]>;
Can this really be a string?
![Uploading Bildschirmfoto 2021-03-12 um 22.05.58.png…]()

2021-03-12 21:33 UTC, QuiiBz commented on schemas/fig.d.ts
> +        postProcess?: StringOrFunction<string, Suggestion[]>;
I’ve made some mistakes on the specs types - will fix it tomorrow. Thanks!

2021-03-12 21:33 UTC, QuiiBz commented on schemas/fig.d.ts
> +    export type Function<T = void, R = void> = (param: T) => R;
Sure!

2021-03-12 21:35 UTC, QuiiBz commented on compiler/log.ts
> +export const log = (message: string, level: Level = Level.INFO) => {
Could you provide an example please? I don’t get the point of using an abstract class for this.

2021-03-12 21:40 UTC, QuiiBz commented on compiler/compiler.ts
> +    if(!newName.endsWith('.js'))
I usually never add curly braces to one-instructions blocks, since it adds useless characters. Let’s wait for the maintainer's opinion.

2021-03-13 07:31 UTC, QuiiBz commented on schemas/fig.d.ts
> +        postProcess?: StringOrFunction<string, Suggestion[]>;
Fixed in cbeff29

2021-03-13 07:31 UTC, QuiiBz commented on schemas/fig.d.ts
> +    export type Function<T = void, R = void> = (param: T) => R;
Fixed in cbeff29

2021-03-13 07:32 UTC, QuiiBz commented on tsconfig.json
> +    "lib": ["dom", "ESNext"],
Fixed in cbeff29

2021-03-13 07:46 UTC, QuiiBz commented on package.json
> +    "dist": "tsc"
Changed at https://github.com/withfig/autocomplete/pull/44/commits/66b3d28faf850e10d267612fa9d0e4c9cb713ed2#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L9-L10 with the custom compiler.

2021-03-13 08:54 UTC, cstrnt commented on compiler/log.ts
> +export const log = (message: string, level: Level = Level.INFO) => {
Sure

You can create the class like this:
```js
abstract class SpecLogger {
  static log(message: string, level: Level = Level.INFO){
      // your code here
  }
}
```

and then call it like that

`SpecLogger.log(...args)`

By doing that the code is more verbose and you don't have to search for the `log` implementation.

2021-03-13 08:56 UTC, cstrnt commented on compiler/compiler.ts
> +    if(!newName.endsWith('.js'))
IMHO characters are NEVER useless if they improve readability. And in the end the code will also be optimized by the typescript compiler either way. I mean it's just a small thing here, but as long as you don't have to write some extremely optimized code which won't be transpiled / compiled in any way, I would always focus on readability - especially if it some open source code.

2021-03-13 08:59 UTC, cstrnt commented on compiler/compiler.ts
> +    const out = path.resolve('dist', newName);
any reason why you resolved this?

2021-03-13 09:06 UTC, QuiiBz commented on compiler/log.ts
> +export const log = (message: string, level: Level = Level.INFO) => {
I just figured out why you wanted to use an `abstract` class - we don't want to instantiate `SpecLogger` mistakenly. Let's change it to this:
```suggestion
/**
 * Log a message in the console. Can specify a Level, which
 * will be INFO by default.
 *
 * @param message The message to log
 * @param level The level to log
 */
export default abstract class SpecLogger {

    static log(message: string, level: Level = Level.INFO) {
        
        console.log(chalk[level](message));
    }
}
```

2021-03-13 09:09 UTC, QuiiBz commented on compiler/compiler.ts
> +import { Level, log } from './log';
```suggestion
import SpecLogger, { Level } from './log';
```

2021-03-13 09:10 UTC, QuiiBz commented on compiler/compiler.ts
> +        log('Could not find specs folder', Level.ERROR);
```suggestion
        SpecLogger.loc('Could not find specs folder', Level.ERROR);
```

2021-03-13 09:10 UTC, QuiiBz commented on compiler/compiler.ts
> +    log(`Processing ${specs.length} specs...`);
```suggestion
    SpecLogger.log(`Processing ${specs.length} specs...`);
```

2021-03-13 09:11 UTC, QuiiBz commented on compiler/compiler.ts
> +    log('Specs compiled successfully to /dist folder!', Level.SUCCESS);
```suggestion
    SpecLogger.log('Specs compiled successfully to /dist folder!', Level.SUCCESS);
```

2021-03-13 09:14 UTC, QuiiBz commented on compiler/compiler.ts
> +    const out = path.resolve('dist', newName);
I resolved this because I made the changes in https://github.com/withfig/autocomplete/pull/44/commits/cbeff291380b20272e976e9c5a212007aaef14dd.

2021-03-13 10:57 UTC, merged