[yarn] Update yarn spec with "global" subcommands
withfig/autocomplete pull request #440
Opened 2021-08-04 21:18 UTC by EliasGcf

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Update yarn spec

**Additional info:**

Add the `global` subcommands below
- `add`
- `bin`
- `dir`
- `ls`
- `list`
- `remove` (with generator)
- `upgrade`
- `upgrade-interactive`

2021-08-05 09:24 UTC, QuiiBz requested changes
Thanks for this PR! Few suggestions to resolve before merging it

2021-08-05 12:15 UTC, EliasGcf commented on dev/yarn.ts
> +      if (dependencyScripts || devDependencyScripts) {
I copy this code from `packageList`, do you want I remove this `if` from there to?

2021-08-06 13:38 UTC, EliasGcf commented
Done!

2021-08-07 09:05 UTC, QuiiBz commented on dev/yarn.ts
> +      if (dependencyScripts || devDependencyScripts) {
That would be great!

2021-08-07 09:06 UTC, QuiiBz commented
> Done!

Thanks! Could you remove the other `if` as discussed here? https://github.com/withfig/autocomplete/pull/440#discussion_r683397116

2021-08-07 16:13 UTC, EliasGcf commented on dev/yarn.ts
> +      if (dependencyScripts || devDependencyScripts) {
As you wish!

2021-08-09 12:36 UTC, QuiiBz approved these changes
LGTM!

2021-08-09 12:36 UTC, merged