[hub] as wrapper for git
withfig/autocomplete pull request #442
Opened 2021-08-04 23:25 UTC by fwesss

What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
Feature

What is the current behavior? (You can also link to an open issue here)
Many people use Github's hub CLI tool as a wrapper and alias for git. When typing git, they expect autocompletions but don't get anything due to Fig reading the command as 'hub' and seeing no applicable spec.

What is the new behavior (if this is a feature change)?
hub gives the same exact suggestions as git. There are additional features that hub provides but I have not added them in.

Additional info:
Per hub's README: "Some hub features feel best when it's aliased as git. This is not dangerous; your normal git commands will all work. hub merely adds some sugar."

There shouldn't be any issues using the git completion spec with hub.

2021-08-05 09:32 UTC, QuiiBz requested changes

2021-08-05 09:32 UTC, QuiiBz commented on dev/hub.ts
> +import git from "../dev/git";
Isn't the path simply `./git`?

2021-08-05 09:32 UTC, QuiiBz commented on dev/hub.ts
> +export default completionSpec;
I think we can take advantage of the `export from` syntax here:
```ts
export { default as Hub } from './git';
```

2021-08-05 15:07 UTC, fwesss commented on dev/hub.ts
> +export default completionSpec;
Much cleaner. Just made the change.

2021-08-07 09:03 UTC, QuiiBz approved these changes
LGTM!

2021-08-07 09:03 UTC, merged