Emacs Spec Add
withfig/autocomplete pull request #449
Opened 2021-08-08 14:23 UTC by yavko

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
adds emacs support
**What is the current behavior? (You can also link to an open issue here)**
doesnt have emacs spec
**What is the new behavior (if this is a feature change)?**
has emacs spec
**Additional info:**

2021-08-08 16:03 UTC, fedeci commented on dev/emacs.ts
> +      name: ["--batch"],
nit:
```suggestion
      name: "--batch",
```

2021-08-08 16:03 UTC, fedeci commented on dev/emacs.ts
> +      name: ["--chdir"],
Ditto

2021-08-09 12:48 UTC, QuiiBz requested changes
Thanks a lot for this PR! I left some comments to resolve before merging it

2021-08-09 12:48 UTC, QuiiBz commented on dev/emacs.ts
> +export const completionSpec: Fig.Spec = {
The syntax has changed since #388 , you now need to `export default` the spec object:
```ts
const completionSpec: Fig.Spec = {
   ...
}

export default completionSpec```

2021-08-09 12:48 UTC, QuiiBz commented on dev/emacs.ts
> +      description: "do not do interactive display; implies -q",
Could you capitalize the first letter of the description? Same for underneath.

Also, looks like it `dependsOn` -q: see https://fig.io/docs/reference/option#dependson

2021-08-09 12:48 UTC, QuiiBz commented on dev/emacs.ts
> +      name: ["--debug-init"],
Does this option takes an argument? If so, I think it should have a template of `filepaths`

2021-08-09 12:48 UTC, QuiiBz commented on dev/emacs.ts
> +      name: ["-t", "--terminal="],
Looks like this option takes an argument

2021-08-09 12:48 UTC, QuiiBz commented on dev/emacs.ts
> +      name: ["--file=", "--find-file=", "--visit="],
Same as above, with a template of `filepaths`

2021-08-09 12:48 UTC, QuiiBz commented on dev/emacs.ts
> +      name: ["--debug-init"],
Duplicate from https://github.com/withfig/autocomplete/pull/449/files#diff-046e66c783cf3b305aa60aa56e84acecb4416899fdc52bbe3c29c52e09d6344cR32

2021-08-09 13:35 UTC, fedeci commented on dev/emacs.ts
> +      name: ["-t", "--terminal="],
Is the `=` at the end allowed?

2021-08-10 12:58 UTC, yavko commented on dev/emacs.ts
> +export const completionSpec: Fig.Spec = {
oof

2021-08-10 12:58 UTC, yavko commented on dev/emacs.ts
> +      description: "do not do interactive display; implies -q",
ok

2021-08-10 12:59 UTC, yavko commented on dev/emacs.ts
> +      name: ["--debug-init"],
i know

2021-08-10 13:01 UTC, yavko commented on dev/emacs.ts
> +      name: ["-t", "--terminal="],
idk thats how it is in the man page

2021-08-10 13:03 UTC, fedeci commented on dev/emacs.ts
> +      description: "do not do interactive display; implies -q",
Does it make sense a lint rule for this?

2021-08-10 13:09 UTC, fedeci commented on dev/emacs.ts
> +      name: ["-t", "--terminal="],
I tried and we can avoid it.

2021-08-10 13:09 UTC, yavko commented on dev/emacs.ts
> +      name: ["--chdir"],
wdym

2021-08-10 13:10 UTC, fedeci commented on dev/emacs.ts
> +      name: ["--chdir"],
Same nitpick as above😄

2021-08-10 13:12 UTC, yavko commented on dev/emacs.ts
> +      name: ["--chdir"],
oh ok

2021-08-10 13:13 UTC, yavko commented on dev/emacs.ts
> +      description: "do not do interactive display; implies -q",
idk

2021-08-10 13:22 UTC, yavko commented
I'm confused why it keeps failing help

2021-08-10 13:29 UTC, fedeci commented on dev/emacs.ts
> +export default completionSpec```
This one :)
```suggestion
export default completionSpec;
```

2021-08-10 13:32 UTC, yavko commented on dev/emacs.ts
> +export default completionSpec```
oh thanks!

2021-08-10 13:36 UTC, yavko commented on dev/emacs.ts
> +export default completionSpec```
still broken

2021-08-10 13:50 UTC, fedeci commented on dev/emacs.ts
> +      dependsOn: "-q",
`dependsOn` always takes an array.

2021-08-10 13:51 UTC, fedeci reviewed
To fix the linter complaints run `npm run lint:fix`

2021-08-10 13:54 UTC, yavko commented on dev/emacs.ts
> +      dependsOn: "-q",
oh

2021-08-10 13:55 UTC, yavko commented
> To fix the linter complaints run `npm run lint:fix`

im on web for now lol can run local until later

2021-08-10 14:18 UTC, yavko commented
YES FINALY OMG YAY

2021-08-10 14:38 UTC, fedeci approved these changes

2021-08-10 17:27 UTC, Nutlope commented
LGTM! Thanks for the review @fedeci & @QuiiBz!

2021-08-10 17:29 UTC, merged

2021-08-12 19:25 UTC, yavko commented
Thanks so much for merging!