chore(eslint): add `no-missing-export` plugin
withfig/autocomplete pull request #450
Opened 2021-08-08 18:18 UTC by fedeci

Based on #330

2021-08-08 18:26 UTC, fedeci commented on dev/hub.ts
> +export default git;
```suggestion
export { default } from './git';
```

2021-08-09 12:58 UTC, QuiiBz requested changes
Thanks, this rule looks great!

2021-08-09 12:58 UTC, QuiiBz commented on scripts/eslint-plugin-fig-linter/rules/no-missing-default-export.js
> +            message: "File must contain one default export.",
The message can be a bit more expressive:
```suggestion
            message: "File must export default the completion spec object",
```

2021-08-12 13:35 UTC, QuiiBz approved these changes
Thanks a lot for this one!

2021-08-12 13:35 UTC, merged