Add pageres spec
withfig/autocomplete pull request #461
Opened 2021-08-12 00:07 UTC by Monkeyank

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature
**What is the new behavior (if this is a feature change)?**
Adds `pageres` spec

2021-08-12 13:41 UTC, QuiiBz requested changes

2021-08-12 13:41 UTC, QuiiBz commented on dev/pageres.ts
> +      description: "Crop to the set height",
Does this option take an argument?

2021-08-12 13:41 UTC, QuiiBz commented on dev/pageres.ts
> +      description: "Override a global crop option within a group",
This option can exclude the `--crop` one

2021-08-12 13:41 UTC, QuiiBz commented on dev/pageres.ts
> +        name: "string",
Looks like we can have a template of `filepaths` here

2021-08-13 00:57 UTC, Monkeyank commented on dev/pageres.ts
> +      description: "Crop to the set height",
This doesn't take an argument

2021-08-14 09:23 UTC, QuiiBz approved these changes
LGTM!

2021-08-14 09:23 UTC, merged