Completed lsd spec
withfig/autocomplete pull request #467
Opened 2021-08-13 15:07 UTC by fwesss

lsd was previously a wrapper for ls but they don't have the same options or arguments.

Completed spec to match lsd --help

2021-08-14 07:43 UTC, Monkeyank requested changes
Small type, otherwise LGTM!

2021-08-14 07:43 UTC, Monkeyank commented on dev/lsd.ts
> +  description: "as ls command with a lot of pretty colors and some other stuff",
```suggestion
  description: "an ls command with a lot of pretty colors and some other stuff",
```

2021-08-17 16:26 UTC, Nutlope approved these changes

2021-08-17 16:32 UTC, Nutlope commented
LGTM!

2021-08-17 16:32 UTC, merged