Add fnm spec
withfig/autocomplete pull request #468
Opened 2021-08-13 16:27 UTC by noftaly

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
Adds a spec for the [`fnm` node version manager](https://github.com/Schniz/fnm)

**What is the new behavior (if this is a feature change)?** /

**Additional info:** 
As this is my first contribution to Fig, don't refrain from suggesting how the spec could be improved or what I should maybe do differently. I'm happy to discuss! :)

2021-08-13 18:59 UTC, fedeci commented
Splitting everything makes useless some linting rules, I'll have to update those.

2021-08-13 19:08 UTC, noftaly commented
> Splitting everything makes useless some linting rules, I'll have to update those.

Ah! 😄 I started with the nvm completions to build this one, and it split everything like this

2021-08-13 19:11 UTC, fedeci commented
In fact it is definitely cleaner! My fault :)

2021-08-14 09:32 UTC, QuiiBz requested changes
Thanks a lot for this PR! Almost everything looks perfect.

I think it should be possible to add custom generators for  `install` and `uninstall` (executing `ls-remote` and `ls` respectively in a generator and mapping the result to suggestions). Here is the [documentation](https://fig.io/docs/reference/generator) for it, tell us if you need any help!

2021-08-14 09:32 UTC, QuiiBz commented on dev/fnm.ts
> +  args: [
No need to englobe this in an array when there is only one `arg`. Same for underneath

2021-08-14 15:40 UTC, noftaly commented on dev/fnm.ts
> +  args: [
sure! I'll commit that. Thanks \:)

2021-08-14 15:44 UTC, noftaly commented
> I think it should be possible to add custom generators for install and uninstall (executing ls-remote and ls respectively in a generator and mapping the result to suggestions). Here is the documentation for it, tell us if you need any help!

Great idea! I'll try to add that :)

2021-08-14 16:05 UTC, noftaly commented
@QuiiBz I've added it for every command that required a `version` argument.

The only thing is, there are a *lot* of versions (for the remoteVersions). Do you think we should do some filtering?
I thought of maybe showing the 4 latest even majors and the last 2 odd majors (so v10, v12, v14, v15, v16, v17) (because in Node, odd majors are beta, and even majors are LTS).
We could also show the latest minor every time, so only v16.6.2 for example, not v16.6.1 and v16.6.0.

Wdyt?

2021-08-21 13:00 UTC, noftaly commented
Quick update: I'll aim for this suggestions:
- Latest patch of all the minor of the last LTS
- All named LTS (latest version)
- Latest patch of latest minor of 1 or 2 latest Beta
- And everything else sorted, but after those (so you still get autocomplete, they are just not visible on top)

Example with Node.js' version of 2021/08/21:
We will have:
v16.7.0
v16.6.2
v16.5.0
v16.4.2
v16.3.0
v16.2.0
v16.1.0
v16.0.0
v15.14.0
v14.17.5 (Fermium)
v12.22.5 (Erbium)
v10.24.1 (Dubnium)
v8.17.0 (Carbon)
v6.17.1 (Boron)
v4.9.1 (Argon)
everything else

If there was a v17, then there will also be latest v17 on top. If there was a v18, v15 would disappear because it's a beta that's too old, but v17 would stay.

I hope it makes sense 😄 I think it's a great compromise to show the latest versions (most commonly used), but also provide completion for every other version.

2021-08-23 05:08 UTC, Nutlope commented
@noftaly this looks awesome, nice work!! LGTM :)

2021-08-23 05:14 UTC, Nutlope approved these changes

2021-08-23 05:14 UTC, merged