eleventy-cli
withfig/autocomplete pull request #473
Opened 2021-08-14 01:51 UTC by yavko

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adds Eleventy Cli Support
**What is the current behavior? (You can also link to an open issue here)**
No support
**What is the new behavior (if this is a feature change)?**
support
**Additional info:**
4th contribution

2021-08-14 02:06 UTC, Monkeyank requested changes

2021-08-14 02:06 UTC, Monkeyank commented on dev/eleventy.ts
> +        name: "Template Names Seperated by ,",
I think we can provide a list of suggestions, such as `md,html,ejs`

2021-08-14 02:06 UTC, Monkeyank commented on dev/eleventy.ts
> +        name: "port",
Maybe add a `default: "8080"`?

2021-08-14 02:12 UTC, yavko commented on dev/eleventy.ts
> +        name: "Template Names Seperated by ,",
ok

2021-08-14 02:12 UTC, yavko commented on dev/eleventy.ts
> +        name: "port",
ok

2021-08-18 17:19 UTC, yavko commented on dev/eleventy.ts
> +        name: "Template Names Seperated by ,",
Idk how tho, I read the docs and i still don't get how

2021-08-19 05:57 UTC, Monkeyank commented on dev/eleventy.ts
> +        name: "Template Names Seperated by ,",
You can add a prop underneath args. Here's an example:

```
args: {
     name: "Template Names Separated by,",
     suggestions: ["md", "html", "eje"]
}
```

2021-08-19 06:02 UTC, yavko commented on dev/eleventy.ts
> +        name: "Template Names Seperated by ,",
ok thanks

2021-08-19 08:52 UTC, fedeci commented on dev/eleventy.ts
> +        name: "Template Names Seperated by ,",
However that does not allow for comma separated values, right?

2021-08-19 14:23 UTC, yavko commented on dev/eleventy.ts
> +        name: "Template Names Seperated by ,",
idk

2021-08-23 12:25 UTC, QuiiBz approved these changes
LGTM, thanks a lot for this PR!

2021-08-23 12:25 UTC, merged

2021-08-23 15:36 UTC, yavko commented
YAYAYA PR 4