Add Spec for N
withfig/autocomplete pull request #479
Opened 2021-08-14 22:01 UTC by sohcah

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
No autocompletion for N

**What is the new behavior (if this is a feature change)?**
Full autocompletion for N

**Additional info:**
Includes dynamic suggestions for versions from `n lsr --all`

2021-08-14 22:54 UTC, fedeci commented on dev/n.ts
> +      name: ["prune"],
nit: see #451 
```suggestion
      name: "prune",
```

2021-08-14 22:54 UTC, fedeci commented on dev/n.ts
> +      args: [versionArg],
nit: both for this and the others
```suggestion
      args: versionArg,
```

2021-08-14 22:54 UTC, fedeci commented on dev/n.ts
> +          name: ["--all"],
ditto:
```suggestion
          name: "--all",
```

2021-08-14 22:54 UTC, fedeci commented on dev/n.ts
> +        });
perf: using a set from the beginning and avoiding redundant operations on strings is a good boost.
```suggestion
        const set = new Set()
        const versions = out
          .split("\n")
          .slice(1)
        for (const version of versions) {
          set.add(version); // 16.1.2
          const splitted = version.split(".")
          set.add(splitted[0] + "." + splitted[1]); // 16.1
          set.add(splitted[0]); // 16
        }
        return Array.from(set).map((version) => {
          return {
            name: [version, `v${version}`],
            description: `Node.js ${version}`,
          };
        });
```

2021-08-16 21:29 UTC, sohcah commented on dev/n.ts
> +        });
Very good idea to use a set from the start
 I had originally not implemented the splitting at all, so didn't use a Set... I had just quickly hacked that in afterwards, which wasn't the wisest idea.

2021-08-23 11:32 UTC, QuiiBz requested changes
Thanks a lot for this PR! `n` looks really cool, I noticed few things to resolve to improve the quality of the spec before merging it.

2021-08-23 11:32 UTC, QuiiBz commented on dev/n.ts
> +      description: "Override system architecture",
I believe that this option takes an argument

2021-08-23 11:32 UTC, QuiiBz commented on dev/n.ts
> +      description:
I think we can add [isDangerous](https://fig.io/docs/reference/option#isdangerous) here!

2021-08-23 11:32 UTC, QuiiBz commented on dev/n.ts
> +        "Override automatic detection of xz support and disable use of xz compressed node downloads.",
Looks like we can use [exclusiveOn](https://fig.io/docs/reference/option#exclusiveon) for those two options.

2021-08-23 11:33 UTC, QuiiBz commented
Also, could you run the `lint:fix` script?

2021-08-28 08:58 UTC, QuiiBz approved these changes
Thanks a lot for this amazing spec!

2021-08-28 08:58 UTC, merged