feat: add `z` spec
withfig/autocomplete pull request #488
Opened 2021-08-16 20:10 UTC by fedeci

Closes #486

2021-08-17 07:05 UTC, Monkeyank requested changes

2021-08-17 07:05 UTC, Monkeyank commented on dev/z.ts
> +    isVariadic: true,
Seems like the regex arg is also optional `z [-chlrtx] [regex1 regex2 ... regexn]`

```suggestion
    isVariadic: true,
    isOptional: true,
```

2021-08-17 07:05 UTC, Monkeyank commented on dev/z.ts
> +  name: "z",
Can we add a description
```suggestion
  name: "z",
  description: "CLI tool to jump around"
```

2021-08-17 08:51 UTC, fedeci commented on dev/z.ts
> +  name: "z",
Completely missed it :)

2021-08-17 08:54 UTC, fedeci commented on dev/z.ts
> +    isVariadic: true,
I am not sure about this. It may just be a syntax misaligned.
@fwesss does it anything if you don't specify args?

2021-08-17 08:56 UTC, fedeci commented on dev/z.ts
> +  name: "z",
```suggestion
  name: "z",
  description: "CLI tool to jump around directories"
```

2021-08-17 09:00 UTC, fedeci commented on dev/z.ts
> +  description: "CLI tool to jump around directories"
```suggestion
  description: "CLI tool to jump around directories",
```

2021-08-17 14:39 UTC, fwesss commented on dev/z.ts
> +    isVariadic: true,
Running `z` with no args outputs the history. Equivalent to running `z -l`.

2021-08-23 11:52 UTC, QuiiBz approved these changes
LGTM! Thanks for this spec

2021-08-23 11:52 UTC, merged