Add autocompletion for composer require command
withfig/autocomplete pull request #490
Opened 2021-08-17 13:56 UTC by duboiss

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
Nothing displayed.

**What is the new behavior (if this is a feature change)?**
![image](https://user-images.githubusercontent.com/29716703/129733446-90ab74a6-cefe-44af-9157-9fa67df091ec.png)

**Additional info:**
I have taken the code from the [NPM specification](https://github.com/withfig/autocomplete/commit/5b3571dca7951d9bcc3a21ca3bcc1a6665c345ed#diff-e2f99ae7f68df3bb044b7f3cf9b942d3e4c00bc120accb009ae58d44352a5b01R1).

2021-08-17 23:05 UTC, fedeci commented on dev/composer.ts
> +                : {}),
```suggestion
			  generators: command.name === "require" 
			    ? searchGenerator 
			    : triggersCommands.includes(command.name) 
			    ? packagesGenerator 
			    : []
```

2021-08-23 11:56 UTC, QuiiBz requested changes
This is looking amazing! Only two small issues to fix before merging it!

2021-08-23 11:56 UTC, QuiiBz commented on dev/composer.ts
> +    return temp;
We can remove the `var` and simplify a bit:

```suggestion
    try {
      return JSON.parse(out).results.map(
        (item) =>
          ({
            name: item.name,
            description: item.description,
            icon: "📦",
          } as Fig.Suggestion)
      ) as Fig.Suggestion[];
    } catch (e) {
      return [];
    }
```

2021-08-23 11:56 UTC, QuiiBz commented on dev/composer.ts
> +    console.log("debug", out);
Could you remove this log?

2021-08-23 13:13 UTC, duboiss commented
I just realized that the autocompletion of arguments (and packages) is missing for `composer global` command.
I might see about fixing this in another PR.

2021-08-23 15:27 UTC, QuiiBz commented
> I just realized that the autocompletion of arguments (and packages) is missing for `composer global` command.
> I might see about fixing this in another PR.

Feel free to do it in this one, we just need to change the title.

Also, could you resolve the merge conflict so we can get it merged?

2021-08-23 16:53 UTC, Nutlope commented
Hey @duboiss, I noticed you deleted the composer spec in the /dev folder and only kept the one inside the php folder. Not actually sure why we added it in the php folder, it should be on the outside since that's how Fig looks for a spec (unless we use `loadSpec` which we're not in this case). Please correct me if I'm wrong @QuiiBz!

Could you move the `composer` spec from the `/dev/php`folder to the `/dev` folder please?

2021-08-23 18:40 UTC, Nutlope approved these changes

2021-08-24 09:21 UTC, QuiiBz commented
> Not actually sure why we added it in the php folder, it should be on the outside since that's how Fig looks for a spec (unless we use `loadSpec` which we're not in this case). Please correct me if I'm wrong @QuiiBz!

That's 100% right! The `php` folder is currently only used for `artisan`, which is used like a sub-command of `php`: `php artisan ...`. That's why it is in this folder, as opposed to `composer` which isn't a sub-command of `php`.

2021-08-24 09:22 UTC, QuiiBz approved these changes
LGTM! Thanks a lot for those amazing generators!

2021-08-24 09:22 UTC, merged