Add backend for the Shortcuts command line utility in macOS Monterey
withfig/autocomplete pull request #492
Opened 2021-08-17 17:32 UTC by rmorey

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
Backend doesn't exist

**What is the new behavior (if this is a feature change)?**
It does exist

**Additional info:**
The Shortucts app and this utility are currently available in the macOS Montery Public Beta, slated for release this Fall.

https://www.apple.com/macos/monterey-preview/
https://sixcolors.com/link/2021/06/shortcuts-shaping-up-on-the-mac/

2021-08-18 17:14 UTC, Monkeyank requested changes
Thanks so much for this completion spec! Just a little nit I found, otherwise LGTM!

2021-08-18 17:14 UTC, Monkeyank commented on dev/shortcuts.ts
> +              name: "mode",
We can add `default: "people-who-know-me"`

2021-08-18 17:59 UTC, fedeci commented on dev/shortcuts.ts
> +        },
It would be great if we could extract this from the `completionSpec` obj.
Like 
```ts
completionSpec.subcommands.filter(command => command.name !== "help").map(({ name, description, icon }) => ({ name, description, icon }))
```

2021-08-19 19:38 UTC, fedeci commented on dev/shortcuts.ts
> +      ),
Just have a look at perf cause this seems to be O(n^2) and is like 70% slower on jsbench.
It may result in problems when the spec is loaded the first time.

2021-08-23 12:23 UTC, QuiiBz approved these changes
This is amazing! Thanks a lot for this spec

2021-08-23 12:24 UTC, merged