[TypeORM] Create TypeORM completion spec
withfig/autocomplete pull request #494
Opened 2021-08-18 00:00 UTC by EliasGcf

Adds autocomplete spec for [TypeORM](https://typeorm.io/#/) CLI.

2021-08-22 14:40 UTC, fedeci commented on dev/yarn.ts
> +      "typeorm",
Can you add it also to the `npx` spec?

2021-08-22 14:56 UTC, fedeci commented on dev/typeorm.ts
> +        cliOptions.version,
This does not need to be added to each subcommand.

2021-08-22 16:25 UTC, fedeci requested changes

2021-08-22 16:25 UTC, fedeci commented on dev/typeorm.ts
> +      name: "migration:create",
`migrations:create` is an alias for this subcommand, same for the other migration commands.

2021-08-23 15:16 UTC, QuiiBz requested changes
That looks really great, thanks! Left some comments to resolve before merging it

2021-08-23 15:16 UTC, QuiiBz commented on dev/yarn.ts
> +      "typeorm",
Agree with @fedeci

2021-08-23 15:16 UTC, QuiiBz commented on dev/typeorm.ts
> +      name: "migration:generate",
```suggestion
      name: ["migration:generate", "migrations:generate"],
```

2021-08-23 15:16 UTC, QuiiBz commented on dev/typeorm.ts
> +      name: "migration:create",
```suggestion
      name: ["migration:create", "migrations:create"],
```

2021-08-23 15:16 UTC, QuiiBz commented on dev/typeorm.ts
> +      name: "migration:show",
```suggestion
      name: ["migration:show", "migrations:show"],
```

2021-08-23 15:16 UTC, QuiiBz commented on dev/typeorm.ts
> +      name: "migration:run",
```suggestion
      name: ["migration:run", "migrations:run"],
```

2021-08-24 13:30 UTC, EliasGcf commented on dev/typeorm.ts
> +      name: "migration:show",
It looks like `migrations:show` does not exist.

2021-08-24 13:33 UTC, EliasGcf commented
Done! @QuiiBz

2021-08-25 07:25 UTC, QuiiBz approved these changes
LGTM, thanks a lot!

2021-08-25 07:25 UTC, merged