feat: add httpie completion spec
withfig/autocomplete pull request #504
Opened 2021-08-21 19:53 UTC by cipi1965

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

This PR adds autocompletion support for httpie (HTTP client).

**What is the current behavior? (You can also link to an open issue here)**

Missing support (closes #462)

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2021-08-22 11:19 UTC, fedeci requested changes
Since they are basically the same spec, can we just create one of the two and then import the other changing the name property before exporting?
```ts
import https from "./http";
https.name = "https";
export default https;
```

2021-08-22 12:06 UTC, cipi1965 commented
@fedeci done, could you please recheck?

2021-08-22 12:43 UTC, fedeci commented
It should be ok now!

2021-08-23 15:01 UTC, QuiiBz requested changes
Didn't know this CLI before, seems really useful! I left some comments to resolve

2021-08-23 15:23 UTC, fedeci commented on dev/https.ts
> +export default completionSpec;
🤔?

2021-08-24 09:51 UTC, QuiiBz approved these changes
LGTM, thanks a lot!

2021-08-24 09:52 UTC, merged

2021-10-01 06:40 UTC, FAvE01 commented
#589