feat: add laravel completion spec
withfig/autocomplete pull request #506
Opened 2021-08-22 10:45 UTC by cipi1965

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

This PR adds autocompletion support for laravel (Laravel Installer cli).

**What is the current behavior? (You can also link to an open issue here)**

Missing support

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2021-08-22 14:19 UTC, fedeci commented on dev/laravel.ts
> +      options: [
Is the `--git` and github related options missing? https://github.com/laravel/installer/blob/da5e8b471d87c0b4762c3a0a4c35f09521b48db9/src/NewCommand.php

2021-08-22 15:55 UTC, cipi1965 commented on dev/laravel.ts
> +      options: [
Oops i think i based my work on a old version of the tool 😅

2021-08-22 16:18 UTC, cipi1965 commented on dev/laravel.ts
> +      options: [
Added

2021-08-23 15:08 UTC, QuiiBz requested changes
PHP devs are gonna thank you! Left some comments to resolve before merging it

2021-08-23 15:08 UTC, QuiiBz commented on dev/laravel.ts
> +        },
I think we could extract those options to a top-level const, instead of duplicating them (see https://github.com/withfig/autocomplete/pull/506/files#diff-ba0e472ae0f57d53510879cf1b3e1a8097585a18dee3325b5d0103192cfdd16eR24-R35)

2021-08-23 15:08 UTC, QuiiBz commented on dev/laravel.ts
> +            name: "STACK",
Could we provide suggestions for this argument?

2021-08-24 09:52 UTC, QuiiBz approved these changes
LGTM, thanks a lot for this spec!

2021-08-24 09:53 UTC, merged