feat: add hyper completion spec
withfig/autocomplete pull request #508
Opened 2021-08-23 05:29 UTC by Deep-Codes

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Feature : adds specs for `hyper`

2021-08-23 12:18 UTC, fedeci reviewed
If I specify a folder as arg does it open that folder in hyper?
e.g. `hyper node/`

2021-08-23 14:49 UTC, Deep-Codes commented
> If I specify a folder as arg does it open that folder in hyper?
> e.g. `hyper node/`

It does adding `folder` as template

<img width="569" alt="Screenshot 2021-08-23 at 8 18 47 PM" src="https://user-images.githubusercontent.com/61158210/130468081-b89513de-765d-4fe3-895c-52bcdcacbdb2.png">

2021-08-23 15:33 UTC, QuiiBz requested changes
Awesome! There are some arguments that are missing thought

2021-08-23 15:33 UTC, QuiiBz commented on dev/hyper.ts
> +      description: "Search for plugins on npm",
If think this option takes an argument, which is a string to search on npm?

2021-08-23 15:33 UTC, QuiiBz commented on dev/hyper.ts
> +      description: "Uninstall plugin",
Same as above but for the name of the plugin

2021-08-23 15:35 UTC, fedeci commented on dev/hyper.ts
> +      description: "Uninstall plugin",
It can actually be autogenerated via the `list` subcommand.

2021-08-23 15:37 UTC, QuiiBz commented on dev/hyper.ts
> +      description: "Uninstall plugin",
Yes! But adding generators isn't mandatory when adding a completely new spec. We can add them later!

2021-08-23 15:39 UTC, Deep-Codes commented on dev/hyper.ts
> +      description: "Search for plugins on npm",
i don't think so 

```
  Usage: hyper [options] [command]
  
  Commands:
    <default>                    Launch Hyper
    docs, d, h, home             Open the npm page of a plugin
    help                         Display help
    install, i                   Install a plugin
    list, ls                     List installed plugins
    list-remote, lsr, ls-remote  List plugins available on npm
    search, s                    Search for plugins on npm
    uninstall, u, rm, remove     Uninstall a plugin
    version                      Show the version of hyper
  
  Options:
    -h, --help     Output usage information
    -v, --verbose  Verbose mode (disabled by default)
  
```

2021-08-23 15:40 UTC, QuiiBz commented on dev/hyper.ts
> +      description: "Search for plugins on npm",
Could you try running `hyper search help`?

2021-08-23 15:41 UTC, Deep-Codes commented on dev/hyper.ts
> +      description: "Search for plugins on npm",
this is the usage 

`> hyper search` doesn't take an argument 🤔 

<img width="707" alt="Screenshot 2021-08-23 at 9 11 34 PM" src="https://user-images.githubusercontent.com/61158210/130476484-29de0931-23e4-40de-901d-3853b31ea630.png">

2021-08-23 15:46 UTC, Deep-Codes commented on dev/hyper.ts
> +      description: "Search for plugins on npm",
Yes it is

2021-08-23 15:47 UTC, QuiiBz commented on dev/hyper.ts
> +      description: "Search for plugins on npm",
Just installed and tried it, and looks like I can add search arguments (`material` here). Maybe we don't have the same version of the cli?
<img width="607" alt="Screenshot 2021-08-23 at 17 46 13" src="https://user-images.githubusercontent.com/43268759/130477217-80d13865-4fc7-425c-8f2f-3a80e0ff0bd7.png">

2021-08-23 15:52 UTC, Deep-Codes commented on dev/hyper.ts
> +      description: "Search for plugins on npm",
yes, it does search according to the argument.

Should i add, args to the search subcommand?

<img width="270" alt="Screenshot 2021-08-23 at 9 21 33 PM" src="https://user-images.githubusercontent.com/61158210/130477994-6d30f741-65d3-4464-974a-20980d69a4ff.png">

2021-08-23 15:53 UTC, QuiiBz commented on dev/hyper.ts
> +      description: "Search for plugins on npm",
Yes you can add it, along with the [isOptional](https://fig.io/docs/reference/arg#isoptional) option!

2021-08-23 15:54 UTC, Deep-Codes commented on dev/hyper.ts
> +      description: "Uninstall plugin",
Can you explain What should I do here?

2021-08-23 15:59 UTC, QuiiBz commented on dev/hyper.ts
> +      description: "Uninstall plugin",
We were talking about [generators](https://fig.io/docs/reference/generator), which is an amazing feature of Fig. They allow you to dynamically provide suggestions, using a shell command. In this case, we could make a generator for `uninstall`, which would run the `hyper ls` command in the background, parse the result, and output it as suggestions.

You don't need to make generators right now, it's just a cool feature that can be added in the future. Feel free to ask if you need more help on this!

2021-08-23 17:23 UTC, Deep-Codes commented on dev/hyper.ts
> +      description: "Search for plugins on npm",
Added ✅

2021-08-23 17:27 UTC, Deep-Codes commented on dev/hyper.ts
> +      description: "Uninstall plugin",
Hey got it running 🚀

<img width="551" alt="Screenshot 2021-08-23 at 10 57 30 PM" src="https://user-images.githubusercontent.com/61158210/130490778-73b20dfb-2eed-486b-89e8-640c05dbc9d4.png">

2021-08-23 17:31 UTC, Deep-Codes commented
Seems like a new lint rule is failing CI 🙂

2021-08-23 17:34 UTC, fedeci commented
You can rebase on master, run `npm run lint:fix` and we are good to go!

2021-08-24 04:01 UTC, Deep-Codes commented
@fedeci i think this is done 🙂

2021-08-24 10:02 UTC, QuiiBz commented
Could you rebase your PR to `master`? There are a lot of past commits above.

2021-08-28 10:01 UTC, QuiiBz approved these changes
Just removed the past commits, thanks a lot for this PR!

2021-08-28 10:01 UTC, merged