feat: create dotnet completion specs
withfig/autocomplete pull request #518
Opened 2021-08-23 19:38 UTC by Mitch528

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

This PR adds specs for the dotnet CLI

**What is the current behavior? (You can also link to an open issue here)**

No support

**What is the new behavior (if this is a feature change)?**

New feature

**Additional info:**

2021-08-24 09:35 UTC, QuiiBz requested changes
Thanks a lot for this huge spec! I left some comments, mostly typos

2021-08-24 09:35 UTC, QuiiBz commented on dev/dotnet.ts
> +        name: "path",
Should this arg have a template of `filepaths` or `folders`?

2021-08-24 09:35 UTC, QuiiBz commented on dev/dotnet/dotnet-build.ts
> +        name: "arch",
Could we provide suggestions for this argument?

2021-08-24 09:35 UTC, QuiiBz commented on dev/dotnet/dotnet-migrate.ts
> +        "Output migration report file as JSON rather than user messages.,",
```suggestion
        "Output migration report file as JSON rather than user messages.",
```

2021-08-24 09:35 UTC, QuiiBz commented on dev/dotnet/dotnet-list.ts
> +            "Lists packages that have known vulnerabilities. Cannot be combined with --deprecated or --outdated options.,",
```suggestion
            "Lists packages that have known vulnerabilities. Cannot be combined with --deprecated or --outdated options.",
```

2021-08-24 09:35 UTC, QuiiBz commented on dev/dotnet/dotnet-migrate.ts
> +        "Output migration report file as JSON rather than user messages.,",
```suggestion
        "Output migration report file as JSON rather than user messages.",
```

2021-08-24 12:23 UTC, Mitch528 commented on dev/dotnet/dotnet-build.ts
> +        name: "arch",
Yep!

2021-08-24 12:24 UTC, Mitch528 commented on dev/dotnet.ts
> +        name: "path",
Yes, it should.

2021-08-24 21:34 UTC, Mitch528 commented
Resolves #517

2021-08-25 07:49 UTC, QuiiBz approved these changes
LGTM! Thanks a lot for this huge spec, dotnet devs are gonna love this

2021-08-25 07:49 UTC, merged