Add spec for Ag (Silver Searcher)
withfig/autocomplete pull request #531
Opened 2021-08-27 10:18 UTC by RSO

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Add all the args from the `man ag` page.

This is my first time writing autocomplete specs so let me know if there's anything I should've done differently!

Fixes #529

2021-08-28 09:18 UTC, QuiiBz requested changes
Thanks a lot for this spec!

> This is my first time writing autocomplete specs so let me know if there's anything I should've done differently!

That's actually really good! I left some comments to improve further the spec. Also, could you rebase/merge `master`, because we added a new ESLint rule (#523) for descriptions, and I think there are some issues with it in this spec.

2021-08-28 09:18 UTC, QuiiBz commented on dev/ag.ts
> +      description: "Don't print color codes in results.",
We can add [exclusiveOn](https://fig.io/docs/reference/option#exclusiveon) for those two options!

2021-08-28 09:18 UTC, QuiiBz commented on dev/ag.ts
> +      description: "Don't follow symlinks.",
Same as above for `filename / nofilename` and `follow / nofollow`

2021-08-28 09:18 UTC, QuiiBz commented on dev/ag.ts
> +        "Refrains from lumping matches in the same file together, and instead places the filename at the start of each match line.",
Same as above

2021-08-28 09:18 UTC, QuiiBz commented on dev/ag.ts
> +      description: "Don't print filenames above matching contents.",
Same as above

2021-08-28 09:18 UTC, QuiiBz commented on dev/ag.ts
> +        description: "The pattern to look for",
I think we can also add a template of `filepaths` and `folders` here

2021-08-28 09:18 UTC, QuiiBz commented on dev/ag.ts
> +        description: "The directory to ignore",
Same as above but only for `folers`

2021-08-28 09:18 UTC, QuiiBz commented on dev/ag.ts
> +      description: "Don't match regexes across newlines",
Same as above for [exclusiveOn](https://fig.io/docs/reference/option#exclusiveon)

2021-08-28 09:18 UTC, QuiiBz commented on dev/ag.ts
> +        description: "The path to the ignore file",
Looks like we can add a template of `filepaths`

2021-08-28 09:18 UTC, QuiiBz commented on dev/ag.ts
> +        description: "The pager",
Could we add [suggestions](https://fig.io/docs/reference/arg#suggestions) to this argument? (just to name a few, more, less, most...)

2021-08-30 08:15 UTC, RSO commented
> > Is there a way to get the autocomplete to show certain options above others?
> 
> Yep! You can use the [`priority`](https://fig.io/docs/reference/option#priority) property.

It seems to me that the priority only is available on the `option` and not on the `arg`? In my case, I'd like the args to be shown above the options if that makes sense!

2021-08-31 07:49 UTC, QuiiBz commented
> It seems to me that the priority only is available on the `option` and not on the `arg`? In my case, I'd like the args to be shown above the options if that makes sense!

You're right, `priority` is currently only available for `options`. We might need to add it to `args`.

2021-08-31 07:53 UTC, QuiiBz approved these changes
LGTM, thanks a lot for this amazing spec!

2021-08-31 07:53 UTC, merged