[aws] sso login
withfig/autocomplete pull request #543
Opened 2021-08-31 15:11 UTC by danilofuchs

Implements the only missing suggestion for AWS SSO

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sso/index.html#cli-aws-sso

2021-09-01 11:58 UTC, fedeci commented on dev/aws/sso.ts
> +            name: "string",
```suggestion
            name: "name",
```

2021-09-02 14:35 UTC, QuiiBz requested changes
Thanks a lot for this contribution!

We only have two comments to resolve before getting this PR merged in.

2021-09-02 14:35 UTC, QuiiBz commented on dev/aws/sso.ts
> +        "Refreshes SSO access tokens and logs in. Required setup using ``aws configure sso``",
Looks like we have some extra `:
```suggestion
        "Refreshes SSO access tokens and logs in. Required setup using `aws configure sso`",
```

2021-09-02 14:35 UTC, QuiiBz commented on dev/aws/sso.ts
> +            name: "string",
Agree with @fedeci

2021-09-03 13:09 UTC, danilofuchs commented on dev/aws/sso.ts
> +        "Refreshes SSO access tokens and logs in. Required setup using ``aws configure sso``",
I've used other AWS commands as template. It seems like all of them use double backticks

2021-09-03 15:20 UTC, QuiiBz approved these changes
LGTM, thanks a lot for this PR!

2021-09-03 15:21 UTC, merged