feat: Add `vultr-cli` spec
withfig/autocomplete pull request #550
Opened 2021-09-01 15:23 UTC by rmorey

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adds spec for the [Vultr CLI](https://github.com/vultr/vultr-cli)

Vultr is a cloud services provider (VPS, object storage, etc) and this is their offical CLI.

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2021-09-12 13:38 UTC, QuiiBz commented
Hello @rmorey, thanks for opening this PR! Is it still in draft, or ready for review?

2021-09-12 14:27 UTC, rmorey commented
> Hello @rmorey, thanks for opening this PR! Is it still in draft, or ready for review?

Still in draft! :)

2021-09-17 06:58 UTC, QuiiBz commented
> Still in draft! :)

Alright, feel free to @ me when you're ready for a review!

2021-09-18 17:44 UTC, fedeci reviewed
Thank you!

2021-09-18 17:44 UTC, fedeci commented on dev/vultr-cli.ts
> +    args: {},
Could you provide a name for the `args` please? Both here and in the other parts of the spec😄

2021-09-18 17:44 UTC, fedeci commented on dev/vultr-cli.ts
> +const createOptions = [
```suggestion
const createOptions: Fig.Option[] = [
```

2021-09-18 17:44 UTC, fedeci commented on dev/vultr-cli.ts
> +          description: "Get a bare metal server's VNC url by <bareMetalID>",
Does it accept a `bareMetalId` arg?
```suggestion
          description: "Get a bare metal server's VNC url by <bareMetalID>",
          args: bareMetalIdArg,
```

2021-09-19 13:10 UTC, QuiiBz requested changes

2021-09-19 13:10 UTC, QuiiBz commented on dev/vultr-cli.ts
> +  // TODO: suggestions
Are you going to implement the suggestions in this PR?

2021-09-29 15:46 UTC, merged