feat: add nativescript completion spec
withfig/autocomplete pull request #563
Opened 2021-09-06 09:37 UTC by pekevski

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature: added the NativeScript completion spec

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**
ns, tns and nativescript autocompletion specs have been introduced to Fig

**Additional info:**

2021-09-06 11:45 UTC, fedeci commented on dev/ns.ts
> +  priority: 1,
Why this is so low?

2021-09-06 11:45 UTC, fedeci commented on dev/ns.ts
> +  priority: 0,
Same here?

2021-09-06 12:20 UTC, fedeci commented on dev/ns.ts
> +  description: "If set forces rebuilding the native application",
I think that "if set" is implicit and should be removed.

2021-09-06 12:20 UTC, fedeci commented on dev/ns.ts
> +  subcommands: [...allCommands],
```suggestion
  subcommands: allCommands,
```

2021-09-06 12:20 UTC, fedeci commented on dev/ns.ts
> +    android: [...androidGeneralOptions],
```suggestion
    android: androidGeneralOptions,
```

2021-09-07 07:21 UTC, pekevski commented on dev/ns.ts
> +    android: [...androidGeneralOptions],
I will apply all your recommendations tonight. Thanks for the review :)

2021-09-07 07:22 UTC, pekevski commented
I will apply the recommendations later tonight. Thanks for the review 🚀

2021-09-07 09:23 UTC, fedeci approved these changes

2021-09-07 09:24 UTC, fedeci approved these changes

2021-09-07 09:24 UTC, fedeci commented on dev/nativescript.ts
> +export { default } from "./ns";
This and tns are just aliases, right?

2021-09-07 09:25 UTC, pekevski commented
Just a note: this will resolve #563

2021-09-07 09:27 UTC, pekevski commented on dev/nativescript.ts
> +export { default } from "./ns";
correct. `ns`, `tns` and `nativescript` are all aliases (need the tns and nativescript alias for legacy reason)

2021-09-07 09:28 UTC, pekevski commented on dev/nativescript.ts
> +export { default } from "./ns";
The nativescript alias is probably extraneous

2021-09-07 09:31 UTC, fedeci commented
Can you add it in the description of the PR, autoclose does not work when written in comments.

2021-09-07 12:32 UTC, QuiiBz requested changes

2021-09-07 12:32 UTC, QuiiBz commented on dev/ns.ts
> +  insertValue: "--timeout {cursor}",
No need for `insertValue` here - we can remove it safely. Same for each `insertValue` underneath

2021-09-07 12:32 UTC, QuiiBz commented on dev/ns.ts
> +    // TODO: create a generator of ns device <platform> --available-devices
Do you want to tackle the generators in this PR?

2021-09-07 12:32 UTC, QuiiBz commented on dev/ns.ts
> +    name: "path",
Looks like this argument can have a [template](https://fig.io/docs/reference/arg#template), not sure if it should be `filepaths` or `folders`

2021-09-07 12:32 UTC, QuiiBz commented on dev/ns.ts
> +const androidGeneralOptions = [
Could you add a type of `Fig.Option[]` here? Same for `androidKeyOptions`, `platformEnvOptions`...

2021-09-07 12:32 UTC, QuiiBz commented on dev/ns.ts
> +      name: "path",
Looks like we can add a `template` of `filepaths`

2021-09-07 12:32 UTC, QuiiBz commented on dev/ns.ts
> +  args: {},
```suggestion
```

2021-09-07 12:32 UTC, QuiiBz commented on dev/ns.ts
> +        name: "directory",
We can add a template of `folders` here!

2021-09-07 12:32 UTC, QuiiBz commented on dev/ns.ts
> +            name: "ipa file path",
Same as above for a template of `filepaths`

2021-09-07 14:01 UTC, pekevski commented on dev/ns.ts
> +  insertValue: "--timeout {cursor}",
Yeah I thought so too, but in my testing it seemed like the argument was never prompted. Without the insert value, it gave the illusion to the user that they could execute the command without providing an argument?

2021-09-07 14:02 UTC, pekevski commented on dev/ns.ts
> +    // TODO: create a generator of ns device <platform> --available-devices
I attempted to however my generator script was throwing an exception in the fig logs. I posted about it on the dev-help channel here, it hasn't gotten a response yet so I thought I would tackle it later?

https://discord.com/channels/837809111248535583/839904703214649345/883695652243128330

2021-09-07 21:56 UTC, mschrage commented on dev/ns.ts
> +    // TODO: create a generator of ns device <platform> --available-devices
@QuiiBz I think it is best practice for the completion spec skeleton to be it's own PR. (Not a hard fast rule, especially for smaller specs, but it just makes things easier to review!)

2021-09-08 10:58 UTC, pekevski commented on dev/ns.ts
> +  insertValue: "--timeout {cursor}",
I noticed pressing tab or enter on an option that requires an argument doesn't force the user to type in the argument. They are able press enter again to execute the command.

2021-09-08 11:38 UTC, pekevski commented on dev/ns.ts
> +    // TODO: create a generator of ns device <platform> --available-devices
running my generator i get the following error. I think i'll just fix it in the future?

```
About to run the following command cd <dir>/forks/fig-autocomplete && ns devices --json | cat: {options: undefined}
we had an error with the script generator
Error: pty execute promise timed out. Running cmd + c in pseudo terminal just in case
```

2021-09-08 11:48 UTC, pekevski commented
Pushed fixes for the previous set of feedback.

2021-09-08 14:51 UTC, QuiiBz commented on dev/ns.ts
> +  insertValue: "--timeout {cursor}",
You have to press `space` to get the suggestions for the argument.

2021-09-08 14:56 UTC, QuiiBz commented on dev/ns.ts
> +    // TODO: create a generator of ns device <platform> --available-devices
> ```
> About to run the following command cd <dir>/forks/fig-autocomplete && ns devices --json | cat: {options: undefined}
> we had an error with the script generator
> Error: pty execute promise timed out. Running cmd + c in pseudo terminal just in case
> ```

Could you try running this command manually (`ns devices --json`)? There is a timeout of 10 seconds for each command, so that might be why you see this error in the console.

2021-09-08 23:08 UTC, pekevski commented on dev/ns.ts
> +    // TODO: create a generator of ns device <platform> --available-devices
timing the command with `time ns devices --json`, i get 
```
ns device --json  1.95s user 1.18s system 31% cpu 9.860 total
```
i think it might just be timing out, is there a way to extend it?

2021-09-10 08:08 UTC, QuiiBz commented on dev/ns.ts
> +    // TODO: create a generator of ns device <platform> --available-devices
It's not currently possible to extend this default timeout - but looks like the command doesn't exceed 10 seconds, that's strange.

2021-09-10 08:11 UTC, QuiiBz commented on dev/ns.ts
> +const iosGeneralOptions: Fig.Option[] = [];
Are there any missing options for `ios`? If they are none, we can safely remove this!

2021-09-10 08:30 UTC, pekevski commented on dev/ns.ts
> +const iosGeneralOptions: Fig.Option[] = [];
It was just a placeholder for future options if they ever got introduced. I can remove it now if you like

2021-09-10 08:37 UTC, QuiiBz commented on dev/ns.ts
> +const iosGeneralOptions: Fig.Option[] = [];
> It was just a placeholder for future options if they ever got introduced. I can remove it now if you like

Thanks for the clarification!

2021-09-10 08:42 UTC, QuiiBz approved these changes
Thank you so much for this amazing contribution! LGTM 🚀

2021-09-10 08:42 UTC, merged

2021-09-10 09:46 UTC, pekevski commented
Huge! Thanks for creating such a simple api 😎

What should we do about the generator timeouts in the meantime?