Adding startup options for bazel
withfig/autocomplete pull request #567
Opened 2021-09-07 02:37 UTC by ly0708

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Adding startup options to bazel

**What is the current behavior? (You can also link to an open issue here)**

There is no options

**What is the new behavior (if this is a feature change)?**

Autocompletion for bazel's options

**Additional info:**

2021-09-07 02:50 UTC, ly0708 commented
Hi reviewer. I am not sure why I have 10 commits to merge?

2021-09-07 09:08 UTC, fedeci commented
For the next times I'd suggest you not to work on your master branch but always create a new one :)

2021-09-07 09:14 UTC, fedeci reviewed
A couple of nits but seems ok! Thanks🎉

2021-09-07 09:14 UTC, fedeci commented on dev/bazel.ts
> +      description: "Opposite of --autodetect_server_javabase",
This is `exclusiveOn: ["--autodetect_server_javabase"]`. Can you add a more descriptive description, please?

2021-09-07 09:14 UTC, fedeci commented on dev/bazel.ts
> +      description:
`exclusiveOn: ["--noautodetect_server_javabase"]`

2021-09-07 09:14 UTC, fedeci commented on dev/bazel.ts
> +      description: "Opposite of --batch",
Same as for `--autodetect_server_javabase` about the `exclusiveOn` and I would add more complete description for `--nobatch` too.

ditto, I've seen that the most of the options are like these ones, could you update all of them?

2021-09-07 12:11 UTC, QuiiBz requested changes
Thanks for those great additions! Left some comments to resolve before merging this

2021-09-07 12:11 UTC, QuiiBz commented on dev/bazel.ts
> +        "The location of the user .bazelrc file containing default values of Bazel options",
Seems like this option takes an argument, and maybe with a template of `filepaths`?

2021-09-07 12:11 UTC, QuiiBz commented on dev/bazel.ts
> +        "The amount of time the client waits for each attempt to connect to the server",
Looks like this option also takes an argument!

2021-09-07 12:11 UTC, QuiiBz commented on dev/bazel.ts
> +        "Specifies a location to write a failure_detail protobuf message if the server experiences a failure and cannot report it via gRPC, as normal. Otherwise, the location will be ${OUTPUT_BASE}/f
Same as above

2021-09-07 12:11 UTC, QuiiBz commented on dev/bazel.ts
> +        "Only on Linux; set a level from 0-7 for best-effort IO scheduling using the sys_ioprio_set system call. 0 is highest priority, 7 is lowest",
Same as above. Could you remove the `{-1,0...}` part from the name, and instead add [suggestions](https://fig.io/docs/reference/arg#suggestions) to the argument?

2021-09-07 12:12 UTC, ly0708 commented
> For the next times I'd suggest you not to work on your master branch but always create a new one :)

Do you mean always create create a new fork everytime?

2021-09-07 12:33 UTC, QuiiBz commented
> Do you mean always create create a new fork everytime?

You just need to create a new branch on your forked repo, and create a PR from this branch

2021-09-12 13:52 UTC, merged

2021-09-13 14:07 UTC, ly0708 commented
@QuiiBz  You merged this PR, have the changes been made. 
Sorry. I haven't been able to work on this, school has been pretty crazy the past week.

2021-09-17 07:02 UTC, QuiiBz commented
> @QuiiBz You merged this PR, but there's no changes yet.

Looks like there were changes: https://github.com/withfig/autocomplete/pull/567/files

> Sorry. I haven't been able to work on this, school has been pretty crazy the past week.
> I see that there's changes to args, so I will work on making the descriptions better.

No worries at all! Feel free to open a new PR when you have the time :)