feat(deno): add generator for `deno doc` filters
withfig/autocomplete pull request #568
Opened 2021-09-07 14:47 UTC by SeparateRecords

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature: Improves `deno doc` suggestions 🎉 

**What is the current behavior? (You can also link to an open issue here)**
Suggests files to doc, doesn't suggest a filter.

**What is the new behavior (if this is a feature change)?**
Uses the scope (the file) to suggest a filter as you type.

**Additional info:**
It's a relatively complicated generator but it runs fast enough to re-generate suggestions as necessary.

I basically never use `deno doc` because searching it is a pain and I can't remember what I named that type... this generator just suggests it!

2021-09-07 14:57 UTC, SeparateRecords commented on dev/deno.ts
> +function docNameToSuggestion(name: string): Fig.Suggestion {
This function is poorly named.

2021-09-07 14:57 UTC, SeparateRecords commented on dev/deno.ts
> +          const commandUntilNode = tokens.slice(0, -1);
Still refers to "node" instead of filter.

2021-09-08 03:33 UTC, SeparateRecords commented
`--private` has finally stopped crashing the cli which has allowed me to find another issue, needs to be resolved before this can be merged

2021-09-08 04:05 UTC, SeparateRecords commented
Should be fine now.

2021-09-08 10:36 UTC, SeparateRecords commented
I've decided to restructure the generator. It's easier to understand and should be about as efficient, but it's a little bit longer. I'm not near a Mac tonight so I can't test it. This PR has been set to a draft until I've had the chance to test it and update my branch.

2021-09-09 02:49 UTC, SeparateRecords commented
(reminder for myself later)
There's a better URL for the versions JSON, so that generator may as well be updated too.

`curl -sLF https://cdn.deno.land/std/meta/versions.json`

2021-09-09 02:51 UTC, SeparateRecords commented
Better URL for the `deno upgrade --version` generator, may as well update this later too:
`curl -sL https://cdn.deno.land/deno/meta/versions.json`

2021-09-10 08:18 UTC, QuiiBz requested changes
Thanks a lot for this amazing stuff! Left some comments to improve the spec before merging it

2021-09-10 08:18 UTC, QuiiBz commented on dev/deno.ts
> +          let docNodes: any[];
Would it be possible to type properly this variable?

2021-09-10 08:18 UTC, QuiiBz commented on dev/deno.ts
> +            });
We can simplify this a bit:
```suggestion
            const foundNodes = docNodes.filter(({ name }) => name === filterName);
```

2021-09-10 08:18 UTC, QuiiBz commented on dev/deno.ts
> +          }
We can avoid duplicating the `for` loop to make this a bit cleaner:
```suggestion
          if (showPrivateSymbols) {
          for (const node of suggestNodes) {
            // Deno includes imports in the JSON regardless of privacy,
            // probably so it's easier to build a module graph. However,
            // imports are (by definition) private, so they must be removed.
            if (!showPrivateSymbols && node.kind === "import") continue;
            suggestionNames.add(node.name);
          }
```

2021-09-10 09:47 UTC, SeparateRecords commented on dev/deno.ts
> +            });
Personally I'd like that! However, that line goes over 80 characters, so the pre-commit formatter puts the condition on the line below. Reading `const foundNodes = docNodes.filter((node) =>` feels awkward, like I've been left hanging, waiting for an expression, a block... something.
Here's what I prefer:
a. The entire callback goes on the next line, which is what it was before (but it's awkward to read)
b. The callback starts on the same line as `.filter` and uses a block instead of an expression

Regardless of what we end up with, it'll be a purely stylistic choice - semantically it's identical. Lmk your thoughts!

2021-09-10 09:50 UTC, SeparateRecords commented on dev/deno.ts
> +          }
It's cleaner, but it ends up checking the `showPrivateSymbols` on each iteration instead of just once. That's probably an inconsequential difference, but it's a bunch of work that _can_ be skipped. If you think the trade off is worth it I'm happy to implement!

2021-09-10 10:04 UTC, SeparateRecords commented on dev/deno.ts
> +          let docNodes: any[];
Initially I'd copied the type definitions into the source, but it's a _pretty big_ file. Next time I'm around a Mac I'll try to gut it to include only the minimum type information :)

2021-09-12 13:09 UTC, QuiiBz commented on dev/deno.ts
> +          let docNodes: any[];
Thanks!

2021-09-12 13:13 UTC, QuiiBz commented on dev/deno.ts
> +            });
Looking at the recent commits, I find the new solution pretty clean - no need to wrap the callback to a new line while being a single-liner, that's sweet! We can keep it as it is right now.

2021-09-12 13:15 UTC, QuiiBz commented on dev/deno.ts
> +          }
How many `node` can be contained inside `suggestNodes`? I don't think that an `if` would cause any issues even if there are thousands of nodes, and I found to not repeat the `for` loop is cleaner. What do you think of it?

2021-09-12 22:09 UTC, fedeci approved these changes

2021-09-12 22:09 UTC, fedeci commented on dev/deno.ts
> +          }
Is it really worth it? I mean, we are checking for a boolean value which is the simplest operation.

2021-09-12 23:49 UTC, SeparateRecords commented on dev/deno.ts
> +          }
I honestly do think that the intention becomes less clear. Don't get me wrong, I don't have a problem with changing this, but it's just less obvious (to me personally) that there are really two separate things happening.

This is what is really going on, and the reason I think the two loops is clearer.
It's putting the names directly into the set to skip creating yet another array.
```typescript
let dups: string[];
if (showPrivateSymbols) {
  dups = suggestNodes
    .map((node) => node.name);
} else {
  dups = suggestNodes
    .filter((node) => node.kind !== "import")
    .map((node) => node.name);
}
const names = new Set(dups);
```

I've written out the suggested code so I can add it when I'm home later:

```suggestion
          for (const node of suggestNodes) {
            if (showPrivateSymbols) {
              names.add(node.name);
              continue;
            }
            // Deno includes imports in the JSON regardless of privacy,
            // probably so it's easier to build a module graph. However,
            // imports are (by definition) private, so they must be removed.
            if (node.kind === "import") continue;

            names.add(node.name);
          }
```

2021-09-13 00:16 UTC, SeparateRecords commented on dev/deno.ts
> +      return (data.versions as string[]).map((version) => ({
Marginally, yeah. Ran a benchmark with 1000 items in the array: the array-map-regex-replace takes about 0.05ms, whereas array-map-slice takes about 0.015. It's an even less meaningful difference with the actual versions data (currently 148 tags)

I think that the resilience of the regex is worth the additional 0.035ms. If a future version is tagged without the leading `v`, it will be fine. With a slice, the leading digit will be removed if there's no 'v'.

I didn't notice I'd deleted the comment explaining my reasoning, though, so that's good to know.

2021-09-13 07:17 UTC, fedeci approved these changes

2021-09-13 07:17 UTC, fedeci commented on dev/deno.ts
> +            if (showPrivateSymbols) {
I even prefer refactoring again to join that call.
```suggestion
            if (showPrivateSymbols || node.kind !== "import") {
```

2021-09-13 08:25 UTC, SeparateRecords commented on dev/deno.ts
> +            if (showPrivateSymbols) {
I think leaving it as-is makes it much easier to read, even if it's longer. @QuiiBz thoughts?

2021-09-13 23:31 UTC, SeparateRecords commented
`deno` 1.14 is being released tomorrow, so best to hold off on this PR. It includes the lastest `deno_doc` that outputs another top level kind of doc node (moduleDoc) that will have to be added to the types and filtered out. I'll test tonight in the Canary build and update when I know this works.

2021-09-15 01:57 UTC, SeparateRecords commented
Looks like it's all working to me. Hopefully we can finish this up today/tomorrow!

2021-09-15 11:15 UTC, fedeci commented
Thanks @SeparateRecords, it seems ok now! I will re-review the PR later to see the other changes

2021-09-17 07:08 UTC, QuiiBz approved these changes
LGTM, love this new generator 🎉

2021-09-17 07:08 UTC, merged