Add autocompletion for composer recipes commands
withfig/autocomplete pull request #569
Opened 2021-09-07 16:20 UTC by duboiss

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
No autocompletion.

**What is the new behavior (if this is a feature change)?**
Two new commands which only appear in the presence of a `symfony.lock` file.

**Additional info:**
This is a composer plugin specific to the symfony framework (symfony flex).

2021-09-08 07:07 UTC, Monkeyank requested changes

2021-09-08 07:07 UTC, Monkeyank commented on dev/composer.ts
> +        { name: "--no-ansi", description: "Disable ANSI output" },
Can we add an `exclusiveOn: ` prop

2021-09-08 07:07 UTC, Monkeyank commented on dev/composer.ts
> +        { name: "--no-plugins", description: "Whether to disable plugins" },
Same as above

2021-09-08 14:45 UTC, QuiiBz requested changes

2021-09-08 14:45 UTC, QuiiBz commented on dev/composer.ts
> +      const recipesCommonOptions = [
Could you add a type of `Fig.Option[]` here?

2021-09-08 14:45 UTC, QuiiBz commented on dev/composer.ts
> +            "If specified, use the given directory as working directory",
Does this option take an argument, which is the working directory?

2021-09-08 14:45 UTC, QuiiBz commented on dev/composer.ts
> +                "Overwrite existing files when a new version of a recipe is available",
We can definitely add [isDangerous](https://fig.io/docs/reference/option#isdangerous) here!

2021-09-09 08:13 UTC, duboiss commented on dev/composer.ts
> +            "If specified, use the given directory as working directory",
We can use :
```
-d <path>
--working-dir=<path>
--working-dir <path>
```

2021-09-09 08:24 UTC, duboiss commented on dev/composer.ts
> +        { name: "--no-plugins", description: "Whether to disable plugins" },
For which command?

2021-09-09 11:04 UTC, SeparateRecords commented on dev/composer.ts
> +        },
```suggestion
        {
          name: ["-d", "--working-dir"],
          description:
            "If specified, use the given directory as working directory",
          args: {
            name: "dir",
            template: "folders",
          },
        },
```

2021-09-09 11:18 UTC, SeparateRecords commented on dev/composer.ts
> +      if (!symfonyLock.endsWith("(No such file or directory)")) {
Nitpicky suggestion: extracting this to a separate variable would make the intention a lot clearer
<sub><i>and yes, I do see the irony, given that I'm the one who suggested this code on discord 😅</i></sub>

```suggestion
      const lockExists = !symfonyLock.endsWith("(No such file or directory)");
      if (lockExists) {
```

2021-09-09 21:58 UTC, fedeci requested changes

2021-09-09 21:58 UTC, fedeci commented on dev/composer.ts
> +          name: ["-v", "-vv", "-vvv", "--verbose"],
These are different options about verbosity. We can'y join all of them together.

2021-09-10 08:31 UTC, QuiiBz requested changes

2021-09-10 08:31 UTC, QuiiBz commented on dev/composer.ts
> +        },
As @fedeci mentioned, this should be separated in 3 options: normal (v), verbose (vv) and debug (vvv)

2021-09-11 22:42 UTC, fedeci approved these changes

2021-09-12 13:16 UTC, QuiiBz approved these changes
Thank you so much for this PR, LGTM 🚀

2021-09-12 13:17 UTC, merged