feat: add autocomplete spec for `mongosh`
withfig/autocomplete pull request #580
Opened 2021-09-10 16:39 UTC by nicholasoxford

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Introduce CLI completion MongoDB's Command Line Tool.

I also noticed the PR to delete package-lock from the repo so I went ahead and did that too.

**What is the current behavior? (You can also link to an open issue here)**

No autocomplete

**What is the new behavior (if this is a feature change)?**

**Additional info:**
https://docs.mongodb.com/mongodb-shell/reference/options/

2021-09-11 00:09 UTC, mschrage requested changes
Hey @nicholasoxford - This is a great first pass! Thanks so much for contributing 🎉

One small thing and then we can get this merged in.  🤞

It seems like a few of the options are missing arguments. To fix this, just identify all of the options that take an argument and add `args: {}`. This is an important signal that the autocomplete-engine uses to provide relevant suggestions!

2021-09-11 00:09 UTC, mschrage commented on dev/mongosh.ts
> +    },
Looks like the `--eval` option takes an argument. This should be 
```suggestion
      name: "--eval",
      description:
        "<javascript>: Evaluates a JavaScript expression that is specified as an argument. mongosh does not load its own environment when evaluating code. As a result many options of the shell environment are not available. The result of evaluating a JavaScript argument is printed to your command line",
        args: {
             name: "javascript"
        }
    },
```

2021-09-11 00:09 UTC, mschrage commented on dev/mongosh.ts
> +    },
I think `--authenticationDatabase` also takes an argument!

2021-09-11 10:10 UTC, fedeci requested changes

2021-09-11 10:10 UTC, fedeci commented on dev/mongosh.ts
> +      },
Can we set the priority of this to something between 25 and 50?

2021-09-11 10:10 UTC, fedeci commented on dev/mongosh.ts
> +        "Specifies the port where the mongod or mongos instance is listening. If --port is not specified, the MongoDB Shell attempts to connect to port 27017",
This takes an arg

2021-09-11 10:10 UTC, fedeci commented on dev/mongosh.ts
> +        "<javascript>: Evaluates a JavaScript expression that is specified as an argument. mongosh does not load its own environment when evaluating code. As a result many options of the shell enviro
Is this the same description as `--eval`?

2021-09-11 10:10 UTC, fedeci commented on dev/mongosh.ts
> +        "Specifies a username with which to authenticate to a MongoDB database that uses authentication. Use in conjunction with the --password and --authenticationDatabase options",
Needs an arg?

2021-09-11 10:10 UTC, fedeci commented on dev/mongosh.ts
> +        "Specifies a password with which to authenticate to a MongoDB database that uses authentication. Use in conjunction with the --username and --authenticationDatabase options",
I think all of these are missing args

2021-09-11 13:32 UTC, nicholasoxford commented
Thank you all for the help, I love fig!

2021-09-11 22:48 UTC, fedeci requested changes

2021-09-11 22:48 UTC, fedeci commented on dev/mongosh.ts
> +      description: "View your current git version",
```suggestion
      description: "View your current mongosh version",
```

2021-09-11 22:48 UTC, fedeci commented on dev/mongosh.ts
> +        "Specifies a password with which to authenticate to a MongoDB database that uses authentication. Use in conjunction with the --username and --authenticationDatabase options",
ping :)

2021-09-12 00:37 UTC, nicholasoxford commented on dev/mongosh.ts
> +        "Specifies a password with which to authenticate to a MongoDB database that uses authentication. Use in conjunction with the --username and --authenticationDatabase options",
Which one did I miss? I see an arg for username and password

2021-09-12 08:57 UTC, fedeci commented on dev/mongosh.ts
> +        "Specifies a password with which to authenticate to a MongoDB database that uses authentication. Use in conjunction with the --username and --authenticationDatabase options",
`Apihostname` and `apiservicename`

2021-09-12 13:23 UTC, QuiiBz requested changes
Thanks a lot for this amazing spec! Left some improvements for the descriptions, you've done great work!

2021-09-12 13:23 UTC, QuiiBz commented on dev/mongosh.ts
> +    "The MongoDB Shell, mongosh , is a fully functional JavaScript and Node.js 14.x REPL environment for interacting with MongoDB deployments",
```suggestion
    "The MongoDB Shell, mongosh  is a fully functional JavaScript and Node.js 14.x REPL environment for interacting with MongoDB deployments",
```

2021-09-12 13:23 UTC, QuiiBz commented on dev/mongosh.ts
> +        "<javascript>: Evaluates a JavaScript expression that is specified as an argument. mongosh does not load its own environment when evaluating code. As a result many options of the shell enviro
I don't think the `<javascript>: ` part is needed since the description explains well how it works:
```suggestion
        "Evaluates a JavaScript expression that is specified as an argument. mongosh does not load its own environment when evaluating code. As a result many options of the shell environment are not available. The result of evaluating a JavaScript argument is printed to your command line",
```

2021-09-12 13:33 UTC, fedeci commented on dev/mongosh.ts
> +    "The MongoDB Shell, mongosh , is a fully functional JavaScript and Node.js 14.x REPL environment for interacting with MongoDB deployments",
I think that comma is useful there, it's an aside of the phrase.

2021-09-12 13:56 UTC, QuiiBz commented on dev/mongosh.ts
> +    "The MongoDB Shell, mongosh , is a fully functional JavaScript and Node.js 14.x REPL environment for interacting with MongoDB deployments",
I made a mistake, wanted to remove the space before the comma, not remove the comma itself 😅
Here is the new suggestion:
```suggestion
    "The MongoDB Shell, mongosh, is a fully functional JavaScript and Node.js 14.x REPL environment for interacting with MongoDB deployments",
```

2021-09-12 14:47 UTC, nicholasoxford commented
Changes pushed.

2021-09-12 15:35 UTC, nicholasoxford commented
Hate to be this guy, but something I noticed on the docs.

https://fig.io/docs/concepts/cli-skeleton#argument

The link in `See "Argument" for a full description of all properties.` does not work.

2021-09-17 06:53 UTC, QuiiBz commented
> Hate to be this guy, but something I noticed on the docs.
> 
> https://fig.io/docs/concepts/cli-skeleton#argument
> 
> The link in `See "Argument" for a full description of all properties.` does not work.

Good catch, thanks! Transfering this issue to fix it asap :)

2021-09-17 06:55 UTC, QuiiBz approved these changes
This looks all good to me, thank you so much for this contribution!

2021-09-17 06:57 UTC, merged