feat: update `gh` spec
withfig/autocomplete pull request #583
Opened 2021-09-13 23:09 UTC by nicholasoxford

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Updated the GH CLI autocomplete to include GH 2.0 commands

**What is the current behavior? (You can also link to an open issue here)**

issing

**What is the new behavior (if this is a feature change)?**

Adds sections like extensions and ssh-key

**Additional info:**

https://cli.github.com/manual/

2021-09-14 11:42 UTC, fedeci reviewed
Can you run `npm run lint:fix && npm run test` locally and then push again?

2021-09-14 14:16 UTC, nicholasoxford commented
I ran it, but it seemed to not stage any changes.

<img width="1168" alt="Screen Shot 2021-09-14 at 10 16 34 AM" src="https://user-images.githubusercontent.com/51415676/133274514-b8fdaa62-d703-4a36-8843-4f75031e235e.png">

2021-09-14 14:32 UTC, fedeci commented on dev/gh.ts
> +      options: [ghOptions.ghRunOptions],
The fact that `tsc` is not marking this as an error is a problem🤔

2021-09-14 14:33 UTC, nicholasoxford commented on dev/gh.ts
> +      options: [ghOptions.ghRunOptions],
What is the type collision?

2021-09-14 14:38 UTC, fedeci requested changes

2021-09-14 14:38 UTC, fedeci commented on dev/gh.ts
> +            ghOptions.ghRunOptions,
I don't think it needs to be repeated in the subcommands too.

2021-09-14 14:38 UTC, fedeci commented on dev/gh.ts
> +  force: { name: "--force", description: "Force upgrade extensions" },
I don't find it logically correct to make this a dictionary. An array is enough. Same for `ghRunOptions`

2021-09-14 14:39 UTC, fedeci commented on dev/gh.ts
> +      options: [ghOptions.ghRunOptions],
The fact that `ghOptions` does not contain a `ghRunOptions` prop.

2021-09-14 14:50 UTC, nicholasoxford commented on dev/gh.ts
> +  force: { name: "--force", description: "Force upgrade extensions" },
Out of curiosity, what's the logic behind making a dictionary?

2021-09-16 01:36 UTC, nicholasoxford commented on dev/gh.ts
> +  force: { name: "--force", description: "Force upgrade extensions" },
Honestly I can't believe I put ghOptins.ghRunOptions 🤣, I probably only put it because it wasn't failing.

2021-09-17 07:13 UTC, QuiiBz commented
Hi @nicholasoxford, thanks a lot for this PR! Could you rebase your branch to keep a clean history?

2021-09-17 14:05 UTC, nicholasoxford commented
rebase did not go as originally planned.

Reopened here: https://github.com/withfig/autocomplete/pull/589

2021-09-17 14:05 UTC, closed without merging