feat: update Deno CLI spec to 1.14
withfig/autocomplete pull request #585
Opened 2021-09-15 01:55 UTC by SeparateRecords

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
This PR adds support for new flags added in Deno CLI 1.14, released earlier today.
This includes 1 new generator (`generateLintRules`).

Relevant issue (not a blocker): withfig/fig#454

2021-09-15 12:07 UTC, fedeci commented on dev/deno.ts
> +        name: "wrap",
```suggestion
        name: "wrap",
        default: "always",
```

2021-09-15 12:24 UTC, SeparateRecords commented on dev/deno.ts
> +        name: "wrap",
Oh, that's neat! I didn't know about `default`. I'll play around with that later. Looking at the docs for that also lead to me finding `isPersistent`, so I'll set that on the global options. Thanks!

2021-09-16 08:40 UTC, SeparateRecords commented on dev/deno.ts
> +        name: "wrap",
I've had a chance to test this now. I've added the `default` prop, but I don't think it's necessary to remove `(default: always)` from the description because the value of the `default` isn't visible in the popup. If/when that's changed, I'll fix it.
For now, it's more useful for the user to be able to see, in the description, that "always" is the default.

2021-09-17 07:24 UTC, QuiiBz requested changes

2021-09-17 07:24 UTC, QuiiBz commented on dev/deno.ts
> +    return suggestions;
I think we can improve the readability of this:
```suggestion
    return out
      .split("\n")
      .filter(line => line.startsWith(" - "))
      .map(line => ({
        name: line.slice(3),
        icon: "fig://icon?type=string",
      }));
```

2021-09-17 07:24 UTC, QuiiBz commented on dev/deno.ts
> +        name: "wrap",
In the future, we might show `default` in the UI, so that would be awesome if you can keep both!

2021-09-17 09:53 UTC, SeparateRecords commented
In implementing @QuiiBz's suggestions I realized that [`--rules` and `--json` can actually be used together](https://github.com/denoland/deno/blob/c04117134ecb07fb6379bfe1057c9da8e0c4f206/cli/tools/lint.rs#L159-L168), which was added by Bartek in denoland/deno#8384. This means we can get a description for each rule, too!

Each description is valid markdown (statically included in the binary from [this directory](https://github.com/denoland/deno_lint/tree/main/docs/rules). This means it's fine to take everything up to the first paragraph separator (`\n\n`), and use that as the description. Also, since Fig doesn't render inline code, I'm removing the surrounding back-ticks.

![image](https://user-images.githubusercontent.com/52195359/133759093-a13e633f-fa47-431d-be5f-4fefee6bea36.png)

2021-09-18 07:04 UTC, SeparateRecords commented
Merge conflicts should be resolved now. Ready for another review :)

2021-09-19 13:03 UTC, QuiiBz approved these changes
LGTM, thank you so much 🎉

2021-09-19 13:04 UTC, merged