feat: update `tailwindcss` spec to latest version
withfig/autocomplete pull request #586
Opened 2021-09-15 11:49 UTC by fedeci

2021-09-17 07:10 UTC, QuiiBz requested changes

2021-09-17 07:10 UTC, QuiiBz commented on dev/tailwindcss.ts
> +  },
Looks like this option is duplicated

2021-09-17 10:33 UTC, fedeci commented on dev/tailwindcss.ts
> +      "Content paths to use for removing unused classes. [Deprecated]: use `--content` instead",
```suggestion
    name: "--content",
    description: "Content paths to use for removing unused classes instead",
```

2021-09-17 10:33 UTC, fedeci commented on dev/tailwindcss.ts
> +  },
🤦‍♂️

2021-09-19 12:41 UTC, QuiiBz requested changes

2021-09-19 12:41 UTC, QuiiBz commented on dev/tailwindcss.ts
>    },
Looks like there are still two options that are the same 😅

2021-09-19 12:57 UTC, fedeci commented on dev/tailwindcss.ts
>    },
Damn😆

2021-09-19 12:58 UTC, fedeci commented on dev/tailwindcss.ts
> +  },
```suggestion
```

2021-09-19 12:58 UTC, fedeci commented on dev/tailwindcss.ts
>    },
Fixed

2021-09-19 13:11 UTC, QuiiBz approved these changes
LGTM 🚀

2021-09-19 13:11 UTC, merged