feat: update gh spec to latest version
withfig/autocomplete pull request #589
Opened 2021-09-17 14:05 UTC by nicholasoxford

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Adds functionality to the gh autocomplete.

**What is the current behavior? (You can also link to an open issue here)**

No autocomplete for arguments like extension

**What is the new behavior (if this is a feature change)?**

**Additional info:**

https://cli.github.com/manual/gh_extension

2021-09-19 12:48 UTC, QuiiBz requested changes
Amazing improvements to the `gh` spec!

2021-09-19 12:48 UTC, QuiiBz commented on dev/gh.ts
> +          description: "Remove an installed extension",
Wrong description for `upgrade`?

2021-09-19 12:48 UTC, QuiiBz commented on dev/gh.ts
> +              description: "Filter runs by workflow",
Looks like those two options both takes an argument

2021-09-19 12:48 UTC, QuiiBz commented on dev/gh.ts
> +              description: "View a specific job ID from a run",
Does this option also take an argument?

2021-09-19 12:48 UTC, QuiiBz commented on dev/gh.ts
> +              description: "Refresh interval in seconds (default 3)",
Same as above

2021-09-19 12:48 UTC, QuiiBz commented on dev/gh.ts
> +            },
It seems like those two options are duplicated in `remove` and `set` subcommands, could you extract them to a top-level const to avoid duplicating them?

2021-09-27 22:02 UTC, mschrage commented
@QuiiBz @nicholasoxford is this still a WIP or are we ready to merge this in?

2021-09-28 15:59 UTC, QuiiBz commented
> @QuiiBz @nicholasoxford is this still a WIP or are we ready to merge this in?

Looks like it's still a WIP, if there isn't any news in few days I will finish the PR myself. @nicholasoxford any news on this?

2021-09-28 16:01 UTC, nicholasoxford commented
Forgot to push. It will be in by end of day

2021-10-01 12:19 UTC, nicholasoxford commented
Lol sorry been learning rust and forgot to push. Let me know if yall need anything else!

2021-10-01 16:37 UTC, QuiiBz approved these changes
LGTM! We just need to resolve the merge conflict and we'll be ready to merge 🚀

2021-10-05 18:25 UTC, merged