feat(subl): add options
withfig/autocomplete pull request #592
Opened 2021-09-18 06:25 UTC by SeparateRecords

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
This PR adds options to `subl`

2021-09-19 13:01 UTC, QuiiBz requested changes
Thanks for this PR!

2021-09-19 13:01 UTC, QuiiBz commented on src/subl.ts
> +  },
I would prefer a cleaner solution, something like:
```suggestion
  filterTemplateSuggestions: (suggestions) => suggestions.map(suggestion => {
    if (suggestion.type === "folder") {
      return suggestion;
    }

    return {
      ...suggestion,
      priority: /^\.sublime-(project|workspace)$/.test(suggestion.name)
        ? 75
        : suggestion.priority
    }
  })
```

2021-09-19 13:20 UTC, SeparateRecords commented on src/subl.ts
> +      description: "Add folders to the current window",
Not by itself, it's just a modifier. When it's present, ST will add the files/dirs to the current window

2021-09-19 13:22 UTC, SeparateRecords commented on src/subl.ts
> +        name: "command",
It's not the kind of command Fig provides completions for, though - it's one of [these](https://docs.sublimetext.io/reference/commands.html#about-paths-in-command-arguments). Should it still be set?

2021-09-19 14:05 UTC, SeparateRecords commented on src/subl.ts
> +  },
I think the actual problem here was my lack of comments explaining the intention :)
This loop also removes the files that _don't_ match the regex, so it's a combined filter/map. The equivalent would be this, which is slower. Debatably clearer, but comments can fix that in the imperative version.

```typescript
const generateProjects: Fig.Generator = {
  template: "filepaths",
  filterTemplateSuggestions: (suggestions) =>
    suggestions
      .filter((suggestion) => {
        if (suggestion.type === "folder") {
          return true;
        }
        return /^\.sublime-(project|workspace)$/.test(suggestion.name);
      })
      .map((suggestion) => {
        if (suggestion.type === "folder") {
          return suggestion;
        }
        return { ...suggestion, priority: 75 };
      }),
};
```

Lmk if you'd rather go ahead with this version!

2021-09-20 01:35 UTC, SeparateRecords commented on src/subl.ts
> +    },
@QuiiBz -n and -a aren't mutually exclusive, but when -n is present -a is silently ignored. Should these be marked as `exclusiveOn`?

2021-09-22 10:04 UTC, QuiiBz commented on src/subl.ts
> +        name: "command",
Thanks for the clarification! So no, no need to set `isCommand`, you're 100% right!

2021-09-22 10:05 UTC, QuiiBz commented on src/subl.ts
> +  },
That would be awesome if you could add some comments!

2021-09-22 10:06 UTC, QuiiBz commented on src/subl.ts
> +    },
Totally! You can add `-a` to `exclusiveOn` for the `"-n", "--new-window"` option

2021-09-22 16:08 UTC, mschrage approved these changes
🙌

2021-09-22 16:11 UTC, merged