Add BSD whois options
withfig/autocomplete pull request #594
Opened 2021-09-20 07:42 UTC by SeparateRecords

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Removes non-existent options and adds all the other options

**What is the current behavior? (You can also link to an open issue here)**
Incorrect options are suggested, and none of the actual options are

**Additional info:**
Because macOS, it's another BSD spec. Will need to be updated in the future.

2021-09-22 10:42 UTC, QuiiBz requested changes

2021-09-22 10:42 UTC, QuiiBz commented on src/whois.ts
> -    { name: ["-H", "-p", "PORT"], description: "Connect to PORT" },
Looks like the `-p` option exists, along with `-h` for host:
![Screenshot 2021-09-22 at 12 41 19](https://user-images.githubusercontent.com/43268759/134329528-eae4a397-866c-46ae-8933-1b12b119c7e4.png)

Could you add them back?

2021-09-22 10:49 UTC, SeparateRecords commented on src/whois.ts
> -    { name: ["-H", "-p", "PORT"], description: "Connect to PORT" },
Already added (L39 and L69) 😄 

Although, I didn't notice that was a pipe between `-c` and `-h` - they are indeed exclusive, so I'll fix that.

2021-09-22 10:54 UTC, QuiiBz commented on src/whois.ts
> -    { name: ["-H", "-p", "PORT"], description: "Connect to PORT" },
I'm dumb, sorry 😅 Alright!

2021-09-26 10:23 UTC, SeparateRecords commented
Btw this is ready for review again 😅 I probably should have said so sooner haha

2021-09-26 12:05 UTC, fedeci approved these changes

2021-09-27 17:12 UTC, QuiiBz approved these changes
LGTM, a big improvement on this spec, thank you so much!

2021-09-27 17:12 UTC, merged