feat(serve): add autocompletion spec
withfig/autocomplete pull request #595
Opened 2021-09-20 19:18 UTC by Pkingo

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature: added autocompletion for serve

**What is the current behavior? (You can also link to an open issue here)**
None.

**What is the new behavior (if this is a feature change)?**
Added autocompletion for serve in accordance with their help section

**Additional info:**
This is my first contribution to fig, and I'm by no means an expert in serve. So if you have any suggestions or something you would like to see different, please let me know.

2021-09-22 10:44 UTC, QuiiBz requested changes
Thank you so much for this PR!

2021-09-22 10:44 UTC, QuiiBz commented on dev/serve.ts
> +            type: "arg",
You can safely remove `type: "arg"` from all the suggestions

2021-09-22 13:22 UTC, Pkingo commented on dev/serve.ts
> +            type: "arg",
Great. Thanks 💪

2021-09-27 16:55 UTC, QuiiBz approved these changes
LGTM, thanks a lot for this spec!

2021-09-27 16:55 UTC, merged