feat: add htop completion spec
withfig/autocomplete pull request #608
Opened 2021-09-26 20:41 UTC by jhrcook

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
New feature: add htop completion spec

**What is the current behavior? (You can also link to an open issue here)**
There is no current behavior.

**What is the new behavior (if this is a feature change)?**
The new behavior is to show completion options for the `htop` command.

**Additional info:**
None.

2021-09-26 20:49 UTC, fedeci commented on src/htop.ts
> +      },
is this supposed to be here?

2021-09-26 20:49 UTC, fedeci approved these changes

2021-09-26 21:32 UTC, jhrcook commented on src/htop.ts
> +      },
Yes,  it is an optional delay for argument for how frequently to update the highlighting. Should I add a description to that argument to explain that?

2021-09-26 21:43 UTC, fedeci commented on src/htop.ts
> +      },
Yes please!

2021-09-27 12:47 UTC, jhrcook commented on src/htop.ts
> +      },
Done

2021-09-27 17:35 UTC, QuiiBz requested changes
Thanks a lot for this PR! Left few comments before merging it :)

2021-09-27 17:35 UTC, QuiiBz commented on src/htop.ts
> +
Extra line not needed:
```suggestion
```

2021-09-27 17:35 UTC, QuiiBz commented on src/htop.ts
> +        suggestions: ["10"],
Maybe we could add 1 and 60?

2021-09-27 17:35 UTC, QuiiBz commented on src/htop.ts
> +        description: "Delay between updates of highlights, in tenths of sec",
Could we add the same suggestions as above?

2021-09-27 17:35 UTC, QuiiBz commented on src/htop.ts
> +        isOptional: false,
You can remove `isOptional` when it's `false`. Same for other places underneath

2021-09-28 17:04 UTC, QuiiBz approved these changes
LGTM, thank you so much for this contribution 🚀

2021-09-28 17:05 UTC, merged