feat: add `ping` completion spec
withfig/autocomplete pull request #612
Opened 2021-09-27 22:25 UTC by mloew

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
New Feature: Add Ping completion spec

**What is the current behavior? (You can also link to an open issue here)**
There is no current behavior.

**What is the new behavior (if this is a feature change)?**
The new behavior is to show completion options for the `ping` command.

**Additional info:**
None.

2021-09-28 17:00 UTC, QuiiBz requested changes
Thanks a lot for this PR! Left some comments to improve further the spec

2021-09-28 17:00 UTC, QuiiBz commented on src/ping.ts
> +        "Audible.  Output a bell (ASCII 0x07) character when no packet is received before the next packet is transmitted.  To cater for round-trip times that are longer than the interval between tran
Extra space after the `.`. Looks like this issue occurs multiple times, could you fix this in the whole file?
```suggestion
        "Audible. Output a bell (ASCII 0x07) character when no packet is received before the next packet is transmitted. To cater for round-trip times that are longer than the interval between trans- missions, further missing packets cause a bell only if the maxi- mum number of unreceived packets has increased",
```

2021-09-28 17:00 UTC, QuiiBz commented on src/ping.ts
> +        name: "trafficclass",
Could we add [suggestions](https://fig.io/docs/reference/arg#suggestions) for the argument? They are listed in the description

2021-09-28 17:00 UTC, QuiiBz commented on src/ping.ts
> +        name: "netservicetype",
Same as above

2021-09-28 17:00 UTC, QuiiBz commented on src/ping.ts
> +        "You may specify up to 16 ``pad'' bytes to fill out the packet you send.  This is useful for diagnosing data-dependent problems in a network.  For example, ``-p ff'' will cause the sent packe
```suggestion
        "You may specify up to 16 'pad' bytes to fill out the packet you send.  This is useful for diagnosing data-dependent problems in a network.  For example, '-p ff' will cause the sent packet to be filled with all ones",
```

2021-11-01 17:31 UTC, QuiiBz commented
Hello @mloew, I was wondering if you're still working on this PR or should we tackle it ourselves?

2021-12-08 19:20 UTC, mschrage commented
@QuiiBz mind making these changes and getting this merged in?

2022-01-22 12:01 UTC, fedeci commented
I'm closing this one since stale :(

2022-01-22 12:01 UTC, closed without merging