feat: add `php please` spec for Statamic 3
withfig/autocomplete pull request #615
Opened 2021-09-29 04:08 UTC by martyf

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Spec addition: Statamic 3's `please` command

**What is the current behavior? (You can also link to an open issue here)**
Currently `please` is not available.

**What is the new behavior (if this is a feature change)?**
Add's Statamic 3's `please` spec based on the command list json output

**Additional info:**
This is replicating the setup of the `artisan` spec for Laravel - perfect fit as Statamic is built on top of Laravel. Full credit to the original authors of the `artisan` implementation for this - this PR operates the same way, but runs the `please` command instead. This includes:
- only adding the spec if `please` is in the current directory, 
- pulls the available options from the `php please list --format=json` command

2021-09-29 15:20 UTC, QuiiBz requested changes
Thanks for this first PR! We have only two small issues to resolve before merging this 🚀

2021-09-29 15:20 UTC, QuiiBz commented on src/php/please.ts
> +    var out = await executeShellCommand("php please list --format=json");
Could you replace this with a `const`?
```suggestion
    const out = await executeShellCommand("php please list --format=json");
```

2021-09-29 15:20 UTC, QuiiBz commented on src/php/please.ts
> +      //
We should add a `console.error(err);` in the catch, to be able to debug the spec in the future

2021-09-29 21:35 UTC, martyf commented
Thanks @QuiiBz - I've just updated the PR with these two tweaks.

2021-09-29 22:18 UTC, fedeci commented on src/php/please.ts
> +          args: Object.keys(command.definition.arguments).map((argumentKey) => {
nit: we can directly use `Object.values` to simplify this logic

2021-09-29 22:18 UTC, fedeci commented on src/php/please.ts
> +          options: Object.keys(command.definition.options).map((optionKey) => {
Same as above

2021-09-29 23:28 UTC, martyf commented
Tweaked to use `Object.values` instead of `Object.keys`

2021-09-30 06:29 UTC, fedeci approved these changes

2021-09-30 17:58 UTC, QuiiBz approved these changes
This looks amazing, thank you so much for this contribution 🎉

2021-09-30 17:58 UTC, merged