feat(`npm`): suggest global deps if global flag is specified
withfig/autocomplete pull request #619
Opened 2021-09-29 19:14 UTC by fedeci

Closes #616

2021-09-30 17:56 UTC, QuiiBz requested changes
Amazing feature! Would it be possible to port it to `yarn` and `pnpm`?

2021-09-30 17:56 UTC, QuiiBz commented on src/npm.ts
> +function uninstallSubcommand(named: string | string[]): Fig.Subcommand {
Any reason why using `named` instead of `name`?

2021-09-30 17:56 UTC, QuiiBz commented on src/npm.ts
> +    console.error(tokens);
We can remove this `console.error`

2021-09-30 18:05 UTC, fedeci commented
Do yarn and pnpm allow global commands?

2021-09-30 18:06 UTC, fedeci commented on src/npm.ts
> +    console.error(tokens);
```suggestion
```

2021-09-30 18:12 UTC, QuiiBz commented
> Do yarn and pnpm allow global commands?

They install binaries the same way as `npm` do, that would be helpful for `yarn global remove ...` & `pnpm remove --global ...`

2021-09-30 18:35 UTC, fedeci commented
pnpm seems to be already using the npm generator

2021-09-30 19:18 UTC, QuiiBz commented
> pnpm seems to be already using the npm generator. Yarn already had the feature.

Nice to hear! But it seems like `yarn` isn't working properly. We might handle this in another PR.

![Screenshot 2021-09-30 at 21 17 24](https://user-images.githubusercontent.com/43268759/135517053-15000765-0a99-446a-926b-89d0a8974e4a.png)

2021-09-30 19:38 UTC, fedeci commented
It is working for me🤔 Try to install a package e.g. express globally and see if works

2021-10-01 16:22 UTC, QuiiBz commented
Found why it's not working: the generator uses `cat`, which I aliased to [`bat`](https://github.com/sharkdp/bat), and the output isn't the same. The simplest way to fix this is to append a `\` to the command, so the shell will execute the right binary, and not the aliased one. I'm going to open a PR since this issue is happening in multiple specs.

2021-10-01 16:22 UTC, QuiiBz approved these changes
LGTM!

2021-10-01 16:23 UTC, merged