added all amplify commands to spec
withfig/autocomplete pull request #625
Opened 2021-10-01 03:33 UTC by Dayton-IX

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Full spec for amplify CLI autocomplete support

**What is the current behavior? (You can also link to an open issue here)**
Only amplify env is supported

**What is the new behavior (if this is a feature change)?**
All amplify commands are supported

**Additional info:**

2021-10-01 16:28 UTC, QuiiBz requested changes
Thanks a lot for this contribution! I left some comments to resolve before getting this PR merged in

2021-10-01 16:28 UTC, QuiiBz commented on src/amplify.ts
> +const amplifyCategories = [
Could you add a type of `Fig.Subcommand[]` here? And a description for each subcommand would be nice to have!

2021-10-01 16:28 UTC, QuiiBz commented on src/amplify.ts
> +const categoryCommands = [
Same as above for the type :)

2021-10-01 16:28 UTC, QuiiBz commented on src/amplify.ts
> +        name: "--y",
Is the name really `--y`, and not `-y` instead? That seems a bit strange to me

2021-10-01 16:28 UTC, QuiiBz commented on src/amplify.ts
> +          name: "--y",
Same as above

2021-10-02 00:38 UTC, Dayton-IX commented on src/amplify.ts
> +        name: "--y",
yeah it really is --y!

2021-10-02 16:15 UTC, QuiiBz approved these changes
LGTM, thank you so much for this contribution!

2021-10-02 16:15 UTC, merged