feat: add truffle completion spec
withfig/autocomplete pull request #627
Opened 2021-10-01 11:56 UTC by FaroukZeino

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Add auto completion for truffle.

**What is the current behavior? (You can also link to an open issue here)**
No current behavior.

**What is the new behavior (if this is a feature change)?**
Show completion options for the truffle suite.

**Additional info:**
[https://www.trufflesuite.com/docs/truffle/reference/truffle-commands](Truffle Commands)

2021-10-01 16:35 UTC, QuiiBz requested changes
Thanks for this contribution! There are some things to improve but the spec is already pretty good!

2021-10-01 16:35 UTC, QuiiBz commented on src/truffle.ts
> +            isOptional: false
You can remove this when `isOptional` is `false` - it's assumed by default! Same for other arguments underneath

2021-10-01 16:35 UTC, QuiiBz commented on src/truffle.ts
> +            description: "The default export must be an object with named keys that will be used to populate the console environment. For example, if your JavaScript is module.exports = { desert: \"y
Looks like this argument can have a [template](https://fig.io/docs/reference/arg#template) of `filepaths`

2021-10-01 16:35 UTC, QuiiBz commented on src/truffle.ts
> +        }
A simpler way to achieve this is:
```suggestion
        template: "filepaths"
```

2021-10-01 16:35 UTC, QuiiBz commented on src/truffle.ts
> +        }
Same as above

2021-10-01 16:35 UTC, QuiiBz commented on src/truffle.ts
> +          isRequired: false
Same as `isOptional`, the default value of `isRequired` is false, so you can remove this :)

2021-10-01 16:35 UTC, QuiiBz commented on src/truffle.ts
> +          name: "--",
Missing option name?

2021-10-01 16:35 UTC, QuiiBz commented on src/truffle.ts
> +          }
Same as above

2021-10-01 16:35 UTC, QuiiBz commented on src/truffle.ts
> +        }
Same as above

2021-10-01 16:51 UTC, QuiiBz commented
Could you also run the `lint:fix` script to fix the linting issues?

2021-10-01 17:14 UTC, FaroukZeino commented on src/truffle.ts
> +          name: "--",
I believe not, this was a little tricky to add, I think the option is dynamic.
[Docs](https://www.trufflesuite.com/docs/truffle/reference/truffle-commands) please check **preserve** command.

2021-10-01 17:44 UTC, FaroukZeino commented
@QuiiBz I have fixed all of the issues except for this [one](https://github.com/withfig/autocomplete/pull/627#discussion_r720388595).

2021-10-02 16:11 UTC, QuiiBz requested changes

2021-10-02 16:11 UTC, QuiiBz commented on src/truffle.ts
> +          name: "--",
I don't think this will work the way you want, because Fig will require a space between the name (`--`) and the argument (`recipe`). We should completely remove this option since there is no way to give right suggestions.

2021-10-02 16:11 UTC, QuiiBz commented on src/truffle.ts
> +const truffleCommands = [
Could you add a type of `Fig.Suggestion[]` here?

2021-10-02 16:11 UTC, QuiiBz commented on src/truffle.ts
> +          description: "--stacktrace --compile-all-debug",
Could you improve the description? Not sure what it really means 😅

2021-10-02 16:12 UTC, QuiiBz commented
> @QuiiBz I have fixed all of the issues except for this [one](https://github.com/withfig/autocomplete/pull/627#discussion_r720388595).

Thanks, I left a new review and we'll be ready to merge then!

2021-10-02 16:28 UTC, FaroukZeino commented
> > @QuiiBz I have fixed all of the issues except for this [one](https://github.com/withfig/autocomplete/pull/627#discussion_r720388595).
> 
> Thanks, I left a new review and we'll be ready to merge then!

All done ✅

2021-10-02 16:29 UTC, QuiiBz approved these changes
Thank you so much for this awesome spec! LGTM 🚀

2021-10-02 16:29 UTC, merged

2021-10-02 16:31 UTC, FaroukZeino commented
> Thank you so much for this awesome spec! LGTM 🚀

You are welcome! And thank you for making Fig.