rustup Spec
withfig/autocomplete pull request #630
Opened 2021-10-01 17:54 UTC by geenva

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
New specification for `rustup`.

**What is the current behavior? (You can also link to an open issue here)**
Work in progress - options are all done but I am now working on subcommands.

**What is the new behavior (if this is a feature change)?**
There is an additional `rustup` completion for Fig.

~~**Additional info:**~~

2021-10-01 17:55 UTC, geenva commented
Hi, sorry for abandoning my PR earlier. I will now continue to work on it.

2021-10-03 16:53 UTC, geenva commented
Ready to review! Thanks.

2021-10-04 12:47 UTC, Milo123459 approved these changes
I don't see any problems. LGTM

2021-10-04 18:14 UTC, grant0417 requested changes
Looks good to me, only issue is the template comments.

2021-10-04 18:14 UTC, grant0417 commented on src/rustup.ts
> +// The below is a dummy example for git. Make sure to change the file name!
Remove these comments or add more specific ones for rustup

2021-10-04 18:16 UTC, grant0417 approved these changes

2021-10-04 18:20 UTC, QuiiBz requested changes
Hi, thanks for creating this PR!

2021-10-04 18:20 UTC, QuiiBz commented on src/rustup.ts
> +      // If you want to build custom suggestions for arguments check out: https://fig.io/docs/concepts/dynamic-suggestions
Is this comment still needed?

2021-10-04 18:20 UTC, QuiiBz commented on src/rustup.ts
> +
Extra line

2021-10-04 18:20 UTC, QuiiBz commented on src/rustup.ts
> +          description: "Add a target to a Rust toolchain",
Doesn’t this sub command have an argument, which is the target to add to the rust tool chain?

2021-10-04 18:20 UTC, QuiiBz commented on src/rustup.ts
> +          description: "Remove a target from a Rust toolchain",
Same as above

2021-10-04 18:20 UTC, QuiiBz commented on src/rustup.ts
> +          description: "Install or update a given toolchain",
Same as above, looks like this issue is repeating a few times underneath

2021-10-04 18:20 UTC, QuiiBz commented on src/rustup.ts
> +          isVariadic: true,
Should we add the `isCommand` flag? See https://fig.io/docs/reference/arg#iscommand

2021-10-04 18:20 UTC, QuiiBz commented on src/rustup.ts
> +          description: "Only print the path tp the documentation",
Typo:
```suggestion
          description: "Only print the path to the documentation",
```

2021-10-04 18:20 UTC, QuiiBz commented on src/rustup.ts
> +          "Topic such as 'core', 'fn', 'usize', 'eprintln!', 'core::arch', 'alloc::format!', 'std::fs', 'std::fs::read_dir', 'std::io::Bytes', 'std::iter::Sum', 'std::io::error::Result' etc",
Could you add these suggestions to the [suggestions](https://fig.io/docs/reference/arg#suggestions) property?

2021-10-04 18:23 UTC, grant0417 commented on src/rustup.ts
> +          "Topic such as 'core', 'fn', 'usize', 'eprintln!', 'core::arch', 'alloc::format!', 'std::fs', 'std::fs::read_dir', 'std::io::Bytes', 'std::iter::Sum', 'std::io::error::Result' etc",
This could be any topic in the lang, i don't know if these would be good as suggestions. A generator would probably be needed.

2021-10-04 18:32 UTC, QuiiBz commented on src/rustup.ts
> +          "Topic such as 'core', 'fn', 'usize', 'eprintln!', 'core::arch', 'alloc::format!', 'std::fs', 'std::fs::read_dir', 'std::io::Bytes', 'std::iter::Sum', 'std::io::error::Result' etc",
Thanks for the clarification, would it be possible to get a list of them with a shell command, so we could make a generator? If not, that’s 100% fine to leave it like this!

2021-10-04 19:03 UTC, grant0417 commented on src/rustup.ts
> +          "Topic such as 'core', 'fn', 'usize', 'eprintln!', 'core::arch', 'alloc::format!', 'std::fs', 'std::fs::read_dir', 'std::io::Bytes', 'std::iter::Sum', 'std::io::error::Result' etc",
Here is a oneliner to grab all the pages in std.
`find $(rustup docs --path | sed -e "s|index\.html|std|") | grep "\.html" | sed -E -e "s|^(.*)/html/std|std|" -e "s|\.html||" -e "s|/|::|g" -e "s/constant\.|trait\.|struct\.|macro\.|fn\.|keyword\.|primitive\.|type\.|enum\.|union\.|::index//" | grep std`

2021-10-04 20:26 UTC, geenva commented
Think everything is alright now?

2021-10-04 20:28 UTC, geenva commented on src/rustup.ts
> +          "Topic such as 'core', 'fn', 'usize', 'eprintln!', 'core::arch', 'alloc::format!', 'std::fs', 'std::fs::read_dir', 'std::io::Bytes', 'std::iter::Sum', 'std::io::error::Result' etc",
> Here is a oneliner to grab all the pages in std. `find $(rustup docs --path | sed -e "s|index.html|std|") | grep "\.html" | sed -E -e "s|^(.*)/html/std|std|" -e "s|\.html||" -e "s|/|::|g" -e "s/constant\.|trait\.|struct\.|macro\.|fn\.|keyword\.|primitive\.|type\.|enum\.|union\.|::index//"`

Thanks so much for this, helped me a lot!

2021-10-04 21:00 UTC, grant0417 requested changes

2021-10-04 21:00 UTC, grant0417 commented on src/rustup.ts
> +        suggestions: [
You can actually generate those all at run time which will always be up to date using a generator

```suggestion
        generators: {
          script: `find $(rustup docs --path | sed -e "s|index\\.html|std|") $(rustup docs --path | sed -e "s|index\.html|alloc|") $(rustup docs --path | sed -e "s|index\\.html|core|") | grep "\\.html" | sed -E -e "s|^(.*)/html/||" -e "s|\\.html||" -e "s|/|::|g" -e "s/constant\\.|trait\\.|struct\\.|macro\\.|fn\\.|keyword\\.|primitive\\.|type\\.|enum\\.|union\\.|traitalias\\.|::index$//"`,
          splitOn: "\n"
        },
```

2021-10-05 06:42 UTC, geenva commented on src/rustup.ts
> +        suggestions: [
Whoa, didn’t know that. Thanks!

2021-10-05 06:43 UTC, geenva commented
Thanks for checking this PR so thoroughly!

2021-10-05 15:58 UTC, grant0417 commented
Almost there, you just forgot to remove all of the suggestion lines.

2021-10-05 17:14 UTC, geenva commented
> Almost there, you just forgot to remove all of the suggestion lines.

Of course, sorry about that. Fixed.

2021-10-05 17:15 UTC, grant0417 approved these changes
Awesome job!

2021-10-05 18:38 UTC, mschrage commented
Let's get this merged in! ✨

2021-10-05 18:39 UTC, geenva commented
Uh oh, I will lint it on my end and recommit.

2021-10-05 18:53 UTC, mschrage approved these changes
🤩

2021-10-05 18:53 UTC, merged