feat: add remotion autocompletion to fig
withfig/autocomplete pull request #633
Opened 2021-10-02 10:21 UTC by MatteoGauthier

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

This PR add [remotion](https://remotion.dev) autocompletion

- [x] I’ve reduced the length of arguments label from "entry-file" to "entry" in order to fit in fig popup
- [x] `npx remotion render`
- [x] `npx remotion still`
- [x] `npx remotion preview`
- [ ] `npx remotion lambda`

2021-10-02 10:28 UTC, fedeci commented on src/npx.ts
> +  },
Should we add it to `yarn` spec too?

2021-10-02 13:39 UTC, MatteoGauthier commented on src/npx.ts
> +  },
yes maybe, what's the command i tried `yarn exec` and `yarn x` can't find a similar way to execute binary in yarn (like npx)

2021-10-02 13:58 UTC, fedeci commented on src/npx.ts
> +  },
Just add it here https://github.com/withfig/autocomplete/blob/5d285e0e9e971a36dc6ba9c1c40162c672e973b2/src/yarn.ts#L9

2021-10-02 14:05 UTC, MatteoGauthier commented on src/npx.ts
> +  },
Okay thanks, but how to use it in the terminal ?

2021-10-02 14:38 UTC, fedeci commented on src/npx.ts
> +  },
You need to be in a repo that has the cli tool installed and then run "yarn cmd"

2021-10-02 16:25 UTC, QuiiBz commented
Hi, thanks for contributing! I converted this PR to draft since `npx remotion lambda` is waiting to be done, feel free to mark it "Ready for review" when it's done!

2021-10-02 18:09 UTC, MatteoGauthier commented
> Hi, thanks for contributing! I converted this PR to draft since `npx remotion lambda` is waiting to be done, feel free to mark it "Ready for review" when it's done!

Okay thanks you !

2021-10-02 18:10 UTC, MatteoGauthier commented on src/npx.ts
> +  },
Ok I will add that thanks

2021-10-04 07:16 UTC, MatteoGauthier commented
I've removed `npx remotion lambda` to the checklist `remotion` creator didn't want this feature implemented for now.

2021-10-04 18:29 UTC, QuiiBz requested changes
Love remotion, thanks for submitting a spec for it!

2021-10-04 18:29 UTC, QuiiBz commented on src/remotion.ts
> +          isOptional: false,
You can remove `isOptional` when the value is `false` - it’s the default one

2021-10-04 18:29 UTC, QuiiBz commented on src/remotion.ts
> +            template: ["filepaths"],
Shouldn’t this argument have `suggestions` instead of this `template`?

2021-10-04 18:29 UTC, QuiiBz commented on src/remotion.ts
> +            default: "80",
I think it would be useful to have suggestions for 0, 10, 20… 80, 90, 100

2021-10-04 18:29 UTC, QuiiBz commented on src/remotion.ts
> +          description: "Render a portion or a still of a video, 0-9, 50",
Does this option have an argument?

2021-10-04 18:29 UTC, QuiiBz commented on src/remotion.ts
> +          description: "Custom port to use for the HTTP server",
Same as above

2021-10-04 18:29 UTC, QuiiBz commented on src/remotion.ts
> +        { name: "--frame", description: "Which frame to render (default 0)" },
Same as above

2021-10-04 18:29 UTC, QuiiBz commented on src/remotion.ts
> +            template: ["filepaths"],
Wrong argument?

2021-10-04 21:12 UTC, MatteoGauthier commented
> Love remotion, thanks for submitting a spec for it!

Thanks for your proposals, loved to work on this !

2021-10-05 18:43 UTC, QuiiBz approved these changes
LGTM, thanks a lot for this contribution 🎉

2021-10-05 18:46 UTC, merged

2021-10-06 09:29 UTC, JonnyBurger commented
Thank you @MatteoGauthier and @QuiiBz! 🥳 Already in the Terminal, so cool!