feat: Add TSDoc for specs
withfig/autocomplete pull request #67
Opened 2021-03-20 10:25 UTC by QuiiBz

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature/Docs

**What is the current behavior? (You can also link to an open issue here)**
We don't get any documentation about the specs args.

**What is the new behavior (if this is a feature change)?**
This PR adds the [documentation](https://withfig.com/docs/autocomplete/api) to each args of each object.

**Additional info:**
Example in WebStorm:
![Screenshot 2021-03-20 at 11 22 56](https://user-images.githubusercontent.com/43268759/111866560-a6a26300-896e-11eb-9fc3-c43cbf7a5a35.png)

And VS Code:
![Screenshot 2021-03-20 at 11 24 32](https://user-images.githubusercontent.com/43268759/111866594-dcdfe280-896e-11eb-898a-e025eb494718.png)

2021-03-20 16:17 UTC, cstrnt requested changes

2021-03-20 16:17 UTC, cstrnt commented on schemas/fig.d.ts
> +         * then return an array of Suggestion objects that will be rendered by Fig.
```suggestion
         * then returns an array of Suggestion objects that will be rendered by Fig.
```

2021-03-20 16:44 UTC, QuiiBz commented on dev/chmod.ts
> +                    type: "subcommand",
You're right, let's fix that.

2021-03-26 08:28 UTC, cstrnt approved these changes

2021-03-26 08:28 UTC, merged