feat: add Redwood cli completion spec
withfig/autocomplete pull request #699
Opened 2021-10-30 21:55 UTC by simoncrypta

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature: add autocompletion for `Redwood`.
Feature: add `create-redwood-app`.

**What is the current behavior? (You can also link to an open issue here)**
No autocompletion for `Redwood`.

**What is the new behavior (if this is a feature change)?**
Add autocompletion for `Redwood`.

**Additional info:**
Reference : [RedwoodJS CLI Doc ](https://redwoodjs.com/docs/cli-commands)

2021-10-31 18:15 UTC, QuiiBz requested changes
Thanks a lot for this contribution! I left some comments to resolve before merging this

2021-10-31 18:15 UTC, QuiiBz commented on src/redwood.ts
> +const prismaCommands = (prismaSpec as Fig.Subcommand).subcommands;
Is this type casting mandatory?

2021-10-31 18:15 UTC, QuiiBz commented on src/redwood.ts
> +            isOptional: false,
You can remove every occurrences of `isOptional ` when it's `false` - it's the default value (see the [docs](https://fig.io/docs/reference/arg#isoptional))

2021-10-31 18:15 UTC, QuiiBz commented on src/redwood.ts
> +          description: "Destroy a  page and route component",
```suggestion
          description: "Destroy a page and route component",
```

2021-10-31 18:15 UTC, QuiiBz commented on src/redwood.ts
> +              description: "Overwrite existing filess",
I think we should add [`isDangerous`](https://fig.io/docs/reference/option#isdangerous) here

2021-10-31 18:15 UTC, QuiiBz commented on src/redwood.ts
> +              description: "Overwrite existing filess",
Same as above, it seems like is repeating a few times

2021-10-31 18:15 UTC, QuiiBz commented on src/redwood.ts
> +            'Choices are "canary", "rc", or a specific version (e.g. "0.19.3"). WARNING: Unstable releases in the case of "canary" and "rc", which will force upgrade packages to the most recent relea
Could we add [`suggestions`](https://fig.io/docs/reference/arg#suggestions)? And I think that this option takes an argument

2021-10-31 18:15 UTC, QuiiBz commented on src/redwood.ts
> +        },
I think these three options should have arguments, and the last one can have a [`template`](https://fig.io/docs/reference/arg#template) of `folders`

2021-10-31 18:15 UTC, QuiiBz commented on src/redwood.ts
> +        ],
In those cases where each suggestion only have a name, we can simply use an array of string:
```suggestion
        suggestions: [
           "api",
          "web",
        ],
```

2021-10-31 18:15 UTC, QuiiBz commented on src/redwood.ts
> +          description: "Which port to run Storybook on (defaults to 7910)",
I think this option also takes an argument

2021-10-31 18:15 UTC, QuiiBz commented on src/redwood.ts
> +              },
Ditto

2021-10-31 18:15 UTC, QuiiBz commented on src/redwood.ts
> +              },
Ditto

2021-10-31 18:15 UTC, QuiiBz commented on src/redwood.ts
> +                  },
Ditto (the last one :))

2021-10-31 18:15 UTC, QuiiBz commented on src/yarn.ts
> +      );
Not sure if this is the best approach, I would prefer something simplier:
```suggestion
      .map((name) => ({
        name: name === "@redwoodjs/core" ? ["redwood", "rw"] : name,
        loadSpec: name,
        icon: "fig://icon?type=package",
      }));
```

2021-10-31 19:00 UTC, simoncrypta commented on src/yarn.ts
> +      );
Agree that is way cleaner, but since it also needs for `loadSpec`, I don't know if is better to repeat the ternary operator or keep it like that ? I let you decide !

2021-10-31 19:03 UTC, simoncrypta commented on src/redwood.ts
> +const prismaCommands = (prismaSpec as Fig.Subcommand).subcommands;
I don't know, I take the blitz spec as reference for that, since we have the same beaver for Prisma.
https://github.com/withfig/autocomplete/blob/e448d42855f362b65ea9f38adf7964d6dd3e7c01/src/blitz.ts#L3

2021-10-31 19:22 UTC, simoncrypta commented
Thank you, @QuiiBz, for this complete review ! I left comments for 2 conversations, let me know what you think. Also, I don't really understand what you mean when you say "Ditto", sorry I'm not a native English speaker.

2021-10-31 20:11 UTC, simoncrypta commented
Oh I understand now! I didn't see some of the reviews. I will fix this

2021-11-01 17:16 UTC, QuiiBz commented on src/redwood.ts
> +const prismaCommands = (prismaSpec as Fig.Subcommand).subcommands;
Could you try to remove the type casting and see if typescript doesn't complain? IMO that would be a lot cleaner is that works!

2021-11-01 17:18 UTC, QuiiBz commented on src/yarn.ts
> +      );
I think using a ternary operation is both smaller and easier to read, so we can go with this!

2021-11-01 17:20 UTC, QuiiBz commented
> I left comments for 2 conversations, let me know what you think.

Just replied to them, will merge this amazing PR when those two small changes are done!

2021-11-01 17:26 UTC, simoncrypta commented on src/redwood.ts
> +const prismaCommands = (prismaSpec as Fig.Subcommand).subcommands;
Typescript need to know that `prismaSpec`is a `Fig.Subcommand`, but I don't think we should have a `const` for that.

2021-11-01 17:35 UTC, simoncrypta commented
> Just replied to them, will merge this amazing PR when those two small changes are done!

Done 👍 Thank you again for this review, I appreciate the effort you put on it 😊

2021-11-01 17:39 UTC, QuiiBz reviewed
LGTM, thank you so much for this contribution 🎉  And thanks for those kind words!

2021-11-01 17:40 UTC, QuiiBz approved these changes

2021-11-01 17:40 UTC, merged