fix(vercel): Added completion for vercel's alias, link, billing
withfig/autocomplete pull request #701
Opened 2021-10-31 20:49 UTC by alexnaiman

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Added completion for for vercel's alias, link, billing
**What is the current behavior? (You can also link to an open issue here)**
Missing completion specs for alias, link, billing. See #694 
**What is the new behavior (if this is a feature change)?**
Completion for vercel's alias, link, billing
**Additional info:**
none

2021-11-01 17:23 UTC, QuiiBz requested changes
Thanks a lot for this PR! There's only one issue that needs to be fixed at few places

2021-11-01 17:23 UTC, QuiiBz commented on src/vercel.ts
> +              name: "deployment url",
The name of the argument should be one word if possible, and then you can add a `description` to explain a bit more about it. Can you change this for each argument underneath?

As example:
```suggestion
              name: "url",
              description: "The URL of the deployment to assign to a domain",
```

2021-11-01 18:40 UTC, mschrage commented on src/vercel.ts
> +              name: "deployment url",
I wonder if we can set up a linter for this? cc @fedeci

2021-11-02 07:51 UTC, QuiiBz commented on src/vercel.ts
> +              name: "deployment url",
That would be a good idea!

2021-11-06 08:11 UTC, QuiiBz approved these changes
LGTM, thanks a lot for this contribution!

2021-11-06 08:11 UTC, merged