[feat] dog spec
withfig/autocomplete pull request #705
Opened 2021-11-03 10:18 UTC by gusfune

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

This adds specs for `dog` as requested on issue #702

2021-11-06 08:25 UTC, QuiiBz requested changes

2021-11-06 08:25 UTC, QuiiBz commented on src/dog.ts
> +    insertValue: "{HOST}",
Not sure what you wanted to achieve with `insertValue` here?

2021-11-06 08:25 UTC, QuiiBz commented on src/dog.ts
> +  args: {},
You can safely remove this if `dog` doesn't take any argument at the root-level

2021-11-06 09:05 UTC, gusfune commented on src/dog.ts
> +  args: {},
Dog can take arguments or no arguments at root-level. That's why I left this option. Shall I remove it?

2021-11-06 19:20 UTC, QuiiBz commented on src/dog.ts
> +  args: {},
In this case, you should add information to each possible argument, such as the name, description, if it's variadic or not etc

2021-11-12 17:24 UTC, QuiiBz commented on src/dog.ts
> +  args: {},
Still waiting for this, and then we'll be ready to merge!

2021-11-14 07:22 UTC, gusfune commented on src/dog.ts
> +  args: {},
Sorry for the delay.
Working this out in a commit soon.

2021-11-14 15:56 UTC, QuiiBz approved these changes
Thanks for fixing the issues! LGTM 🚀

2021-11-14 15:56 UTC, merged