doppler spec
withfig/autocomplete pull request #711
Opened 2021-11-06 10:13 UTC by gusfune

This adds specs for `doppler` as requested on issue #704

2021-11-06 19:26 UTC, QuiiBz requested changes
Thanks for this PR, Doppler is such a great tool! Left some messages to resolve before merging

2021-11-06 19:26 UTC, QuiiBz commented on src/doppler.ts
> +};
Can these arguments have a [`template`](https://fig.io/docs/reference/arg#template) of `filepaths`?

2021-11-06 19:26 UTC, QuiiBz commented on src/doppler.ts
> +  args: { name: "string" },
Would love the see some [`suggestions`](https://fig.io/docs/reference/arg#suggestions) for this argument! (json, env, yaml...)

2021-11-06 19:26 UTC, QuiiBz commented on src/doppler.ts
> +    args: { name: "string", template: "filepaths" },
Should this argument have a `template` of `filepaths`? I'm not sure by looking at the description

2021-11-06 19:26 UTC, QuiiBz commented on src/doppler.ts
> +          args: { name: "string" },
Can this argument have the [`isCommand`](https://fig.io/docs/reference/arg#iscommand) property?

2021-11-07 11:18 UTC, gusfune commented
> Thanks for this PR, Doppler is such a great tool! Left some messages to resolve before merging

Thanks a lot! I just made the adjustments.

2021-11-07 18:46 UTC, QuiiBz approved these changes
Thanks for making the changes, and thanks for the contribution! LGTM 🎉

2021-11-07 18:46 UTC, merged