feat: add jupyter completion spec
withfig/autocomplete pull request #714
Opened 2021-11-08 22:42 UTC by TanayB11

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature: Add completion spec for Jupyter

2021-11-09 17:38 UTC, QuiiBz requested changes
Thanks a lot for this contribution!

2021-11-09 17:38 UTC, QuiiBz commented on src/jupyter.ts
> +    args: {},
Could you fill this argument with at least a `name`?

2021-11-09 17:38 UTC, QuiiBz commented on src/jupyter.ts
> +    args: {},
Same as above, and I think it can have a [`template`](https://fig.io/docs/reference/arg#template) of `filepaths`

2021-11-09 17:38 UTC, QuiiBz commented on src/jupyter.ts
> +          description: "Apply the operation only for the given user",
Does this option take an argument?

2021-11-09 17:38 UTC, QuiiBz commented on src/jupyter.ts
> +          args: {},
Please add at least a `name` for each argument, it's repeating a few times underneath

2021-11-09 17:38 UTC, QuiiBz commented on src/jupyter.ts
> +      description: "",
Would love to see a `description` for this suncommand! Same for `serverextension` and `trust`

2021-11-12 17:22 UTC, QuiiBz commented
Hi @TanayB11, just pinging you to know if you still want to resolve the code review, or if we should handle it ourselves. Thanks!

2021-11-17 01:04 UTC, TanayB11 commented
> Hi @TanayB11, just pinging you to know if you still want to resolve the code review, or if we should handle it ourselves. Thanks!

Hi, I don't have the bandwidth to resolve at this moment. If you'd like it done faster, it's okay if you handle it.

2021-11-18 21:29 UTC, mschrage commented
No worries - thanks for getting the ball rolling with for `jupyter` spec! This is definitely one that lots of people will appreciate :)

@QuiiBz can you make the necessary changes when you have a chance?

2021-11-19 18:16 UTC, QuiiBz commented
Done! Would love a review @fedeci before merging this

2021-11-20 16:34 UTC, fedeci commented
Sure @QuiiBz

2021-11-20 16:36 UTC, fedeci approved these changes

2021-11-20 16:44 UTC, QuiiBz approved these changes
Thanks for the initial contribution @TanayB11!

2021-11-20 16:44 UTC, merged