feat(deno): update spec to 1.16
withfig/autocomplete pull request #715
Opened 2021-11-09 14:16 UTC by SeparateRecords

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Spec update

**What is the current behavior? (You can also link to an open issue here)**
Not up to date.

**What is the new behavior (if this is a feature change)?**
Updates Deno spec to 1.15 & 1.16. This modernises the spec a bit (sets `requiresEquals` where appropriate) and, because requiresEquals optional arguments are supported now, adds an environment variable generator for `--allow-env`.

**Additional info:**
Deno 1.16 technically isn't out yet, but will be in less than 24 hours. It doesn't actually introduce anything in the CLI, all the new stuff was in 1.15.
(Still saying it's updated to 1.16 so future-me doesn't get confused when updating to 1.17)

Also, I've been gone for a while for a bunch of _really_ stupid reasons that I've resolved now, all to do with my flaky setup. Hopefully I'll be back to being active in this community :)

2021-11-09 14:24 UTC, SeparateRecords commented
Hah! 1.16 was released _while I was writing the PR description_.

<img width="236" alt="image" src="https://user-images.githubusercontent.com/52195359/140941518-8bcf5bac-1b29-4fb6-b8b3-b3f972fddfc8.png">

2021-11-09 14:34 UTC, SeparateRecords commented
Reverting to draft - didn't realise that Fig spawns a new shell so `env` won't show the user's variables. Will fix tomorrow

2021-11-10 20:22 UTC, QuiiBz requested changes
Thanks for this contribution!

2021-11-10 20:22 UTC, QuiiBz commented on src/deno.ts
>  // TODO: When fig supports this option (or something like it), uncomment the arguments.
Can we remove this TODO comment?

2021-11-10 20:22 UTC, QuiiBz commented on src/deno.ts
> -            console.error("Returning early due to error:", err);
That can still be useful if anything goes wrong, to make debugging easier

2021-11-11 06:50 UTC, SeparateRecords commented on src/deno.ts
>  // TODO: When fig supports this option (or something like it), uncomment the arguments.
Thanks for noticing that. I removed that suggestion from the find&replace results and totally forgot to remove it 😆

2021-11-12 17:18 UTC, QuiiBz approved these changes
LGTM, thanks for keeping this spec up to date!

2021-11-12 17:18 UTC, merged