feat: add stack completion spec
withfig/autocomplete pull request #726
Opened 2021-11-16 08:06 UTC by nitinprakash96

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature: Adds Haskell stack completion spec

**What is the current behavior? (You can also link to an open issue here)**
Completely new feature. Here's a screenshot:
<img width="621" alt="CleanShot 2021-11-16 at 13 29 32@2x" src="https://user-images.githubusercontent.com/15181803/141944446-0f027080-a9ee-4f82-a9cb-d6945ca5df26.png">

**What is the new behavior (if this is a feature change)?**
Not a feature change. But an addition.

**Additional info:**

I tend to use fig a lot and thought it would be nice to have Haskell (my goto language at the moment) tools present as well. Currently I've only started with `stack` but there's also another build tool `cabal` which is pretty popular (and then ofc there's the `ghc` compiler itself which might be useful). I'll probably add those as well once this PR gets an approval. 
This is not the complete completion spec, yet. I'm in the process of adding more but might be a little slow (sorry!). Therefore, keeping it as a draft. Hope that works.

2021-12-08 19:21 UTC, mschrage commented
Hey @nitinprakash96! Just wanted to check in here. We'd love to provide better support for the Haskell ecosystem. Is there anything we can do to help with this spec?

2021-12-09 14:37 UTC, nitinprakash96 commented
@mschrage Very sorry for delaying this. Been busy lately. I have just a bit more to finish. Will do so by this weekend. Hope thats okay.

2021-12-09 22:04 UTC, mschrage commented
No rush! I just wanted to see if you were stuck on something we could help with. Thanks again for contributing ❤️

2021-12-19 14:16 UTC, fedeci requested changes

2021-12-19 14:16 UTC, fedeci commented on src/stack.ts
> +          "WHEN is 'always', 'never', or 'auto'. On Windows versions before Windows 10, for terminals that do not support color codes, the default is 'never'; color may work on terminals that support
```suggestion
        name: "WHEN",
        suggestions: ["always", "never", "auto"],
        default: "never",
        description:
          "WHEN is 'always', 'never', or 'auto'. On Windows versions before Windows 10, for terminals that do not support color codes, the default is 'never'; color may work on terminals that support color codes",
```

2021-12-19 14:16 UTC, fedeci commented on src/stack.ts
> +      description: "Verbosity: silent, error, warn, info, debug",
Is this used to set the verbosity level or to get it?

2021-12-19 14:16 UTC, fedeci commented on src/stack.ts
> +        { name: "--no-open", description: "Disable opening the local Haddock" },
Most of the options, for examples these ones, seem to be exclusive on the opposite.
e.g.
`--haddock` is [exclusiveOn](https://fig.io/docs/reference/option#exclusiveon) `--no-haddock` and vice versa.

2023-09-28 23:13 UTC, brendanfalk approved these changes

2023-09-28 23:14 UTC, brendanfalk commented
@nitinprakash96 Could you please sign the CLA so we can get this merged?

2023-09-30 05:21 UTC, nitinprakash96 commented
I have read the CLA Document and I hereby sign the CLA

2023-10-12 19:05 UTC, mschrage approved these changes

2023-10-12 19:06 UTC, merged