Support for elm cli
withfig/autocomplete pull request #730
Opened 2021-11-17 02:24 UTC by wolfadex

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature: Support for [Elm](https://elm-lang.org/)'s cli

**What is the new behavior (if this is a feature change)?**
Support all of the `elm` cli commands:
- `elm repl`
- `elm init`
- `elm reactor`
- `elm make`
- `elm install`
- `elm bump`
- `elm diff`
- `elm publish`

Includes suggestions for the packages that can be installed as well.

**Additional info:**
Recording of the install suggestions:
https://user-images.githubusercontent.com/1542461/142098308-65a6b161-d8de-4de3-b187-8499d7ac9c49.mp4

2021-11-18 21:25 UTC, mschrage approved these changes
This looks good to me! Thanks so much for your contribution :)

2021-11-19 17:53 UTC, QuiiBz requested changes
Thank you so much for this contribution! There's only one small change before merging this PR

2021-11-19 17:53 UTC, QuiiBz commented on src/elm.ts
> +            isOptional: false,
You can remove `isOptional` when the value is `false`, it's the default one!

2021-11-19 17:53 UTC, QuiiBz commented on src/elm.ts
> +            isOptional: false,
Same as above, looks like it's repeating a few times, could you fix all of them?

2021-11-19 17:58 UTC, wolfadex commented on src/elm.ts
> +            isOptional: false,
Can do, and done!

2021-11-19 18:29 UTC, QuiiBz approved these changes
LGTM, thanks a lot for this contribution 🚀

2021-11-19 18:29 UTC, merged