feat: ansible + ansible-playbook completion specs
withfig/autocomplete pull request #733
Opened 2021-11-18 04:17 UTC by zp4rker

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adds `ansible` and `ansible-playbook` completion specs. Implements https://github.com/withfig/autocomplete/issues/621

**What is the current behavior? (You can also link to an open issue here)**
Not present.

**What is the new behavior (if this is a feature change)?**
Implements them.

**Additional info:**
This is only 2 out of 12+ different ansible commands (all separate binaries), these are by far the most used commands out of the lot. I may implement more in the future but don't have a need for it at the moment (aka laziness). May possibly also add generators for enhancement in the future such as giving host pattern suggestions based on inventory but not right now (again due to laziness).

2021-11-19 17:46 UTC, QuiiBz requested changes
Thanks a lot for this contribution!

2021-11-19 17:46 UTC, QuiiBz commented on src/ansible-playbook.ts
> +    isOptional: false,
You can remove `isOptional` when the value is `false`, it's the default value!

2021-11-19 17:46 UTC, QuiiBz commented on src/ansible-playbook.ts
> +        name: "vault password file",
I think this argument can have a [template](https://fig.io/docs/reference/arg#template) of `filepaths`

2021-11-19 17:46 UTC, QuiiBz commented on src/ansible-playbook.ts
> +        name: "connection type",
Could we provide [suggestions](https://fig.io/docs/reference/arg#suggestions) for this argument?

2021-11-19 17:46 UTC, QuiiBz commented on src/ansible.ts
> +    isOptional: false,
Same as above, you can remove this

2021-11-19 17:46 UTC, QuiiBz commented on src/ansible.ts
> +        name: "playbook dir",
Same as above for the template, but a template of `folders`

2021-11-19 17:46 UTC, QuiiBz commented on src/ansible.ts
> +        name: "vault password file",
Same as above for the template of `filepaths`

2021-11-21 03:03 UTC, zp4rker commented on src/ansible-playbook.ts
> +        name: "connection type",
It's not as simple as a static list of suggestions for this one, it's based on what connection plugins are installed. Could possibly be implemented in the future using generators.

2021-11-22 18:18 UTC, QuiiBz approved these changes
LGTM, thanks a lot for these amazing specs!

2021-11-22 18:18 UTC, merged