feat: add scc spec
withfig/autocomplete pull request #734
Opened 2021-11-18 08:08 UTC by SeparateRecords

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adds a spec for scc (https://github.com/boyter/scc)

There's one generator in there, the other generators will require more work so if I do implement them it'll definitely be a separate PR.

2021-11-19 17:50 UTC, QuiiBz requested changes
Thanks for this contribution, love the types and comments, that really helps!

2021-11-19 17:50 UTC, QuiiBz commented on src/scc.ts
> +      //       (trigger on ':', remove on ',')
Can you tackle this TODO?

2021-11-19 17:50 UTC, QuiiBz commented on src/scc.ts
> +      // suggest formats immediately, then files on `:`, then reset to formats on `,`
Same as above

2021-11-20 02:17 UTC, SeparateRecords commented on src/scc.ts
> +      //       (trigger on ':', remove on ',')
As in to have these generators done for this PR? As I said in the PR message I think it would be better to add these complicated generators in a follow up PR.
For this particular option, the syntax scc expects is `ext:Name,ext2:"Spaced Name"` so there's a fair amount of logic that would have to go into that generator (and I just don't have the time to implement that right now, but will next week)

2021-11-20 14:14 UTC, SeparateRecords commented on src/scc.ts
> +      //       (trigger on ':', remove on ',')
Was just about to sleep and figured I should clarify, I'm happy to leave this PR open until I have time if you'd prefer that!

2021-11-20 16:43 UTC, QuiiBz commented on src/scc.ts
> +      //       (trigger on ':', remove on ',')
Thanks for the clarification, I think we can merge this PR - and the generators can be done in a new one as you said!

2021-11-20 16:43 UTC, QuiiBz approved these changes
LGTM, looking for the generators PR :)

2021-11-20 16:43 UTC, merged