feat: add create-react-app completion spec
withfig/autocomplete pull request #736
Opened 2021-11-19 00:33 UTC by symsmith

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature: Add `create-react-app` completion spec

2021-11-19 18:21 UTC, QuiiBz requested changes
Thanks a lot for this contribution! Only one small change and we'll be ready to merge!

2021-11-19 18:21 UTC, QuiiBz commented on src/create-react-app.ts
> +        isOptional: false,
You can remove `isOptional` when it's `false` - it's the default value!

2021-11-19 18:22 UTC, QuiiBz commented
And there's also the lint script which is failing - could you run the `lint:fix` script?

2021-11-19 19:34 UTC, symsmith commented
It looks like the linter is failing on `dangerfile-greeting.ts`, which I haven't edited.

Log:
```
/home/runner/work/autocomplete/autocomplete/dangerfile-greeting.ts
  26:69  error  Parsing error: ',' expected
```

2021-11-19 19:43 UTC, symsmith commented
The problem comes from unescaped backticks, I can commit the fix if you want.

2021-11-20 16:37 UTC, QuiiBz commented
> The problem comes from unescaped backticks, I can commit the fix if you want.

I pushed a fix yesterday to `master`, so you can simply rebase/merge!

2021-11-20 17:04 UTC, symsmith commented
Thanks, should be all good now!

2021-11-22 18:08 UTC, QuiiBz approved these changes
LGTM, thank you so much for this contribution!

2021-11-22 18:08 UTC, merged