feat(scc): add generators
withfig/autocomplete pull request #742
Opened 2021-11-21 10:21 UTC by SeparateRecords

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adds generators to the `scc` spec.
This PR also improves assorted descriptions and sets the 'files or directories' argument to optional.

**What is the current behavior? (You can also link to an open issue here)**
The following options needed generators for contextual suggestions. They all take a comma-separated `key:value` list.
- --count-as (`extension:Language`)
- --format-multi (`format:output`)
- --remap-all (`anystring:Language`)
- --remap-unknown (`anystring:Language`)

**What is the new behavior (if this is a feature change)?**
The options above now have generators.

**Additional info:**
Didn't expect to have time for this so soon! Glad to have it started 😎

2021-11-21 10:37 UTC, SeparateRecords commented
Just caught a mistake, will get some help on Discord and push a fix later.

2021-11-21 14:29 UTC, SeparateRecords reviewed
I'll deal with this tomorrow. Out for the night!

2021-11-21 14:29 UTC, SeparateRecords commented on src/scc.ts
> +  // If we're writing a file extension, suggest known extensions
This comment is irrelevant and should be deleted.

2021-11-21 14:29 UTC, SeparateRecords commented on src/scc.ts
> +const remapGenerator: Fig.Generator = {
Rename to `generateRemap` (maybe)

2021-11-21 14:29 UTC, SeparateRecords commented on src/scc.ts
> +const formats = [
Needs a better name, like `outputFormatSuggestions`

2021-11-22 18:30 UTC, QuiiBz requested changes
Again, the comments really help so thanks for that!

2021-11-22 18:30 UTC, QuiiBz commented on src/scc.ts
> +              }));
Not sure about the wording of `ext` and `name`, shouldn't it be `name` and `description`?

2021-11-23 00:58 UTC, SeparateRecords commented on src/scc.ts
> +              }));
I'm using "name" to refer to the language name (since `files` is a map of file extension => language name).  I think avoiding the word "name" entirely would be much clearer (probably will go with "lang")

2021-11-24 19:10 UTC, QuiiBz approved these changes
LGTM, thank you so much for this amazing contribution!

2021-11-24 19:10 UTC, merged