feat: add mvn (Maven) completion spec
withfig/autocomplete pull request #746
Opened 2021-11-23 01:45 UTC by zp4rker

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
New completion spec

**What is the current behavior? (You can also link to an open issue here)**
Non-existent

**What is the new behavior (if this is a feature change)?**
Existent

**Additional info:**
Resolves https://github.com/withfig/autocomplete/issues/605

2021-11-24 19:09 UTC, QuiiBz requested changes
Thanks a lot for this contribution!

2021-11-24 19:09 UTC, QuiiBz commented on src/mvn.ts
> +        suggestions: ["filepaths", "folders"],
This should actually be:

```suggestion
        template: ["filepaths", "folders"],
```

2021-11-24 19:09 UTC, QuiiBz commented on src/mvn.ts
> +    name: "goal/phase",
Could you also add a description for this argument?

2021-11-24 21:13 UTC, zp4rker commented on src/mvn.ts
> +        suggestions: ["filepaths", "folders"],
I blame GitHub Copilot 😂 

Fixed.

2021-11-24 21:13 UTC, zp4rker commented on src/mvn.ts
> +    name: "goal/phase",
Thanks for noticing, fixed!

2021-11-27 14:10 UTC, QuiiBz approved these changes
LGTM, thanks a lot for this contribution!

2021-11-27 14:10 UTC, merged