feat: add elm-review spec
withfig/autocomplete pull request #755
Opened 2021-11-29 17:17 UTC by wolfadex

### What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
Feature: Support for elm-review cli

### What is the new behavior (if this is a feature change)?
Support all of the publicly shown elm-review cli commands as of elm-review version 2.6.1.

2021-12-01 01:45 UTC, mschrage requested changes
Some minor tweaks but this looks great! Excited to get it merged in. Really appreciate your contribution @wolfadex ✨

2021-12-01 01:45 UTC, mschrage commented on src/elm-review.ts
> +      },
This `arg` object should have `isVariadic: true` set on it

```suggestion
      args: {
        name: "<dir1,dir2,...>",
        template: "folders",
        isVariadic: true,
      },
```

2021-12-01 01:45 UTC, mschrage commented on src/elm-review.ts
> +      },
Should also have `isVariadic: true` enabled.
```suggestion
      args: {
        name: "<file1,file2,...>",
        template: "filepaths",
        isVariadic: true,
      },
```

2021-12-13 19:27 UTC, wolfadex commented on src/elm-review.ts
> +      },
Fixed this with the inclusion of the elm-review 2.7.0 changes

2021-12-13 19:27 UTC, wolfadex commented on src/elm-review.ts
> +      },
Fixed this with the inclusion of the elm-review 2.7.0 changes

2021-12-13 20:21 UTC, mschrage approved these changes

2021-12-13 20:23 UTC, mschrage commented
Looks good to me @wolfadex! Merging in now 🤩

### Next steps
💬 **If you are in our [Discord](https://fig.io/community)**: let me know your username so I can give you the 'Contributor' badge!

🐥 **If you have a Twitter**: tweet that `elm-review` is now supported and we'll retweet from the [@fig](https://twitter.com/fig) account :)

🛠 **Are you interested in being a codeowner?** You'll be pinged to review any future PRs for the `elm-review` completion spec.

2021-12-13 20:23 UTC, merged

2022-01-04 15:46 UTC, wolfadex commented
@mschrage catching up on stuff after the holidays, I'd be happy to be a codeowner for any of the `elm-*` specs, as AFAIK I'm the only one contributing them right now. I also plan on making PRs for other Elm cli tools in the coming months.