feat: add `pulumi cli` to autocomplete
withfig/autocomplete pull request #763
Opened 2021-12-01 23:05 UTC by MishaKav

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature add [pulumi-cli](https://www.pulumi.com/docs/reference/cli/)

**What is the current behavior? (You can also link to an open issue here)**
No autocomplete for `pulumi-cli`

**What is the new behavior (if this is a feature change)?**
Add autocomplete to `pulumi-cli`

**Additional info:**
Resolves #669 
Spec has been added manually from the [official documentation](https://www.pulumi.com/docs/reference/cli/)

2021-12-02 19:33 UTC, QuiiBz requested changes
Thanks a lot for this PR!

2021-12-02 19:33 UTC, QuiiBz commented on src/pulumi.ts
> +  // args: {}
Can you remove these comments?

2021-12-02 19:33 UTC, QuiiBz commented on src/pulumi.ts
> +    name: "file",
Looks like this argument can have a `template` of `filepaths`

2021-12-02 19:33 UTC, QuiiBz commented on src/pulumi.ts
> +      default: "./",
Same as above but with a template of `folders`

2021-12-02 19:33 UTC, QuiiBz commented on src/pulumi.ts
> +      name: "file",
Same as above, I think this issue is repeating a few times

2021-12-02 19:33 UTC, QuiiBz commented on src/pulumi.ts
> +  description: "",
Can you add a description?

2021-12-02 19:33 UTC, QuiiBz commented on src/pulumi.ts
> +                "The key contains a path to a property in a map or list to set",
This argument can also have a `template`

2021-12-02 19:33 UTC, QuiiBz commented on src/pulumi.ts
> +      args: { name: "[type] [name] [id]" },
This should be split in multiple arguments:
```suggestion
      args: [
        {
          name: "type",
        },
        {
          name: "name",
        },
        ...
      ],
```

2021-12-02 19:33 UTC, QuiiBz commented on src/pulumi.ts
> +          description:
Should we add `isDangerous`?

2021-12-05 00:00 UTC, MishaKav commented on src/pulumi.ts
> +    name: "file",
add whenever it's possible

2021-12-05 00:00 UTC, MishaKav commented on src/pulumi.ts
> +      default: "./",
add whenever it possible

2021-12-05 00:02 UTC, MishaKav commented on src/pulumi.ts
> +                "The key contains a path to a property in a map or list to set",
it's a path to property inside the dictionary, not `filepath`.

2021-12-05 00:03 UTC, MishaKav commented on src/pulumi.ts
> +      name: "file",
add whenever it possible

2021-12-05 00:03 UTC, MishaKav commented on src/pulumi.ts
> +  description: "",
done

2021-12-05 00:03 UTC, MishaKav commented on src/pulumi.ts
> +      args: { name: "[type] [name] [id]" },
done

2021-12-05 00:04 UTC, MishaKav commented on src/pulumi.ts
> +          description:
added whenever it's possible

2021-12-05 16:41 UTC, QuiiBz approved these changes
LGTM, thank you so much for this huge contribution!

2021-12-05 16:44 UTC, merged