feat: add `just` spec
withfig/autocomplete pull request #765
Opened 2021-12-02 08:54 UTC by SeparateRecords

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adds the `just` spec (https://github.com/casey/just)
`just` is a task runner, similar in concept to `make`. You can create a "justfile" and invoke any amount of "recipes". These recipes can also take arguments (see below).

**Additional info:**
Relevant issue: withfig/fig#638
TL;DR: Fig doesn't have a way to model this behaviour natively, so it all has to be implemented in a generator. I've gone to great lengths to make things "just work" 😉

This spec is _nearly_ done in terms of feature-completeness, but I have a long way to go with clarity. This will be changed before this PR is ready for review.

Current to-do:
- [ ] Suggest aliases in args generator
- [ ] Factor out args generator into functions
- [ ] Use said functions in the other generators
- [ ] Re-write comments for clarity

<details>
<summary>Screenshots</summary>

<img width="450" alt="Default justfile" src="https://user-images.githubusercontent.com/52195359/144387730-88549a51-d5c1-48fb-a431-a6b753c145a3.png">

<img width="450" alt="Custom justfile" src="https://user-images.githubusercontent.com/52195359/144387516-88440812-2a86-4b5f-b2e4-3a1875ff87a0.png">

<img width="450" alt="Set variables" src="https://user-images.githubusercontent.com/52195359/144387908-29db78fd-5c31-4178-bd2d-9d47127ae4af.png">

</details>

2021-12-03 01:08 UTC, SeparateRecords commented on src/just.ts
> +      trigger: " ",
Is this necessary? I was under the (possibly incorrect) impression that generators are run once per token by default if not specified otherwise

2021-12-05 05:47 UTC, import-brain approved these changes
LGTM, I'm just not sure if that whitespace trigger is necessary.

2021-12-05 13:32 UTC, SeparateRecords commented
> LGTM, I'm just not sure if that whitespace trigger is necessary.

I didn't think so either but wasn't 100% sure, thanks for the second opinion 😊

2021-12-05 15:31 UTC, import-brain commented
> > LGTM, I'm just not sure if that whitespace trigger is necessary.
> 
> I didn't think so either but wasn't 100% sure, thanks for the second opinion 😊

To be honest, I'm not sure either, but if the whitespace is necessary, you can always revert commit fce4a9e and force push here :)

2021-12-05 16:56 UTC, QuiiBz requested changes
Didn't know `just`, that looks really cool.

2021-12-05 16:56 UTC, QuiiBz commented on src/just.ts
> +interface RecipeArityMapping {
Any reason why using an `interface` here, but `type` above?

2021-12-05 16:56 UTC, QuiiBz commented on src/just.ts
> +        name: "command",
I think we can add the [`isCommand`](https://fig.io/docs/reference/arg#iscommand) flag here

2021-12-06 05:24 UTC, SeparateRecords commented on src/just.ts
> +interface RecipeArityMapping {
There was a reason but it's not relevant anymore, I'll make it consistent with `interface` where possible

2021-12-06 05:29 UTC, SeparateRecords commented on src/just.ts
> +        name: "command",
Totally right! I'll add that.

2021-12-06 06:32 UTC, SeparateRecords commented
Realised there's another opportunity to make things simpler. Will implement that right now!

2021-12-06 13:06 UTC, SeparateRecords commented on src/just.ts
> +interface RecipeArityMapping {
Finally figured out how to word my rationale! It was gnawing at me all day, I just couldn't put it into words haha

I use `interface` when I'm planning on implementing a type, but if it's to model something external (eg data from an API or CLI) then I use `type`.

That distinction doesn't matter at all but that's what I do in my own projects, so it's habit 😁

2021-12-06 13:48 UTC, fedeci approved these changes
Thanks!

2021-12-06 15:19 UTC, import-brain approved these changes

2021-12-10 04:39 UTC, SeparateRecords commented
Just want to check, is there something holding this up from being merged?

2021-12-10 07:05 UTC, mschrage commented
Looks good to me! Let's get this merged 🤩

2021-12-10 07:05 UTC, merged