feat: add cordova completion spec
withfig/autocomplete pull request #766
Opened 2021-12-02 16:11 UTC by mpfeil

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature: Add [cordova cli](https://cordova.apache.org/docs/en/10.x/reference/cordova-cli/index.html)

**What is the current behavior? (You can also link to an open issue here)**
There is no autocompletion for `cordova`

**What is the new behavior (if this is a feature change)?**
Adds autocomplete functionality for `cordova` cli

**Additional info:**
Cordova CLI specs can be found [here](https://cordova.apache.org/docs/en/10.x/reference/cordova-cli/index.html)

2021-12-02 19:38 UTC, QuiiBz requested changes
Thanks a lot for this PR! I left some messages to resolve before getting this merged, feel free to ask if you need any help!

2021-12-02 19:38 UTC, QuiiBz commented on src/cordova.ts
> +  // args: {}
You can safely remove this comment

2021-12-02 19:38 UTC, QuiiBz commented on src/cordova.ts
> +          name: "edit",
The edit subcommand doesn't have any argument? Also, would love to see some descriptions!

2021-12-02 19:38 UTC, QuiiBz commented on src/cordova.ts
> +              },
This generator looks almost the same as `platformGenerator`, could you refactor them into a curried function to avoid duplication?

2021-12-02 19:38 UTC, QuiiBz commented on src/cordova.ts
> +          description: "",
Could you add a description for this option?

2021-12-02 19:38 UTC, QuiiBz commented on src/cordova.ts
> +          description: "",
Same as above

2021-12-07 14:59 UTC, mpfeil commented on src/cordova.ts
> +          name: "edit",
`edit` is working without any argument ant opens the config in an editor. Also added the missing descriptions.

2021-12-07 15:01 UTC, mpfeil commented on src/cordova.ts
> +              },
Added a new `plugin` generator using the build in `cordova` cli functionality. No need to parse the `pacakge.json` content.

2021-12-08 19:17 UTC, mschrage approved these changes
Looks good to me! Thanks so much for contributing @mpfeil 🤩

2021-12-08 19:20 UTC, merged