feat: add CircleCI completion spec
withfig/autocomplete pull request #767
Opened 2021-12-03 05:23 UTC by import-brain

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature: add circleci spec
**What is the current behavior? (You can also link to an open issue here)**
Normal
**What is the new behavior (if this is a feature change)?**
New autocomplete suggestions for the CircleCI CLI
**Additional info:**
N/A

2021-12-05 16:39 UTC, QuiiBz requested changes
Sorry for the delay on this PR, but thanks a lot for opening it!

2021-12-05 16:39 UTC, QuiiBz commented on src/circleci.ts
> +      options: [
Each `options` that doesn't start with `-` (or `--`) should be `subcommands`, could you please change all of them?

2021-12-05 18:09 UTC, import-brain commented on src/circleci.ts
> +      options: [
Done

2021-12-08 19:19 UTC, mschrage approved these changes
Thanks for making these changes @import-brain! Really appreciate your contribution :)

2021-12-08 19:19 UTC, merged

2021-12-08 22:44 UTC, import-brain commented
No problem!