feat: add Agrippa completion spec
withfig/autocomplete pull request #773
Opened 2021-12-06 09:32 UTC by NicoBru31

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature: add [Agrippa](https://github.com/NitzanHen/agrippa) spec
**What is the current behavior? (You can also link to an open issue here)**
Normal
**What is the new behavior (if this is a feature change)?**
New autocomplete suggestions for the [Agrippa CLI](https://github.com/NitzanHen/agrippa)
**Additional info:**
N/A

2021-12-07 13:38 UTC, import-brain commented on src/agrippa.ts
> +            "Whether to generate Typescript components. Defaults to `true` if the CLI manages to find a `tsconfig.json` file, false otherwise",
```suggestion
            "Option to generate TypeScript components, defaults to `true` if the CLI manages to find a `tsconfig.json` file, false otherwise",
```

2021-12-07 13:38 UTC, import-brain commented on src/agrippa.ts
> +            "Whether to import React at the top of the component. Default to `true` if the CLI manages to find a `tsconfig.json` file and it has a `jsx` field under `compilerOptions` with `react-jsx`
```suggestion
            "Option to import React at the top of the component. Defaults to `true` if the CLI manages to find a `tsconfig.json` file and it has a `jsx` field under `compilerOptions` with `react-jsx` or `react-jsxdev` as the value, `false` otherwise",
```

2021-12-07 13:38 UTC, import-brain commented on src/agrippa.ts
> +                  "Generate a Typescript interface for props (this requires the typescript option to be true)",
```suggestion
                  "Generate a TypeScript interface for props (this requires the typescript option to be true)",
```

2021-12-07 13:38 UTC, import-brain commented on src/agrippa.ts
> +            "Whether to generate Typescript components. Defaults to `true` if the CLI manages to find a `tsconfig.json` file, false otherwise",
I would personally phrase it this way, but I think this is up to personal preference.

2021-12-07 13:38 UTC, import-brain commented on src/agrippa.ts
> +                  "Generate a Typescript interface for props (this requires the typescript option to be true)",
Minor capitalization change

2021-12-07 13:38 UTC, import-brain commented on src/agrippa.ts
> +            "Whether to import React at the top of the component. Default to `true` if the CLI manages to find a `tsconfig.json` file and it has a `jsx` field under `compilerOptions` with `react-jsx`
Minor phrasing change, just like the first one.

2021-12-08 07:49 UTC, NicoBru31 commented on src/agrippa.ts
> +            "Whether to generate Typescript components. Defaults to `true` if the CLI manages to find a `tsconfig.json` file, false otherwise",
I agree, this is better with your suggestion 👍

2021-12-08 22:47 UTC, import-brain approved these changes
LGTM, great job! 👍 :)

2021-12-09 01:20 UTC, mschrage requested changes
Thanks so much for contributing @NicoBru31! The completion spec structure for `agrippa` is almost there, but I found a few minor issues.

2021-12-09 01:20 UTC, mschrage commented on src/agrippa.ts
> +          args: {
This looks like it might be a subcommand? Either that or it should be prefixed with a `--`

2021-12-09 01:20 UTC, mschrage commented on src/agrippa.ts
> +        },
It seems like this should take an argument that has `isCommand: true`?

2021-12-09 01:20 UTC, mschrage commented on src/agrippa.ts
> +          name: "flat",
Is this an option missing a "--" prefix or is this a subcommand?

2021-12-09 01:20 UTC, mschrage commented on src/agrippa.ts
> +        name: "directory",
Maybe this should be called `"component"` rather than `"directory"`?

2021-12-09 01:20 UTC, mschrage commented on src/agrippa.ts
> +        {
`--children` is a boolean flag. 

It would be used like this:
✅ `agrippa generate component-name --children`. 

You would not pass an additional argument to it:
❌ `agrippa generate component-name --children false`

Unless I am misunderstanding how the `agrippa` CLI tool is used, you should remove the `args` object from this (and any other boolean flag).

You can verify if something is a boolean flag in `agrippa` by looking here: https://github.com/NitzanHen/agrippa/blob/main/src/generate/index.ts

2021-12-09 08:05 UTC, NicoBru31 commented on src/agrippa.ts
> +          args: {
Indeed this is an option f132e249265cdcf0a9eb5cee5f41eeb02bb435b8

2021-12-09 08:07 UTC, NicoBru31 commented on src/agrippa.ts
> +        },
I didn't know about the `isCommand: true`, what a wonderful tool 😍  1738640c10916853c626286c20cc5ee72f0e5ce9

2021-12-09 08:07 UTC, NicoBru31 commented on src/agrippa.ts
> +          name: "flat",
08abcbd2458dd4240aee7340b4cdce2c745c7e57

2021-12-09 08:07 UTC, NicoBru31 commented on src/agrippa.ts
> +        name: "directory",
You're right 5794451f613129de6dc2b8c2970ebb80ad2a65a5

2021-12-09 08:09 UTC, NicoBru31 commented on src/agrippa.ts
> +        {
My bad I wasn't using the CLI the proper way 73b4803326fc1c953b82722447cd302f2327c01e

2021-12-09 08:11 UTC, NicoBru31 commented
> Thanks so much for contributing @NicoBru31! The completion spec structure for `agrippa` is almost there, but I found a few minor issues.

Thank you for your review (I am sorry for the small mistakes like the missing `--` for the options). This is my first PR ever and I'm glad this is for such a great tool !

2021-12-09 08:11 UTC, NicoBru31 commented
> LGTM, great job! 👍 :)

Thank you for the review I appreciate :)

2021-12-09 22:22 UTC, mschrage approved these changes

2021-12-09 22:26 UTC, mschrage commented
Hey @NicoBru31! Thank you so much for contributing. You picked up the spec format super quick :)

Also, please let me know if there is anything we can do to improve the spec development experience and onboarding. 

### Next steps
💬 **If you are in our [Discord](https://fig.io/community)**: let me know your username so I can give you the 'Contributor' badge!

🐥 **If you have a Twitter**: tweet that stepzen is now supported and we'll retweet from the [@fig](https://twitter.com/fig) account :)

🛠 **Are you interested in being a codeowner?** You'll be pinged to review any future PRs for the `agrippa` completion spec.

2021-12-09 22:26 UTC, merged