feat(docker): enhance docker run completion
withfig/autocomplete pull request #796
Opened 2021-12-20 11:32 UTC by xwjdsh

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**
![image](https://user-images.githubusercontent.com/11025519/146760914-41308054-0c42-4587-acd7-859394f8f776.png)

**Additional info:**

2021-12-20 12:06 UTC, fedeci approved these changes
There are still a lot of missing options, but this PR LGTM. Thank you!

2021-12-21 04:49 UTC, xwjdsh commented
> There are still a lot of missing options, but this PR LGTM. Thank you!

@fedeci I wrote a script and added the missing options.

2021-12-21 10:13 UTC, fedeci requested changes

2021-12-21 10:13 UTC, fedeci commented on src/docker.ts
> +          name: "string",
```suggestion
          name: "string",
          suggestions: ["json-file", "syslog", "journald", "gelf", "fluentd", "awslogs", "splunk", "etwlogs", "gcplogs", "none"],
```

2021-12-21 10:13 UTC, fedeci commented on src/docker.ts
> +          name: "string",
this will require to rerun the linter

2021-12-21 21:52 UTC, mschrage approved these changes
Thanks so much for adding all of these options to the spec @xwjdsh! Really appreciate your contribution! 🤩

Would you be interested in becoming a codeowner for the docker completion spec?

2021-12-22 02:04 UTC, xwjdsh commented on src/docker.ts
> +          name: "string",
Done.

2021-12-22 02:10 UTC, xwjdsh commented
@mschrage Of course, I'm working on it.

2021-12-22 09:26 UTC, fedeci approved these changes
Thanks!

2021-12-22 09:27 UTC, merged