feat: add autocomplete for pre-commit
withfig/autocomplete pull request #798
Opened 2021-12-21 21:02 UTC by miketheman

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature - new spec

**What is the current behavior? (You can also link to an open issue here)**
no spec exists

**What is the new behavior (if this is a feature change)?**
new completions!

**Additional info:**
Popular CLI tool: https://pre-commit.com/

I left a couple of notes inline to help improve this in the future.

2021-12-21 21:07 UTC, miketheman commented on src/pre-commit.ts
> +    'sed -nE "s/[[:space:]]+-[[:space:]]+id:[[:space:]](.*)$/\\1/p" .pre-commit-config.yaml',
Tested on macOS 12.1, which uses BSD `sed`. Since fig targets macOS for now, this seemed safe enough until https://github.com/withfig/fig/issues/733 is implemented

2021-12-21 21:07 UTC, miketheman commented on src/pre-commit.ts
> +      // TODO: am I allowed to import a generator for `git.ts`?
I didn't want to copy a bunch of generator code over needlessly, but figured I'd inquire. Seems like there may be a benefit for other git-related utilities to have a set of shared util functions somewhere?

2021-12-21 21:07 UTC, miketheman commented on src/pre-commit.ts
> +    globalOptions[0], // top level only takes `help`
I wasn't sure about this approach, but it works. Happy to take any advice on a better accessor for the `help` without having to split out the option from `glopbalOptions`

2021-12-21 21:42 UTC, fedeci commented on src/pre-commit.ts
> +    'sed -nE "s/[[:space:]]+-[[:space:]]+id:[[:space:]](.*)$/\\1/p" .pre-commit-config.yaml',
This is not the only command we will need to update in the future, it's great for the moment!

2021-12-21 21:43 UTC, fedeci commented on src/pre-commit.ts
> +      // TODO: am I allowed to import a generator for `git.ts`?
Sure you can, we are doing something similar for `yarn`, `npm` and `pnpm` specs

2021-12-21 21:44 UTC, fedeci commented on src/pre-commit.ts
> +    globalOptions[0], // top level only takes `help`
Can't we just do this?
```suggestion
    help,
```

2021-12-21 21:48 UTC, miketheman commented on src/pre-commit.ts
> +      // TODO: am I allowed to import a generator for `git.ts`?
Awesome! Will look at those now.

2021-12-21 21:48 UTC, miketheman commented on src/pre-commit.ts
> +    globalOptions[0], // top level only takes `help`
Oh, that's sneaky. Will update!

2021-12-21 21:50 UTC, mschrage requested changes
This looks good to me! Also really agree with your instincts around shared generators.

Just a few nits:

2021-12-21 21:50 UTC, mschrage commented on src/pre-commit.ts
> +      // TODO: am I allowed to import a generator for `git.ts`?
We are adding something like this now. See https://github.com/withfig/autocomplete/pull/794

And I agree that git generators are good candidates to be shared between specs.

2021-12-21 21:50 UTC, mschrage commented on src/pre-commit.ts
> +  },
```suggestion
  args: {
    name: "CONFIG",
    template: "filepaths"
  },
```

2021-12-21 21:50 UTC, mschrage commented on src/pre-commit.ts
> +    globalOptions[0], // top level only takes `help`
It seems like `globalOptions` are _already_ split out. I would just use the existing `help` value to make this more explicit.

2021-12-21 21:50 UTC, fedeci requested changes
I added a few suggestions, but apart from those nits this PR looks great. Thank you!

2021-12-21 21:50 UTC, fedeci commented on src/pre-commit.ts
> +      options: [...globalOptions],
super nitpicky:
```suggestion
      options: globalOptions,
```

2021-12-21 21:50 UTC, fedeci commented on src/pre-commit.ts
> +      options: [...globalOptions],
```suggestion
      options: globalOptions,
```

2021-12-21 21:50 UTC, fedeci commented on src/pre-commit.ts
> +      options: [...globalOptions],
```suggestion
      options: globalOptions,
```

2021-12-21 21:50 UTC, fedeci commented on src/pre-commit.ts
> +      options: [...globalOptions],
```suggestion
      options: globalOptions,
```

2021-12-21 21:50 UTC, fedeci commented on src/pre-commit.ts
> +      options: [...globalOptions],
```suggestion
      options: globalOptions,
```

2021-12-21 21:50 UTC, fedeci commented on src/pre-commit.ts
> +      options: [...globalOptions],
This accepts an arg with the name of the command, right? We can probably extract the keys from `Object.keys(completionSpec.subcommands) and remove "help" from there` 

@mschrage would it be nice to have some other sugar to get this behaviour for free adding a new template? Commander has this kind of help too if I am not wrong and many specs may benefit of it.

2021-12-21 21:51 UTC, fedeci commented
Reviews overlapping, nice😆

2021-12-21 23:06 UTC, miketheman commented on src/pre-commit.ts
> +    'sed -nE "s/[[:space:]]+-[[:space:]]+id:[[:space:]](.*)$/\\1/p" .pre-commit-config.yaml',
I have a refactor locally, but it depends on #800 being merged first, so will hold off pushing just yet.

2021-12-22 02:24 UTC, mschrage commented on src/pre-commit.ts
> +      options: [...globalOptions],
I think Cobra does as well. Definitely makes sense to me to add this in as `template: "subcommands"` or `template: "help"`.

2021-12-22 09:35 UTC, fedeci commented on src/pre-commit.ts
> +      options: [...globalOptions],
I will add it then!

2021-12-22 15:02 UTC, miketheman commented on src/pre-commit.ts
> +    'sed -nE "s/[[:space:]]+-[[:space:]]+id:[[:space:]](.*)$/\\1/p" .pre-commit-config.yaml',
Pushed 570460225550ffddafe85b3e6a384c8952139162

2021-12-22 15:02 UTC, miketheman commented
I think this is ready for review/merge!

2021-12-22 18:52 UTC, mschrage commented
Hey @miketheman! Thanks so much for this contribution 🤩

### Next steps

🐥 **If you have a Twitter**: tweet that `precommit` is now supported and we'll retweet from the [@fig](https://twitter.com/fig) account :)

🛠 **Are you interested in being a codeowner?** You'll be pinged to review any future PRs for the `precommit` completion spec.

2021-12-22 18:52 UTC, merged