feat: add `pass` completion spec
withfig/autocomplete pull request #810
Opened 2021-12-29 23:14 UTC by whobutsb

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
New Feature: Added [pass](https://www.passwordstore.org/) auto completion.

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**
Man page for pass - https://git.zx2c4.com/password-store/about/

- [ ] Add me as codeowner of new files (you will be added as a codeowner of the files added in this PR)

2021-12-29 23:32 UTC, whobutsb commented
👍

2021-12-30 15:20 UTC, fedeci submitted a review, later dismissed
Can you fix the listing errors, please? `npm run lint:fix` should do the work!

2021-12-30 15:26 UTC, whobutsb commented
@fedeci Linted!  Thank you for the consideration!

2021-12-30 16:50 UTC, whobutsb commented
Question for the fig team.  Within the `pass` command you can use `pass git` which allows you to interact with the local `~/.password-store` git repo and run normal git commands.  Is there a way to reference the fig `git` completion spec when someone types in `pass git`?  I doesn't make sense to rewrite the entire git spec.  Currently I have the following for the arguments: 

```
    {
      name: "git",
      description: "Password store git functions",
      args: {
        name: "git-command-arguments",
        description: "Git command arguments",
      },
    },
```

The `pass grep` command is the same as well where you can grep inside the files to find a particular line.  It would be great to show the git and grep specs as completions when you enter the sub commands.

Thanks!

2021-12-30 17:08 UTC, whobutsb commented
> Question for the fig team. Within the `pass` command you can use `pass git` which allows you to interact with the local `~/.password-store` git repo and run normal git commands. Is there a way to reference the fig `git` completion spec when someone types in `pass git`? I doesn't make sense to rewrite the entire git spec. Currently I have the following for the arguments:
> 
> ```
>     {
>       name: "git",
>       description: "Password store git functions",
>       args: {
>         name: "git-command-arguments",
>         description: "Git command arguments",
>       },
>     },
> ```
> 
> The `pass grep` command is the same as well where you can grep inside the files to find a particular line. It would be great to show the git and grep specs as completions when you enter the sub commands.
> 
> Thanks!

Figured this out!  Added `loadSpec: true` to the `pass git` and `pass grep` commands, to get the full completion.  Super useful!

2021-12-30 18:34 UTC, mschrage commented
Hey @whobutsb! `loadSpec` is the right property, but I'm surprised it passes typechecking as a boolean.

I think it should be `loadSpec: "git"` and `loadSpec: "grep"` instead

2021-12-30 19:07 UTC, whobutsb commented
@mschrage Updated!  Thanks for the hint.  Yeah it was working fine for both commands with `true`, interesting stuff!

2021-12-30 19:14 UTC, whobutsb reviewed
Ran `npm run lint:fix`.

2021-12-30 19:27 UTC, mschrage requested changes
Thanks for contributing @whobutsb! A few small tweaks but this looks great overall :)

2021-12-30 19:27 UTC, mschrage commented on src/pass.ts
> +    return `gpg --list-keys --with-colons --with-fingerprint | awk -F: '/^uid:/ { print $10 }`;
Can you try to move the parsing logic to Javascript? Sometimes people have different versions of `awk` and `sed` installed, so it is best to keep as much as possible in the JS runtime.

2021-12-30 19:27 UTC, mschrage commented on src/pass.ts
> +    return `grep -r -l '' $HOME/.password-store --exclude-dir=.git | sed "s|$HOME/.password-store/||g"`;
Can we remove `sed` and put this logic in JS?

2021-12-30 19:27 UTC, mschrage commented on src/pass.ts
> +    return `ls -dR1a $HOME/.password-store/*/ | sed "s|$HOME/.password-store/||g"`;
Same as above?

2021-12-30 20:00 UTC, whobutsb commented on src/pass.ts
> +    return `gpg --list-keys --with-colons --with-fingerprint | awk -F: '/^uid:/ { print $10 }`;
@mschrage - I'm going to remove this function altogether.  I wasn't 100% sure that the output that I was receiving was the correct argument for the `pass init` command.

2021-12-30 20:02 UTC, whobutsb commented on src/pass.ts
> +    return `grep -r -l '' $HOME/.password-store --exclude-dir=.git | sed "s|$HOME/.password-store/||g"`;
Updated now using: 
```
const listPasswords: Fig.Generator = {
  script: function () {
    return `grep -r -l '' $HOME/.password-store --exclude-dir=.git`;
  },
  postProcess: (output) => {
    return output.split("\n").map((password) => ({
      name: password.split(".password-store/").pop().replace(".gpg", ""),
    }));
  },
};
```
This will remove everything before the `.password-store/` directory and output just the pass-names and directories.

2021-12-30 20:03 UTC, whobutsb commented on src/pass.ts
> +    return `ls -dR1a $HOME/.password-store/*/ | sed "s|$HOME/.password-store/||g"`;
Same as previous.

2021-12-30 21:57 UTC, fedeci approved these changes
Thanks!

2021-12-31 05:03 UTC, import-brain approved these changes

2021-12-31 06:34 UTC, mschrage approved these changes

2021-12-31 06:35 UTC, merged