Add Exercism support
withfig/autocomplete pull request #812
Opened 2022-01-02 11:34 UTC by hendrikmitk

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature: Add completion spec for Exercism CLI

**What is the current behavior? (You can also link to an open issue here)**
Currently, there are no completion options for the `exercism` command.

**What is the new behavior (if this is a feature change)?**
There will be completion options available for the `exercism` command.

**Additional info:**
https://exercism.org/docs/using/solving-exercises/working-locally

2022-01-10 23:10 UTC, mschrage requested changes
This looks great! Thanks so much for contributing @hendrikmitk! Just one small tweak and we can get this merged in:

2022-01-10 23:10 UTC, mschrage commented on src/exercism.ts
> +];
I saw that this `helpOption` is included everywhere -- it's a nice touch of polish, but you can get the same behavior with less copy and pasting by setting [`isPersistent`](https://fig.io/docs/reference/option#ispersistent) to true!

Just make sure `helpOption` added to the root subcommand and the `--help` flag will appear for all child subcommands as well. 

```suggestion
const helpOption: Fig.Option[] = [
  {
    name: ["-h", "--help"],
    description: "More information about command",
    isPersistent: true,
  },
];
```

2022-01-11 08:30 UTC, hendrikmitk commented on src/exercism.ts
> +];
Thanks a lot for the feedback @mschrage! Using `isPersistent` is indeed a nice touch that makes the whole thing a bit clearer. I removed the `helpOption` because the same option had already been available at the top level.

This also made me notice that the global flags were not yet available for all subcommands as intended.

2022-01-14 19:46 UTC, mschrage approved these changes

2022-01-14 19:47 UTC, merged

2022-01-14 19:47 UTC, mschrage commented
Thanks so much for contributing @hendrikmitk! 🥳

2022-01-15 12:21 UTC, hendrikmitk commented
Thanks to you and your team for building such a great tool @mschrage! 🙂