Doctl
withfig/autocomplete pull request #826
Opened 2022-01-10 04:44 UTC by japrozs

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Completion for the digital ocean CLI :: `doctl`

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2022-01-10 12:39 UTC, fedeci requested changes
Thanks, could you fix the lint errors, please? Then we should be ready to merge it!

2022-01-10 12:39 UTC, fedeci commented on dev/doctl.ts
> +      additionalSuggestions: ["bash", "zsh", "fish"],
We should use an `arg` along with `suggestion` here:
```suggestion
      args: {
        name: "shell",
        suggestions: ["bash", "zsh", "fish"],
      },
```

2022-01-11 03:48 UTC, japrozs commented
I fixed the linting changes

2022-01-11 18:41 UTC, fedeci requested changes

2022-01-11 18:41 UTC, fedeci commented on dev/doctl.ts
> +        },
```suggestion
```

2022-01-11 18:41 UTC, fedeci commented on dev/doctl.ts
> +      insertValue: "json",
```suggestion
      args: {
        name: "format",
        suggestions: ["text", "json"],
      },
```

2022-01-11 18:41 UTC, fedeci commented on dev/doctl.ts
> +      description: 'Desired output format [text|json] (default "text")',
```suggestion
      description: "Desired output format",
      default: "text"
```

2022-01-12 04:18 UTC, japrozs commented
more changes

2022-01-12 17:21 UTC, fedeci approved these changes
Thanks!

2022-01-12 17:21 UTC, merged

2022-01-12 17:37 UTC, japrozs commented
No problem. Are there any other CLI's that you want specs for

2022-01-12 19:28 UTC, fedeci commented
You can check for [issues](https://github.com/withfig/autocomplete/issues?q=is%3Aissue+is%3Aopen+label%3A%22CLI+request%22)!

2022-01-26 00:15 UTC, brendanfalk commented
Hey @japrozs - would you be able to add support for the options for these subcommands?

e.g. `--ip-range` for `doctl vpcs`

2022-01-26 10:24 UTC, japrozs commented
> Hey @japrozs - would you be able to add support for the options for these subcommands?
> 
> e.g. `--ip-range` for `doctl vpcs`

sure!