Adding completion spec for IaC scanner Checkov
withfig/autocomplete pull request #829
Opened 2022-01-11 12:03 UTC by eurogig

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Added autocompletion spec for the open source IaC scanning tool Checkov by Bridgecrew.io

**What is the current behavior? (You can also link to an open issue here)**
No previous support for this CLI tool.

**What is the new behavior (if this is a feature change)?**
Support for Checkov!

**Additional info:**
Fig rocks!

2022-01-11 12:08 UTC, eurogig commented
Sorry I didn't keep the to "feat: add checkov completion spec".  Got excited and missed that contributor detail.  Double checked all the args and tested the commands.

2022-01-11 18:43 UTC, fedeci commented on src/checkov.ts
> +      description: "Show the version of checkov",
I think this is not the correct description

2022-01-11 18:44 UTC, fedeci commented on src/checkov.ts
> +      description: "IaC file(can not be used together with --directory)",
```suggestion
      description: "IaC file",
      exclusiveOn: ["--file"],
```

2022-01-11 18:45 UTC, fedeci commented on src/checkov.ts
> +        "Path (file or directory) to skip, using regular expression logic, relative to current working directory. Word boundaries are not implicit; i.e., specifying 'dir1' will skip any directory or
This seems to be variadic

2022-01-11 18:45 UTC, fedeci commented on src/checkov.ts
> +  description: "",
Could you add a short description for the tool please?

2022-01-11 18:51 UTC, fedeci requested changes
Thanks a lot for your contribution! I left some suggestions to improve the spec but it looks great🎉

2022-01-11 18:51 UTC, fedeci commented on src/checkov.ts
> +      name: "----run-all-external-checks",
these are a lot of dashes 😄

2022-01-11 18:51 UTC, fedeci commented on src/checkov.ts
> +        "Scan docker images by name or ID. Only works with --bc-api-key flag",
This needs [`dependsOn`](https://fig.io/docs/reference/option#dependson)

2022-01-11 18:51 UTC, fedeci commented on src/checkov.ts
> +        "Selected branch of the persisted repository. Only has effect when using the --bc-api-key flag",
Also this needs `dependsOn`

2022-01-11 18:51 UTC, fedeci commented on src/checkov.ts
> +        "Save all current results to a '.checkov.baseline' file so future runs will only flag new findings. Works only with `--directory` flag",
this probably is missing `dependsOn`

2022-01-11 18:51 UTC, fedeci commented on src/checkov.ts
> +        "Directory containing the hcl code used to generate a given plan file. Use with -f FILE",
This is missing dependsOn

2022-01-11 18:51 UTC, fedeci commented on src/checkov.ts
> +      },
This is both depending on `--directory` and exclusive on `--file`. A the same `--file` should be exclusive on this one.

2022-01-11 18:51 UTC, fedeci commented on src/checkov.ts
> +    },
This `dependsOn` bc-api-key

2022-01-11 18:51 UTC, fedeci commented on src/checkov.ts
> +      name: "--skip-policy-download",
This dependsOn bc-api-key

2022-01-11 18:54 UTC, eurogig commented on src/checkov.ts
> +        "Path (file or directory) to skip, using regular expression logic, relative to current working directory. Word boundaries are not implicit; i.e., specifying 'dir1' will skip any directory or
...and you would be correct.  Feel free to open a pull request on our tool to fix it.  This exercise of providing support for Checkov has been interesting in me having the same revelations.  Unfortunately that description is cut and paste from our help.

2022-01-11 18:55 UTC, eurogig commented on src/checkov.ts
> +  description: "",
Can do.  Saw a lot of files in the src directory without descriptions so wasn't sure how key this was.  Will add one.

2022-01-11 18:56 UTC, eurogig commented on src/checkov.ts
> +      name: "----run-all-external-checks",
Sh****t.. Will fix.

2022-01-11 18:56 UTC, eurogig commented on src/checkov.ts
> +        "Scan docker images by name or ID. Only works with --bc-api-key flag",
Didn't see that feature.  Like it.  Will take all these on and resubmit.

2022-01-11 19:05 UTC, fedeci commented on src/checkov.ts
> +  description: "",
Thanks!

2022-01-11 19:08 UTC, fedeci commented on src/checkov.ts
> +        "Path (file or directory) to skip, using regular expression logic, relative to current working directory. Word boundaries are not implicit; i.e., specifying 'dir1' will skip any directory or
I meant we can add the variadic prop to the argument of the option in the spec😄

2022-01-11 19:08 UTC, fedeci commented on src/checkov.ts
> +        "Scan docker images by name or ID. Only works with --bc-api-key flag",
Great!

2022-01-12 11:08 UTC, eurogig commented on src/checkov.ts
> +        "Path (file or directory) to skip, using regular expression logic, relative to current working directory. Word boundaries are not implicit; i.e., specifying 'dir1' will skip any directory or
Oh oh... yeah that.  Ok thanks!

2022-01-12 12:09 UTC, eurogig commented on src/checkov.ts
> +      description: "IaC file(can not be used together with --directory)",
It was exclusive on --directory actually.  Added.

2022-01-12 12:10 UTC, eurogig commented on src/checkov.ts
> +        "Path (file or directory) to skip, using regular expression logic, relative to current working directory. Word boundaries are not implicit; i.e., specifying 'dir1' will skip any directory or
Changes made

2022-01-12 12:14 UTC, eurogig commented on src/checkov.ts
> +        "Save all current results to a '.checkov.baseline' file so future runs will only flag new findings. Works only with `--directory` flag",
Ok should be done.  All suggestions should be resolved.

2022-01-12 12:15 UTC, eurogig commented
@fedeci thanks!  All changes should be resolved now.

2022-01-12 17:14 UTC, fedeci approved these changes
Thank you!

2022-01-12 17:22 UTC, merged