feat: add minikube completion spec
withfig/autocomplete pull request #834
Opened 2022-01-13 18:24 UTC by singhiqbal1007

[Minikube](https://github.com/kubernetes/minikube) implements a local Kubernetes cluster on macOS, Linux, and Windows. 

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
`minikube` commands are currently not-supported

**What is the new behavior (if this is a feature change)?**
Autocomplete and documentation to help guide developers using the `minikube` CLI

**Additional info:**

2022-01-20 12:19 UTC, singhiqbal1007 commented
@fedeci / @mschrage / @QuiiBz is there something that I am missing for this PR to get reviewed? I am new to open source I think I followed steps from the Guide. I would love to use minikube completions without dev mode 😛. Do let me know. Thnx.

2022-01-21 17:48 UTC, fedeci requested changes
Thank you for the spec @singhiqbal1007, sorry for the late review😃

2022-01-21 17:48 UTC, fedeci commented on src/minikube.ts
> +};
Fig does not support this format for args ([see](https://fig.io/docs/getting-started/first-completion-spec#3-adding-args)).

2022-01-21 17:48 UTC, fedeci commented on src/minikube.ts
> +    description: "Format to print stdout in. Options include: [text,json]",
```suggestion
    description: "Format to print stdout in",
    args: {
      name: "format",
      suggestions: ["json", "text"],
    },
```

2022-01-26 13:27 UTC, singhiqbal1007 commented
@fedeci Thank you for taking out time for reviewing the PR. I have made changes as requested. I also added suggestions wherever I found necessary. Please review.

2022-01-26 22:21 UTC, fedeci approved these changes
Thanks @singhiqbal1007! I think there are some listing errors, you can run `npm run lint:fix` to automatically fix them, then we should be ready to merge this in!

2022-01-27 07:59 UTC, singhiqbal1007 commented
@fedeci I ran `lint:fix` command again today. There was no change in the file after running it. Plus I am using ESLint extension in vscode which automatically fix everything on saving the file. Let me know if i am missing something. Thnx

2022-01-27 11:37 UTC, fedeci commented
In fact the linting action is not failing, thanks again!

2022-01-27 11:37 UTC, merged