Feat/eb use subcommand
withfig/autocomplete pull request #845
Opened 2022-01-15 03:40 UTC by nmassardot

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feat

**What is the current behavior? (You can also link to an open issue here)**
It doesn't support all `eb` commands from AWS

**What is the new behavior (if this is a feature change)?**
Now supports `use` subcommands and all of the options and args

**Additional info:**
None.

2022-01-16 06:07 UTC, import-brain approved these changes

2022-01-17 09:41 UTC, fedeci commented on src/eb.ts
> +          name: "--source codecommit/",
This appears to be wrong:
```suggestion
          name: "--source",
```

2022-01-17 09:41 UTC, fedeci commented on src/eb.ts
> +            name: "repository-name/repository-branch",
```suggestion
            name: "codecommit/repository-name/repository-branch",
```

2022-01-17 09:42 UTC, fedeci requested changes
A few things to change and we can get this merged in

2022-01-18 02:16 UTC, nmassardot commented
Ready @fedeci

2022-01-18 10:00 UTC, fedeci approved these changes

2022-01-18 10:00 UTC, merged