Add mkdir completion
withfig/autocomplete pull request #852
Opened 2022-01-19 02:17 UTC by qazwini

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adds folder completion to the `mkdir` command.

**What is the current behavior? (You can also link to an open issue here)**
Currently, if I’m at ~ and I’m trying to make a new folder in ~/Desktop/work/, I have to manually type in `mkdir Desktop/work/<folder name>`. There is no autocomplete for “Desktop/work/”.

**What is the new behavior (if this is a feature change)?**
If I am at ~ and I’m trying to make a new folder in ~/Desktop/work/, I will see my list of folders in the cwd as soon as I type `mkdir `. Then I will be able to autocomplete Desktop/ and same for work/.

**Additional info:**

2022-01-19 07:22 UTC, mschrage commented
@qazwini we definitely should provide some suggestions here, however I think just using the `folder` template could create some UX issues.

For instance, if a user is trying to create a new directory called "App" in a folder that already contains another folder called "Application":

<img width="441" alt="Screen Shot 2022-01-18 at 11 15 30 PM" src="https://user-images.githubusercontent.com/3155109/150082273-f7c65658-009d-487f-89a7-e1731469d9ee.png">

The user would need to hide the autocomplete window before being able to press enter.

What we really want is this behavior. 
<img width="436" alt="Screen Shot 2022-01-18 at 11 17 05 PM" src="https://user-images.githubusercontent.com/3155109/150082459-2c71fa37-80cc-4f2c-a6a1-fb56a16e9c7f.png">

My naive attempt was to add another generator that just outputs the current token. 
```ts
 generators: [{
        template: [ "folders" ],
      },
      // ensure that current token is always a valid suggestion
      {
        custom:  async (tokens) => {
          return [ { name: tokens[tokens.length - 1] } ]
        }
      }
    ]
```

However, this results in strange behavior like this:
<img width="503" alt="Screen Shot 2022-01-18 at 11 21 13 PM" src="https://user-images.githubusercontent.com/3155109/150083157-865c472a-6e8d-4b7e-8260-0c2eb0ad1ce1.png">
<img width="532" alt="Screen Shot 2022-01-18 at 11 21 25 PM" src="https://user-images.githubusercontent.com/3155109/150083158-33b1127e-5347-461b-913e-0f4c11d0ae12.png">

Any thoughts @fedeci or @SeparateRecords ?

2022-01-21 17:25 UTC, fedeci commented
IMO the only solution without touching the AE is to create a new custom generator that simulates the behaviour of the folders template but is able to handle that edge case @mschrage.

2022-01-24 00:11 UTC, mschrage commented
@fedeci this feels like something that should be handled internally in the autocomplete-engine. I think we should add a new field on `Arg` that triggers this behavior?

2022-01-24 14:21 UTC, fedeci commented
Will work on that in these days!

2022-01-27 20:13 UTC, qazwini commented
I also just noticed the same issue exists for `touch`. For, `dir/dir/newfile`, `dir/dir/` will not autocomplete.

2022-02-06 21:23 UTC, fedeci commented
@qazwini @a7med-mahmoud See https://github.com/withfig/autocomplete-tools/pull/36

2022-02-07 11:31 UTC, fedeci requested changes

2022-02-07 11:31 UTC, fedeci commented on src/mkdir.ts
> +    template: "folders",
```suggestion
    template: "folders",
    suggestCurrentToken: true,
```

2022-02-08 15:34 UTC, merged