Add Nest Spec
withfig/autocomplete pull request #863
Opened 2022-01-21 16:17 UTC by bmeverett

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
No autocomplete support for nest

**What is the new behavior (if this is a feature change)?**
Adds autocomplete for the [Nest Cli](https://docs.nestjs.com/cli/overview)

**Additional info:**

2022-01-21 16:44 UTC, fedeci requested changes
A couple tweaks and it should be ready to be merged in!

2022-01-21 16:44 UTC, fedeci commented on src/nest.ts
> +    description: "Enforce spec files generation (default: true)",
```suggestion
    description: "Enforce spec files generation (default: true)",
    exclusiveOn: ["--no-spec"],
```

2022-01-21 16:44 UTC, fedeci commented on src/nest.ts
> +    description: "Disable spec files generation",
```suggestion
    description: "Disable spec files generation",
    exclusiveOn: ["--spec"],
```

2022-01-21 16:44 UTC, fedeci commented on src/nest.ts
> +  description: "",
Could you add a description?

2022-01-22 00:07 UTC, bmeverett commented on src/nest.ts
> +  description: "",
Updated

2022-01-22 11:42 UTC, fedeci approved these changes
Thanks!

2022-01-22 11:47 UTC, merged