Add support for vim command line options, for #858
withfig/autocomplete pull request #888
Opened 2022-01-28 08:01 UTC by Yohannfra

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Add vim command line options 
**What is the current behavior? (You can also link to an open issue here)**
No command line options
**What is the new behavior (if this is a feature change)?**
Command line options

2022-01-28 20:06 UTC, mschrage requested changes
Thanks so much for fleshing out the `vim` spec @Yohannfra. There are a few minor changes before we can get this merged in.

2022-01-28 20:06 UTC, mschrage commented on src/vim.ts
> +    },
The `name` field must only contain the flag name and nothing else. Please combine the two `-r` flags.

2022-01-28 20:06 UTC, mschrage commented on src/vim.ts
> +        isOptional: false,
Add `isCommand: true` here so that Fig will continue to provide suggestions :)

2022-01-28 20:06 UTC, mschrage commented on src/vim.ts
> +        isOptional: false,
Should this have `template: "filepaths"`?

2022-01-28 22:57 UTC, Yohannfra commented on src/vim.ts
> +        isOptional: false,
yes thanks

2022-01-28 23:05 UTC, mschrage commented on src/vim.ts
> +        isOptional: false,
`isOptional` should be `true` here, right?

2022-01-28 23:24 UTC, Yohannfra commented on src/vim.ts
> +        isOptional: false,
yes oops! thanks you

2022-01-29 00:34 UTC, mschrage approved these changes

2022-01-29 17:43 UTC, merged