feat: add yarn icon for scripts from package.json
withfig/autocomplete pull request #89
Opened 2021-04-02 20:25 UTC by cstrnt

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
When running `yarn <scriptname>` or `yarn run <scriptname>` the yarn icon doesn't appear like it does when invoking `npm run <scriptname`

**What is the new behavior (if this is a feature change)?**
The icon is displayed

**Additional info:**

2021-04-03 07:16 UTC, QuiiBz requested changes

2021-04-03 07:16 UTC, QuiiBz commented on dev/yarn.ts
> +};
We shouldn't use type assertion, rather infer the type at the declaration level:
```suggestion
const yarnGenerators: Record<string, Fig.Generator> = {
  getScripts: {
    script: "cat package.json",
    postProcess: function (output) {
      if (output.trim() == "") {
        return [];
      }
      try {
        const packageContent = JSON.parse(output);
        const scripts = packageContent["scripts"];
        if (scripts) {
          return Object.keys(scripts).map((scriptName) => ({
            name: scriptName,
            icon: "https://yarnpkg.com/favicon-32x32.png",
          }));
        }
      } catch (e) {}

      return [];
    },
  },
};
```

2021-04-03 07:17 UTC, cstrnt commented on dev/yarn.ts
> +};
I did this before, but doing that causes autocompletion when typing `yarnGenerators.` not to work. When you use `string` as the key of a record it means it can be any `string` and it will not show you (atleast in vscode) completions for `getScripts`

2021-04-03 07:28 UTC, QuiiBz commented on dev/yarn.ts
> +};
Nevermind, you're right. We could hard write the `getScripts` property like this to get the completion: `const yarnGenerators: { getScripts: Fig.Generator } = {`, but it's not very clean.

2021-04-03 07:29 UTC, QuiiBz approved these changes

2021-04-08 00:52 UTC, mattschrage approved these changes
lgtm!

2021-04-08 00:52 UTC, merged