Feat: Added completion specs for onboardbase
withfig/autocomplete pull request #895
Opened 2022-01-31 10:49 UTC by iamnasirudeen

Added Specs for Onboardbase

2022-02-01 11:35 UTC, fedeci requested changes
Thank you this spec! Could you please run `npm run lint:fix` and add basic names to args? Then we are ready to merge this 🚀

2022-02-01 11:35 UTC, fedeci commented on src/onboardbase.ts
> +          args: {},
```suggestion
          args: {
            name: "environment",
          },
```

2022-02-01 11:35 UTC, fedeci commented on src/onboardbase.ts
> +        { name: ["-p", "--project"], description: "name of project", args: {} },
```suggestion
        { name: ["-p", "--project"], description: "name of project", args: { name: "project name" } },
```

2022-02-01 11:35 UTC, fedeci commented on src/onboardbase.ts
> +  name: "onboardbase",
```suggestion
  name: "onboardbase",
  description:  "Onboardbase manages app secrets and credentials securely with team work and contractors in mind",
```

2022-02-01 14:53 UTC, fedeci commented
> Thank you this spec! Could you please run `npm run lint:fix` and add basic names to args? Then we are ready to merge this 🚀

There are still a lot of args missing the name :) We need it to let the user know what to insert, so it is quite important.

2022-02-02 11:07 UTC, iamnasirudeen reviewed
Update the args

2022-02-02 13:36 UTC, fedeci approved these changes
Thanks!

2022-02-02 13:36 UTC, merged