adding generators for okteto ns and ctx
withfig/autocomplete pull request #899
Opened 2022-02-02 09:27 UTC by RinkiyaKeDad

Signed-off-by: Arsh Sharma <arshsharma461@gmail.com>

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Adds generators for `okteto ns use/delete` and `okteto ctx use/delete`

**What is the current behavior? (You can also link to an open issue here)**
https://github.com/okteto/okteto/issues/1998

**What is the new behavior (if this is a feature change)?**

https://user-images.githubusercontent.com/56963264/152126700-1bd8d582-044f-4fe4-b5c7-4b84a72f1373.mov

**Additional info:**

A couple of questions:

- where do we upload the Okteto logo so that we can use `fig://icon?type=okteto`?
- as seen in the demo, there is a bit of delay showing the namespaces when doing `okteto ns use/delete` - is there a way to do some sort of caching to speed this up?
- is it possible to show the generated results in fig at the top of the list, that is, above the flag suggestions?

Thanks in advance!

cc @rberrelleza

2022-02-02 13:47 UTC, fedeci requested changes
/cc @mschrage there is an icon request https://www.okteto.com/favicon-32x32.png?v=f033e5af6700c9cb7abf797278bfe155

2022-02-02 13:47 UTC, fedeci commented on src/okteto.ts
> +  script: "okteto context list",
This is how we can add cache to a generator
```suggestion
  script: "okteto context list",
  cache: {
    ttl: 1000 * 60 * 60 * 24 * 2 // 2 days
  },
```

2022-02-03 09:03 UTC, RinkiyaKeDad commented on src/okteto.ts
> +  script: "okteto context list",
Thanks @fedeci! If this `ttl` is 2 days, does this mean that even if new `contexts` are available, they won't be shown until the `ttl` expires, and we request for the `contexts` again?

2022-02-03 11:41 UTC, fedeci commented on src/okteto.ts
> +  script: "okteto context list",
That's what we do!

2022-02-08 09:26 UTC, RinkiyaKeDad commented on src/okteto.ts
> +  script: "okteto context list",
@rberrelleza do we want this? This would mean new `contexts` don't show up immediately. We could reduce the `ttl` to an hour to make it more convenient, but I could still see this being problematic in cases where a newly created `context` won't load up in the suggestions immediately.

2022-02-18 18:01 UTC, rberrelleza commented on src/okteto.ts
> +  script: "okteto context list",
@RinkiyaKeDad I think that we should have a cache. 30 minutes sounds reasonable as a starting point. Once cache invalidation is available, we can rethink this approach.

2022-02-19 14:13 UTC, fedeci approved these changes
Thanks!

2022-02-19 14:13 UTC, fedeci commented on src/okteto.ts
> +    });
```suggestion
    return output
      .split("\n")
      .slice(1)
      .map((context, ind) => {
        context = context.split(" ")[0];
        return {
          name: context.replace("*", "").trim(),
          description: "Context",
          icon: "fig://icon?type=okteto",
        };
      });
```

2022-02-19 14:13 UTC, fedeci commented on src/okteto.ts
> +    });
```suggestion
    return output
      .split("\n")
      .slice(1)
      .map((namespace, ind) => {
        namespace = namespace.split(" ")[0];
        return {
          name: namespace.replace("*", "").trim(),
          description: "Namespace",
          icon: "fig://icon?type=okteto",
        };
      });
```

2022-02-19 14:17 UTC, merged

2022-02-21 09:04 UTC, RinkiyaKeDad commented
Thanks a lot for making the changes and getting the PR merged @fedeci! I also wanted to ask if there is a way we can automate sending PRs to this repo whenever we release a new version of our CLI?

2022-02-21 09:16 UTC, fedeci commented
That's definitely something I have to start working on! @ryanccn implemented something and I will probably take some inspiration from his work.

2022-02-22 08:57 UTC, RinkiyaKeDad commented
Awesome, thanks! 

Do you know how long will it take for the changes in this PR to reflect? I updated fig to the latest version but running `okteto ns delete` still doesn't load the autocomplete suggestions based on generators for me. And has the Okteto logo been uploaded?

2022-02-22 10:40 UTC, fedeci commented
Does it provide suggestions for okteto subcommands? Changes should be live as soon as the PR gets merged.
I will add the icon soon.

2022-03-14 11:47 UTC, RinkiyaKeDad commented
Hey @fedeci! Apologies for the late reply; the suggestions are now working. Could you please add the icon soon? We need to record a demo for a blog post we're writing 🙏 

![Screenshot 2022-03-14 at 5 13 24 PM](https://user-images.githubusercontent.com/56963264/158165662-99bbba63-7fd8-4b2b-90c1-1d42cf4b4adb.png)

2022-03-14 21:32 UTC, fedeci commented
@RinkiyaKeDad see https://github.com/withfig/autocomplete/commit/9ecb1538ffd0bc226bdd2883b97337da7abbc371. This won't be available immediately but it will in the next fig release.

2022-03-15 07:41 UTC, RinkiyaKeDad commented
Thanks @fedeci! Do you know when's the next release planned?

2022-03-15 09:06 UTC, fedeci commented
@mschrage knows that better than me!

2022-03-15 16:28 UTC, mschrage commented
Later today @RinkiyaKeDad