Add velociraptor
withfig/autocomplete pull request #904
Opened 2022-02-03 12:44 UTC by ryanccn

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

feature

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

added a completion spec for [Velociraptor](https://velociraptor.run), the npm-style script runner for Deno

**Additional info:**

2022-02-03 21:17 UTC, fedeci commented on src/vr.ts
> +        name: "version",
If you run `vr upgrade` without args does it install the latest version? In that case we should mark this arg as optional

2022-02-03 21:17 UTC, fedeci commented on src/vr.ts
> +      },
Can we create a generator for this one?

2022-02-05 11:50 UTC, ryanccn commented
It turns out that parsing `vr`'s output is incredibly hard because I can't force it to not use colors, and it doesn't have any program-friendly output (such as JSON output)...﻿

2022-02-05 11:50 UTC, ryanccn commented on src/vr.ts
> +        name: "version",
This is done

2022-02-05 13:57 UTC, fedeci commented
@ryanccn do you think the `velociraptor` maintainers are willing to add a --json option to the command so that we can get a nicer and more parsable output?

2022-02-05 15:54 UTC, ryanccn commented
That's great! I guess I'll wait for the upstream issue to be resolved 😅

2022-02-05 16:06 UTC, fedeci commented
We can merge it without the generators if you prefer! We can add those in a second time.

2022-02-06 02:38 UTC, ryanccn commented
OK, sure! I'm not sure why the linter is failing on `cat` though 🤔

2022-02-06 09:49 UTC, fedeci commented
Rebasing on top of main should fix!

2022-02-09 00:25 UTC, SeparateRecords commented
BTW, velociraptor respects NO_COLOR - try running any generators with `NO_COLOR=1 vr [...]` 🙂

2022-02-09 04:20 UTC, ryanccn commented
Voilà!

2022-02-09 04:20 UTC, ryanccn commented
(It looks for the bullet points, lol)

2022-02-09 10:10 UTC, fedeci requested changes

2022-02-09 10:10 UTC, fedeci commented on src/vr.ts
> +      description: "Show help for Velociraptor",
We can add this prop to `--help` and remove his repetitions in the subcommands
```suggestion
      description: "Show help for Velociraptor",
      isPersistent: true,
```

2022-02-09 10:10 UTC, fedeci commented on src/vr.ts
> +      }
I prefer a C style loop instead of the `.findIndex`.
```suggestion
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (!line.startsWith(SCRIPT_KEYWORD)) continue;

        suggestions.push({
          name: line.replace(SCRIPT_KEYWORD, ""),
          ...(lines[i + 1] && { description: lines[i + 1].trim() }),
        }),
      }
```

2022-02-09 12:06 UTC, fedeci approved these changes
Thanks!

2022-02-09 12:06 UTC, merged