add: trex cli for deno
withfig/autocomplete pull request #914
Opened 2022-02-06 22:35 UTC by ShawnCockburn

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

feature

**What is the current behavior? (You can also link to an open issue here)**

trex cli has no autocomplete

**What is the new behavior (if this is a feature change)?**

trex cli has autocomplete

**Additional info:**

Trex is a CLI tool for [Deno](https://deno.land) projects, it is similar to npm, however it follows the deno style of dependencies (inport maps) and adds a npm like script file.

trex website: https://crewdevio.mod.land/projects/Trex

trex repo: https://github.com/crewdevio/Trex

2022-02-06 22:46 UTC, fedeci requested changes
Thanks! Some changes and this is ready to be merged.

2022-02-06 22:46 UTC, fedeci commented on src/trex.ts
> +    if (out && out !== "") {
This check is enough, in JS an empty string returns false when boolean tested:
```suggestion
    if (out) {
```

2022-02-06 22:46 UTC, fedeci commented on src/trex.ts
> +      const deps = JSON.parse(out);
Can we trycatch around this and return an empty array on error?

2022-02-06 22:46 UTC, fedeci commented on src/trex.ts
> +      const scriptsObj = JSON.parse(out);
Same here

2022-02-06 22:46 UTC, fedeci commented on src/trex.ts
> +  help: { name: ["-h", "--help"], description: "Print help info" },
In the spec help does not need to be repeated for every single subcommand but we can use [isPersistent](https://fig.io/docs/reference/option#ispersistent)

2022-02-06 22:46 UTC, fedeci commented on src/trex.ts
> +          description: "Update outdate dependencies",
```suggestion
          description: "Update outdated dependencies",
```

2022-02-06 22:54 UTC, ShawnCockburn commented on src/trex.ts
> +    if (out && out !== "") {
Of course, silly me!

2022-02-06 23:02 UTC, ShawnCockburn commented on src/trex.ts
> +      const deps = JSON.parse(out);
yes

2022-02-06 23:36 UTC, ShawnCockburn commented on src/trex.ts
> +  help: { name: ["-h", "--help"], description: "Print help info" },
This is great to know, thanks!

2022-02-06 23:37 UTC, ShawnCockburn commented
@fedeci done!

2022-02-07 09:51 UTC, fedeci approved these changes
Thanks!

2022-02-07 09:51 UTC, merged