feat: add lerna command
withfig/autocomplete pull request #93
Opened 2021-04-06 12:20 UTC by cstrnt

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
There is no completion spec for [lerna](https://github.com/lerna/lerna)

**What is the new behavior (if this is a feature change)?**
It adds the completion spec 🥳 

**Additional info:**

2021-04-06 20:03 UTC, QuiiBz commented on dev/lerna.ts
> +    output.split("\n").map((packageName) => ({
Can be simplified by using the same `name` variable name:
```suggestion
    output.split("\n").map(name => ({
```

2021-04-06 20:03 UTC, QuiiBz commented on dev/lerna.ts
> +      name: packageName,
So this would become just:
```suggestion
      name,
```

2021-04-07 06:15 UTC, cstrnt commented on dev/lerna.ts
> +    output.split("\n").map((packageName) => ({
I agree with you that it makes it less code but I'm always struggling whether verbose code is better or *cleaner* code

2021-04-07 06:53 UTC, QuiiBz commented on dev/lerna.ts
> +    output.split("\n").map((packageName) => ({
In this case, I feel like it's both cleaner and better code since it's easy to understand and easier to read.

2021-04-07 18:09 UTC, mattschrage requested changes
Just update the npm icon in a few places + a few clarifying questions!

2021-04-07 18:09 UTC, mattschrage commented on dev/lerna.ts
> +        "https://img.pngio.com/publishing-to-npm-from-kentcdodds-on-eggheadio-npm-png-800_800.png",
I know this isn't documented, but there is actually an `npm` icon builtin. `fig://icon?type=npm`

I really need to make a list.

2021-04-07 18:09 UTC, mattschrage commented on dev/lerna.ts
> +          "https://img.pngio.com/publishing-to-npm-from-kentcdodds-on-eggheadio-npm-png-800_800.png",
Same as above.

2021-04-07 18:09 UTC, mattschrage commented on specs/lerna.js
> +var __spreadArray = (this && this.__spreadArray) || function (to, from) {
Are these utility functions computed at compile time or runtime?

Also - does it make sense to include this in the dev environment by default so every spec doesn't need to reimplement?

2021-04-07 18:54 UTC, cstrnt commented on dev/lerna.ts
> +        "https://img.pngio.com/publishing-to-npm-from-kentcdodds-on-eggheadio-npm-png-800_800.png",
That would be awesome!

2021-04-07 18:56 UTC, cstrnt commented on specs/lerna.js
> +var __spreadArray = (this && this.__spreadArray) || function (to, from) {
I don't think it is possible to add them to the dev environment as we are not bundling them, they just exist next to each other. 
And they are interpreted at run time because it's JS I think

2021-04-07 21:09 UTC, merged