add new subcommands to amplify cli
withfig/autocomplete pull request #933
Opened 2022-02-17 09:34 UTC by adilusman51

add new sub commands to amplify cli

2022-02-17 11:08 UTC, fedeci requested changes

2022-02-17 11:08 UTC, fedeci commented on src/amplify.ts
>        },
This should be an option actually and not a subcommand. Can you change that?

2022-02-17 11:08 UTC, fedeci commented on src/amplify.ts
> +          name: "-y",
Same here

2022-02-20 11:28 UTC, adilusman51 commented on src/amplify.ts
>        },
Kindly review, I have made the requested changes

2022-02-20 16:10 UTC, fedeci approved these changes
Thanks!

2022-02-20 16:20 UTC, fedeci commented
It seems that lint is failing, can you run `npm run lint:fix` please?

2022-02-22 09:25 UTC, adilusman51 commented
@fedeci Lint issues resolved

2022-02-22 09:26 UTC, fedeci commented
Great, thanks!

2022-02-22 09:29 UTC, merged