feat: implement bat spec
withfig/autocomplete pull request #984
Opened 2022-02-28 13:23 UTC by threadflow

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Implement bat command spect

**What is the current behavior? (You can also link to an open issue here)**

bat command could auto-complete now

**What is the new behavior (if this is a feature change)?**

The feature before is just a copy of cat that introduce the command briefly. 

Now, the whole auto-complete is worked.

**Additional info:**

2022-02-28 13:31 UTC, threadflow commented
👍

2022-03-01 13:16 UTC, fedeci requested changes

2022-03-01 13:16 UTC, fedeci commented on src/bat.ts
> +import { Script } from "vm";
Do we need this import?

2022-03-01 13:16 UTC, fedeci commented on src/bat.ts
> +              })
```suggestion
              out.split("\n").map((outLine) => {
                const langLine = outLine.split(":");
                const descriptionString = langLine[0].trim();
                return outLine
                  .replace(/\:/g, ",")
                  .split(",")
                  .map((item) => {
                    return {
                      name: item.trim(),
                      description: descriptionString + " language",
                    };
                  });
              }
```

2022-03-01 13:59 UTC, threadflow commented on src/bat.ts
> +import { Script } from "vm";
Sorry, this line copied from template and forget to removed before commit. It can be removed.

2022-03-01 22:24 UTC, fedeci commented on src/bat.ts
> +              })
Yeah, I missed a return 😁

2022-03-01 22:25 UTC, fedeci commented on src/bat.ts
> +              })
Yeah, I missed a return 😁

2022-03-01 22:26 UTC, fedeci commented on src/bat.ts
> +              })
```suggestion
              return out.split("\n").map((outLine) => {
                const langLine = outLine.split(":");
                const descriptionString = langLine[0].trim();
                return outLine
                  .replace(/\:/g, ",")
                  .split(",")
                  .map((item) => {
                    return {
                      name: item.trim(),
                      description: descriptionString + " language",
                    };
                  });
              }
```

2022-03-02 01:35 UTC, threadflow commented on src/bat.ts
> +              })
I do test the previous suggested code with adding the 'return'.  It not work.

The code here is used to unpack a 2 dimension array, so the committed code is needed.

2022-03-02 08:56 UTC, fedeci commented on src/bat.ts
> +              })
I see, the I still prefer `Array.flat` method than `.concat` which happens to have some perf issues on some browsers.

2022-03-02 12:41 UTC, threadflow commented on src/bat.ts
> +              })
I refactored this option with `flat()` and tested. Please check again

2022-03-04 04:10 UTC, mschrage approved these changes

2022-03-04 04:10 UTC, merged