feat: add svn completion spec
withfig/autocomplete pull request #986
Opened 2022-03-01 16:46 UTC by sh-sabbir

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
Currently not available

**What is the new behavior (if this is a feature change)?**
Partial support for SVN auto-completion

**Additional info:**
Added support for a few subcommands. But I'll continue improving the spec by adding more properties to the spec

2022-03-01 22:32 UTC, fedeci requested changes
A couple nits and it is good to be shipped!

2022-03-01 22:32 UTC, fedeci commented on src/svn.ts
> +        suggestions: subcommandsList,
```suggestion
        template: ["help"],
```

2022-03-01 22:32 UTC, fedeci commented on src/svn.ts
> +        suggestions: subcommandsList,
```suggestion
        template: ["help"],
```

2022-03-01 22:32 UTC, fedeci commented on src/svn.ts
> +      isPersistent: false,
```suggestion
```

2022-03-01 22:32 UTC, fedeci commented on src/svn.ts
> +        isOptional: false,
```suggestion
```

2022-03-04 15:05 UTC, fedeci commented on src/svn.ts
> +        suggestions: subcommandsList,
It returns all the sibling subcommands but appears to be broken rn. I'm fixing it though so you can safely add it!

2023-10-12 19:09 UTC, mschrage approved these changes

2023-10-12 19:10 UTC, merged