feat: add `micro` completion spec
withfig/autocomplete pull request #988
Opened 2022-03-01 19:23 UTC by t-bre

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Add completion spec for [micro](https://github.com/zyedidia/micro) editor.

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

2022-03-01 22:39 UTC, fedeci requested changes

2022-03-01 22:39 UTC, fedeci commented on src/micro.ts
> +            isVariadic: false,
This is implicit.
```suggestion
```

2022-03-01 22:39 UTC, fedeci commented on src/micro.ts
> +        isVariadic: false,
Same here

2022-03-01 22:58 UTC, t-bre reviewed
Removed implicit `isVariadic: false`

2022-03-02 08:48 UTC, fedeci approved these changes
Thanks!

2022-03-02 08:48 UTC, merged