Add spec for id
withfig/autocomplete pull request #995
Opened 2022-03-03 04:16 UTC by anthonycastaneda

**What kind of change does this PR introduce? New completion spec for id

**Additional info:**
This is my first spec, and first pull request.  I'm a beginner, so the code may not be correct.  It did pass the npm test and lint:fix.

2022-03-03 08:10 UTC, SeparateRecords submitted a review, later dismissed
Looking really good!! Left a couple of comments, all super easy to fix up.

There's also one option missing (`-r`) that should be added.

Quick note, don't just use "commit suggestion" since that will do individual commits and make me co-author of them haha

@fedeci I'll defer to you on whether we should keep the `exclusiveOn` or `dependsOn` - it's really hard for me to visualize the relationship between these damn options...

2022-03-03 08:10 UTC, SeparateRecords commented on src/id.ts
> +      exclusiveOn: exclusiveOptions,
`-n` can only be specified if one of `-G`, `-g`, or `-u` are given

```suggestion
      dependsOn: ["-G", "-g", "-u"],
      exclusiveOn: exclusiveOptions
```

2022-03-03 08:10 UTC, SeparateRecords commented on src/id.ts
> +    isOptional: true,
This generator _should_ show all the users on the computer! It's lifted [straight out of `killall.ts`](https://github.com/withfig/autocomplete/blob/126dbafce73301ae36af84ee7e163b9923cbf438/src/killall.ts#L116-L124)

```suggestion
    isOptional: true,
    generators: {
      script: "dscl . -list /Users | grep -v '^_'",
      postProcess: (out) =>
        out
          .trim()
          .split("\n")
          .map((username) => ({
            name: username,
            icon: "fig://template?badge=👤",
          })),
    }
```

2022-03-03 14:29 UTC, anthonycastaneda commented on src/id.ts
> +      exclusiveOn: exclusiveOptions,
The code block shows `-u` but your comment mentions `-n`.  I've made this change on the `-n` option.

2022-03-03 23:39 UTC, mschrage requested changes

2022-03-03 23:39 UTC, mschrage commented on src/id.ts
> +    },
I'm not sure if you can have "-A" in the list of exclusive options for itself? @fedeci any idea if this is okay or not?

2022-03-04 10:44 UTC, fedeci commented on src/id.ts
> +    },
I'm checking!

2022-03-04 10:53 UTC, fedeci commented on src/id.ts
> +    },
It doesn't appear to be a problem!

2022-03-04 10:54 UTC, fedeci approved these changes
Thanks!

2022-03-04 10:56 UTC, merged